import { hazirPath, type SectorTemplate, type SectorId } from '../types';

type Doc = 'fatura' | 'arsiv' | 'irsaliye' | 'ihracat' | 'mikro-ihracat';
const MODULE: Record<Doc, string> = { fatura: 'fatura', arsiv: 'arsiv', irsaliye: 'irsaliye', ihracat: 'ihracat', 'mikro-ihracat': 'mikro_ihracat' };

const tpl = (id: string, sector: SectorId, doc: Doc, accent: string, name: string, description: string, tags: string[]): SectorTemplate => ({
    id, sector, name, description, docTypeId: doc, moduleId: MODULE[doc], accent,
    xslt: hazirPath(id, 'xslt'), xml: hazirPath(id, 'xml'), tags,
});

/** Tekstil, konfeksiyon, ayakkabı ve deri: e-Fatura, e-Arşiv, e-İrsaliye, e-İhracat ve e-Mikro İhracat (scripts/moda/ ile üretilir). */
export const MODA_TEMPLATES: SectorTemplate[] = [
    tpl('ayakkabi-toptan-seri-fatura', 'ayakkabi', 'fatura', '#a16207', 'Ayakkabı Toptan Seri (Asorti) Faturası',
        'Ayakkabı üreticisi ve toptancıları için kraft kutu etiketi görünümü; her modelde numara asorti ızgarası, seri × çift hesabı ve şablon harfli toplam.',
        ['Numara asortisi', 'Seri × çift', 'Kutu etiketi', 'Model / renk']),
    tpl('ham-deri-tevkifat-fatura', 'ayakkabi', 'fatura', '#7c2d12', 'Ham Deri Teslim Faturası (Tevkifatlı)',
        'Tabakhaneye tuzlu ham deri tesliminde dikişli deri başlıklı defter görünümü; A/B kalite mühürleri, adet / kg özeti ve 9/10 KDV tevkifatı kutusu.',
        ['Tevkifat 622 · 9/10', 'Kalite rozeti', 'Adet & kg', 'Deri defteri']),
    tpl('kumas-top-fatura', 'tekstil', 'fatura', '#dc2626', 'Top Kumaş Satış Faturası (Bauhaus)',
        'Dokuma fabrikaları için Bauhaus geometrisinde fatura; her kalemde kumaşın renginde ve örgüsünde numune karesi, lif kompozisyonu çubuğu, top / en / gramaj.',
        ['Kumaş numunesi', 'Lif kompozisyonu', 'Top / en / gramaj', 'Örgü tipi']),
    tpl('iplik-lot-fatura', 'tekstil', 'fatura', '#1d4ed8', 'İplik Lot Sertifikalı Fatura',
        'İplik fabrikaları için laboratuvar sertifikası konseptinde milimetrik zemin; her lot için Ne, büküm, mukavemet, nem ve Uster değerli test kartı ve onay damgası.',
        ['Lot / bobin', 'Ne & büküm', 'Uster testi', 'Uygunluk damgası']),
    tpl('sneaker-distributor-fatura', 'ayakkabi', 'fatura', '#65a30d', 'Sneaker Distribütör Faturası (Streetwear)',
        'Spor ayakkabı distribütörlerinden mağazalara sezon satışı için siyah zeminli, neon vurgulu streetwear fatura; colorway etiketi ve hap biçiminde numara dağılımı.',
        ['Colorway', 'Numara dağılımı', 'Sezon drop', 'Neon tasarım']),

    tpl('ayakkabi-butik-arsiv', 'ayakkabi', 'arsiv', '#a68a4b', 'Ayakkabı Butiği e-Arşiv Faturası',
        'Lüks ayakkabı butikleri için krem zemin, yaldız çift çerçeve ve monogramlı e-Arşiv fatura; ürün başına numara rozeti ve deri bakım önerileri kartı.',
        ['Numara rozeti', 'Monogram', 'Bakım kartı', 'Lüks butik']),
    tpl('butik-giyim-editoryal-arsiv', 'tekstil', 'arsiv', '#111827', 'Butik Giyim Editoryal e-Arşiv',
        'Butik giyim mağazaları için moda dergisi kapağı görünümü; dev serif marka başlığı, sezon satırı, numaralı editoryal ürün listesi ve kesilebilir değişim kuponu.',
        ['Dergi kapağı', 'Beden / renk', 'Değişim kuponu', 'Editoryal']),
    tpl('moda-eticaret-arsiv', 'tekstil', 'arsiv', '#c026d3', 'Online Moda Mağazası e-Arşiv (İnternet Satışı)',
        'Moda e-ticaret siteleri için mobil uygulama görünümlü e-Arşiv; sipariş durum çizelgesi, renkli ürün kartları, GİB internet satışı bilgileri ve barkodlu iade kodu.',
        ['İnternet satışı', 'Kargo & ödeme aracı', 'Sipariş durumu', 'İade kodu']),
    tpl('terzi-ismarlama-arsiv', 'tekstil', 'arsiv', '#1e3a8a', 'Terzi Ismarlama Takım e-Arşiv',
        'Ismarlama terziler için kalıp kâğıdı zeminli e-Arşiv; kalıp parçası silüetleri, mezura şeridi üzerinde müşteri ölçüleri ve prova zaman çizelgesi.',
        ['Ölçü kartı', 'Kalıp kâğıdı', 'Prova takvimi', 'Kişiye özel']),
    tpl('cocuk-ayakkabi-arsiv', 'ayakkabi', 'arsiv', '#f472b6', 'Çocuk Ayakkabı Mağazası e-Arşiv',
        'Çocuk ayakkabıcıları için pastel, oyunbaz e-Arşiv; ayak izi içinde numara, ölçülen ayak uzunluğu / genişliği ve bir sonraki ölçüm günü hatırlatması.',
        ['Ayak ölçüsü', 'Numara', 'Ölçüm hatırlatma', 'Pastel tasarım']),

    tpl('ayakkabi-koli-irsaliye', 'ayakkabi', 'irsaliye', '#eab308', 'Ayakkabı Koli Sevk İrsaliyesi',
        'Fabrikadan depoya koli sevkiyatı için tehlike şeritli, şablon harfli koli manifestosu; koli aralıkları, koli içi asorti, koli × seri = çift hesabı ve plaka görünümlü araç bilgisi.',
        ['Koli manifestosu', 'Asorti', 'Taşıma işaretleri', 'Plaka & şoför']),
    tpl('kumas-boyahane-irsaliye', 'tekstil', 'irsaliye', '#7c3aed', 'Boyahane Kumaş Teslim İrsaliyesi',
        'Boya-apre işletmeleri için renk laboratuvarı konseptli irsaliye; süreç adımları, Pantone tarzı renk kartları, lot / top / metre / kg künyesi ve haslık çubukları.',
        ['Renk kartı', 'Haslık değerleri', 'Lot / top / kg', 'Süreç adımları']),
    tpl('konfeksiyon-magaza-dagitim-irsaliye', 'tekstil', 'irsaliye', '#0d9488', 'Konfeksiyon Mağaza Dağıtım İrsaliyesi',
        'Hazır giyim dağıtım merkezlerinden mağazalara sevkiyat için metro hattı rotası; askılı / katlı gruplar, beden dağılımı grafiği, mühür no ve mağaza kabul listesi.',
        ['Rota haritası', 'Askılı / katlı', 'Beden grafiği', 'Mühür no']),
    tpl('deri-tabakhane-irsaliye', 'ayakkabi', 'irsaliye', '#92400e', 'Tabakhane Deri Sevk İrsaliyesi (Daktilo)',
        'Tabakhanelerden saraciye ve ayakkabı atölyelerine deri sevki için eskimiş sepya kâğıtta daktilo irsaliye; parti, kalite, kalınlık, balya, ft² ve ıslak damgalar.',
        ['Parti / kalite', 'ft² ölçü', 'Balya', 'Islak damga']),
    tpl('kesimhane-dikim-irsaliye', 'tekstil', 'irsaliye', '#1e40af', 'Kesimhane → Fason Dikim İrsaliyesi',
        'Kesimhanelerden fason atölyelere kesilmiş parça sevki için teknik çizim (blueprint) irsaliye; pastal / kat / demet künyesi, beden tablosu ve parça listesi.',
        ['Pastal & kat', 'Demet no', 'Parça listesi', 'Fason dikim']),

    tpl('ayakkabi-ihracat-tir-fatura', 'ayakkabi', 'ihracat', '#7f1d1d', 'Ayakkabı İhracatı (TIR · Pasaport Tasarımı)',
        'Karayoluyla ayakkabı ihracatı için pasaport / vize konseptli e-İhracat faturası; makinede okunur bölge (MRZ), gümrük mühürleri, GTİP, teslim şartı ve kap bilgileri.',
        ['DAP · Karayolu', 'GTİP', 'Kap / koli', 'KDV istisnası 301']),
    tpl('hazir-giyim-ihracat-fatura', 'tekstil', 'ihracat', '#18181b', 'Hazır Giyim İhracatı (Moda Evi)',
        'Hazır giyim ihracatçıları için siyah-beyaz, Didot başlıklı iki dilli (TR / EN) e-İhracat faturası; stil kodu, kompozisyon, beden oranı ve swing tag üzerinde toplam.',
        ['FOB · Denizyolu', 'İki dilli', 'Stil kodu', 'GBP']),
    tpl('denim-kumas-ihracat-fatura', 'tekstil', 'ihracat', '#1e3a8a', 'Denim Kumaş İhracatı',
        'Denim üreticileri için indigo dimi zeminli, deri patch başlıklı ve kontrast dikişli e-İhracat faturası; kumaş kartelası, oz / en / yıkama çipleri, top bazında kap bilgisi.',
        ['CIF · Denizyolu', 'Kumaş kartelası', 'Oz / en', 'EUR']),
    tpl('deri-ceket-ihracat-japonya', 'ayakkabi', 'ihracat', '#b91c1c', 'Deri Giyim İhracatı (Japon Minimalizmi)',
        'Deri giyim ihracatçıları için washi tonlu, dikey başlıklı ve hanko mühürlü minimal e-İhracat faturası; havayolu (AWB), CIP sigorta ve enso fırça dairesinde toplam.',
        ['CIP · Havayolu', 'AWB', 'GTİP', 'USD']),
    tpl('terlik-sandalet-konteyner-ihracat', 'ayakkabi', 'ihracat', '#c2410c', 'Terlik & Sandalet Konteyner İhracatı',
        'Konteynerle ayakkabı ihracatı için konteyner kapısı başlıklı e-İhracat faturası; liman rotası, koli adetlerine göre yükleme planı, manifesto tablosu ve mühür etiketi.',
        ['FCA · Konteyner', 'Yükleme planı', 'Konşimento', 'Mühür no']),

    tpl('atolye-deri-canta-mikro', 'ayakkabi', 'mikro-ihracat', '#9a5b2c', 'El Yapımı Deri Ürün Mikro İhracatı',
        'Etsy / kendi sitesinden yurt dışına satış yapan deri atölyeleri için kraft kâğıt ve washi bantlı e-Arşiv; ETGB, PTT EMS takibi, döviz ve alıcıya teşekkür kartı.',
        ['ETGB', 'PTT EMS', 'KDV istisnası 301', 'USD']),
    tpl('pazaryeri-havlu-mikro', 'tekstil', 'mikro-ihracat', '#65a30d', 'Pazaryeri Havlu & Bornoz Mikro İhracatı',
        'Yurt dışı pazaryerlerinde satan ev tekstili üreticileri için sipariş föyü görünümlü e-Arşiv; SKU / ebat / GTİP tablosu, gönderim adımları ve kesilebilir paket fişi.',
        ['ETGB', 'Paket fişi', 'SKU & GTİP', 'EUR']),
    tpl('sneaker-eticaret-mikro', 'ayakkabi', 'mikro-ihracat', '#ef4444', 'Sneaker E-Ticaret Mikro İhracatı',
        'Yurt dışına sneaker satan e-ticaret siteleri için sokak modası tasarımı; EU / US / UK / cm numara tablosunda alınan numara otomatik vurgulanır, UPS takip ve ETGB.',
        ['Numara tablosu', 'ETGB', 'UPS takip', 'EUR']),
    tpl('pestemal-mikro-ihracat', 'tekstil', 'mikro-ihracat', '#1e40af', 'Peştamal Mikro İhracatı (İznik Çinisi)',
        'El tezgâhı peştamal ve hamam tekstili satıcıları için İznik çinisi kenarlı, kemer başlıklı e-Arşiv; renkli kemerli ürün kartları, ETGB ve PTT EMS bilgisi.',
        ['ETGB', 'PTT EMS', 'İznik çinisi', 'AUD']),
    tpl('abiye-elbise-mikro', 'tekstil', 'mikro-ihracat', '#a07c3b', 'Abiye & Gelinlik Mikro İhracatı',
        'Kişiye özel abiye / gelinlik atölyeleri için dantel fistolu, şampanya tonlu e-Arşiv; elbise silüeti üzerinde müşteri ölçüleri, FedEx takibi ve ETGB.',
        ['Kişiye özel ölçü', 'ETGB', 'FedEx', 'GBP']),
];
