import { hazirPath, type SectorTemplate } from '../types';

/** Sanayi ikinci dalga: inşaat, üretim, ihracat, otomotiv, enerji-akaryakıt, tarım-hayvancılık. */
export const SANAYI2_TEMPLATES: SectorTemplate[] = [
    {
        id: 'hazir-beton-irsaliye',
        sector: 'insaat',
        name: 'Hazır Beton Sevk İrsaliyesi',
        description: 'Beton santralleri için mikser plakası, şoför, santral çıkış saati, beton sınıfı, slump ölçeği, pompa ve döküm adresi bilgileri; şantiye teslim koçanıyla mikser başına sevk irsaliyesi.',
        docTypeId: 'irsaliye',
        moduleId: 'irsaliye',
        accent: '#f97316',
        xslt: hazirPath('hazir-beton-irsaliye', 'xslt'),
        xml: hazirPath('hazir-beton-irsaliye', 'xml'),
        tags: ['Beton sınıfı & slump', 'Mikser plakası', 'Santral çıkış saati', 'Döküm adresi', 'Teslim koçanı'],
    },
    {
        id: 'tekstil-fason-fatura',
        sector: 'uretim',
        name: 'Tekstil Fason Dikim Faturası (Tevkifatlı)',
        description: 'Konfeksiyon atölyeleri için sezon, model kodu, renk kartelası, beden dağılımı ve sipariş-irsaliye referanslı; fason tekstil işlerinde KDV tevkifatlı askılı etiket görünümlü fatura.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#a21caf',
        xslt: hazirPath('tekstil-fason-fatura', 'xslt'),
        xml: hazirPath('tekstil-fason-fatura', 'xml'),
        tags: ['Tevkifat 609 · 7/10', 'Model & sezon', 'Renk kartelası', 'Beden dağılımı', 'Sipariş / irsaliye ref.'],
    },
    {
        id: 'mobilya-imalat-arsiv',
        sector: 'uretim',
        name: 'Mobilya İmalat e-Arşiv Faturası',
        description: 'Ahşap mobilya atölyeleri için ceviz dokulu başlık, ölçü krokisi, modül ölçüleri ve malzeme bilgisi, teslim tarihi, garanti sertifikası ve taksitli kart ödemesiyle bireysel müşteriye e-Arşiv fatura.',
        docTypeId: 'arsiv',
        moduleId: 'arsiv',
        accent: '#92400e',
        xslt: hazirPath('mobilya-imalat-arsiv', 'xslt'),
        xml: hazirPath('mobilya-imalat-arsiv', 'xml'),
        tags: ['Ölçü krokisi', 'Malzeme & ebat', 'Teslim tarihi', 'Garanti sertifikası', 'Taksitli ödeme'],
    },
    {
        id: 'ihrac-kayitli-fatura',
        sector: 'ihracat',
        name: 'İhraç Kayıtlı Satış Faturası',
        description: 'İhracatçıya ihraç kaydıyla teslim yapan imalatçılar için gümrük beyannamesi kutucuklu düzende; satır bazında GTİP, DİİB belge no, KDV hesaplanıp tahsil edilmeyen 702 istisnası.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#1d4ed8',
        xslt: hazirPath('ihrac-kayitli-fatura', 'xslt'),
        xml: hazirPath('ihrac-kayitli-fatura', 'xml'),
        tags: ['IHRACKAYITLI · 702', 'Satır GTİP', 'DİİB belge no', 'KDV tecil', 'Gümrük formu düzeni'],
    },
    {
        id: 'hayvancilik-mustahsil',
        sector: 'tarim',
        name: 'Büyükbaş Hayvan e-Müstahsil Makbuzu',
        description: 'Celep ve besicilerden hayvan alan işletmeler için küpe no, ırk, cinsiyet, yaş ve canlı kg bilgileri; veteriner sağlık raporu, kantar fişi ve stopaj, borsa, SGK kesintileriyle müstahsil makbuzu.',
        docTypeId: 'mustahsil',
        moduleId: 'mustahsil',
        accent: '#15803d',
        xslt: hazirPath('hayvancilik-mustahsil', 'xslt'),
        xml: hazirPath('hayvancilik-mustahsil', 'xml'),
        tags: ['Küpe no', 'Canlı kg', 'Veteriner raporu', 'Stopaj %1', 'Borsa & SGK kesintisi'],
    },
    {
        id: 'zirai-bayi-fatura',
        sector: 'tarim',
        name: 'Zirai Bayi Satış Faturası',
        description: 'Gübre, tohum ve zirai ilaç bayileri için kooperatife satışta lot/parti no, ruhsat no, ürün kategorileri ve %1 · %10 · %20 karışık KDV özetli, hasat sonu vadeli fatura.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#4d7c0f',
        xslt: hazirPath('zirai-bayi-fatura', 'xslt'),
        xml: hazirPath('zirai-bayi-fatura', 'xml'),
        tags: ['KDV %1 / %10 / %20', 'Lot / parti no', 'Ruhsat no', 'Kooperatif alıcı', 'Hasat sonu vade'],
    },
    {
        id: 'galeri-arac-satis',
        sector: 'otomotiv',
        name: 'Galeri İkinci El Araç Satış Faturası',
        description: 'Oto galeriler için showroom görünümlü; plaka, şasi ve motor no, kilometre, model yılı, renk, noter satış bilgisi, kapora mahsubu ve özel matrah (alış-satış farkı) KDV hesabıyla e-Arşiv fatura.',
        docTypeId: 'arsiv',
        moduleId: 'arsiv',
        accent: '#b08d57',
        xslt: hazirPath('galeri-arac-satis', 'xslt'),
        xml: hazirPath('galeri-arac-satis', 'xml'),
        tags: ['OZELMATRAH', 'Plaka · şasi · motor', 'Kilometre & model yılı', 'Noter satışı', 'Kapora / kalan'],
    },
    {
        id: 'ges-kurulum-fatura',
        sector: 'enerji',
        name: 'GES Anahtar Teslim Kurulum Faturası',
        description: 'Güneş enerjisi EPC firmaları için panel, inverter, konstrüksiyon, kablo ve işçilik kalemleri; kurulu güç (kWp), yıllık üretim tahmini, şebeke bağlantı ve sözleşme bilgisi, kalem bazında garanti süreleri.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#f59e0b',
        xslt: hazirPath('ges-kurulum-fatura', 'xslt'),
        xml: hazirPath('ges-kurulum-fatura', 'xml'),
        tags: ['Kurulu güç kWp', 'Yıllık üretim', 'Şebeke bağlantısı', 'EPC sözleşmesi', 'Garanti süreleri'],
    },
    {
        id: 'akaryakit-istasyon-arsiv',
        sector: 'enerji',
        name: 'Akaryakıt İstasyonu e-Arşiv Faturası',
        description: 'Akaryakıt istasyonları için LED pompa ekranı, pompa/tabanca no, araç plakası ve kilometre; motorin/benzin satırlarında ÖTV (0071) ve KDV kırılımı, market ürünleri ve kartlı ödemeyle e-Arşiv fatura.',
        docTypeId: 'arsiv',
        moduleId: 'arsiv',
        accent: '#eab308',
        xslt: hazirPath('akaryakit-istasyon-arsiv', 'xslt'),
        xml: hazirPath('akaryakit-istasyon-arsiv', 'xml'),
        tags: ['ÖTV 0071 dahil', 'Pompa no', 'Plaka & km', 'Market ürünleri', 'Kartlı ödeme'],
    },
];
