import { hazirPath, type SectorTemplate } from '../types';

/** İnşaat, lojistik, üretim, ihracat, tarım, otomotiv servis, enerji (EV şarj). */
export const SANAYI_TEMPLATES: SectorTemplate[] = [
    {
        id: 'insaat-hakedis-tevkifat',
        sector: 'insaat',
        name: 'İnşaat Hakediş Faturası (Tevkifatlı)',
        description: 'Müteahhit ve taahhüt firmaları için hakediş no, imalat dönemi, sözleşme/proje bilgisi, 4/10 KDV tevkifatı ve teminat kesintisi notuyla hakediş faturası.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#d97706',
        xslt: hazirPath('insaat-hakedis-tevkifat', 'xslt'),
        xml: hazirPath('insaat-hakedis-tevkifat', 'xml'),
        tags: ['Tevkifat 601 · 4/10', 'Hakediş no & dönem', 'Sözleşme / proje', 'Teminat kesintisi', 'Banka bilgisi'],
    },
    {
        id: 'lojistik-nakliye-irsaliye',
        sector: 'lojistik',
        name: 'Nakliye Sevk İrsaliyesi',
        description: 'Lojistik ve depolama firmaları için çıkış → varış rota başlığı, araç/dorse plakası, şoförler, taşıyıcı firma, palet ve brüt ağırlık özetli e-İrsaliye.',
        docTypeId: 'irsaliye',
        moduleId: 'irsaliye',
        accent: '#0284c7',
        xslt: hazirPath('lojistik-nakliye-irsaliye', 'xslt'),
        xml: hazirPath('lojistik-nakliye-irsaliye', 'xml'),
        tags: ['Araç & dorse plakası', 'Şoför bilgisi', 'Taşıyıcı firma', 'Palet / ağırlık', 'Tahmini teslim'],
    },
    {
        id: 'uretim-sanayi-fatura',
        sector: 'uretim',
        name: 'Üretim & Sanayi Satış Faturası',
        description: 'Döküm, talaşlı imalat ve yan sanayi üreticileri için teknik resim paftası görünümünde; ürün kodu, kg/m/m² birimleri, satır iskontosu, sipariş-irsaliye referansı ve vadeli ödeme.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#475569',
        xslt: hazirPath('uretim-sanayi-fatura', 'xslt'),
        xml: hazirPath('uretim-sanayi-fatura', 'xml'),
        tags: ['Ürün kodu', 'Satır iskontosu', 'Sipariş & irsaliye ref.', 'Vade', 'TL + döviz hesabı'],
    },
    {
        id: 'ihracat-fatura',
        sector: 'ihracat',
        name: 'İhracat Faturası (TR / EN)',
        description: 'İhracatçılar için Türkçe-İngilizce çift dilli; yabancı alıcı, Incoterms, gönderim şekli, GTİP, kap bilgisi, döviz tutar ve TL karşılığıyla istisnalı ihracat faturası.',
        docTypeId: 'ihracat',
        moduleId: 'ihracat',
        accent: '#10b981',
        xslt: hazirPath('ihracat-fatura', 'xslt'),
        xml: hazirPath('ihracat-fatura', 'xml'),
        tags: ['Çift dil TR/EN', 'Incoterms', 'GTİP', 'Kap bilgisi', 'Döviz + TL karşılığı', 'KDV istisnası'],
    },
    {
        id: 'tarim-hububat-mustahsil',
        sector: 'tarim',
        name: 'Hububat e-Müstahsil Makbuzu',
        description: 'Hububat ve bakliyat tüccarları için çiftçi bilgisi, SMS doğrulama, analiz notları, GV stopajı, borsa tescil ve Bağ-Kur kesintileriyle net ödenen tutarı gösteren müstahsil makbuzu.',
        docTypeId: 'mustahsil',
        moduleId: 'mustahsil',
        accent: '#65a30d',
        xslt: hazirPath('tarim-hububat-mustahsil', 'xslt'),
        xml: hazirPath('tarim-hububat-mustahsil', 'xml'),
        tags: ['Stopaj %2', 'Borsa tescil', 'Bağ-Kur / SGK', 'SMS doğrulama', 'Net ödenen'],
    },
    {
        id: 'oto-servis-fatura',
        sector: 'otomotiv',
        name: 'Oto Servis Bakım-Onarım Faturası',
        description: 'Oto servisler için plaka, şasi no, kilometre ve iş emri içeren araç kartı; yedek parça ve işçilik kalemleri ayrı gruplarda ara toplamlarla.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#dc2626',
        xslt: hazirPath('oto-servis-fatura', 'xslt'),
        xml: hazirPath('oto-servis-fatura', 'xml'),
        tags: ['Plaka & şasi', 'Kilometre', 'İş emri', 'Parça / işçilik grupları', 'İskonto'],
    },
    {
        id: 'ev-sarj-fatura',
        sector: 'enerji',
        name: 'Elektrikli Araç Şarj Faturası',
        description: 'Şarj operatörleri için GİB ENERJI · SARJANLIK yapısında; aktarılan kWh, oturum süresi ve ortalama güç, plaka, istasyon, şarj ünitesi seri no ve kartlı ödeme bilgisi.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#16a34a',
        xslt: hazirPath('ev-sarj-fatura', 'xslt'),
        xml: hazirPath('ev-sarj-fatura', 'xml'),
        tags: ['ENERJI · SARJANLIK', 'kWh & süre', 'Plaka', 'İstasyon / soket', 'Kartlı ödeme'],
    },
];
