import { hazirPath, type SectorTemplate } from '../types';

/** TIR / uluslararası nakliye, yurtiçi nakliye, kargo-kurye, otobüs-yolcu taşıma. */
export const TASIMA_TEMPLATES: SectorTemplate[] = [
    {
        id: 'tir-uluslararasi-nakliye',
        sector: 'uluslararasi-nakliye',
        name: 'TIR Uluslararası Nakliye Faturası',
        description: 'Uluslararası karayolu taşımacıları için güzergâh haritası bandı, AB/TR çekici-dorse plakaları, CMR ve sefer referansları, EUR tutar + TCMB kuru ile TL karşılığı ve KDV 311 istisnalı nakliye faturası.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#1d4ed8',
        xslt: hazirPath('tir-uluslararasi-nakliye', 'xslt'),
        xml: hazirPath('tir-uluslararasi-nakliye', 'xml'),
        tags: ['Güzergâh haritası', 'İstisna 311', 'EUR + kur / TL karşılığı', 'Çekici & dorse plakası', 'CMR referansı'],
    },
    {
        id: 'tir-yukleme-irsaliye',
        sector: 'uluslararasi-nakliye',
        name: 'TIR Yükleme İrsaliyesi (CMR Görünümlü)',
        description: 'İhracat yüklemeleri için CMR formu gibi numaralı kutular; gümrük kapısı teslim adresi, mühür numaraları, GTİP kodlu yük tablosu, koli/palet/brüt-net ağırlık toplamları, Incoterms ve imza alanları.',
        docTypeId: 'irsaliye',
        moduleId: 'irsaliye',
        accent: '#b91c1c',
        xslt: hazirPath('tir-yukleme-irsaliye', 'xslt'),
        xml: hazirPath('tir-yukleme-irsaliye', 'xml'),
        tags: ['CMR kutuları', 'GTİP kodu', 'Mühür numaraları', 'Brüt / net kg & palet', 'Incoterms'],
    },
    {
        id: 'nakliye-tevkifatli-fatura',
        sector: 'lojistik',
        name: 'Yurtiçi Nakliye Faturası (Tevkifatlı)',
        description: 'Yük taşımacılığı firmaları için otoyol levhası temalı; sefer bazında yükleme–teslim noktası, plaka ve tarih satırları, araç bazlı filo özeti ve 2/10 KDV tevkifatı (624) uyarılı aylık nakliye faturası.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#15803d',
        xslt: hazirPath('nakliye-tevkifatli-fatura', 'xslt'),
        xml: hazirPath('nakliye-tevkifatli-fatura', 'xml'),
        tags: ['Tevkifat 624 · 2/10', 'Sefer satırları', 'Yükleme → teslim', 'Araç bazlı özet', 'Plaka'],
    },
    {
        id: 'kargo-gonderi-arsiv',
        sector: 'kargo',
        name: 'Kargo Gönderi e-Arşiv Faturası',
        description: 'Şube gönderileri için termal kargo etiketi görünümlü üst bölüm (takip barkodu, desi, ödeme tipi, servis) ve kesim çizgisinin altında bireysel müşteriye e-Arşiv fatura.',
        docTypeId: 'arsiv',
        moduleId: 'arsiv',
        accent: '#f59e0b',
        xslt: hazirPath('kargo-gonderi-arsiv', 'xslt'),
        xml: hazirPath('kargo-gonderi-arsiv', 'xml'),
        tags: ['Takip barkodu', 'Desi', 'Gönderici / alıcı', 'Ödeme tipi', 'Termal etiket'],
    },
    {
        id: 'kargo-kurumsal-aylik',
        sector: 'kargo',
        name: 'Kurumsal Aylık Kargo Faturası',
        description: 'E-ticaret ve kurumsal müşterilere aylık toplu kargo faturası; gönderi/desi/tahsilat/iade özet kartları, hizmet grubu dağılım çubuğu, grup başlıkları ve ara toplamlı hizmet tablosu.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#7c3aed',
        xslt: hazirPath('kargo-kurumsal-aylik', 'xslt'),
        xml: hazirPath('kargo-kurumsal-aylik', 'xml'),
        tags: ['Aylık dönem', 'Özet kartları', 'Hizmet grubu ara toplamı', 'Ortalama desi', 'Sözleşme no'],
    },
    {
        id: 'kurye-moto-arsiv',
        sector: 'kargo',
        name: 'Moto Kurye e-Arşiv Faturası',
        description: 'Şehir içi moto kurye teslimatları için sipariş → alım → teslim zaman çizelgesi, mesafe ve bekleme metrikleri, teslim süresi garantisi rozeti ve kurye/plaka kartlı e-Arşiv fatura.',
        docTypeId: 'arsiv',
        moduleId: 'arsiv',
        accent: '#e11d48',
        xslt: hazirPath('kurye-moto-arsiv', 'xslt'),
        xml: hazirPath('kurye-moto-arsiv', 'xml'),
        tags: ['Zaman çizelgesi', 'Mesafe (km)', 'Bekleme süresi', 'Kurye & plaka', 'Ekspres servis'],
    },
    {
        id: 'otobus-yolcu-bilet',
        sector: 'yolcu-tasima',
        name: 'Otobüs e-Bilet (Biniş Kartı)',
        description: 'Şehirlerarası otobüs firmaları için koparılabilir koçanlı biniş kartı tasarımı; kalkış–varış otogarları, sefer günü ve yolculuk süresi, peron, koltuk, plaka, PNR ve KDV dahil bilet bedeli.',
        docTypeId: 'bilet',
        moduleId: 'bilet',
        accent: '#ea580c',
        xslt: hazirPath('otobus-yolcu-bilet', 'xslt'),
        xml: hazirPath('otobus-yolcu-bilet', 'xml'),
        tags: ['Biniş kartı', 'Kalkış → varış', 'Koltuk & peron', 'Yolculuk süresi', 'PNR'],
    },
    {
        id: 'otobus-yolcu-listesi',
        sector: 'yolcu-tasima',
        name: 'Otobüs e-Yolcu Listesi (Sefer Manifestosu)',
        description: 'Sefer başlık kartı (sefer no, hareket saati ve noktası, plaka), 2+1 koltuk planı ve doluluk oranı, yolcu tablosu, toplam hasılat ve taşıtı işleten komisyon bilgili e-Yolcu Listesi görünümü.',
        docTypeId: 'bilet-yolcu',
        moduleId: 'bilet-yolcu',
        accent: '#9a3412',
        xslt: hazirPath('otobus-yolcu-listesi', 'xslt'),
        xml: hazirPath('otobus-yolcu-listesi', 'xml'),
        tags: ['Sefer kartı', '2+1 koltuk planı', 'Doluluk oranı', 'Toplam hasılat', 'İşleten komisyonu'],
    },
];
