import { hazirPath, type SectorTemplate } from '../types';

/** Ticaret ikinci dalga: perakende, e-ticaret, toptan/hal, kuyumcu-döviz, hurda. */
export const TICARET2_TEMPLATES: SectorTemplate[] = [
    {
        id: 'perakende-iade-fatura',
        sector: 'perakende',
        name: 'Mağaza İade Faturası',
        description: 'Mağazanın tedarikçiye kestiği iade faturası: asıl fatura ve iade irsaliyesi bilet kartları, satır bazında iade nedeni çipleri, "İADE" filigranlı kırmızı şeritli tasarım.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#be123c',
        xslt: hazirPath('perakende-iade-fatura', 'xslt'),
        xml: hazirPath('perakende-iade-fatura', 'xml'),
        tags: ['iade', 'perakende', 'tekstil', 'BillingReference', 'iade nedeni'],
    },
    {
        id: 'market-zincir-arsiv',
        sector: 'perakende',
        name: 'Zincir Market Fişi e-Arşiv',
        description: 'Süpermarket e-Arşiv faturası: raf etiketi başlık, kasa/fiş/kasiyer çipleri, tartılı ürün rozetli fiş listesi, KDV grup (A/B/C) dökümü ve sadakat kartı puan paneli.',
        docTypeId: 'arsiv',
        moduleId: 'arsiv',
        accent: '#15803d',
        xslt: hazirPath('market-zincir-arsiv', 'xslt'),
        xml: hazirPath('market-zincir-arsiv', 'xml'),
        tags: ['market', 'perakende', 'KDV %1/%10/%20', 'tartılı', 'sadakat puanı'],
    },
    {
        id: 'eticaret-pazaryeri-komisyon',
        sector: 'eticaret',
        name: 'Pazaryeri Komisyon Faturası',
        description: 'Pazaryerinin satıcı mağazaya kestiği aylık komisyon ve hizmet faturası: koyu yan panelli finans paneli görünümü, hakediş dönemi, gösterge kutucukları ve kalem payı çubukları.',
        docTypeId: 'fatura',
        moduleId: 'fatura',
        accent: '#0891b2',
        xslt: hazirPath('eticaret-pazaryeri-komisyon', 'xslt'),
        xml: hazirPath('eticaret-pazaryeri-komisyon', 'xml'),
        tags: ['pazaryeri', 'komisyon', 'hakediş', 'TICARIFATURA', 'dashboard'],
    },
    {
        id: 'eticaret-abonelik-arsiv',
        sector: 'eticaret',
        name: 'Abonelik Kutusu e-Arşiv',
        description: 'Aylık abonelik kutusu için internet satışı e-Arşiv faturası: pastel renkler, abonelik ilerleme noktaları, evcil dost kartı, kargo/ödeme aracısı paneli ve bilet tarzı toplam.',
        docTypeId: 'arsiv',
        moduleId: 'arsiv',
        accent: '#f472b6',
        xslt: hazirPath('eticaret-abonelik-arsiv', 'xslt'),
        xml: hazirPath('eticaret-abonelik-arsiv', 'xml'),
        tags: ['abonelik', 'internet satışı', 'e-Arşiv', 'kargo', 'evcil hayvan'],
    },
    {
        id: 'hal-hks-irsaliye',
        sector: 'toptan',
        name: 'Hal Künyeli Sevk İrsaliyesi',
        description: 'Hal komisyoncusunun HKS sevk irsaliyesi: kraft kâğıt dokusu, ıslak mühür başlık, satır bazında künye barkodu ve üretici, kasa adetleri, plaka/dorse ve şoför şeridi.',
        docTypeId: 'irsaliye',
        moduleId: 'irsaliye',
        accent: '#92400e',
        xslt: hazirPath('hal-hks-irsaliye', 'xslt'),
        xml: hazirPath('hal-hks-irsaliye', 'xml'),
        tags: ['HKS', 'hal', 'künye', 'sebze meyve', 'HKSIRSALIYE'],
    },
    {
        id: 'kuyumcu-altin-alim',
        sector: 'kuyumcu',
        name: 'Hurda Altın Alım Raporu',
        description: 'Kuyumcunun müşteriden hurda altın aldığı kıymetli maden ALIM belgesi: milimetrik kâğıt üzerinde ayar analiz tablosu (milyem, has gram, saflık çubuğu) ve değerleme göstergeleri.',
        docTypeId: 'doviz',
        moduleId: 'doviz',
        accent: '#c2410c',
        xslt: hazirPath('kuyumcu-altin-alim', 'xslt'),
        xml: hazirPath('kuyumcu-altin-alim', 'xml'),
        tags: ['kıymetli maden', 'ALIM', 'hurda altın', 'milyem', 'has gram'],
    },
    {
        id: 'doviz-burosu-satim',
        sector: 'kuyumcu',
        name: 'Döviz Bürosu Satım Fişi',
        description: 'Döviz bürosunun müşteriye efektif sattığı SATIM belgesi: siyah LED kur panosu, TL → döviz akış kutuları, banknot kupür kartları ve BSMV dahil ödenecek tutar.',
        docTypeId: 'doviz',
        moduleId: 'doviz-satim',
        accent: '#f59e0b',
        xslt: hazirPath('doviz-burosu-satim', 'xslt'),
        xml: hazirPath('doviz-burosu-satim', 'xml'),
        tags: ['döviz', 'SATIM', 'kur panosu', 'BSMV', 'efektif'],
    },
    {
        id: 'hurda-gider-pusulasi',
        sector: 'geri-donusum',
        name: 'Hurda Alım Gider Pusulası',
        description: 'Geri dönüşüm firmasının bireyden hurda alımı için e-Gider Pusulası: perçinli çelik başlık, BRÜT/DARA/NET kantar göstergeleri, malzeme renk kartelası ve %2 stopaj dökümü.',
        docTypeId: 'gider-pusulasi',
        moduleId: 'gider-pusulasi',
        accent: '#4d7c0f',
        xslt: hazirPath('hurda-gider-pusulasi', 'xslt'),
        xml: hazirPath('hurda-gider-pusulasi', 'xml'),
        tags: ['hurda', 'geri dönüşüm', 'kantar', 'stopaj', 'SMS'],
    },
];
