import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Factura núm.',
        date: 'Data d’emissió',
        due: 'Data de venciment',
        currency: 'Moneda',
        buyerRef: 'Ref. del comprador',
        order: 'Núm. de comanda',
        contract: 'Contracte',
        project: 'Projecte',
        preceding: 'Factura rectificada',
        period: 'Període de facturació',
        delivery: 'Data de lliurament',
        deliverTo: 'Lloc de lliurament',
        seller: 'Venedor',
        buyer: 'Comprador',
        payee: 'Beneficiari',
        vat: 'NIF-IVA',
        taxNo: 'NIF',
        reg: 'Identificador legal',
        endpoint: 'Adreça electrònica',
        contact: 'Contacte',
        lines: 'Línies de factura',
        pos: 'Núm.',
        item: 'Descripció',
        itemNo: 'Ref.',
        qty: 'Quantitat',
        price: 'Preu unitari',
        vatRate: 'IVA',
        net: 'Import net',
        allowances: 'Descomptes i càrrecs',
        allowance: 'Descompte',
        charge: 'Càrrec',
        vatBreakdown: 'Desglossament de l’IVA',
        category: 'Categoria',
        taxable: 'Base imposable',
        taxAmount: 'Quota d’IVA',
        sumLines: 'Suma de línies',
        totalAllow: 'Descomptes',
        totalCharge: 'Càrrecs',
        taxExcl: 'Total sense IVA',
        taxTotal: 'Total IVA',
        taxAccounting: 'IVA en moneda comptable',
        taxIncl: 'Total amb IVA',
        prepaid: 'Import pagat',
        rounding: 'Arrodoniment',
        payable: 'Import a pagar',
        payment: 'Dades de pagament',
        means: 'Mitjà de pagament',
        accountName: 'Titular del compte',
        remittance: 'Referència de pagament',
        mandate: 'Referència del mandat',
        card: 'Targeta',
        terms: 'Condicions de pagament',
        notes: 'Notes',
        legal: 'Aquesta vista és una representació llegible; la factura amb validesa legal és el fitxer XML.',
        pcs: 'u.',
        hour: 'h',
        day: 'dia',
        month: 'mes',
        lumpsum: 'global',
        m10: 'Efectiu',
        m30: 'Transferència',
        m42: 'Pagament en compte bancari',
        m48: 'Targeta bancària',
        m49: 'Domiciliació bancària',
        m54: 'Targeta de crèdit',
        m57: 'Acord permanent',
        m58: 'Transferència SEPA',
        m59: 'Càrrec directe SEPA',
        catS: 'Tipus general',
        catZ: 'Tipus zero',
        catE: 'Exempt',
        catAE: 'Inversió del subjecte passiu',
        catK: 'Lliurament intracomunitari',
        catG: 'Exportació fora de la UE',
        catO: 'No subjecte a IVA',
    },
    despatch: {
        date: 'Data d’emissió',
        order: 'Núm. de comanda',
        supplier: 'Expedidor',
        deliveryParty: 'Destinatari',
        buyer: 'Comprador',
        seller: 'Venedor',
        endpoint: 'Adreça electrònica',
        partyId: 'Identificador',
        contact: 'Contacte',
        shipment: 'Enviament',
        shipmentId: 'ID de l’enviament',
        despatched: 'Data d’expedició',
        estimated: 'Lliurament previst',
        carrier: 'Transportista',
        tracking: 'Núm. de seguiment',
        weight: 'Pes brut',
        volume: 'Volum',
        deliverTo: 'Adreça de lliurament',
        units: 'Bults',
        lines: 'Línies expedides',
        pos: 'Núm.',
        item: 'Article',
        itemNo: 'Ref.',
        orderLine: 'Línia de comanda',
        lot: 'Lot',
        expiry: 'Caducitat',
        delivered: 'Lliurat',
        backorder: 'Pendent',
        notes: 'Notes',
        legal: 'Aquesta vista és una representació llegible de l’albarà XML.',
        pcs: 'u.',
        pallet: 'Palet',
    },
};

export default xslt;
