import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Číslo faktury',
        date: 'Datum vystavení',
        due: 'Datum splatnosti',
        currency: 'Měna',
        buyerRef: 'Reference odběratele',
        order: 'Objednávka',
        contract: 'Smlouva',
        project: 'Projekt',
        preceding: 'Původní faktura',
        period: 'Fakturační období',
        delivery: 'Datum dodání',
        deliverTo: 'Místo dodání',
        seller: 'Dodavatel',
        buyer: 'Odběratel',
        payee: 'Příjemce platby',
        vat: 'DIČ',
        taxNo: 'Daňové číslo',
        reg: 'IČO',
        endpoint: 'Elektronická adresa',
        contact: 'Kontakt',
        lines: 'Položky faktury',
        pos: 'Č.',
        item: 'Popis',
        itemNo: 'Kód',
        qty: 'Množství',
        price: 'Cena za jedn.',
        vatRate: 'DPH',
        net: 'Bez DPH',
        allowances: 'Slevy a příplatky',
        allowance: 'Sleva',
        charge: 'Příplatek',
        vatBreakdown: 'Rekapitulace DPH',
        category: 'Kategorie',
        taxable: 'Základ daně',
        taxAmount: 'Výše DPH',
        sumLines: 'Součet položek bez DPH',
        totalAllow: 'Slevy',
        totalCharge: 'Příplatky',
        taxExcl: 'Celkem bez DPH',
        taxTotal: 'DPH celkem',
        taxAccounting: 'DPH v účetní měně',
        taxIncl: 'Celkem s DPH',
        prepaid: 'Uhrazeno',
        rounding: 'Zaokrouhlení',
        payable: 'K úhradě',
        payment: 'Platební údaje',
        means: 'Způsob platby',
        accountName: 'Majitel účtu',
        remittance: 'Variabilní symbol',
        mandate: 'Mandát k inkasu',
        card: 'Karta',
        terms: 'Platební podmínky',
        notes: 'Poznámky',
        legal: 'Toto je čitelné zobrazení; právně platnou fakturou je soubor XML.',
        pcs: 'ks',
        hour: 'hod',
        day: 'den',
        month: 'měs.',
        lumpsum: 'paušál',
        m10: 'Hotově',
        m30: 'Bankovním převodem',
        m42: 'Platba na bankovní účet',
        m48: 'Platební karta',
        m49: 'Inkaso',
        m54: 'Kreditní karta',
        m57: 'Trvalý příkaz',
        m58: 'Převod SEPA',
        m59: 'Inkaso SEPA',
        catS: 'Základní sazba',
        catZ: 'Nulová sazba',
        catE: 'Osvobozeno od DPH',
        catAE: 'Přenesená daňová povinnost',
        catK: 'Dodání zboží do jiného členského státu',
        catG: 'Vývoz mimo EU',
        catO: 'Nepodléhá DPH',
    },
    despatch: {
        date: 'Datum vystavení',
        order: 'Objednávka',
        supplier: 'Odesílatel',
        deliveryParty: 'Příjemce',
        buyer: 'Odběratel',
        seller: 'Dodavatel',
        endpoint: 'Elektronická adresa',
        partyId: 'Identifikátor',
        contact: 'Kontakt',
        shipment: 'Zásilka',
        shipmentId: 'Číslo zásilky',
        despatched: 'Odesláno',
        estimated: 'Předpokládané dodání',
        carrier: 'Dopravce',
        tracking: 'Sledovací číslo',
        weight: 'Hmotnost brutto',
        volume: 'Objem',
        deliverTo: 'Dodací adresa',
        units: 'Přepravní jednotky',
        lines: 'Dodané položky',
        pos: 'Č.',
        item: 'Položka',
        itemNo: 'Kód',
        orderLine: 'Řádek objednávky',
        lot: 'Šarže',
        expiry: 'Spotřebujte do',
        delivered: 'Dodáno',
        backorder: 'Nedodáno',
        notes: 'Poznámky',
        legal: 'Toto je čitelné zobrazení avíza o odeslání ve formátu XML.',
        pcs: 'ks',
        pallet: 'Paleta',
    },
};

export default xslt;
