import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Fakturanr.',
        date: 'Fakturadato',
        due: 'Forfaldsdato',
        currency: 'Valuta',
        buyerRef: 'Deres reference',
        order: 'Ordrereference',
        contract: 'Kontrakt',
        project: 'Projekt',
        preceding: 'Tidligere faktura',
        period: 'Faktureringsperiode',
        delivery: 'Leveringsdato',
        deliverTo: 'Leveringsadresse',
        seller: 'Sælger',
        buyer: 'Køber',
        payee: 'Betalingsmodtager',
        vat: 'Momsnr.',
        taxNo: 'Skattenr.',
        reg: 'CVR-nr.',
        endpoint: 'Elektronisk adresse',
        contact: 'Kontaktperson',
        lines: 'Fakturalinjer',
        pos: 'Nr.',
        item: 'Beskrivelse',
        itemNo: 'Varenr.',
        qty: 'Antal',
        price: 'Enhedspris',
        vatRate: 'Moms',
        net: 'Nettobeløb',
        allowances: 'Rabatter og gebyrer',
        allowance: 'Rabat',
        charge: 'Gebyr',
        vatBreakdown: 'Momsspecifikation',
        category: 'Kategori',
        taxable: 'Momsgrundlag',
        taxAmount: 'Momsbeløb',
        sumLines: 'Sum af linjer netto',
        totalAllow: 'Rabatter',
        totalCharge: 'Gebyrer',
        taxExcl: 'I alt ekskl. moms',
        taxTotal: 'Moms i alt',
        taxAccounting: 'Moms i regnskabsvaluta',
        taxIncl: 'I alt inkl. moms',
        prepaid: 'Betalt beløb',
        rounding: 'Afrunding',
        payable: 'Til betaling',
        payment: 'Betalingsoplysninger',
        means: 'Betalingsform',
        accountName: 'Kontonavn',
        remittance: 'Betalingsreference',
        mandate: 'Mandatreference',
        card: 'Kort',
        terms: 'Betalingsbetingelser',
        notes: 'Bemærkninger',
        legal: 'Dette er en læsbar visning; XML-filen er den juridisk gyldige faktura.',
        pcs: 'stk.',
        hour: 't.',
        day: 'dag',
        month: 'md.',
        lumpsum: 'fast pris',
        m10: 'Kontant',
        m30: 'Bankoverførsel',
        m42: 'Betaling til bankkonto',
        m48: 'Betalingskort',
        m49: 'Direkte debitering',
        m54: 'Kreditkort',
        m57: 'Fast aftale',
        m58: 'SEPA-overførsel',
        m59: 'SEPA direkte debitering',
        catS: 'Standardsats',
        catZ: 'Nulsats',
        catE: 'Momsfritaget',
        catAE: 'Omvendt betalingspligt',
        catK: 'Levering inden for EU',
        catG: 'Eksport uden for EU',
        catO: 'Ikke momspligtig',
    },
    despatch: {
        date: 'Dato',
        order: 'Ordrereference',
        supplier: 'Afsender',
        deliveryParty: 'Modtager',
        buyer: 'Køber',
        seller: 'Sælger',
        endpoint: 'Elektronisk adresse',
        partyId: 'ID',
        contact: 'Kontaktperson',
        shipment: 'Forsendelse',
        shipmentId: 'Forsendelses-ID',
        despatched: 'Afsendt',
        estimated: 'Forventet levering',
        carrier: 'Transportør',
        tracking: 'Sporingsnummer',
        weight: 'Bruttovægt',
        volume: 'Volumen',
        deliverTo: 'Leveringsadresse',
        units: 'Kolli',
        lines: 'Afsendte varer',
        pos: 'Nr.',
        item: 'Vare',
        itemNo: 'Varenr.',
        orderLine: 'Ordrelinje',
        lot: 'Batch',
        expiry: 'Udløb',
        delivered: 'Leveret',
        backorder: 'Restordre',
        notes: 'Bemærkninger',
        legal: 'Dette er en læsbar visning af XML-følgesedlen.',
        pcs: 'stk.',
        pallet: 'Palle',
    },
};

export default xslt;
