/**
 * XSLT etiket kaynağı (İngilizce). Diğer belge dillerinin dosyaları bu anahtarların
 * tamamını içermek zorundadır; `scripts/build-intl-xslt-labels.mjs` bunları
 * public/ebelge/intl/*.xslt içindeki |dil=metin| satırlarına yazar.
 * Belge başlıkları (invoice, credit, …, despatch) burada değil, `../<dil>.ts` titles içindedir.
 */
const xslt = {
    invoice: {
        number: 'Invoice no.',
        date: 'Issue date',
        due: 'Due date',
        currency: 'Currency',
        buyerRef: 'Buyer reference',
        order: 'Order reference',
        contract: 'Contract',
        project: 'Project',
        preceding: 'Preceding invoice',
        period: 'Invoice period',
        delivery: 'Delivery date',
        deliverTo: 'Deliver to',
        seller: 'Seller',
        buyer: 'Buyer',
        payee: 'Payee',
        vat: 'VAT ID',
        taxNo: 'Tax number',
        reg: 'Legal registration',
        endpoint: 'Electronic address',
        contact: 'Contact',
        lines: 'Invoice lines',
        pos: '#',
        item: 'Description',
        itemNo: 'Item no.',
        qty: 'Quantity',
        price: 'Unit price',
        vatRate: 'VAT',
        net: 'Net amount',
        allowances: 'Allowances and charges',
        allowance: 'Allowance',
        charge: 'Charge',
        vatBreakdown: 'VAT breakdown',
        category: 'Category',
        taxable: 'Taxable amount',
        taxAmount: 'VAT amount',
        sumLines: 'Sum of line net amounts',
        totalAllow: 'Allowances',
        totalCharge: 'Charges',
        taxExcl: 'Total without VAT',
        taxTotal: 'Total VAT',
        taxAccounting: 'VAT in accounting currency',
        taxIncl: 'Total with VAT',
        prepaid: 'Paid amount',
        rounding: 'Rounding',
        payable: 'Amount due',
        payment: 'Payment details',
        means: 'Payment means',
        accountName: 'Account name',
        remittance: 'Payment reference',
        mandate: 'Mandate reference',
        card: 'Card',
        terms: 'Payment terms',
        notes: 'Notes',
        legal: 'This is a human-readable rendering; the XML file is the legally valid invoice.',
        pcs: 'pcs',
        hour: 'h',
        day: 'day',
        month: 'month',
        lumpsum: 'lump sum',
        m10: 'Cash',
        m30: 'Credit transfer',
        m42: 'Payment to bank account',
        m48: 'Bank card',
        m49: 'Direct debit',
        m54: 'Credit card',
        m57: 'Standing agreement',
        m58: 'SEPA credit transfer',
        m59: 'SEPA direct debit',
        catS: 'Standard rate',
        catZ: 'Zero rated',
        catE: 'Exempt',
        catAE: 'Reverse charge',
        catK: 'Intra-community supply',
        catG: 'Export outside the EU',
        catO: 'Not subject to VAT',
    },
    despatch: {
        date: 'Issue date',
        order: 'Order reference',
        supplier: 'Despatch party',
        deliveryParty: 'Delivery party',
        buyer: 'Buyer',
        seller: 'Seller',
        endpoint: 'Electronic address',
        partyId: 'Identifier',
        contact: 'Contact',
        shipment: 'Shipment',
        shipmentId: 'Shipment ID',
        despatched: 'Despatched',
        estimated: 'Estimated delivery',
        carrier: 'Carrier',
        tracking: 'Tracking ID',
        weight: 'Gross weight',
        volume: 'Volume',
        deliverTo: 'Delivery address',
        units: 'Handling units',
        lines: 'Despatched lines',
        pos: '#',
        item: 'Item',
        itemNo: 'Item no.',
        orderLine: 'Order line',
        lot: 'Lot',
        expiry: 'Expiry',
        delivered: 'Delivered',
        backorder: 'Backorder',
        notes: 'Notes',
        legal: 'This is a human-readable rendering of the XML despatch advice.',
        pcs: 'pcs',
        pallet: 'Pallet',
    },
};

export type XsltLabels = typeof xslt;
export default xslt;
