import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Arve nr',
        date: 'Arve kuupäev',
        due: 'Maksetähtaeg',
        currency: 'Valuuta',
        buyerRef: 'Ostja viide',
        order: 'Tellimuse viide',
        contract: 'Leping',
        project: 'Projekt',
        preceding: 'Eelnev arve',
        period: 'Arveldusperiood',
        delivery: 'Tarnekuupäev',
        deliverTo: 'Tarneaadress',
        seller: 'Müüja',
        buyer: 'Ostja',
        payee: 'Makse saaja',
        vat: 'KMKR nr',
        taxNo: 'Maksunumber',
        reg: 'Registrikood',
        endpoint: 'E-arve aadress',
        contact: 'Kontaktisik',
        lines: 'Arveread',
        pos: 'Nr',
        item: 'Kirjeldus',
        itemNo: 'Tootekood',
        qty: 'Kogus',
        price: 'Ühikuhind',
        vatRate: 'KM',
        net: 'Netosumma',
        allowances: 'Allahindlused ja lisatasud',
        allowance: 'Allahindlus',
        charge: 'Lisatasu',
        vatBreakdown: 'Käibemaksu jaotus',
        category: 'Kategooria',
        taxable: 'Maksustatav summa',
        taxAmount: 'Käibemaks',
        sumLines: 'Ridade netosumma',
        totalAllow: 'Allahindlused',
        totalCharge: 'Lisatasud',
        taxExcl: 'Summa käibemaksuta',
        taxTotal: 'Käibemaks kokku',
        taxAccounting: 'KM arvestusvaluutas',
        taxIncl: 'Summa käibemaksuga',
        prepaid: 'Tasutud',
        rounding: 'Ümardus',
        payable: 'Tasuda',
        payment: 'Makseandmed',
        means: 'Makseviis',
        accountName: 'Konto omanik',
        remittance: 'Viitenumber',
        mandate: 'Volituse viide',
        card: 'Kaart',
        terms: 'Maksetingimused',
        notes: 'Märkused',
        legal: 'See on inimloetav esitus; juriidiliselt kehtiv arve on XML-fail.',
        pcs: 'tk',
        hour: 'h',
        day: 'päev',
        month: 'kuu',
        lumpsum: 'kompl',
        m10: 'Sularaha',
        m30: 'Pangaülekanne',
        m42: 'Makse pangakontole',
        m48: 'Pangakaart',
        m49: 'Otsekorraldus',
        m54: 'Krediitkaart',
        m57: 'Püsikorraldus',
        m58: 'SEPA ülekanne',
        m59: 'SEPA otsekorraldus',
        catS: 'Standardmäär',
        catZ: 'Nullmäär',
        catE: 'Maksuvaba',
        catAE: 'Pöördmaksustamine',
        catK: 'Ühendusesisene käive',
        catG: 'Eksport väljapoole ELi',
        catO: 'Ei kuulu käibemaksu alla',
    },
    despatch: {
        date: 'Kuupäev',
        order: 'Tellimuse viide',
        supplier: 'Saatja',
        deliveryParty: 'Kauba saaja',
        buyer: 'Ostja',
        seller: 'Müüja',
        endpoint: 'E-aadress',
        partyId: 'Tunnus',
        contact: 'Kontaktisik',
        shipment: 'Saadetis',
        shipmentId: 'Saadetise tunnus',
        despatched: 'Lähetatud',
        estimated: 'Eeldatav tarne',
        carrier: 'Vedaja',
        tracking: 'Jälgimisnumber',
        weight: 'Brutokaal',
        volume: 'Maht',
        deliverTo: 'Tarneaadress',
        units: 'Transpordiühikud',
        lines: 'Lähetatud read',
        pos: 'Nr',
        item: 'Kaup',
        itemNo: 'Tootekood',
        orderLine: 'Tellimuse rida',
        lot: 'Partii',
        expiry: 'Kõlblik kuni',
        delivered: 'Tarnitud',
        backorder: 'Järeltarne',
        notes: 'Märkused',
        legal: 'See on XML-saatelehe inimloetav esitus.',
        pcs: 'tk',
        pallet: 'Alus',
    },
};

export default xslt;
