import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Faktura zk.',
        date: 'Jaulkipen-data',
        due: 'Muga-eguna',
        currency: 'Moneta',
        buyerRef: 'Eroslearen erref.',
        order: 'Eskaera zk.',
        contract: 'Kontratua',
        project: 'Proiektua',
        preceding: 'Faktura zuzendua',
        period: 'Fakturazio-aldia',
        delivery: 'Entrega-data',
        deliverTo: 'Entrega-lekua',
        seller: 'Saltzailea',
        buyer: 'Eroslea',
        payee: 'Onuraduna',
        vat: 'IFZ-BEZ',
        taxNo: 'IFZ',
        reg: 'Identifikatzaile legala',
        endpoint: 'Helbide elektronikoa',
        contact: 'Harremana',
        lines: 'Fakturaren lerroak',
        pos: 'Zk.',
        item: 'Deskribapena',
        itemNo: 'Erref.',
        qty: 'Kantitatea',
        price: 'Unitate-prezioa',
        vatRate: 'BEZ',
        net: 'Zenbateko garbia',
        allowances: 'Deskontuak eta kargak',
        allowance: 'Deskontua',
        charge: 'Karga',
        vatBreakdown: 'BEZaren xehapena',
        category: 'Kategoria',
        taxable: 'Zerga-oinarria',
        taxAmount: 'BEZ kuota',
        sumLines: 'Lerroen batura',
        totalAllow: 'Deskontuak',
        totalCharge: 'Kargak',
        taxExcl: 'Guztira BEZik gabe',
        taxTotal: 'BEZa guztira',
        taxAccounting: 'BEZa kontabilitate-monetan',
        taxIncl: 'Guztira BEZa barne',
        prepaid: 'Ordaindutako zenbatekoa',
        rounding: 'Biribiltzea',
        payable: 'Ordaintzeko zenbatekoa',
        payment: 'Ordainketa-datuak',
        means: 'Ordainbidea',
        accountName: 'Kontuaren titularra',
        remittance: 'Ordainketa-erreferentzia',
        mandate: 'Aginduaren erreferentzia',
        card: 'Txartela',
        terms: 'Ordainketa-baldintzak',
        notes: 'Oharrak',
        legal: 'Ikuspegi hau irakurtzeko moduko irudikapena da; balio juridikoa duen faktura XML fitxategia da.',
        pcs: 'ud.',
        hour: 'h',
        day: 'egun',
        month: 'hilabete',
        lumpsum: 'globala',
        m10: 'Eskudirua',
        m30: 'Transferentzia',
        m42: 'Banku-kontuan ordaintzea',
        m48: 'Banku-txartela',
        m49: 'Banku-helbideratzea',
        m54: 'Kreditu-txartela',
        m57: 'Akordio iraunkorra',
        m58: 'SEPA transferentzia',
        m59: 'SEPA zordunketa zuzena',
        catS: 'Tasa orokorra',
        catZ: 'Zero tasa',
        catE: 'Salbuetsia',
        catAE: 'Subjektu pasiboaren inbertsioa',
        catK: 'Erkidego barruko entrega',
        catG: 'EBtik kanpoko esportazioa',
        catO: 'BEZaren kargapean ez',
    },
    despatch: {
        date: 'Jaulkipen-data',
        order: 'Eskaera zk.',
        supplier: 'Bidaltzailea',
        deliveryParty: 'Hartzailea',
        buyer: 'Eroslea',
        seller: 'Saltzailea',
        endpoint: 'Helbide elektronikoa',
        partyId: 'Identifikatzailea',
        contact: 'Harremana',
        shipment: 'Bidalketa',
        shipmentId: 'Bidalketaren IDa',
        despatched: 'Bidalketa-data',
        estimated: 'Aurreikusitako entrega',
        carrier: 'Garraiolaria',
        tracking: 'Jarraipen zk.',
        weight: 'Pisu gordina',
        volume: 'Bolumena',
        deliverTo: 'Entrega-helbidea',
        units: 'Fardoak',
        lines: 'Bidalitako lerroak',
        pos: 'Zk.',
        item: 'Artikulua',
        itemNo: 'Erref.',
        orderLine: 'Eskaera-lerroa',
        lot: 'Lotea',
        expiry: 'Iraungitzea',
        delivered: 'Entregatua',
        backorder: 'Zain',
        notes: 'Oharrak',
        legal: 'Ikuspegi hau XML albaranaren irakurtzeko moduko irudikapena da.',
        pcs: 'ud.',
        pallet: 'Paleta',
    },
};

export default xslt;
