import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Laskun nro',
        date: 'Laskun pvm',
        due: 'Eräpäivä',
        currency: 'Valuutta',
        buyerRef: 'Viitteenne',
        order: 'Tilausviite',
        contract: 'Sopimus',
        project: 'Projekti',
        preceding: 'Aiempi lasku',
        period: 'Laskutuskausi',
        delivery: 'Toimituspäivä',
        deliverTo: 'Toimitusosoite',
        seller: 'Myyjä',
        buyer: 'Ostaja',
        payee: 'Maksunsaaja',
        vat: 'ALV-tunniste',
        taxNo: 'Veronumero',
        reg: 'Y-tunnus',
        endpoint: 'Verkkolaskuosoite',
        contact: 'Yhteyshenkilö',
        lines: 'Laskurivit',
        pos: 'Nro',
        item: 'Kuvaus',
        itemNo: 'Tuotenro',
        qty: 'Määrä',
        price: 'À-hinta',
        vatRate: 'ALV',
        net: 'Netto',
        allowances: 'Alennukset ja lisämaksut',
        allowance: 'Alennus',
        charge: 'Lisämaksu',
        vatBreakdown: 'ALV-erittely',
        category: 'Luokka',
        taxable: 'Veron peruste',
        taxAmount: 'ALV:n määrä',
        sumLines: 'Rivit yhteensä',
        totalAllow: 'Alennukset',
        totalCharge: 'Lisämaksut',
        taxExcl: 'Yhteensä veroton',
        taxTotal: 'ALV yhteensä',
        taxAccounting: 'ALV kirjanpitovaluutassa',
        taxIncl: 'Yhteensä verollinen',
        prepaid: 'Maksettu',
        rounding: 'Pyöristys',
        payable: 'Maksettava',
        payment: 'Maksutiedot',
        means: 'Maksutapa',
        accountName: 'Tilin nimi',
        remittance: 'Viitenumero',
        mandate: 'Valtuutuksen viite',
        card: 'Kortti',
        terms: 'Maksuehdot',
        notes: 'Lisätiedot',
        legal: 'Tämä on luettava esitys; oikeudellisesti pätevä lasku on XML-tiedosto.',
        pcs: 'kpl',
        hour: 'h',
        day: 'pv',
        month: 'kk',
        lumpsum: 'erä',
        m10: 'Käteinen',
        m30: 'Tilisiirto',
        m42: 'Maksu pankkitilille',
        m48: 'Pankkikortti',
        m49: 'Suoraveloitus',
        m54: 'Luottokortti',
        m57: 'Pysyvä sopimus',
        m58: 'SEPA-tilisiirto',
        m59: 'SEPA-suoraveloitus',
        catS: 'Yleinen verokanta',
        catZ: 'Nollaverokanta',
        catE: 'Verovapaa',
        catAE: 'Käännetty verovelvollisuus',
        catK: 'Yhteisömyynti',
        catG: 'Vienti EU:n ulkopuolelle',
        catO: 'Ei ALV:n alainen',
    },
    despatch: {
        date: 'Päivämäärä',
        order: 'Tilausviite',
        supplier: 'Lähettäjä',
        deliveryParty: 'Vastaanottaja',
        buyer: 'Ostaja',
        seller: 'Myyjä',
        endpoint: 'Sähköinen osoite',
        partyId: 'Tunniste',
        contact: 'Yhteyshenkilö',
        shipment: 'Lähetys',
        shipmentId: 'Lähetyksen tunniste',
        despatched: 'Lähetetty',
        estimated: 'Arvioitu toimitus',
        carrier: 'Kuljetusliike',
        tracking: 'Seurantanumero',
        weight: 'Bruttopaino',
        volume: 'Tilavuus',
        deliverTo: 'Toimitusosoite',
        units: 'Kuljetusyksiköt',
        lines: 'Lähetetyt rivit',
        pos: 'Nro',
        item: 'Tuote',
        itemNo: 'Tuotenro',
        orderLine: 'Tilausrivi',
        lot: 'Erä',
        expiry: 'Viimeinen käyttöpäivä',
        delivered: 'Toimitettu',
        backorder: 'Jälkitoimitus',
        notes: 'Lisätiedot',
        legal: 'Tämä on XML-lähetysilmoituksen luettava esitys.',
        pcs: 'kpl',
        pallet: 'Lava',
    },
};

export default xslt;
