import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Uimh. sonraisc',
        date: 'Dáta eisiúna',
        due: 'Dáta dlite',
        currency: 'Airgeadra',
        buyerRef: 'Tagairt an cheannaitheora',
        order: 'Tagairt ordaithe',
        contract: 'Conradh',
        project: 'Tionscadal',
        preceding: 'Sonrasc roimhe seo',
        period: 'Tréimhse sonrascaithe',
        delivery: 'Dáta seachadta',
        deliverTo: 'Seoladh seachadta',
        seller: 'Díoltóir',
        buyer: 'Ceannaitheoir',
        payee: 'Íocaí',
        vat: 'Uimhir CBL',
        taxNo: 'Uimhir chánach',
        reg: 'Clárú dlíthiúil',
        endpoint: 'Seoladh leictreonach',
        contact: 'Teagmháil',
        lines: 'Línte sonraisc',
        pos: 'Uimh.',
        item: 'Cur síos',
        itemNo: 'Uimh. míre',
        qty: 'Cainníocht',
        price: 'Praghas aonaid',
        vatRate: 'CBL',
        net: 'Glanmhéid',
        allowances: 'Lascainí agus muirir',
        allowance: 'Lascaine',
        charge: 'Muirear',
        vatBreakdown: 'Miondealú CBL',
        category: 'Catagóir',
        taxable: 'Méid incháinithe',
        taxAmount: 'Méid CBL',
        sumLines: 'Suim na nglanmhéideanna líne',
        totalAllow: 'Lascainí',
        totalCharge: 'Muirir',
        taxExcl: 'Iomlán gan CBL',
        taxTotal: 'CBL iomlán',
        taxAccounting: 'CBL san airgeadra cuntasaíochta',
        taxIncl: 'Iomlán le CBL',
        prepaid: 'Méid íoctha',
        rounding: 'Slánú',
        payable: 'Méid dlite',
        payment: 'Sonraí íocaíochta',
        means: 'Modh íocaíochta',
        accountName: 'Ainm an chuntais',
        remittance: 'Tagairt íocaíochta',
        mandate: 'Tagairt an tsainordaithe',
        card: 'Cárta',
        terms: 'Téarmaí íocaíochta',
        notes: 'Nótaí',
        legal: 'Is léiriú inléite é seo; is é an comhad XML an sonrasc atá bailí go dlíthiúil.',
        pcs: 'píosaí',
        hour: 'uair',
        day: 'lá',
        month: 'mí',
        lumpsum: 'cnapshuim',
        m10: 'Airgead tirim',
        m30: 'Aistriú creidmheasa',
        m42: 'Íocaíocht chuig cuntas bainc',
        m48: 'Cárta bainc',
        m49: 'Dochar díreach',
        m54: 'Cárta creidmheasa',
        m57: 'Comhaontú buan',
        m58: 'Aistriú creidmheasa SEPA',
        m59: 'Dochar díreach SEPA',
        catS: 'Ráta caighdeánach',
        catZ: 'Ráta nialasach',
        catE: 'Díolmhaithe',
        catAE: 'Aisiompú muirir',
        catK: 'Soláthar laistigh den Chomhphobal',
        catG: 'Onnmhairiú lasmuigh den AE',
        catO: 'Nach bhfuil faoi réir CBL',
    },
    despatch: {
        date: 'Dáta eisiúna',
        order: 'Tagairt ordaithe',
        supplier: 'Seoltóir',
        deliveryParty: 'Faighteoir',
        buyer: 'Ceannaitheoir',
        seller: 'Díoltóir',
        endpoint: 'Seoladh leictreonach',
        partyId: 'Aitheantóir',
        contact: 'Teagmháil',
        shipment: 'Lastas',
        shipmentId: 'ID an lastais',
        despatched: 'Dáta seolta',
        estimated: 'Seachadadh measta',
        carrier: 'Iompróir',
        tracking: 'Uimh. rianaithe',
        weight: 'Meáchan comhlán',
        volume: 'Toirt',
        deliverTo: 'Seoladh seachadta',
        units: 'Aonaid láimhseála',
        lines: 'Línte seolta',
        pos: 'Uimh.',
        item: 'Mír',
        itemNo: 'Uimh. míre',
        orderLine: 'Líne ordaithe',
        lot: 'Baisc',
        expiry: 'Dáta éaga',
        delivered: 'Seachadta',
        backorder: 'Fós le seachadadh',
        notes: 'Nótaí',
        legal: 'Is léiriú inléite é seo ar an bhfógra seolta XML.',
        pcs: 'píosaí',
        pallet: 'Pailléad',
    },
};

export default xslt;
