import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Factura n.º',
        date: 'Data de emisión',
        due: 'Data de vencemento',
        currency: 'Moeda',
        buyerRef: 'Ref. do comprador',
        order: 'N.º de pedido',
        contract: 'Contrato',
        project: 'Proxecto',
        preceding: 'Factura rectificada',
        period: 'Período de facturación',
        delivery: 'Data de entrega',
        deliverTo: 'Lugar de entrega',
        seller: 'Vendedor',
        buyer: 'Comprador',
        payee: 'Beneficiario',
        vat: 'NIF-IVE',
        taxNo: 'NIF',
        reg: 'Identificador legal',
        endpoint: 'Enderezo electrónico',
        contact: 'Contacto',
        lines: 'Liñas da factura',
        pos: 'N.º',
        item: 'Descrición',
        itemNo: 'Ref.',
        qty: 'Cantidade',
        price: 'Prezo unitario',
        vatRate: 'IVE',
        net: 'Importe neto',
        allowances: 'Descontos e cargos',
        allowance: 'Desconto',
        charge: 'Cargo',
        vatBreakdown: 'Desagregación do IVE',
        category: 'Categoría',
        taxable: 'Base impoñible',
        taxAmount: 'Cota de IVE',
        sumLines: 'Suma de liñas',
        totalAllow: 'Descontos',
        totalCharge: 'Cargos',
        taxExcl: 'Total sen IVE',
        taxTotal: 'Total IVE',
        taxAccounting: 'IVE en moeda contable',
        taxIncl: 'Total con IVE',
        prepaid: 'Importe pagado',
        rounding: 'Arredondamento',
        payable: 'Importe a pagar',
        payment: 'Datos de pagamento',
        means: 'Medio de pagamento',
        accountName: 'Titular da conta',
        remittance: 'Referencia de pagamento',
        mandate: 'Referencia do mandato',
        card: 'Tarxeta',
        terms: 'Condicións de pagamento',
        notes: 'Notas',
        legal: 'Esta vista é unha representación lexible; a factura con validez legal é o ficheiro XML.',
        pcs: 'ud.',
        hour: 'h',
        day: 'día',
        month: 'mes',
        lumpsum: 'global',
        m10: 'Efectivo',
        m30: 'Transferencia',
        m42: 'Pagamento en conta bancaria',
        m48: 'Tarxeta bancaria',
        m49: 'Domiciliación bancaria',
        m54: 'Tarxeta de crédito',
        m57: 'Acordo permanente',
        m58: 'Transferencia SEPA',
        m59: 'Adebedo directo SEPA',
        catS: 'Tipo xeral',
        catZ: 'Tipo cero',
        catE: 'Exento',
        catAE: 'Inversión do suxeito pasivo',
        catK: 'Entrega intracomunitaria',
        catG: 'Exportación fóra da UE',
        catO: 'Non suxeito a IVE',
    },
    despatch: {
        date: 'Data de emisión',
        order: 'N.º de pedido',
        supplier: 'Expedidor',
        deliveryParty: 'Destinatario',
        buyer: 'Comprador',
        seller: 'Vendedor',
        endpoint: 'Enderezo electrónico',
        partyId: 'Identificador',
        contact: 'Contacto',
        shipment: 'Envío',
        shipmentId: 'ID do envío',
        despatched: 'Data de expedición',
        estimated: 'Entrega prevista',
        carrier: 'Transportista',
        tracking: 'N.º de seguimento',
        weight: 'Peso bruto',
        volume: 'Volume',
        deliverTo: 'Enderezo de entrega',
        units: 'Vultos',
        lines: 'Liñas expedidas',
        pos: 'N.º',
        item: 'Artigo',
        itemNo: 'Ref.',
        orderLine: 'Liña de pedido',
        lot: 'Lote',
        expiry: 'Caducidade',
        delivered: 'Entregado',
        backorder: 'Pendente',
        notes: 'Notas',
        legal: 'Esta vista é unha representación lexible do albará XML.',
        pcs: 'ud.',
        pallet: 'Palé',
    },
};

export default xslt;
