import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Broj računa',
        date: 'Datum izdavanja',
        due: 'Datum dospijeća',
        currency: 'Valuta',
        buyerRef: 'Referenca kupca',
        order: 'Narudžba',
        contract: 'Ugovor',
        project: 'Projekt',
        preceding: 'Prethodni račun',
        period: 'Obračunsko razdoblje',
        delivery: 'Datum isporuke',
        deliverTo: 'Mjesto isporuke',
        seller: 'Prodavatelj',
        buyer: 'Kupac',
        payee: 'Primatelj plaćanja',
        vat: 'PDV ID broj',
        taxNo: 'Porezni broj',
        reg: 'Matični broj',
        endpoint: 'Elektronička adresa',
        contact: 'Kontakt',
        lines: 'Stavke računa',
        pos: 'R. br.',
        item: 'Opis',
        itemNo: 'Šifra',
        qty: 'Količina',
        price: 'Jed. cijena',
        vatRate: 'PDV',
        net: 'Neto iznos',
        allowances: 'Popusti i dodatni troškovi',
        allowance: 'Popust',
        charge: 'Dodatni trošak',
        vatBreakdown: 'Rekapitulacija PDV-a',
        category: 'Kategorija',
        taxable: 'Porezna osnovica',
        taxAmount: 'Iznos PDV-a',
        sumLines: 'Zbroj neto iznosa stavki',
        totalAllow: 'Popusti',
        totalCharge: 'Dodatni troškovi',
        taxExcl: 'Ukupno bez PDV-a',
        taxTotal: 'Ukupno PDV',
        taxAccounting: 'PDV u obračunskoj valuti',
        taxIncl: 'Ukupno s PDV-om',
        prepaid: 'Plaćeno',
        rounding: 'Zaokruživanje',
        payable: 'Za platiti',
        payment: 'Podaci za plaćanje',
        means: 'Način plaćanja',
        accountName: 'Vlasnik računa',
        remittance: 'Poziv na broj',
        mandate: 'Referenca suglasnosti',
        card: 'Kartica',
        terms: 'Uvjeti plaćanja',
        notes: 'Napomene',
        legal: 'Ovo je čitljiv prikaz; pravno valjani račun je XML datoteka.',
        pcs: 'kom',
        hour: 'sat',
        day: 'dan',
        month: 'mjesec',
        lumpsum: 'paušal',
        m10: 'Gotovina',
        m30: 'Kreditni transfer',
        m42: 'Uplata na bankovni račun',
        m48: 'Bankovna kartica',
        m49: 'Izravno terećenje',
        m54: 'Kreditna kartica',
        m57: 'Trajni nalog',
        m58: 'SEPA kreditni transfer',
        m59: 'SEPA izravno terećenje',
        catS: 'Standardna stopa',
        catZ: 'Nulta stopa',
        catE: 'Oslobođeno',
        catAE: 'Prijenos porezne obveze',
        catK: 'Isporuka unutar EU',
        catG: 'Izvoz izvan EU',
        catO: 'Nije predmet PDV-a',
    },
    despatch: {
        date: 'Datum izdavanja',
        order: 'Narudžba',
        supplier: 'Pošiljatelj',
        deliveryParty: 'Primatelj',
        buyer: 'Kupac',
        seller: 'Prodavatelj',
        endpoint: 'Elektronička adresa',
        partyId: 'Identifikator',
        contact: 'Kontakt',
        shipment: 'Pošiljka',
        shipmentId: 'ID pošiljke',
        despatched: 'Otpremljeno',
        estimated: 'Očekivana isporuka',
        carrier: 'Prijevoznik',
        tracking: 'Broj za praćenje',
        weight: 'Bruto težina',
        volume: 'Volumen',
        deliverTo: 'Adresa isporuke',
        units: 'Transportne jedinice',
        lines: 'Otpremljene stavke',
        pos: 'R. br.',
        item: 'Artikl',
        itemNo: 'Šifra',
        orderLine: 'Stavka narudžbe',
        lot: 'Lot',
        expiry: 'Rok trajanja',
        delivered: 'Isporučeno',
        backorder: 'Naknadna isporuka',
        notes: 'Napomene',
        legal: 'Ovo je čitljiv prikaz XML otpremnice.',
        pcs: 'kom',
        pallet: 'Paleta',
    },
};

export default xslt;
