import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Számlaszám',
        date: 'Kiállítás dátuma',
        due: 'Fizetési határidő',
        currency: 'Pénznem',
        buyerRef: 'Vevői hivatkozás',
        order: 'Megrendelés',
        contract: 'Szerződés',
        project: 'Projekt',
        preceding: 'Előzmény számla',
        period: 'Elszámolási időszak',
        delivery: 'Teljesítés dátuma',
        deliverTo: 'Szállítási cím',
        seller: 'Eladó',
        buyer: 'Vevő',
        payee: 'Kedvezményezett',
        vat: 'Közösségi adószám',
        taxNo: 'Adószám',
        reg: 'Cégjegyzékszám',
        endpoint: 'Elektronikus cím',
        contact: 'Kapcsolattartó',
        lines: 'Számlatételek',
        pos: 'Ssz.',
        item: 'Megnevezés',
        itemNo: 'Cikkszám',
        qty: 'Mennyiség',
        price: 'Egységár',
        vatRate: 'ÁFA',
        net: 'Nettó érték',
        allowances: 'Engedmények és felárak',
        allowance: 'Engedmény',
        charge: 'Felár',
        vatBreakdown: 'ÁFA-összesítő',
        category: 'Kategória',
        taxable: 'Adóalap',
        taxAmount: 'ÁFA összege',
        sumLines: 'Tételek nettó összege',
        totalAllow: 'Engedmények',
        totalCharge: 'Felárak',
        taxExcl: 'Nettó összesen',
        taxTotal: 'ÁFA összesen',
        taxAccounting: 'ÁFA az elszámolási pénznemben',
        taxIncl: 'Bruttó összesen',
        prepaid: 'Kifizetett összeg',
        rounding: 'Kerekítés',
        payable: 'Fizetendő',
        payment: 'Fizetési adatok',
        means: 'Fizetési mód',
        accountName: 'Számlatulajdonos',
        remittance: 'Közlemény',
        mandate: 'Megbízás azonosítója',
        card: 'Kártya',
        terms: 'Fizetési feltételek',
        notes: 'Megjegyzések',
        legal: 'Ez egy olvasható megjelenítés; a jogilag érvényes számla az XML-fájl.',
        pcs: 'db',
        hour: 'óra',
        day: 'nap',
        month: 'hónap',
        lumpsum: 'átalány',
        m10: 'Készpénz',
        m30: 'Átutalás',
        m42: 'Bankszámlára fizetés',
        m48: 'Bankkártya',
        m49: 'Csoportos beszedés',
        m54: 'Hitelkártya',
        m57: 'Állandó megbízás',
        m58: 'SEPA-átutalás',
        m59: 'SEPA csoportos beszedés',
        catS: 'Általános adókulcs',
        catZ: 'Nulla százalékos kulcs',
        catE: 'Adómentes',
        catAE: 'Fordított adózás',
        catK: 'Közösségen belüli értékesítés',
        catG: 'EU-n kívüli export',
        catO: 'ÁFA hatályán kívül',
    },
    despatch: {
        date: 'Kiállítás dátuma',
        order: 'Megrendelés',
        supplier: 'Feladó',
        deliveryParty: 'Átvevő',
        buyer: 'Vevő',
        seller: 'Eladó',
        endpoint: 'Elektronikus cím',
        partyId: 'Azonosító',
        contact: 'Kapcsolattartó',
        shipment: 'Küldemény',
        shipmentId: 'Küldeményazonosító',
        despatched: 'Feladva',
        estimated: 'Várható kézbesítés',
        carrier: 'Fuvarozó',
        tracking: 'Nyomkövetési szám',
        weight: 'Bruttó tömeg',
        volume: 'Térfogat',
        deliverTo: 'Szállítási cím',
        units: 'Szállítási egységek',
        lines: 'Szállított tételek',
        pos: 'Ssz.',
        item: 'Termék',
        itemNo: 'Cikkszám',
        orderLine: 'Megrendelési tétel',
        lot: 'Sarzs',
        expiry: 'Lejárat',
        delivered: 'Szállítva',
        backorder: 'Hátralék',
        notes: 'Megjegyzések',
        legal: 'Ez az XML szállítási értesítő olvasható megjelenítése.',
        pcs: 'db',
        pallet: 'Raklap',
    },
};

export default xslt;
