import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Reikningsnr.',
        date: 'Útgáfudagur',
        due: 'Gjalddagi',
        currency: 'Gjaldmiðill',
        buyerRef: 'Tilvísun kaupanda',
        order: 'Pöntun',
        contract: 'Samningur',
        project: 'Verkefni',
        preceding: 'Fyrri reikningur',
        period: 'Reikningstímabil',
        delivery: 'Afhendingardagur',
        deliverTo: 'Afhendingarstaður',
        seller: 'Seljandi',
        buyer: 'Kaupandi',
        payee: 'Greiðsluviðtakandi',
        vat: 'VSK-númer',
        taxNo: 'Skattnúmer',
        reg: 'Kennitala',
        endpoint: 'Rafrænt heimilisfang',
        contact: 'Tengiliður',
        lines: 'Reikningslínur',
        pos: 'Nr.',
        item: 'Lýsing',
        itemNo: 'Vörunr.',
        qty: 'Magn',
        price: 'Einingarverð',
        vatRate: 'VSK',
        net: 'Nettóupphæð',
        allowances: 'Afslættir og gjöld',
        allowance: 'Afsláttur',
        charge: 'Gjald',
        vatBreakdown: 'Sundurliðun VSK',
        category: 'Flokkur',
        taxable: 'Skattstofn',
        taxAmount: 'VSK-upphæð',
        sumLines: 'Samtala nettóupphæða lína',
        totalAllow: 'Afslættir',
        totalCharge: 'Gjöld',
        taxExcl: 'Samtals án VSK',
        taxTotal: 'VSK samtals',
        taxAccounting: 'VSK í uppgjörsgjaldmiðli',
        taxIncl: 'Samtals með VSK',
        prepaid: 'Greitt',
        rounding: 'Námundun',
        payable: 'Til greiðslu',
        payment: 'Greiðsluupplýsingar',
        means: 'Greiðslumáti',
        accountName: 'Reikningseigandi',
        remittance: 'Greiðslutilvísun',
        mandate: 'Tilvísun heimildar',
        card: 'Kort',
        terms: 'Greiðsluskilmálar',
        notes: 'Athugasemdir',
        legal: 'Þetta er læsileg framsetning; XML-skráin er hinn lagalega gildi reikningur.',
        pcs: 'stk.',
        hour: 'klst.',
        day: 'dagur',
        month: 'mánuður',
        lumpsum: 'fast gjald',
        m10: 'Reiðufé',
        m30: 'Millifærsla',
        m42: 'Greiðsla inn á bankareikning',
        m48: 'Bankakort',
        m49: 'Beingreiðsla',
        m54: 'Kreditkort',
        m57: 'Fastur greiðslusamningur',
        m58: 'SEPA-millifærsla',
        m59: 'SEPA-beingreiðsla',
        catS: 'Almennt þrep',
        catZ: 'Núllhlutfall',
        catE: 'Undanþegið',
        catAE: 'Öfug skattskylda',
        catK: 'Afhending innan ESB',
        catG: 'Útflutningur út fyrir ESB',
        catO: 'Utan gildissviðs VSK',
    },
    despatch: {
        date: 'Útgáfudagur',
        order: 'Pöntun',
        supplier: 'Sendandi',
        deliveryParty: 'Viðtakandi',
        buyer: 'Kaupandi',
        seller: 'Seljandi',
        endpoint: 'Rafrænt heimilisfang',
        partyId: 'Auðkenni',
        contact: 'Tengiliður',
        shipment: 'Sending',
        shipmentId: 'Auðkenni sendingar',
        despatched: 'Sent',
        estimated: 'Áætluð afhending',
        carrier: 'Flutningsaðili',
        tracking: 'Rakningarnúmer',
        weight: 'Brúttóþyngd',
        volume: 'Rúmmál',
        deliverTo: 'Afhendingarstaður',
        units: 'Flutningseiningar',
        lines: 'Sendar línur',
        pos: 'Nr.',
        item: 'Vara',
        itemNo: 'Vörunr.',
        orderLine: 'Pöntunarlína',
        lot: 'Lota',
        expiry: 'Fyrningardagur',
        delivered: 'Afhent',
        backorder: 'Í bið',
        notes: 'Athugasemdir',
        legal: 'Þetta er læsileg framsetning á XML-fylgiseðlinum.',
        pcs: 'stk.',
        pallet: 'Bretti',
    },
};

export default xslt;
