import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Fattura n.',
        date: 'Data emissione',
        due: 'Scadenza',
        currency: 'Valuta',
        buyerRef: 'Rif. acquirente',
        order: 'Rif. ordine',
        contract: 'Contratto',
        project: 'Progetto',
        preceding: 'Fattura precedente',
        period: 'Periodo di fatturazione',
        delivery: 'Data consegna',
        deliverTo: 'Luogo di consegna',
        seller: 'Venditore',
        buyer: 'Acquirente',
        payee: 'Beneficiario',
        vat: 'Partita IVA',
        taxNo: 'Codice fiscale',
        reg: 'Iscrizione registro imprese',
        endpoint: 'Indirizzo elettronico',
        contact: 'Referente',
        lines: 'Righe fattura',
        pos: 'N.',
        item: 'Descrizione',
        itemNo: 'Codice art.',
        qty: 'Quantità',
        price: 'Prezzo unitario',
        vatRate: 'IVA',
        net: 'Importo netto',
        allowances: 'Sconti e maggiorazioni',
        allowance: 'Sconto',
        charge: 'Maggiorazione',
        vatBreakdown: 'Riepilogo IVA',
        category: 'Categoria',
        taxable: 'Imponibile',
        taxAmount: 'Imposta',
        sumLines: 'Totale righe',
        totalAllow: 'Sconti',
        totalCharge: 'Maggiorazioni',
        taxExcl: 'Totale IVA esclusa',
        taxTotal: 'Totale IVA',
        taxAccounting: 'IVA in valuta contabile',
        taxIncl: 'Totale IVA inclusa',
        prepaid: 'Importo pagato',
        rounding: 'Arrotondamento',
        payable: 'Totale da pagare',
        payment: 'Dati di pagamento',
        means: 'Modalità di pagamento',
        accountName: 'Intestatario del conto',
        remittance: 'Causale di pagamento',
        mandate: 'Rif. mandato',
        card: 'Carta',
        terms: 'Condizioni di pagamento',
        notes: 'Note',
        legal: 'Questa è una rappresentazione leggibile; la fattura con valore legale è il file XML.',
        pcs: 'pz',
        hour: 'h',
        day: 'giorno',
        month: 'mese',
        lumpsum: 'forfait',
        m10: 'Contanti',
        m30: 'Bonifico',
        m42: 'Pagamento su conto bancario',
        m48: 'Carta bancaria',
        m49: 'Addebito diretto',
        m54: 'Carta di credito',
        m57: 'Accordo permanente',
        m58: 'Bonifico SEPA',
        m59: 'Addebito diretto SEPA',
        catS: 'Aliquota ordinaria',
        catZ: 'Aliquota zero',
        catE: 'Esente',
        catAE: 'Inversione contabile',
        catK: 'Cessione intracomunitaria',
        catG: 'Esportazione extra UE',
        catO: 'Fuori campo IVA',
    },
    despatch: {
        date: 'Data emissione',
        order: 'Rif. ordine',
        supplier: 'Mittente',
        deliveryParty: 'Destinatario',
        buyer: 'Acquirente',
        seller: 'Venditore',
        endpoint: 'Indirizzo elettronico',
        partyId: 'Identificativo',
        contact: 'Referente',
        shipment: 'Spedizione',
        shipmentId: 'ID spedizione',
        despatched: 'Data spedizione',
        estimated: 'Consegna prevista',
        carrier: 'Vettore',
        tracking: 'N. tracciamento',
        weight: 'Peso lordo',
        volume: 'Volume',
        deliverTo: 'Luogo di destinazione',
        units: 'Colli',
        lines: 'Righe spedite',
        pos: 'N.',
        item: 'Articolo',
        itemNo: 'Codice art.',
        orderLine: 'Riga ordine',
        lot: 'Lotto',
        expiry: 'Scadenza',
        delivered: 'Consegnato',
        backorder: 'Inevaso',
        notes: 'Note',
        legal: 'Questa è una rappresentazione leggibile dell’avviso di spedizione XML.',
        pcs: 'pz',
        pallet: 'Pallet',
    },
};

export default xslt;
