import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Sąskaitos faktūros Nr.',
        date: 'Išrašymo data',
        due: 'Apmokėti iki',
        currency: 'Valiuta',
        buyerRef: 'Pirkėjo nuoroda',
        order: 'Užsakymo nuoroda',
        contract: 'Sutartis',
        project: 'Projektas',
        preceding: 'Ankstesnė sąskaita faktūra',
        period: 'Atsiskaitymo laikotarpis',
        delivery: 'Pristatymo data',
        deliverTo: 'Pristatymo adresas',
        seller: 'Pardavėjas',
        buyer: 'Pirkėjas',
        payee: 'Mokėjimo gavėjas',
        vat: 'PVM mokėtojo kodas',
        taxNo: 'Mokesčių mokėtojo kodas',
        reg: 'Įmonės kodas',
        endpoint: 'Elektroninis adresas',
        contact: 'Kontaktinis asmuo',
        lines: 'Sąskaitos eilutės',
        pos: 'Eil. Nr.',
        item: 'Pavadinimas',
        itemNo: 'Prekės kodas',
        qty: 'Kiekis',
        price: 'Kaina',
        vatRate: 'PVM',
        net: 'Suma be PVM',
        allowances: 'Nuolaidos ir priemokos',
        allowance: 'Nuolaida',
        charge: 'Priemoka',
        vatBreakdown: 'PVM suvestinė',
        category: 'Kategorija',
        taxable: 'Apmokestinamoji vertė',
        taxAmount: 'PVM suma',
        sumLines: 'Eilučių suma be PVM',
        totalAllow: 'Nuolaidos',
        totalCharge: 'Priemokos',
        taxExcl: 'Iš viso be PVM',
        taxTotal: 'PVM iš viso',
        taxAccounting: 'PVM apskaitos valiuta',
        taxIncl: 'Iš viso su PVM',
        prepaid: 'Sumokėta',
        rounding: 'Apvalinimas',
        payable: 'Mokėtina suma',
        payment: 'Mokėjimo informacija',
        means: 'Mokėjimo būdas',
        accountName: 'Sąskaitos savininkas',
        remittance: 'Mokėjimo paskirtis',
        mandate: 'Sutikimo nuoroda',
        card: 'Kortelė',
        terms: 'Mokėjimo sąlygos',
        notes: 'Pastabos',
        legal: 'Tai žmogui skaitomas vaizdas; teisiškai galiojanti sąskaita faktūra yra XML failas.',
        pcs: 'vnt.',
        hour: 'val.',
        day: 'd.',
        month: 'mėn.',
        lumpsum: 'kompl.',
        m10: 'Grynieji pinigai',
        m30: 'Kredito pervedimas',
        m42: 'Mokėjimas į banko sąskaitą',
        m48: 'Banko kortelė',
        m49: 'Tiesioginis debetas',
        m54: 'Kredito kortelė',
        m57: 'Periodinis mokėjimas',
        m58: 'SEPA kredito pervedimas',
        m59: 'SEPA tiesioginis debetas',
        catS: 'Standartinis tarifas',
        catZ: 'Nulinis tarifas',
        catE: 'Neapmokestinama',
        catAE: 'Atvirkštinis apmokestinimas',
        catK: 'Tiekimas Bendrijos viduje',
        catG: 'Eksportas už ES ribų',
        catO: 'Ne PVM objektas',
    },
    despatch: {
        date: 'Išrašymo data',
        order: 'Užsakymo nuoroda',
        supplier: 'Siuntėjas',
        deliveryParty: 'Krovinio gavėjas',
        buyer: 'Pirkėjas',
        seller: 'Pardavėjas',
        endpoint: 'Elektroninis adresas',
        partyId: 'Identifikatorius',
        contact: 'Kontaktinis asmuo',
        shipment: 'Siunta',
        shipmentId: 'Siuntos ID',
        despatched: 'Išsiųsta',
        estimated: 'Numatomas pristatymas',
        carrier: 'Vežėjas',
        tracking: 'Sekimo Nr.',
        weight: 'Bruto svoris',
        volume: 'Tūris',
        deliverTo: 'Pristatymo adresas',
        units: 'Transporto vienetai',
        lines: 'Išsiųstos prekės',
        pos: 'Eil. Nr.',
        item: 'Prekė',
        itemNo: 'Prekės kodas',
        orderLine: 'Užsakymo eilutė',
        lot: 'Partija',
        expiry: 'Tinka iki',
        delivered: 'Pristatyta',
        backorder: 'Nepristatyta',
        notes: 'Pastabos',
        legal: 'Tai žmogui skaitomas XML važtaraščio vaizdas.',
        pcs: 'vnt.',
        pallet: 'Padėklas',
    },
};

export default xslt;
