import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Rēķina nr.',
        date: 'Izrakstīšanas datums',
        due: 'Apmaksas termiņš',
        currency: 'Valūta',
        buyerRef: 'Pircēja atsauce',
        order: 'Pasūtījuma atsauce',
        contract: 'Līgums',
        project: 'Projekts',
        preceding: 'Iepriekšējais rēķins',
        period: 'Norēķinu periods',
        delivery: 'Piegādes datums',
        deliverTo: 'Piegādes adrese',
        seller: 'Pārdevējs',
        buyer: 'Pircējs',
        payee: 'Maksājuma saņēmējs',
        vat: 'PVN reģ. nr.',
        taxNo: 'Nodokļu maksātāja nr.',
        reg: 'Reģ. nr.',
        endpoint: 'Elektroniskā adrese',
        contact: 'Kontaktpersona',
        lines: 'Rēķina rindas',
        pos: 'Nr.',
        item: 'Nosaukums',
        itemNo: 'Preces kods',
        qty: 'Daudzums',
        price: 'Cena',
        vatRate: 'PVN',
        net: 'Summa bez PVN',
        allowances: 'Atlaides un piemaksas',
        allowance: 'Atlaide',
        charge: 'Piemaksa',
        vatBreakdown: 'PVN sadalījums',
        category: 'Kategorija',
        taxable: 'Apliekamā summa',
        taxAmount: 'PVN summa',
        sumLines: 'Rindu summa bez PVN',
        totalAllow: 'Atlaides',
        totalCharge: 'Piemaksas',
        taxExcl: 'Kopā bez PVN',
        taxTotal: 'PVN kopā',
        taxAccounting: 'PVN uzskaites valūtā',
        taxIncl: 'Kopā ar PVN',
        prepaid: 'Samaksāts',
        rounding: 'Noapaļošana',
        payable: 'Summa apmaksai',
        payment: 'Maksājuma informācija',
        means: 'Maksājuma veids',
        accountName: 'Konta īpašnieks',
        remittance: 'Maksājuma mērķis',
        mandate: 'Pilnvaras atsauce',
        card: 'Karte',
        terms: 'Apmaksas noteikumi',
        notes: 'Piezīmes',
        legal: 'Šis ir cilvēkam lasāms attēlojums; juridiski derīgais rēķins ir XML fails.',
        pcs: 'gab.',
        hour: 'st.',
        day: 'd.',
        month: 'mēn.',
        lumpsum: 'kompl.',
        m10: 'Skaidra nauda',
        m30: 'Pārskaitījums',
        m42: 'Maksājums uz bankas kontu',
        m48: 'Bankas karte',
        m49: 'Tiešais debets',
        m54: 'Kredītkarte',
        m57: 'Pastāvīgais rīkojums',
        m58: 'SEPA pārskaitījums',
        m59: 'SEPA tiešais debets',
        catS: 'Standarta likme',
        catZ: 'Nulles likme',
        catE: 'Atbrīvots no PVN',
        catAE: 'Apgrieztā maksāšana',
        catK: 'Piegāde Kopienas iekšienē',
        catG: 'Eksports ārpus ES',
        catO: 'Neapliekams ar PVN',
    },
    despatch: {
        date: 'Izrakstīšanas datums',
        order: 'Pasūtījuma atsauce',
        supplier: 'Nosūtītājs',
        deliveryParty: 'Kravas saņēmējs',
        buyer: 'Pircējs',
        seller: 'Pārdevējs',
        endpoint: 'Elektroniskā adrese',
        partyId: 'Identifikators',
        contact: 'Kontaktpersona',
        shipment: 'Sūtījums',
        shipmentId: 'Sūtījuma ID',
        despatched: 'Nosūtīts',
        estimated: 'Paredzamā piegāde',
        carrier: 'Pārvadātājs',
        tracking: 'Izsekošanas nr.',
        weight: 'Bruto svars',
        volume: 'Tilpums',
        deliverTo: 'Piegādes adrese',
        units: 'Transporta vienības',
        lines: 'Nosūtītās preces',
        pos: 'Nr.',
        item: 'Prece',
        itemNo: 'Preces kods',
        orderLine: 'Pasūtījuma rinda',
        lot: 'Partija',
        expiry: 'Derīgs līdz',
        delivered: 'Piegādāts',
        backorder: 'Nepiegādāts',
        notes: 'Piezīmes',
        legal: 'Šis ir XML pavadzīmes cilvēkam lasāms attēlojums.',
        pcs: 'gab.',
        pallet: 'Palete',
    },
};

export default xslt;
