import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Fattura Nru',
        date: 'Data tal-ħruġ',
        due: 'Data tal-iskadenza',
        currency: 'Munita',
        buyerRef: 'Ref. tax-xerrej',
        order: 'Ref. tal-ordni',
        contract: 'Kuntratt',
        project: 'Proġett',
        preceding: 'Fattura preċedenti',
        period: 'Perjodu tal-fatturazzjoni',
        delivery: 'Data tal-kunsinna',
        deliverTo: 'Post tal-kunsinna',
        seller: 'Bejjiegħ',
        buyer: 'Xerrej',
        payee: 'Benefiċjarju',
        vat: 'Nru tal-VAT',
        taxNo: 'Nru tat-taxxa (TIN)',
        reg: 'Reġistrazzjoni legali',
        endpoint: 'Indirizz elettroniku',
        contact: 'Kuntatt',
        lines: 'Linji tal-fattura',
        pos: 'Nru',
        item: 'Deskrizzjoni',
        itemNo: 'Nru tal-oġġett',
        qty: 'Kwantità',
        price: 'Prezz unitarju',
        vatRate: 'VAT',
        net: 'Ammont nett',
        allowances: 'Skontijiet u ħlasijiet addizzjonali',
        allowance: 'Skont',
        charge: 'Ħlas addizzjonali',
        vatBreakdown: 'Tqassim tal-VAT',
        category: 'Kategorija',
        taxable: 'Ammont taxxabbli',
        taxAmount: 'Ammont tal-VAT',
        sumLines: 'Total tal-linji',
        totalAllow: 'Skontijiet',
        totalCharge: 'Ħlasijiet addizzjonali',
        taxExcl: 'Total mingħajr VAT',
        taxTotal: 'Total tal-VAT',
        taxAccounting: 'VAT fil-munita tal-kontabilità',
        taxIncl: 'Total inkluż il-VAT',
        prepaid: 'Ammont imħallas',
        rounding: 'Arrotondament',
        payable: 'Ammont dovut',
        payment: 'Dettalji tal-ħlas',
        means: 'Mezz ta’ ħlas',
        accountName: 'Isem tal-kont',
        remittance: 'Referenza tal-ħlas',
        mandate: 'Ref. tal-mandat',
        card: 'Karta',
        terms: 'Termini tal-ħlas',
        notes: 'Noti',
        legal: 'Din hija rappreżentazzjoni li tinqara; il-fattura legalment valida hija l-fajl XML.',
        pcs: 'biċċiet',
        hour: 'siegħa',
        day: 'jum',
        month: 'xahar',
        lumpsum: 'somma f’daqqa',
        m10: 'Flus kontanti',
        m30: 'Trasferiment ta’ kreditu',
        m42: 'Ħlas f’kont bankarju',
        m48: 'Karta bankarja',
        m49: 'Debitu dirett',
        m54: 'Karta ta’ kreditu',
        m57: 'Ftehim permanenti',
        m58: 'Trasferiment ta’ kreditu SEPA',
        m59: 'Debitu dirett SEPA',
        catS: 'Rata standard',
        catZ: 'Rata żero',
        catE: 'Eżenti',
        catAE: 'Inverżjoni tal-ħlas',
        catK: 'Provvista intra-Komunitarja',
        catG: 'Esportazzjoni barra mill-UE',
        catO: 'Mhux suġġett għall-VAT',
    },
    despatch: {
        date: 'Data tal-ħruġ',
        order: 'Ref. tal-ordni',
        supplier: 'Mittent',
        deliveryParty: 'Destinatarju',
        buyer: 'Xerrej',
        seller: 'Bejjiegħ',
        endpoint: 'Indirizz elettroniku',
        partyId: 'Identifikatur',
        contact: 'Kuntatt',
        shipment: 'Spedizzjoni',
        shipmentId: 'ID tal-ispedizzjoni',
        despatched: 'Data tal-ispedizzjoni',
        estimated: 'Kunsinna stmata',
        carrier: 'Trasportatur',
        tracking: 'Nru tal-intraċċar',
        weight: 'Piż gross',
        volume: 'Volum',
        deliverTo: 'Indirizz tal-kunsinna',
        units: 'Unitajiet tal-immaniġġar',
        lines: 'Linji mibgħuta',
        pos: 'Nru',
        item: 'Oġġett',
        itemNo: 'Nru tal-oġġett',
        orderLine: 'Linja tal-ordni',
        lot: 'Lott',
        expiry: 'Skadenza',
        delivered: 'Ikkunsinnat',
        backorder: 'Pendenti',
        notes: 'Noti',
        legal: 'Din hija rappreżentazzjoni li tinqara tal-avviż tal-kunsinna XML.',
        pcs: 'biċċiet',
        pallet: 'Palett',
    },
};

export default xslt;
