import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Fakturanr.',
        date: 'Fakturadato',
        due: 'Forfallsdato',
        currency: 'Valuta',
        buyerRef: 'Deres referanse',
        order: 'Ordrereferanse',
        contract: 'Kontrakt',
        project: 'Prosjekt',
        preceding: 'Tidligere faktura',
        period: 'Faktureringsperiode',
        delivery: 'Leveringsdato',
        deliverTo: 'Leveringsadresse',
        seller: 'Selger',
        buyer: 'Kjøper',
        payee: 'Betalingsmottaker',
        vat: 'Mva-nr.',
        taxNo: 'Skattenummer',
        reg: 'Org.nr.',
        endpoint: 'Elektronisk adresse',
        contact: 'Kontaktperson',
        lines: 'Fakturalinjer',
        pos: 'Nr.',
        item: 'Beskrivelse',
        itemNo: 'Varenr.',
        qty: 'Antall',
        price: 'Enhetspris',
        vatRate: 'Mva',
        net: 'Nettobeløp',
        allowances: 'Rabatter og gebyrer',
        allowance: 'Rabatt',
        charge: 'Gebyr',
        vatBreakdown: 'Mva-spesifikasjon',
        category: 'Kategori',
        taxable: 'Grunnlag',
        taxAmount: 'Mva-beløp',
        sumLines: 'Sum linjer netto',
        totalAllow: 'Rabatter',
        totalCharge: 'Gebyrer',
        taxExcl: 'Sum ekskl. mva',
        taxTotal: 'Sum mva',
        taxAccounting: 'Mva i regnskapsvaluta',
        taxIncl: 'Sum inkl. mva',
        prepaid: 'Betalt beløp',
        rounding: 'Øreavrunding',
        payable: 'Å betale',
        payment: 'Betalingsinformasjon',
        means: 'Betalingsmåte',
        accountName: 'Kontonavn',
        remittance: 'KID / betalingsreferanse',
        mandate: 'Fullmaktsreferanse',
        card: 'Kort',
        terms: 'Betalingsbetingelser',
        notes: 'Merknader',
        legal: 'Dette er en lesbar visning; XML-filen er den juridisk gyldige fakturaen.',
        pcs: 'stk.',
        hour: 't',
        day: 'dag',
        month: 'mnd.',
        lumpsum: 'fastpris',
        m10: 'Kontant',
        m30: 'Bankoverføring',
        m42: 'Betaling til bankkonto',
        m48: 'Bankkort',
        m49: 'Direkte debitering',
        m54: 'Kredittkort',
        m57: 'Fast avtale',
        m58: 'SEPA-overføring',
        m59: 'SEPA direkte debitering',
        catS: 'Standardsats',
        catZ: 'Nullsats',
        catE: 'Unntatt fra mva',
        catAE: 'Omvendt avgiftsplikt',
        catK: 'Levering innen EU/EØS',
        catG: 'Eksport utenfor EU',
        catO: 'Utenfor mva-området',
    },
    despatch: {
        date: 'Dato',
        order: 'Ordrereferanse',
        supplier: 'Avsender',
        deliveryParty: 'Mottaker',
        buyer: 'Kjøper',
        seller: 'Selger',
        endpoint: 'Elektronisk adresse',
        partyId: 'ID',
        contact: 'Kontaktperson',
        shipment: 'Forsendelse',
        shipmentId: 'Forsendelses-ID',
        despatched: 'Sendt',
        estimated: 'Forventet levering',
        carrier: 'Transportør',
        tracking: 'Sporingsnummer',
        weight: 'Bruttovekt',
        volume: 'Volum',
        deliverTo: 'Leveringsadresse',
        units: 'Kolli',
        lines: 'Sendte varer',
        pos: 'Nr.',
        item: 'Vare',
        itemNo: 'Varenr.',
        orderLine: 'Ordrelinje',
        lot: 'Batch',
        expiry: 'Best før',
        delivered: 'Levert',
        backorder: 'Restordre',
        notes: 'Merknader',
        legal: 'Dette er en lesbar visning av XML-følgeseddelen.',
        pcs: 'stk.',
        pallet: 'Pall',
    },
};

export default xslt;
