import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Factuurnr.',
        date: 'Factuurdatum',
        due: 'Vervaldatum',
        currency: 'Valuta',
        buyerRef: 'Uw referentie',
        order: 'Orderreferentie',
        contract: 'Contract',
        project: 'Project',
        preceding: 'Voorgaande factuur',
        period: 'Factuurperiode',
        delivery: 'Leverdatum',
        deliverTo: 'Afleveradres',
        seller: 'Verkoper',
        buyer: 'Koper',
        payee: 'Begunstigde',
        vat: 'Btw-nummer',
        taxNo: 'Fiscaal nummer',
        reg: 'Registratienummer',
        endpoint: 'Elektronisch adres',
        contact: 'Contactpersoon',
        lines: 'Factuurregels',
        pos: 'Nr.',
        item: 'Omschrijving',
        itemNo: 'Art.nr.',
        qty: 'Aantal',
        price: 'Stukprijs',
        vatRate: 'Btw',
        net: 'Nettobedrag',
        allowances: 'Kortingen en toeslagen',
        allowance: 'Korting',
        charge: 'Toeslag',
        vatBreakdown: 'Btw-specificatie',
        category: 'Categorie',
        taxable: 'Grondslag',
        taxAmount: 'Btw-bedrag',
        sumLines: 'Som nettoregelbedragen',
        totalAllow: 'Kortingen',
        totalCharge: 'Toeslagen',
        taxExcl: 'Totaal excl. btw',
        taxTotal: 'Totaal btw',
        taxAccounting: 'Btw in boekingsvaluta',
        taxIncl: 'Totaal incl. btw',
        prepaid: 'Reeds betaald',
        rounding: 'Afronding',
        payable: 'Te betalen',
        payment: 'Betalingsgegevens',
        means: 'Betaalwijze',
        accountName: 'Ten name van',
        remittance: 'Betalingskenmerk',
        mandate: 'Machtigingskenmerk',
        card: 'Kaart',
        terms: 'Betalingsvoorwaarden',
        notes: 'Opmerkingen',
        legal: 'Dit is een leesbare weergave; het XML-bestand is de rechtsgeldige factuur.',
        pcs: 'st.',
        hour: 'uur',
        day: 'dag',
        month: 'maand',
        lumpsum: 'forfait',
        m10: 'Contant',
        m30: 'Overboeking',
        m42: 'Betaling op bankrekening',
        m48: 'Betaalkaart',
        m49: 'Automatische incasso',
        m54: 'Creditcard',
        m57: 'Vaste overeenkomst',
        m58: 'SEPA-overboeking',
        m59: 'SEPA-incasso',
        catS: 'Standaardtarief',
        catZ: 'Nultarief',
        catE: 'Vrijgesteld',
        catAE: 'Btw verlegd',
        catK: 'Intracommunautaire levering',
        catG: 'Export buiten de EU',
        catO: 'Niet onderworpen aan btw',
    },
    despatch: {
        date: 'Datum',
        order: 'Orderreferentie',
        supplier: 'Verzender',
        deliveryParty: 'Ontvanger',
        buyer: 'Koper',
        seller: 'Verkoper',
        endpoint: 'Elektronisch adres',
        partyId: 'Identificatie',
        contact: 'Contactpersoon',
        shipment: 'Zending',
        shipmentId: 'Zendingsnummer',
        despatched: 'Verzonden',
        estimated: 'Verwachte levering',
        carrier: 'Vervoerder',
        tracking: 'Trackingnummer',
        weight: 'Brutogewicht',
        volume: 'Volume',
        deliverTo: 'Afleveradres',
        units: 'Colli',
        lines: 'Verzonden artikelen',
        pos: 'Nr.',
        item: 'Artikel',
        itemNo: 'Art.nr.',
        orderLine: 'Orderregel',
        lot: 'Lot',
        expiry: 'Houdbaar tot',
        delivered: 'Geleverd',
        backorder: 'Nalevering',
        notes: 'Opmerkingen',
        legal: 'Dit is een leesbare weergave van het XML-verzendbericht.',
        pcs: 'st.',
        pallet: 'Pallet',
    },
};

export default xslt;
