import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Nr faktury',
        date: 'Data wystawienia',
        due: 'Termin płatności',
        currency: 'Waluta',
        buyerRef: 'Referencja nabywcy',
        order: 'Nr zamówienia',
        contract: 'Umowa',
        project: 'Projekt',
        preceding: 'Faktura pierwotna',
        period: 'Okres rozliczeniowy',
        delivery: 'Data dostawy',
        deliverTo: 'Miejsce dostawy',
        seller: 'Sprzedawca',
        buyer: 'Nabywca',
        payee: 'Odbiorca płatności',
        vat: 'NIP',
        taxNo: 'Numer podatkowy',
        reg: 'Numer rejestrowy',
        endpoint: 'Adres elektroniczny',
        contact: 'Kontakt',
        lines: 'Pozycje faktury',
        pos: 'Lp.',
        item: 'Nazwa',
        itemNo: 'Kod towaru',
        qty: 'Ilość',
        price: 'Cena jedn. netto',
        vatRate: 'VAT',
        net: 'Wartość netto',
        allowances: 'Rabaty i opłaty dodatkowe',
        allowance: 'Rabat',
        charge: 'Opłata dodatkowa',
        vatBreakdown: 'Zestawienie VAT',
        category: 'Kategoria',
        taxable: 'Podstawa',
        taxAmount: 'Kwota VAT',
        sumLines: 'Suma wartości netto pozycji',
        totalAllow: 'Rabaty',
        totalCharge: 'Opłaty dodatkowe',
        taxExcl: 'Razem netto',
        taxTotal: 'Razem VAT',
        taxAccounting: 'VAT w walucie rozliczenia',
        taxIncl: 'Razem brutto',
        prepaid: 'Zapłacono',
        rounding: 'Zaokrąglenie',
        payable: 'Do zapłaty',
        payment: 'Dane do płatności',
        means: 'Forma płatności',
        accountName: 'Posiadacz rachunku',
        remittance: 'Tytuł przelewu',
        mandate: 'Numer mandatu',
        card: 'Karta',
        terms: 'Warunki płatności',
        notes: 'Uwagi',
        legal: 'To jest wizualizacja dokumentu; prawnie wiążącą fakturą jest plik XML.',
        pcs: 'szt.',
        hour: 'godz.',
        day: 'dzień',
        month: 'mies.',
        lumpsum: 'ryczałt',
        m10: 'Gotówka',
        m30: 'Przelew',
        m42: 'Wpłata na rachunek bankowy',
        m48: 'Karta płatnicza',
        m49: 'Polecenie zapłaty',
        m54: 'Karta kredytowa',
        m57: 'Zlecenie stałe',
        m58: 'Przelew SEPA',
        m59: 'Polecenie zapłaty SEPA',
        catS: 'Stawka podstawowa',
        catZ: 'Stawka 0%',
        catE: 'Zwolnione z VAT',
        catAE: 'Odwrotne obciążenie',
        catK: 'Wewnątrzwspólnotowa dostawa towarów',
        catG: 'Eksport poza UE',
        catO: 'Nie podlega opodatkowaniu',
    },
    despatch: {
        date: 'Data wystawienia',
        order: 'Nr zamówienia',
        supplier: 'Wysyłający',
        deliveryParty: 'Odbiorca',
        buyer: 'Nabywca',
        seller: 'Sprzedawca',
        endpoint: 'Adres elektroniczny',
        partyId: 'Identyfikator',
        contact: 'Kontakt',
        shipment: 'Przesyłka',
        shipmentId: 'Nr przesyłki',
        despatched: 'Data wysyłki',
        estimated: 'Przewidywana dostawa',
        carrier: 'Przewoźnik',
        tracking: 'Nr śledzenia',
        weight: 'Waga brutto',
        volume: 'Objętość',
        deliverTo: 'Adres dostawy',
        units: 'Jednostki transportowe',
        lines: 'Wydane pozycje',
        pos: 'Lp.',
        item: 'Towar',
        itemNo: 'Kod towaru',
        orderLine: 'Poz. zamówienia',
        lot: 'Partia',
        expiry: 'Data ważności',
        delivered: 'Wydano',
        backorder: 'Zaległe',
        notes: 'Uwagi',
        legal: 'To jest wizualizacja awiza wysyłki zapisanego w pliku XML.',
        pcs: 'szt.',
        pallet: 'Paleta',
    },
};

export default xslt;
