import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Fatura n.º',
        date: 'Data de emissão',
        due: 'Vencimento',
        currency: 'Moeda',
        buyerRef: 'Ref. do adquirente',
        order: 'Ref. da encomenda',
        contract: 'Contrato',
        project: 'Projeto',
        preceding: 'Fatura anterior',
        period: 'Período de faturação',
        delivery: 'Data de entrega',
        deliverTo: 'Local de entrega',
        seller: 'Vendedor',
        buyer: 'Adquirente',
        payee: 'Beneficiário',
        vat: 'N.º de IVA',
        taxNo: 'NIF',
        reg: 'Registo comercial',
        endpoint: 'Endereço eletrónico',
        contact: 'Contacto',
        lines: 'Linhas da fatura',
        pos: 'N.º',
        item: 'Descrição',
        itemNo: 'Ref. artigo',
        qty: 'Quantidade',
        price: 'Preço unitário',
        vatRate: 'IVA',
        net: 'Valor líquido',
        allowances: 'Descontos e encargos',
        allowance: 'Desconto',
        charge: 'Encargo',
        vatBreakdown: 'Resumo do IVA',
        category: 'Categoria',
        taxable: 'Incidência',
        taxAmount: 'Valor do IVA',
        sumLines: 'Soma das linhas',
        totalAllow: 'Descontos',
        totalCharge: 'Encargos',
        taxExcl: 'Total sem IVA',
        taxTotal: 'Total do IVA',
        taxAccounting: 'IVA na moeda contabilística',
        taxIncl: 'Total com IVA',
        prepaid: 'Valor pago',
        rounding: 'Arredondamento',
        payable: 'Total a pagar',
        payment: 'Dados de pagamento',
        means: 'Meio de pagamento',
        accountName: 'Titular da conta',
        remittance: 'Referência de pagamento',
        mandate: 'Ref. da autorização',
        card: 'Cartão',
        terms: 'Condições de pagamento',
        notes: 'Observações',
        legal: 'Esta é uma representação legível; a fatura juridicamente válida é o ficheiro XML.',
        pcs: 'un.',
        hour: 'h',
        day: 'dia',
        month: 'mês',
        lumpsum: 'valor global',
        m10: 'Numerário',
        m30: 'Transferência bancária',
        m42: 'Pagamento em conta bancária',
        m48: 'Cartão bancário',
        m49: 'Débito direto',
        m54: 'Cartão de crédito',
        m57: 'Acordo permanente',
        m58: 'Transferência SEPA',
        m59: 'Débito direto SEPA',
        catS: 'Taxa normal',
        catZ: 'Taxa zero',
        catE: 'Isento',
        catAE: 'Autoliquidação',
        catK: 'Transmissão intracomunitária',
        catG: 'Exportação para fora da UE',
        catO: 'Não sujeito a IVA',
    },
    despatch: {
        date: 'Data de emissão',
        order: 'Ref. da encomenda',
        supplier: 'Expedidor',
        deliveryParty: 'Destinatário',
        buyer: 'Adquirente',
        seller: 'Vendedor',
        endpoint: 'Endereço eletrónico',
        partyId: 'Identificador',
        contact: 'Contacto',
        shipment: 'Expedição',
        shipmentId: 'ID da expedição',
        despatched: 'Expedido em',
        estimated: 'Entrega prevista',
        carrier: 'Transportador',
        tracking: 'N.º de seguimento',
        weight: 'Peso bruto',
        volume: 'Volume',
        deliverTo: 'Local de descarga',
        units: 'Volumes',
        lines: 'Linhas expedidas',
        pos: 'N.º',
        item: 'Artigo',
        itemNo: 'Ref. artigo',
        orderLine: 'Linha da encomenda',
        lot: 'Lote',
        expiry: 'Validade',
        delivered: 'Entregue',
        backorder: 'Pendente',
        notes: 'Observações',
        legal: 'Esta é uma representação legível do aviso de expedição em XML.',
        pcs: 'un.',
        pallet: 'Palete',
    },
};

export default xslt;
