import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Factură nr.',
        date: 'Data emiterii',
        due: 'Scadență',
        currency: 'Monedă',
        buyerRef: 'Ref. cumpărător',
        order: 'Ref. comandă',
        contract: 'Contract',
        project: 'Proiect',
        preceding: 'Factura anterioară',
        period: 'Perioada de facturare',
        delivery: 'Data livrării',
        deliverTo: 'Livrare la',
        seller: 'Vânzător',
        buyer: 'Cumpărător',
        payee: 'Beneficiar plată',
        vat: 'Cod TVA',
        taxNo: 'Cod fiscal',
        reg: 'Nr. Reg. Com.',
        endpoint: 'Adresă electronică',
        contact: 'Contact',
        lines: 'Linii factură',
        pos: 'Nr.',
        item: 'Descriere',
        itemNo: 'Cod articol',
        qty: 'Cantitate',
        price: 'Preț unitar',
        vatRate: 'TVA',
        net: 'Valoare netă',
        allowances: 'Reduceri și taxe suplimentare',
        allowance: 'Reducere',
        charge: 'Taxă suplimentară',
        vatBreakdown: 'Defalcare TVA',
        category: 'Categorie',
        taxable: 'Bază impozabilă',
        taxAmount: 'Valoare TVA',
        sumLines: 'Total linii',
        totalAllow: 'Reduceri',
        totalCharge: 'Taxe suplimentare',
        taxExcl: 'Total fără TVA',
        taxTotal: 'Total TVA',
        taxAccounting: 'TVA în moneda contabilă',
        taxIncl: 'Total cu TVA',
        prepaid: 'Sumă plătită',
        rounding: 'Rotunjire',
        payable: 'Total de plată',
        payment: 'Date de plată',
        means: 'Modalitate de plată',
        accountName: 'Titular cont',
        remittance: 'Referință plată',
        mandate: 'Ref. mandat',
        card: 'Card',
        terms: 'Condiții de plată',
        notes: 'Mențiuni',
        legal: 'Aceasta este o reprezentare lizibilă; factura valabilă din punct de vedere legal este fișierul XML.',
        pcs: 'buc.',
        hour: 'h',
        day: 'zi',
        month: 'lună',
        lumpsum: 'forfetar',
        m10: 'Numerar',
        m30: 'Ordin de plată',
        m42: 'Plată în cont bancar',
        m48: 'Card bancar',
        m49: 'Debitare directă',
        m54: 'Card de credit',
        m57: 'Acord permanent',
        m58: 'Transfer SEPA',
        m59: 'Debitare directă SEPA',
        catS: 'Cotă standard',
        catZ: 'Cotă zero',
        catE: 'Scutit',
        catAE: 'Taxare inversă',
        catK: 'Livrare intracomunitară',
        catG: 'Export în afara UE',
        catO: 'Neimpozabil',
    },
    despatch: {
        date: 'Data emiterii',
        order: 'Ref. comandă',
        supplier: 'Expeditor',
        deliveryParty: 'Destinatar',
        buyer: 'Cumpărător',
        seller: 'Vânzător',
        endpoint: 'Adresă electronică',
        partyId: 'Identificator',
        contact: 'Contact',
        shipment: 'Expediere',
        shipmentId: 'ID expediere',
        despatched: 'Expediat',
        estimated: 'Livrare estimată',
        carrier: 'Transportator',
        tracking: 'Nr. urmărire',
        weight: 'Greutate brută',
        volume: 'Volum',
        deliverTo: 'Adresa de livrare',
        units: 'Unități de transport',
        lines: 'Linii expediate',
        pos: 'Nr.',
        item: 'Articol',
        itemNo: 'Cod articol',
        orderLine: 'Linie comandă',
        lot: 'Lot',
        expiry: 'Expirare',
        delivered: 'Livrat',
        backorder: 'Restant',
        notes: 'Mențiuni',
        legal: 'Aceasta este o reprezentare lizibilă a avizului de expediție XML.',
        pcs: 'buc.',
        pallet: 'Palet',
    },
};

export default xslt;
