import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Číslo faktúry',
        date: 'Dátum vyhotovenia',
        due: 'Dátum splatnosti',
        currency: 'Mena',
        buyerRef: 'Referencia odberateľa',
        order: 'Objednávka',
        contract: 'Zmluva',
        project: 'Projekt',
        preceding: 'Pôvodná faktúra',
        period: 'Fakturačné obdobie',
        delivery: 'Dátum dodania',
        deliverTo: 'Miesto dodania',
        seller: 'Dodávateľ',
        buyer: 'Odberateľ',
        payee: 'Príjemca platby',
        vat: 'IČ DPH',
        taxNo: 'DIČ',
        reg: 'IČO',
        endpoint: 'Elektronická adresa',
        contact: 'Kontakt',
        lines: 'Položky faktúry',
        pos: 'Č.',
        item: 'Popis',
        itemNo: 'Kód',
        qty: 'Množstvo',
        price: 'Jedn. cena',
        vatRate: 'DPH',
        net: 'Bez DPH',
        allowances: 'Zľavy a prirážky',
        allowance: 'Zľava',
        charge: 'Prirážka',
        vatBreakdown: 'Rekapitulácia DPH',
        category: 'Kategória',
        taxable: 'Základ dane',
        taxAmount: 'Výška DPH',
        sumLines: 'Súčet položiek bez DPH',
        totalAllow: 'Zľavy',
        totalCharge: 'Prirážky',
        taxExcl: 'Spolu bez DPH',
        taxTotal: 'DPH spolu',
        taxAccounting: 'DPH v účtovnej mene',
        taxIncl: 'Spolu s DPH',
        prepaid: 'Uhradené',
        rounding: 'Zaokrúhlenie',
        payable: 'Na úhradu',
        payment: 'Platobné údaje',
        means: 'Spôsob úhrady',
        accountName: 'Majiteľ účtu',
        remittance: 'Variabilný symbol',
        mandate: 'Mandát na inkaso',
        card: 'Karta',
        terms: 'Platobné podmienky',
        notes: 'Poznámky',
        legal: 'Toto je čitateľné zobrazenie; právne platnou faktúrou je súbor XML.',
        pcs: 'ks',
        hour: 'hod',
        day: 'deň',
        month: 'mes.',
        lumpsum: 'paušál',
        m10: 'V hotovosti',
        m30: 'Bankovým prevodom',
        m42: 'Platba na bankový účet',
        m48: 'Platobná karta',
        m49: 'Inkaso',
        m54: 'Kreditná karta',
        m57: 'Trvalý príkaz',
        m58: 'Prevod SEPA',
        m59: 'Inkaso SEPA',
        catS: 'Základná sadzba',
        catZ: 'Nulová sadzba',
        catE: 'Oslobodené od dane',
        catAE: 'Prenesenie daňovej povinnosti',
        catK: 'Dodanie tovaru do iného členského štátu',
        catG: 'Vývoz mimo EÚ',
        catO: 'Nepodlieha DPH',
    },
    despatch: {
        date: 'Dátum vyhotovenia',
        order: 'Objednávka',
        supplier: 'Odosielateľ',
        deliveryParty: 'Príjemca',
        buyer: 'Odberateľ',
        seller: 'Dodávateľ',
        endpoint: 'Elektronická adresa',
        partyId: 'Identifikátor',
        contact: 'Kontakt',
        shipment: 'Zásielka',
        shipmentId: 'Číslo zásielky',
        despatched: 'Odoslané',
        estimated: 'Predpokladané dodanie',
        carrier: 'Dopravca',
        tracking: 'Sledovacie číslo',
        weight: 'Hmotnosť brutto',
        volume: 'Objem',
        deliverTo: 'Dodacia adresa',
        units: 'Prepravné jednotky',
        lines: 'Dodané položky',
        pos: 'Č.',
        item: 'Položka',
        itemNo: 'Kód',
        orderLine: 'Riadok objednávky',
        lot: 'Šarža',
        expiry: 'Spotrebujte do',
        delivered: 'Dodané',
        backorder: 'Nedodané',
        notes: 'Poznámky',
        legal: 'Toto je čitateľné zobrazenie avíza o odoslaní vo formáte XML.',
        pcs: 'ks',
        pallet: 'Paleta',
    },
};

export default xslt;
