import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Št. računa',
        date: 'Datum izdaje',
        due: 'Datum zapadlosti',
        currency: 'Valuta',
        buyerRef: 'Sklic kupca',
        order: 'Naročilo',
        contract: 'Pogodba',
        project: 'Projekt',
        preceding: 'Predhodni račun',
        period: 'Obračunsko obdobje',
        delivery: 'Datum dobave',
        deliverTo: 'Naslov dobave',
        seller: 'Prodajalec',
        buyer: 'Kupec',
        payee: 'Prejemnik plačila',
        vat: 'ID za DDV',
        taxNo: 'Davčna številka',
        reg: 'Matična številka',
        endpoint: 'Elektronski naslov',
        contact: 'Kontakt',
        lines: 'Postavke računa',
        pos: 'Zap. št.',
        item: 'Opis',
        itemNo: 'Šifra',
        qty: 'Količina',
        price: 'Cena na enoto',
        vatRate: 'DDV',
        net: 'Neto znesek',
        allowances: 'Popusti in doplačila',
        allowance: 'Popust',
        charge: 'Doplačilo',
        vatBreakdown: 'Rekapitulacija DDV',
        category: 'Kategorija',
        taxable: 'Davčna osnova',
        taxAmount: 'Znesek DDV',
        sumLines: 'Vsota neto zneskov postavk',
        totalAllow: 'Popusti',
        totalCharge: 'Doplačila',
        taxExcl: 'Skupaj brez DDV',
        taxTotal: 'Skupaj DDV',
        taxAccounting: 'DDV v valuti obračuna',
        taxIncl: 'Skupaj z DDV',
        prepaid: 'Plačano',
        rounding: 'Zaokrožitev',
        payable: 'Za plačilo',
        payment: 'Podatki za plačilo',
        means: 'Način plačila',
        accountName: 'Imetnik računa',
        remittance: 'Sklic plačila',
        mandate: 'Sklic soglasja',
        card: 'Kartica',
        terms: 'Plačilni pogoji',
        notes: 'Opombe',
        legal: 'To je berljiv prikaz; pravno veljaven račun je datoteka XML.',
        pcs: 'kos',
        hour: 'ura',
        day: 'dan',
        month: 'mesec',
        lumpsum: 'pavšal',
        m10: 'Gotovina',
        m30: 'Nakazilo',
        m42: 'Plačilo na bančni račun',
        m48: 'Bančna kartica',
        m49: 'Direktna obremenitev',
        m54: 'Kreditna kartica',
        m57: 'Trajni nalog',
        m58: 'SEPA nakazilo',
        m59: 'SEPA direktna obremenitev',
        catS: 'Splošna stopnja',
        catZ: 'Ničelna stopnja',
        catE: 'Oproščeno',
        catAE: 'Obrnjena davčna obveznost',
        catK: 'Dobava znotraj Skupnosti',
        catG: 'Izvoz izven EU',
        catO: 'Ni predmet DDV',
    },
    despatch: {
        date: 'Datum izdaje',
        order: 'Naročilo',
        supplier: 'Pošiljatelj',
        deliveryParty: 'Prejemnik',
        buyer: 'Kupec',
        seller: 'Prodajalec',
        endpoint: 'Elektronski naslov',
        partyId: 'Identifikator',
        contact: 'Kontakt',
        shipment: 'Pošiljka',
        shipmentId: 'ID pošiljke',
        despatched: 'Odpremljeno',
        estimated: 'Predvidena dobava',
        carrier: 'Prevoznik',
        tracking: 'Številka za sledenje',
        weight: 'Bruto teža',
        volume: 'Prostornina',
        deliverTo: 'Naslov dobave',
        units: 'Transportne enote',
        lines: 'Odpremljene postavke',
        pos: 'Zap. št.',
        item: 'Artikel',
        itemNo: 'Šifra',
        orderLine: 'Postavka naročila',
        lot: 'Lot',
        expiry: 'Rok uporabe',
        delivered: 'Dobavljeno',
        backorder: 'Nedobavljeno',
        notes: 'Opombe',
        legal: 'To je berljiv prikaz dobavnice v obliki XML.',
        pcs: 'kos',
        pallet: 'Paleta',
    },
};

export default xslt;
