import type { XsltLabels } from './en';

const xslt: XsltLabels = {
    invoice: {
        number: 'Fakturanr',
        date: 'Fakturadatum',
        due: 'Förfallodatum',
        currency: 'Valuta',
        buyerRef: 'Er referens',
        order: 'Orderreferens',
        contract: 'Avtal',
        project: 'Projekt',
        preceding: 'Tidigare faktura',
        period: 'Faktureringsperiod',
        delivery: 'Leveransdatum',
        deliverTo: 'Leveransadress',
        seller: 'Säljare',
        buyer: 'Köpare',
        payee: 'Betalningsmottagare',
        vat: 'Momsreg.nr',
        taxNo: 'Skattenummer',
        reg: 'Org.nr',
        endpoint: 'Elektronisk adress',
        contact: 'Kontaktperson',
        lines: 'Fakturarader',
        pos: 'Nr',
        item: 'Beskrivning',
        itemNo: 'Art.nr',
        qty: 'Antal',
        price: 'À-pris',
        vatRate: 'Moms',
        net: 'Nettobelopp',
        allowances: 'Rabatter och avgifter',
        allowance: 'Rabatt',
        charge: 'Avgift',
        vatBreakdown: 'Momsspecifikation',
        category: 'Kategori',
        taxable: 'Underlag',
        taxAmount: 'Momsbelopp',
        sumLines: 'Summa rader netto',
        totalAllow: 'Rabatter',
        totalCharge: 'Avgifter',
        taxExcl: 'Summa exkl. moms',
        taxTotal: 'Summa moms',
        taxAccounting: 'Moms i redovisningsvaluta',
        taxIncl: 'Summa inkl. moms',
        prepaid: 'Betalt belopp',
        rounding: 'Öresavrundning',
        payable: 'Att betala',
        payment: 'Betalningsuppgifter',
        means: 'Betalningssätt',
        accountName: 'Kontonamn',
        remittance: 'Betalningsreferens',
        mandate: 'Medgivandereferens',
        card: 'Kort',
        terms: 'Betalningsvillkor',
        notes: 'Noteringar',
        legal: 'Detta är en läsbar återgivning; XML-filen är den juridiskt giltiga fakturan.',
        pcs: 'st',
        hour: 'tim',
        day: 'dag',
        month: 'mån',
        lumpsum: 'fast pris',
        m10: 'Kontant',
        m30: 'Banköverföring',
        m42: 'Betalning till bankkonto',
        m48: 'Bankkort',
        m49: 'Autogiro',
        m54: 'Kreditkort',
        m57: 'Stående överenskommelse',
        m58: 'SEPA-överföring',
        m59: 'SEPA-autogiro',
        catS: 'Normalskattesats',
        catZ: 'Nollskattesats',
        catE: 'Undantagen från moms',
        catAE: 'Omvänd betalningsskyldighet',
        catK: 'Unionsintern leverans',
        catG: 'Export utanför EU',
        catO: 'Ej föremål för moms',
    },
    despatch: {
        date: 'Datum',
        order: 'Orderreferens',
        supplier: 'Avsändare',
        deliveryParty: 'Mottagare',
        buyer: 'Köpare',
        seller: 'Säljare',
        endpoint: 'Elektronisk adress',
        partyId: 'ID',
        contact: 'Kontaktperson',
        shipment: 'Försändelse',
        shipmentId: 'Försändelse-ID',
        despatched: 'Avsänt',
        estimated: 'Beräknad leverans',
        carrier: 'Transportör',
        tracking: 'Spårningsnummer',
        weight: 'Bruttovikt',
        volume: 'Volym',
        deliverTo: 'Leveransadress',
        units: 'Kollin',
        lines: 'Levererade rader',
        pos: 'Nr',
        item: 'Artikel',
        itemNo: 'Art.nr',
        orderLine: 'Orderrad',
        lot: 'Batch',
        expiry: 'Bäst före',
        delivered: 'Levererat',
        backorder: 'Restnoterat',
        notes: 'Noteringar',
        legal: 'Detta är en läsbar återgivning av XML-följesedeln.',
        pcs: 'st',
        pallet: 'Pall',
    },
};

export default xslt;
