/**
 * Asistanın Türkçe dışındaki arayüz dillerindeki yerleşik bilgi bankası (Avrupa sürümü:
 * EN 16931 / Peppol / XRechnung). Kimlikler Türkçe bankayla aynıdır; fiyatlar ziyaretçinin
 * para birimiyle (EUR / GBP) yazılır. Düğme adları o dildeki arayüz metinleriyle aynı olmalı.
 */
const NUMBER_LOCALE = { en: 'en-GB', de: 'de-DE', fr: 'fr-FR', es: 'es-ES' };

export const INTL_LANGS = Object.keys(NUMBER_LOCALE);

const money = (lang, currency, amount) => {
    const n = Number(amount);
    const digits = Number.isInteger(n) ? 0 : 2;
    return new Intl.NumberFormat(NUMBER_LOCALE[lang], { style: 'currency', currency, minimumFractionDigits: digits, maximumFractionDigits: digits }).format(n);
};

const ACTIONS = {
    's-nedir': ['register', 'product'],
    's-baslangic': ['register', 'login'],
    's-fiyat': ['pricing', 'register'],
    's-hak': ['pricing'],
    's-ucretsiz': ['register', 'pricing'],
    's-belgeler': ['docs'],
    's-ulke': ['docs'],
    's-xslt': ['product'],
    's-kendi-xslt': ['login'],
    's-sablon': ['register'],
    's-satin': ['pricing', 'login'],
    's-iade': ['contact'],
    's-odeme-hata': ['contact'],
    's-uyelik': ['register'],
    's-sifre': ['contact'],
    's-tasarimlarim': ['login'],
    's-destek': ['contact', 'login'],
    's-veri': ['faq'],
};

const CONTACT = '+90 533 666 01 25';
const MAIL = 'destek@edxdocu.com';

const TEXTS = {
    en: ({ list, from }) => [
        ['s-nedir', 'What does this site do? What is the e-Document Designer?', 'site what is purpose service product platform edxdocu designer xslt layout einvoice',
            'The e-Document Designer lets you create the **layout file (XSLT)** for your e-invoices and delivery notes in the European formats **EN 16931**, **Peppol BIS 3** and **XRechnung**.\n- Pick a ready-made template or upload your own XSLT.\n- Edit logo, stamp, bank details and fields in the visual editor with drag and drop.\n- Preview with your own XML, then download the XSLT and use it in your invoicing system or access point.'],
        ['s-baslangic', 'How do I start? How do I create my first design?', 'how start first design step guide begin new create',
            'You can start in three steps:\n- **Create an account** and sign in.\n- In the wizard choose your **country** and document type, then the template and the sample data.\n- Edit the layout in the design screen, **Save** it, try it with **Test Download** (free) and, when you are happy, get the final file with **Approve** (1 credit).'],
        ['s-fiyat', 'What are the prices? How much are the packages?', 'price prices cost package how much plan one basic pro subscription euro pound',
            `One-time payment, no subscription. Credits never expire:\n${list}\n\nPrices include VAT. Every package includes all document types, all ready-made templates and XSLT download.`],
        ['s-hak', 'When is a design credit used? Does saving use a credit?', 'credit used spend save approve when design credit',
            'A design credit is used only at the **Approve** step, once per design.\n- **Save:** free, as often as you like.\n- **Test Download:** free (the file carries a large TEST watermark).\n- **Approve (1 credit):** the design is locked and the final file without TEST is downloaded.\n- You can download approved designs again for **free** from **Completed designs**.'],
        ['s-ucretsiz', 'Is there a free trial? Can I use it for free?', 'free trial demo without paying try test',
            'Signing up is free and you can do a lot without buying credits:\n- Use all templates and the editor, design and save.\n- Download the file with **Test Download** for free and try it in your own system (it carries a TEST watermark).\n\nThe final file without TEST needs 1 design credit at the **Approve** step. New accounts start with 0 credits.'],
        ['s-test', 'What is Test Download? Why does it say TEST?', 'test download watermark trial file',
            '**Test Download** (free) downloads your design with a large diagonal **TEST** watermark so you can try it in your own system.\n- It does not use a credit; download as often as you like.\n- If you upload the TEST file in the wizard again, the watermark is removed and you continue where you left off.\n- For the final file without TEST, use **Approve** (1 credit).'],
        ['s-onay', 'Can I change a design after approving it?', 'after approve change edit locked approved design',
            'An approved design is **locked**: it can no longer be edited, only downloaded.\n- You can download it again for free from **Completed designs**.\n- For changes you start a new design (approval uses 1 credit again).\n\nThat is why we recommend trying it with **Test Download** first.'],
        ['s-belgeler', 'Which document types can I design?', 'document types supported invoice credit note corrected prepayment partial delivery note despatch advice list',
            'For European countries:\n- Invoice, credit note, corrected invoice\n- Prepayment invoice, partial invoice\n- Delivery note (Peppol despatch advice)\n\nWhich of these are offered depends on the country you choose; each document is shown under its local name.'],
        ['s-ulke', 'Which countries and formats are supported?', 'country countries europe eu eea uk switzerland format profile peppol xrechnung en16931 cius language',
            'All EU and EEA countries, the United Kingdom and Switzerland. When you choose a country in the wizard, its documents are listed with the matching XML profile: **EN 16931**, **Peppol BIS Billing 3.0**, **XRechnung 3.0 (UBL)**, CIUS-RO, HR CIUS, CIUS-PT or **Peppol Despatch Advice**.\n- The document language follows the country (labels, dates and number format), and you can switch it where a country has several languages.\n- Documents that share the same XML format use the same template.'],
        ['s-xslt', 'Do I need to know XSLT? What is XSLT?', 'xslt what is need know code programming technical',
            'No, you do not need to know XSLT. XSLT is the layout file that defines how the XML data of an e-invoice looks on screen and in print.\n- You pick a ready-made template and edit it with **drag and drop**.\n- You can also upload your own XSLT file (.xslt / .xsl, up to 5 MB) with **Use my own XSLT file** in the wizard.'],
        ['s-xml', 'Can I preview with my own XML file?', 'xml upload own sample data preview',
            'Yes. In the wizard’s data step you can use the sample XML of your country or choose your own XML file (.xml, up to 5 MB).\n\nThe XML is only for the preview; the design works with any data. Uploaded files are checked automatically against the core rules of the profile.'],
        ['s-kendi-xslt', 'Can I upload and edit my existing XSLT layout?', 'existing xslt upload edit import my layout',
            'Yes. After signing in, choose the document type in the wizard, then in the design step select **Use my own XSLT file** and pick or drop your file. It is checked and then opens in the design screen for visual editing.\n\nNote: an already approved (purchased) design file cannot be opened for editing again; download it from **Completed designs**.'],
        ['s-logo', 'How do I add a logo, stamp or signature?', 'logo stamp signature image picture add png',
            'In the design screen choose **Image** in the **Insert** bar (click it or drag it to the desired place in the preview), then upload your logo, stamp or signature. The image is embedded in the file, so you do not need to host it anywhere. Adjust size and position in the panel on the right.'],
        ['s-banka', 'How do I add bank / IBAN details?', 'bank iban account payment details bic',
            'The field list in the design screen contains payment fields such as IBAN, BIC and account name; search for "IBAN" and click the field or drag it into the preview. The values come from the payment details in the XML. For fixed bank details you can also insert a **Text** element.'],
        ['s-editor', 'What can I do in the design screen?', 'editor design screen features drag drop table column text formula undo zoom',
            'In the design screen you can:\n- Use the **Insert** bar: Text, Image, Table, Formula, Box, QR Code, Column\n- Add any XML field from the field list by clicking or dragging it\n- Change fonts, colours, spacing and borders; hide or delete table columns\n- Undo (Ctrl+Z) / redo (Ctrl+Y), zoom and fit to width\n- **Save**, **Test Download** (free), **Approve** (1 credit)'],
        ['s-sablon', 'Are there ready-made templates?', 'ready made template templates gallery sample design',
            'Yes. For every European document type there is a ready-made EN 16931 / Peppol template with labels in the document language and sample data of the chosen country. You open it in the design screen with one click and adapt it to your company.'],
        ['s-uyum', 'Are the designs EN 16931 compliant?', 'compliant compliance en16931 peppol xrechnung schematron valid rules standard',
            'The templates follow the **EN 16931** UBL structure and the **Peppol BIS 3** and **XRechnung 3.0** profiles and are tested with sample invoices from several countries. The wizard checks uploaded XML against the core rules and warns you.\n\nThese checks are a subset of the official Schematron rules, and documents are not sent to any portal; test the final file in your own system with **Test Download**.'],
        ['s-entegrator', 'Where do I use the downloaded XSLT file?', 'where use upload xslt access point erp invoicing software',
            'Upload the .xslt file wherever your invoicing software, ERP or e-invoicing provider (for example your Peppol access point) lets you set a **visual layout / stylesheet** for invoices. We recommend trying the **Test Download** file first.'],
        ['s-satin', 'How do I buy? How does payment work?', 'buy purchase payment card paytr 3d secure package order pay',
            `Sign up and sign in, then click **Buy package** at the top right of the selection screen.\n- Choose a package, enter your billing details and continue to payment. Payment runs through **PayTR 3D Secure**; your card details never reach our server.\n- After a successful payment the credits are added to your account automatically.\n\nPackages start at ${from}.`],
        ['s-iade', 'Is there a refund? What happens to unused credits?', 'refund money back cancel unused credits expire transfer',
            'Credits **never expire** and stay in your account until you use them. Under the terms of use, purchased credits are not refunded and cannot be transferred to other accounts. If you had a payment problem, please contact support.'],
        ['s-odeme-hata', 'My payment failed, what should I do?', 'payment failed error card declined charged credits missing',
            'If your card was not charged, you can simply try again; make sure the 3D Secure code is correct and your card allows online payments. If you were charged but the credits did not arrive, please contact support with your account e-mail.'],
        ['s-uyelik', 'How do I sign up? What do I need?', 'sign up register account create registration',
            'Open the sign-up form with **Create account**: full name, company name, e-mail and password are required; phone is optional. You are signed in automatically afterwards. Signing up is free.'],
        ['s-sifre', 'I forgot my password, what should I do?', 'forgot password reset cannot sign in login',
            `Automatic password reset is not available yet. Write to support from your registered e-mail address (${MAIL}); we will reset your password after verifying your account.`],
        ['s-tasarimlarim', 'Where are my saved designs?', 'my designs saved where drafts completed list find',
            'After signing in, the selection screen shows:\n- **Designs in progress:** your saved drafts; open them with **Continue**.\n- **Completed designs:** your approved designs; preview and download them again for free.'],
        ['s-destek', 'How can I contact support?', 'support contact phone whatsapp email help customer service',
            `When signed in, use the support button at the bottom right to open a ticket or request live online support. You can also reach us without signing in:\n- **Phone / WhatsApp:** ${CONTACT}\n- **E-mail:** ${MAIL}`],
        ['s-veri', 'Is my data safe? Where is it stored?', 'data security privacy gdpr storage server personal',
            'User and design data are stored in a PostgreSQL database; for payments your card details never reach our server (PayTR 3D Secure). Details are in the privacy and cookie policy links at the bottom of the page.'],
        ['s-mobil', 'Can I use it on a phone or tablet?', 'mobile phone tablet app install browser',
            'The site runs in the browser; nothing needs to be installed. Account tasks work fine on a phone, but the design screen needs a wide screen, so we recommend a computer for designing.'],
    ],
    de: ({ list, from }) => [
        ['s-nedir', 'Wofür ist diese Website? Was ist der E-Beleg-Designer?', 'website wofur was ist zweck dienst produkt plattform edxdocu designer xslt layout e-rechnung',
            'Mit dem E-Beleg-Designer erstellen Sie die **Layoutdatei (XSLT)** für Ihre E-Rechnungen und Lieferscheine in den europäischen Formaten **EN 16931**, **Peppol BIS 3** und **XRechnung**.\n- Wählen Sie eine fertige Vorlage oder laden Sie Ihre eigene XSLT hoch.\n- Bearbeiten Sie Logo, Stempel, Bankdaten und Felder im visuellen Editor per Drag & Drop.\n- Prüfen Sie die Vorschau mit Ihrer eigenen XML, laden Sie die XSLT herunter und nutzen Sie sie in Ihrer Rechnungssoftware.'],
        ['s-baslangic', 'Wie fange ich an? Wie erstelle ich mein erstes Design?', 'wie anfangen erstes design schritt anleitung beginnen neu erstellen',
            'In drei Schritten:\n- **Konto eröffnen** und anmelden.\n- Im Assistenten **Land** und Belegart wählen, dann Vorlage und Beispieldaten.\n- Das Layout im Gestaltungsbildschirm bearbeiten, **Speichern**, mit **Test-Download** (kostenlos) ausprobieren und die fertige Datei mit **Freigeben** (1 Guthaben) holen.'],
        ['s-fiyat', 'Was kosten die Pakete? Wie sind die Preise?', 'preis preise kosten paket wie viel tarif one basic pro abo euro pfund',
            `Einmalzahlung, kein Abo. Guthaben verfallen nicht:\n${list}\n\nPreise inkl. MwSt. Jedes Paket enthält alle Belegarten, alle fertigen Vorlagen und den XSLT-Download.`],
        ['s-hak', 'Wann wird ein Design-Guthaben verbraucht? Kostet Speichern Guthaben?', 'guthaben verbraucht speichern freigeben wann design kredit',
            'Ein Design-Guthaben wird nur beim **Freigeben** verbraucht, einmal pro Design.\n- **Speichern:** kostenlos, beliebig oft.\n- **Test-Download:** kostenlos (die Datei trägt ein großes TEST-Wasserzeichen).\n- **Freigeben (1 Guthaben):** das Design wird gesperrt und die fertige Datei ohne TEST heruntergeladen.\n- Freigegebene Designs laden Sie unter **Abgeschlossene Designs** jederzeit **kostenlos** erneut herunter.'],
        ['s-ucretsiz', 'Gibt es eine kostenlose Testversion? Kann ich es gratis nutzen?', 'kostenlos gratis test testversion demo ohne bezahlen ausprobieren',
            'Die Registrierung ist kostenlos, und ohne Guthaben können Sie schon viel tun:\n- Alle Vorlagen und den Editor nutzen, gestalten und speichern.\n- Die Datei mit **Test-Download** kostenlos herunterladen und in Ihrem System testen (mit TEST-Wasserzeichen).\n\nFür die fertige Datei ohne TEST wird beim **Freigeben** 1 Design-Guthaben benötigt. Neue Konten starten mit 0 Guthaben.'],
        ['s-test', 'Was ist der Test-Download? Warum steht dort TEST?', 'test download wasserzeichen testdatei',
            'Der **Test-Download** (kostenlos) lädt Ihr Design mit einem großen, diagonalen **TEST**-Wasserzeichen herunter, damit Sie es in Ihrem System ausprobieren können.\n- Er verbraucht kein Guthaben und ist beliebig oft möglich.\n- Laden Sie die TEST-Datei erneut im Assistenten hoch, wird das Wasserzeichen entfernt und Sie arbeiten dort weiter.\n- Die fertige Datei ohne TEST erhalten Sie mit **Freigeben** (1 Guthaben).'],
        ['s-onay', 'Kann ich ein Design nach der Freigabe noch ändern?', 'nach freigabe andern bearbeiten gesperrt freigegeben design',
            'Ein freigegebenes Design ist **gesperrt**: Es kann nicht mehr bearbeitet, nur noch heruntergeladen werden.\n- Unter **Abgeschlossene Designs** laden Sie es kostenlos erneut herunter.\n- Für Änderungen starten Sie ein neues Design (die Freigabe kostet erneut 1 Guthaben).\n\nTesten Sie deshalb vorher mit dem **Test-Download**.'],
        ['s-belgeler', 'Welche Belegarten kann ich gestalten?', 'belegarten belege rechnung gutschrift korrektur anzahlung teilrechnung lieferschein lieferavis liste',
            'Für europäische Länder:\n- Rechnung, Gutschrift, Rechnungskorrektur\n- Anzahlungsrechnung, Teilrechnung\n- Lieferschein (Peppol-Lieferavis)\n\nWelche davon angeboten werden, hängt vom gewählten Land ab; jeder Beleg erscheint unter seinem landesüblichen Namen.'],
        ['s-ulke', 'Welche Länder und Formate werden unterstützt?', 'land lander europa eu ewr vereinigtes konigreich schweiz format profil peppol xrechnung en16931 cius sprache',
            'Alle Länder der EU und des EWR, das Vereinigte Königreich und die Schweiz. Wählen Sie im Assistenten ein Land, werden dessen Belege mit dem passenden XML-Profil angezeigt: **EN 16931**, **Peppol BIS Billing 3.0**, **XRechnung 3.0 (UBL)**, CIUS-RO, HR CIUS, CIUS-PT oder **Peppol Despatch Advice**.\n- Die Belegsprache richtet sich nach dem Land (Beschriftungen, Datum, Zahlenformat); bei mehrsprachigen Ländern ist sie umschaltbar.\n- Belege mit demselben XML-Format nutzen dieselbe Vorlage.'],
        ['s-xslt', 'Muss ich XSLT beherrschen? Was ist XSLT?', 'xslt was ist kenntnisse code programmieren technisch',
            'Nein, XSLT-Kenntnisse sind nicht nötig. XSLT ist die Layoutdatei, die festlegt, wie die XML-Daten einer E-Rechnung am Bildschirm und im Druck aussehen.\n- Sie wählen eine fertige Vorlage und bearbeiten sie per **Drag & Drop**.\n- Sie können auch Ihre eigene XSLT-Datei (.xslt / .xsl, bis 5 MB) im Assistenten mit **Eigene XSLT-Datei verwenden** hochladen.'],
        ['s-xml', 'Kann ich die Vorschau mit meiner eigenen XML prüfen?', 'xml hochladen eigene beispieldaten vorschau',
            'Ja. Im Datenschritt des Assistenten nutzen Sie die Beispiel-XML Ihres Landes oder wählen mit **Eigene XML-Datei wählen** Ihre eigene Datei (.xml, bis 5 MB).\n\nDie XML dient nur der Vorschau; das Design funktioniert mit allen Daten. Hochgeladene Dateien werden automatisch gegen die Kernregeln des Profils geprüft.'],
        ['s-kendi-xslt', 'Kann ich mein vorhandenes XSLT-Layout hochladen und bearbeiten?', 'vorhandene xslt hochladen bearbeiten importieren layout',
            'Ja. Melden Sie sich an, wählen Sie im Assistenten die Belegart und im Gestaltungsschritt **Eigene XSLT-Datei verwenden**. Die Datei wird geprüft und öffnet sich dann im Gestaltungsbildschirm zur visuellen Bearbeitung.\n\nHinweis: Eine bereits freigegebene (gekaufte) Designdatei lässt sich nicht erneut bearbeiten; laden Sie sie unter **Abgeschlossene Designs** herunter.'],
        ['s-logo', 'Wie füge ich Logo, Stempel oder Unterschrift hinzu?', 'logo stempel unterschrift bild grafik hinzufugen png',
            'Wählen Sie im Gestaltungsbildschirm in der Leiste **Einfügen** das Element **Bild** (anklicken oder an die gewünschte Stelle der Vorschau ziehen) und laden Sie Logo, Stempel oder Unterschrift hoch. Das Bild wird in die Datei eingebettet. Größe und Position stellen Sie im rechten Bereich ein.'],
        ['s-banka', 'Wie füge ich Bankdaten / IBAN hinzu?', 'bank iban konto zahlungsdaten bic bankverbindung',
            'Die Feldliste im Gestaltungsbildschirm enthält Zahlungsfelder wie IBAN, BIC und Kontoinhaber; suchen Sie nach „IBAN“ und klicken oder ziehen Sie das Feld in die Vorschau. Die Werte kommen aus den Zahlungsdaten der XML. Für feste Bankdaten können Sie auch ein **Text**-Element einfügen.'],
        ['s-editor', 'Was kann ich im Gestaltungsbildschirm tun?', 'editor gestaltung funktionen drag drop tabelle spalte text formel ruckgangig zoom',
            'Im Gestaltungsbildschirm können Sie:\n- über die Leiste **Einfügen** Text, Bild, Tabelle, Formel, Box, QR-Code und Spalten hinzufügen\n- jedes XML-Feld aus der Feldliste per Klick oder Ziehen einfügen\n- Schrift, Farben, Abstände und Rahmen ändern; Tabellenspalten aus- oder einblenden\n- rückgängig machen (Strg+Z) / wiederholen (Strg+Y), zoomen und an die Breite anpassen\n- **Speichern**, **Test-Download** (kostenlos), **Freigeben** (1 Guthaben)'],
        ['s-sablon', 'Gibt es fertige Vorlagen?', 'fertige vorlage vorlagen galerie beispiel design',
            'Ja. Für jede europäische Belegart gibt es eine fertige EN-16931-/Peppol-Vorlage mit Beschriftungen in der Belegsprache und Beispieldaten des gewählten Landes. Mit einem Klick öffnen Sie sie im Gestaltungsbildschirm und passen sie an Ihr Unternehmen an.'],
        ['s-uyum', 'Sind die Designs EN-16931-konform?', 'konform konformitat en16931 peppol xrechnung schematron gultig regeln standard',
            'Die Vorlagen folgen der UBL-Struktur nach **EN 16931** sowie den Profilen **Peppol BIS 3** und **XRechnung 3.0** und wurden mit Beispielrechnungen aus mehreren Ländern getestet. Der Assistent prüft hochgeladene XML gegen die Kernregeln und weist auf Probleme hin.\n\nDiese Prüfungen sind eine Teilmenge der offiziellen Schematron-Regeln, und Belege werden an kein Portal übermittelt; testen Sie die fertige Datei mit dem **Test-Download** in Ihrem System.'],
        ['s-entegrator', 'Wo verwende ich die heruntergeladene XSLT-Datei?', 'wo verwenden hochladen xslt access point erp rechnungssoftware',
            'Laden Sie die .xslt-Datei dort hoch, wo Ihre Rechnungssoftware, Ihr ERP oder Ihr E-Rechnungsdienstleister (z. B. Ihr Peppol-Access-Point) ein **Layout / Stylesheet** für Rechnungen erlaubt. Testen Sie zuerst die Datei aus dem **Test-Download**.'],
        ['s-satin', 'Wie kaufe ich? Wie funktioniert die Zahlung?', 'kaufen bestellen zahlung karte paytr 3d secure paket bezahlen',
            `Registrieren und melden Sie sich an, dann klicken Sie oben rechts im Auswahlbildschirm auf **Paket kaufen**.\n- Paket wählen, Rechnungsdaten eingeben und zur Zahlung gehen. Die Zahlung läuft über **PayTR 3D Secure**; Ihre Kartendaten erreichen unseren Server nie.\n- Nach erfolgreicher Zahlung wird das Guthaben automatisch gutgeschrieben.\n\nPakete gibt es ab ${from}.`],
        ['s-iade', 'Gibt es eine Rückerstattung? Was passiert mit ungenutztem Guthaben?', 'ruckerstattung erstattung geld zuruck storno guthaben verfallt ubertragen',
            'Guthaben **verfallen nicht** und bleiben bis zur Nutzung in Ihrem Konto. Laut Nutzungsbedingungen werden gekaufte Guthaben nicht erstattet und sind nicht auf andere Konten übertragbar. Bei Zahlungsproblemen wenden Sie sich bitte an den Support.'],
        ['s-odeme-hata', 'Meine Zahlung ist fehlgeschlagen, was nun?', 'zahlung fehlgeschlagen fehler karte abgelehnt abgebucht guthaben fehlt',
            'Wurde Ihre Karte nicht belastet, versuchen Sie es einfach erneut; prüfen Sie den 3D-Secure-Code und ob Ihre Karte für Online-Zahlungen freigeschaltet ist. Wurde abgebucht, aber kein Guthaben gutgeschrieben, kontaktieren Sie bitte den Support mit Ihrer Konto-E-Mail.'],
        ['s-uyelik', 'Wie registriere ich mich? Was brauche ich?', 'registrieren anmelden konto erstellen registrierung',
            'Öffnen Sie das Formular mit **Konto eröffnen**: Name, Firmenname, E-Mail und Passwort sind Pflicht, Telefon ist optional. Danach sind Sie automatisch angemeldet. Die Registrierung ist kostenlos.'],
        ['s-sifre', 'Ich habe mein Passwort vergessen, was tun?', 'passwort vergessen zurucksetzen anmeldung nicht moglich',
            `Eine automatische Passwort-Zurücksetzung gibt es noch nicht. Schreiben Sie dem Support von Ihrer registrierten E-Mail-Adresse (${MAIL}); nach Prüfung Ihres Kontos setzen wir das Passwort zurück.`],
        ['s-tasarimlarim', 'Wo finde ich meine gespeicherten Designs?', 'meine designs gespeichert wo entwurfe abgeschlossen liste finden',
            'Nach der Anmeldung zeigt der Auswahlbildschirm:\n- **Laufende Designs:** Ihre gespeicherten Entwürfe; öffnen mit **Weiter**.\n- **Abgeschlossene Designs:** Ihre freigegebenen Designs; Vorschau und erneuter Download kostenlos.'],
        ['s-destek', 'Wie erreiche ich den Support?', 'support kontakt telefon whatsapp e-mail hilfe kundendienst',
            `Angemeldet öffnen Sie über die Support-Schaltfläche unten rechts ein Ticket oder fordern Live-Online-Support an. Auch ohne Anmeldung erreichen Sie uns:\n- **Telefon / WhatsApp:** ${CONTACT}\n- **E-Mail:** ${MAIL}`],
        ['s-veri', 'Sind meine Daten sicher? Wo werden sie gespeichert?', 'daten sicherheit datenschutz dsgvo speicherung server personlich',
            'Benutzer- und Designdaten werden in einer PostgreSQL-Datenbank gespeichert; bei Zahlungen erreichen Ihre Kartendaten unseren Server nie (PayTR 3D Secure). Details finden Sie in den Links zu Datenschutz und Cookie-Richtlinie unten auf der Seite.'],
        ['s-mobil', 'Kann ich es auf Smartphone oder Tablet nutzen?', 'mobil handy smartphone tablet app installieren browser',
            'Die Website läuft im Browser, eine Installation ist nicht nötig. Kontofunktionen gehen gut am Smartphone; der Gestaltungsbildschirm braucht aber einen breiten Bildschirm, daher empfehlen wir zum Gestalten einen Computer.'],
    ],
    fr: ({ list, from }) => [
        ['s-nedir', 'À quoi sert ce site ? Qu’est-ce que le Concepteur d’e-documents ?', 'site quoi sert but service produit plateforme edxdocu concepteur xslt mise en page facture electronique',
            'Le Concepteur d’e-documents vous permet de créer le **fichier de mise en page (XSLT)** de vos factures électroniques et bons de livraison aux formats européens **EN 16931**, **Peppol BIS 3** et **XRechnung**.\n- Choisissez un modèle prêt à l’emploi ou importez votre propre XSLT.\n- Modifiez logo, cachet, coordonnées bancaires et champs par glisser-déposer dans l’éditeur visuel.\n- Prévisualisez avec votre propre XML, puis téléchargez le XSLT pour votre logiciel de facturation.'],
        ['s-baslangic', 'Comment commencer ? Comment créer ma première conception ?', 'comment commencer premiere conception etape guide debuter nouveau creer',
            'En trois étapes :\n- **Créez un compte** et connectez-vous.\n- Dans l’assistant, choisissez votre **pays** et le type de document, puis le modèle et les données d’exemple.\n- Modifiez la mise en page dans l’écran de conception, **Enregistrer**, essayez avec **Télécharger le test** (gratuit) puis récupérez le fichier final avec **Valider** (1 crédit).'],
        ['s-fiyat', 'Quels sont les tarifs ? Combien coûtent les formules ?', 'tarif tarifs prix cout formule combien one basic pro abonnement euro livre',
            `Paiement unique, sans abonnement. Les crédits n’expirent pas :\n${list}\n\nPrix TVA incluse. Chaque formule comprend tous les types de documents, tous les modèles prêts à l’emploi et le téléchargement XSLT.`],
        ['s-hak', 'Quand un crédit est-il utilisé ? L’enregistrement consomme-t-il un crédit ?', 'credit utilise consomme enregistrer valider quand conception',
            'Un crédit de conception n’est utilisé qu’à l’étape **Valider**, une fois par conception.\n- **Enregistrer :** gratuit, autant de fois que vous voulez.\n- **Télécharger le test :** gratuit (le fichier porte un grand filigrane TEST).\n- **Valider (1 crédit) :** la conception est verrouillée et le fichier final sans TEST est téléchargé.\n- Vous pouvez retélécharger **gratuitement** les conceptions validées depuis **Conceptions terminées**.'],
        ['s-ucretsiz', 'Y a-t-il un essai gratuit ? Puis-je l’utiliser gratuitement ?', 'gratuit essai demo sans payer tester',
            'L’inscription est gratuite et vous pouvez faire beaucoup sans acheter de crédits :\n- Utiliser tous les modèles et l’éditeur, concevoir et enregistrer.\n- Télécharger le fichier gratuitement avec **Télécharger le test** et l’essayer dans votre système (avec filigrane TEST).\n\nLe fichier final sans TEST nécessite 1 crédit à l’étape **Valider**. Les nouveaux comptes commencent avec 0 crédit.'],
        ['s-test', 'Qu’est-ce que « Télécharger le test » ? Pourquoi est-il écrit TEST ?', 'telecharger test filigrane fichier essai',
            '**Télécharger le test** (gratuit) télécharge votre conception avec un grand filigrane **TEST** en diagonale pour l’essayer dans votre système.\n- Aucun crédit n’est utilisé ; téléchargez autant que vous voulez.\n- Si vous réimportez le fichier TEST dans l’assistant, le filigrane est retiré et vous reprenez où vous en étiez.\n- Pour le fichier final sans TEST, utilisez **Valider** (1 crédit).'],
        ['s-onay', 'Puis-je modifier une conception après validation ?', 'apres validation modifier editer verrouille conception validee',
            'Une conception validée est **verrouillée** : elle ne peut plus être modifiée, seulement téléchargée.\n- Vous pouvez la retélécharger gratuitement depuis **Conceptions terminées**.\n- Pour des changements, commencez une nouvelle conception (la validation coûte de nouveau 1 crédit).\n\nC’est pourquoi nous conseillons d’essayer d’abord avec **Télécharger le test**.'],
        ['s-belgeler', 'Quels types de documents puis-je concevoir ?', 'types documents facture avoir rectificative acompte partielle bon livraison avis expedition liste',
            'Pour les pays européens :\n- Facture, avoir, facture rectificative\n- Facture d’acompte, facture partielle\n- Bon de livraison (avis d’expédition Peppol)\n\nL’offre dépend du pays choisi ; chaque document apparaît sous son nom local.'],
        ['s-ulke', 'Quels pays et formats sont pris en charge ?', 'pays europe ue eee royaume uni suisse format profil peppol xrechnung en16931 cius langue',
            'Tous les pays de l’UE et de l’EEE, le Royaume-Uni et la Suisse. Lorsque vous choisissez un pays dans l’assistant, ses documents s’affichent avec le profil XML correspondant : **EN 16931**, **Peppol BIS Billing 3.0**, **XRechnung 3.0 (UBL)**, CIUS-RO, HR CIUS, CIUS-PT ou **Peppol Despatch Advice**.\n- La langue du document suit le pays (libellés, dates, format des nombres) et peut être changée dans les pays multilingues.\n- Les documents qui partagent le même format XML utilisent le même modèle.'],
        ['s-xslt', 'Dois-je connaître XSLT ? Qu’est-ce que XSLT ?', 'xslt quoi connaitre code programmation technique',
            'Non, inutile de connaître XSLT. XSLT est le fichier de mise en page qui définit l’apparence des données XML d’une facture électronique à l’écran et à l’impression.\n- Vous choisissez un modèle prêt à l’emploi et le modifiez par **glisser-déposer**.\n- Vous pouvez aussi importer votre propre XSLT (.xslt / .xsl, jusqu’à 5 Mo) avec **Utiliser mon propre fichier XSLT** dans l’assistant.'],
        ['s-xml', 'Puis-je prévisualiser avec mon propre fichier XML ?', 'xml importer propre donnees exemple apercu',
            'Oui. À l’étape des données de l’assistant, utilisez le XML d’exemple de votre pays ou choisissez votre fichier avec **Choisir mon propre fichier XML** (.xml, jusqu’à 5 Mo).\n\nLe XML ne sert qu’à l’aperçu ; la conception fonctionne avec toutes les données. Les fichiers importés sont contrôlés automatiquement selon les règles essentielles du profil.'],
        ['s-kendi-xslt', 'Puis-je importer et modifier ma mise en page XSLT existante ?', 'xslt existant importer modifier mise en page',
            'Oui. Après connexion, choisissez le type de document dans l’assistant puis, à l’étape de conception, **Utiliser mon propre fichier XSLT**. Le fichier est contrôlé puis s’ouvre dans l’écran de conception pour une modification visuelle.\n\nRemarque : un fichier de conception déjà validé (acheté) ne peut pas être rouvert en modification ; téléchargez-le depuis **Conceptions terminées**.'],
        ['s-logo', 'Comment ajouter un logo, un cachet ou une signature ?', 'logo cachet signature image ajouter png',
            'Dans l’écran de conception, choisissez **Image** dans la barre **Insérer** (cliquez ou faites glisser à l’endroit voulu de l’aperçu), puis importez votre logo, cachet ou signature. L’image est intégrée au fichier. Réglez taille et position dans le panneau de droite.'],
        ['s-banka', 'Comment ajouter les coordonnées bancaires / IBAN ?', 'banque iban compte paiement bic coordonnees bancaires',
            'La liste des champs de l’écran de conception contient des champs de paiement comme IBAN, BIC et titulaire ; recherchez « IBAN » puis cliquez ou faites glisser le champ dans l’aperçu. Les valeurs proviennent des données de paiement du XML. Pour des coordonnées fixes, insérez un élément **Texte**.'],
        ['s-editor', 'Que puis-je faire dans l’écran de conception ?', 'editeur conception fonctions glisser deposer tableau colonne texte formule annuler zoom',
            'Dans l’écran de conception, vous pouvez :\n- ajouter Texte, Image, Tableau, Formule, Bloc, QR code et colonnes via la barre **Insérer**\n- insérer tout champ XML depuis la liste des champs par clic ou glisser\n- modifier polices, couleurs, marges et bordures ; masquer ou supprimer des colonnes\n- annuler (Ctrl+Z) / rétablir (Ctrl+Y), zoomer et ajuster à la largeur\n- **Enregistrer**, **Télécharger le test** (gratuit), **Valider** (1 crédit)'],
        ['s-sablon', 'Y a-t-il des modèles prêts à l’emploi ?', 'modele modeles prets galerie exemple conception',
            'Oui. Chaque type de document européen dispose d’un modèle EN 16931 / Peppol prêt à l’emploi, avec des libellés dans la langue du document et des données d’exemple du pays choisi. Ouvrez-le en un clic dans l’écran de conception et adaptez-le à votre entreprise.'],
        ['s-uyum', 'Les conceptions sont-elles conformes EN 16931 ?', 'conforme conformite en16931 peppol xrechnung schematron valide regles norme',
            'Les modèles suivent la structure UBL de la norme **EN 16931** et les profils **Peppol BIS 3** et **XRechnung 3.0**, et ont été testés avec des factures d’exemple de plusieurs pays. L’assistant contrôle les XML importés selon les règles essentielles et vous avertit.\n\nCes contrôles sont un sous-ensemble des règles Schematron officielles et les documents ne sont envoyés à aucun portail ; testez le fichier final dans votre système avec **Télécharger le test**.'],
        ['s-entegrator', 'Où utiliser le fichier XSLT téléchargé ?', 'ou utiliser importer xslt point acces erp logiciel facturation',
            'Importez le fichier .xslt là où votre logiciel de facturation, votre ERP ou votre prestataire de facturation électronique (par exemple votre point d’accès Peppol) permet de définir une **mise en page / feuille de style** pour les factures. Essayez d’abord le fichier de **Télécharger le test**.'],
        ['s-satin', 'Comment acheter ? Comment fonctionne le paiement ?', 'acheter achat paiement carte paytr 3d secure formule commander payer',
            `Inscrivez-vous et connectez-vous, puis cliquez sur **Acheter une formule** en haut à droite de l’écran de sélection.\n- Choisissez une formule, saisissez vos informations de facturation et passez au paiement. Le paiement passe par **PayTR 3D Secure** ; vos données de carte n’atteignent jamais notre serveur.\n- Après un paiement réussi, les crédits sont ajoutés automatiquement à votre compte.\n\nLes formules commencent à ${from}.`],
        ['s-iade', 'Y a-t-il un remboursement ? Que deviennent les crédits inutilisés ?', 'remboursement rembourser annuler credits inutilises expirent transferer',
            'Les crédits **n’expirent pas** et restent sur votre compte jusqu’à leur utilisation. Selon les conditions d’utilisation, les crédits achetés ne sont pas remboursés ni transférables vers d’autres comptes. En cas de problème de paiement, contactez le support.'],
        ['s-odeme-hata', 'Mon paiement a échoué, que faire ?', 'paiement echoue erreur carte refusee debite credits manquants',
            'Si votre carte n’a pas été débitée, réessayez simplement ; vérifiez le code 3D Secure et que votre carte autorise les paiements en ligne. Si vous avez été débité sans recevoir les crédits, contactez le support avec l’e-mail de votre compte.'],
        ['s-uyelik', 'Comment s’inscrire ? Que faut-il ?', 'inscription inscrire compte creer enregistrement',
            'Ouvrez le formulaire avec **Créer un compte** : nom, entreprise, e-mail et mot de passe sont obligatoires, le téléphone est facultatif. Vous êtes ensuite connecté automatiquement. L’inscription est gratuite.'],
        ['s-sifre', 'J’ai oublié mon mot de passe, que faire ?', 'mot de passe oublie reinitialiser connexion impossible',
            `La réinitialisation automatique n’est pas encore disponible. Écrivez au support depuis votre adresse e-mail enregistrée (${MAIL}) ; nous réinitialiserons votre mot de passe après vérification de votre compte.`],
        ['s-tasarimlarim', 'Où sont mes conceptions enregistrées ?', 'mes conceptions enregistrees ou brouillons terminees liste trouver',
            'Après connexion, l’écran de sélection affiche :\n- **Conceptions en cours :** vos brouillons ; ouvrez-les avec **Continuer**.\n- **Conceptions terminées :** vos conceptions validées ; aperçu et nouveau téléchargement gratuits.'],
        ['s-destek', 'Comment contacter le support ?', 'support contact telephone whatsapp e-mail aide service client',
            `Une fois connecté, utilisez le bouton d’assistance en bas à droite pour ouvrir un ticket ou demander une assistance en ligne en direct. Vous pouvez aussi nous joindre sans connexion :\n- **Téléphone / WhatsApp :** ${CONTACT}\n- **E-mail :** ${MAIL}`],
        ['s-veri', 'Mes données sont-elles en sécurité ? Où sont-elles stockées ?', 'donnees securite confidentialite rgpd stockage serveur personnelles',
            'Les données des utilisateurs et des conceptions sont stockées dans une base PostgreSQL ; lors des paiements, vos données de carte n’atteignent jamais notre serveur (PayTR 3D Secure). Les détails figurent dans les liens confidentialité et cookies en bas de page.'],
        ['s-mobil', 'Puis-je l’utiliser sur téléphone ou tablette ?', 'mobile telephone tablette application installer navigateur',
            'Le site fonctionne dans le navigateur, sans installation. La gestion du compte se fait bien sur téléphone, mais l’écran de conception nécessite un grand écran : nous recommandons un ordinateur pour concevoir.'],
    ],
    es: ({ list, from }) => [
        ['s-nedir', '¿Para qué sirve este sitio? ¿Qué es el Diseñador de e-documentos?', 'sitio para que sirve objetivo servicio producto plataforma edxdocu disenador xslt diseno factura electronica',
            'El Diseñador de e-documentos te permite crear el **archivo de diseño (XSLT)** de tus facturas electrónicas y albaranes en los formatos europeos **EN 16931**, **Peppol BIS 3** y **XRechnung**.\n- Elige una plantilla lista o sube tu propio XSLT.\n- Edita logotipo, sello, datos bancarios y campos arrastrando y soltando en el editor visual.\n- Previsualiza con tu propio XML y descarga el XSLT para tu software de facturación.'],
        ['s-baslangic', '¿Cómo empiezo? ¿Cómo hago mi primer diseño?', 'como empezar primer diseno paso guia comenzar nuevo crear',
            'En tres pasos:\n- **Crea una cuenta** e inicia sesión.\n- En el asistente elige tu **país** y el tipo de documento, después la plantilla y los datos de ejemplo.\n- Edita el diseño en la pantalla de diseño, **Guardar**, pruébalo con **Descargar prueba** (gratis) y obtén el archivo final con **Aprobar** (1 crédito).'],
        ['s-fiyat', '¿Cuáles son los precios? ¿Cuánto cuestan los paquetes?', 'precio precios coste paquete cuanto tarifa one basic pro suscripcion euro libra',
            `Pago único, sin suscripción. Los créditos no caducan:\n${list}\n\nPrecios con IVA incluido. Todos los paquetes incluyen todos los tipos de documento, todas las plantillas listas y la descarga del XSLT.`],
        ['s-hak', '¿Cuándo se usa un crédito de diseño? ¿Guardar consume crédito?', 'credito usa consume guardar aprobar cuando diseno',
            'Un crédito de diseño solo se usa en el paso **Aprobar**, una vez por diseño.\n- **Guardar:** gratis, tantas veces como quieras.\n- **Descargar prueba:** gratis (el archivo lleva una gran marca de agua TEST).\n- **Aprobar (1 crédito):** el diseño se bloquea y se descarga el archivo final sin TEST.\n- Puedes volver a descargar **gratis** los diseños aprobados desde **Diseños terminados**.'],
        ['s-ucretsiz', '¿Hay prueba gratuita? ¿Puedo usarlo gratis?', 'gratis gratuito prueba demo sin pagar probar',
            'El registro es gratuito y puedes hacer mucho sin comprar créditos:\n- Usar todas las plantillas y el editor, diseñar y guardar.\n- Descargar el archivo gratis con **Descargar prueba** y probarlo en tu sistema (con marca de agua TEST).\n\nEl archivo final sin TEST requiere 1 crédito en el paso **Aprobar**. Las cuentas nuevas empiezan con 0 créditos.'],
        ['s-test', '¿Qué es «Descargar prueba»? ¿Por qué pone TEST?', 'descargar prueba marca de agua archivo test',
            '**Descargar prueba** (gratis) descarga tu diseño con una gran marca de agua **TEST** en diagonal para que lo pruebes en tu sistema.\n- No usa créditos; descárgalo tantas veces como quieras.\n- Si vuelves a subir el archivo TEST en el asistente, la marca se elimina y sigues donde lo dejaste.\n- Para el archivo final sin TEST, usa **Aprobar** (1 crédito).'],
        ['s-onay', '¿Puedo cambiar un diseño después de aprobarlo?', 'despues aprobar cambiar editar bloqueado diseno aprobado',
            'Un diseño aprobado queda **bloqueado**: ya no se puede editar, solo descargar.\n- Puedes volver a descargarlo gratis desde **Diseños terminados**.\n- Para hacer cambios, empieza un diseño nuevo (la aprobación vuelve a costar 1 crédito).\n\nPor eso recomendamos probar antes con **Descargar prueba**.'],
        ['s-belgeler', '¿Qué tipos de documento puedo diseñar?', 'tipos documento factura nota credito rectificativa anticipo parcial albaran aviso expedicion lista',
            'Para países europeos:\n- Factura, nota de crédito, factura rectificativa\n- Factura de anticipo, factura parcial\n- Albarán (aviso de expedición Peppol)\n\nLos disponibles dependen del país elegido; cada documento aparece con su nombre local.'],
        ['s-ulke', '¿Qué países y formatos se admiten?', 'pais paises europa ue eee reino unido suiza formato perfil peppol xrechnung en16931 cius idioma',
            'Todos los países de la UE y del EEE, el Reino Unido y Suiza. Al elegir un país en el asistente, sus documentos aparecen con el perfil XML correspondiente: **EN 16931**, **Peppol BIS Billing 3.0**, **XRechnung 3.0 (UBL)**, CIUS-RO, HR CIUS, CIUS-PT o **Peppol Despatch Advice**.\n- El idioma del documento sigue al país (etiquetas, fechas y formato numérico) y puede cambiarse en países multilingües.\n- Los documentos que comparten el mismo formato XML usan la misma plantilla.'],
        ['s-xslt', '¿Necesito saber XSLT? ¿Qué es XSLT?', 'xslt que es saber codigo programacion tecnico',
            'No, no necesitas saber XSLT. XSLT es el archivo de diseño que define cómo se ven en pantalla e impresos los datos XML de una factura electrónica.\n- Eliges una plantilla lista y la editas **arrastrando y soltando**.\n- También puedes subir tu propio XSLT (.xslt / .xsl, hasta 5 MB) con **Usar mi propio archivo XSLT** en el asistente.'],
        ['s-xml', '¿Puedo previsualizar con mi propio archivo XML?', 'xml subir propio datos ejemplo vista previa',
            'Sí. En el paso de datos del asistente puedes usar el XML de ejemplo de tu país o elegir tu archivo con **Elegir mi propio archivo XML** (.xml, hasta 5 MB).\n\nEl XML solo sirve para la vista previa; el diseño funciona con cualquier dato. Los archivos subidos se revisan automáticamente con las reglas básicas del perfil.'],
        ['s-kendi-xslt', '¿Puedo subir y editar mi diseño XSLT actual?', 'xslt existente subir editar importar diseno',
            'Sí. Tras iniciar sesión, elige el tipo de documento en el asistente y, en el paso de diseño, **Usar mi propio archivo XSLT**. El archivo se revisa y se abre en la pantalla de diseño para editarlo visualmente.\n\nNota: un archivo de diseño ya aprobado (comprado) no puede volver a editarse; descárgalo desde **Diseños terminados**.'],
        ['s-logo', '¿Cómo añado logotipo, sello o firma?', 'logo logotipo sello firma imagen anadir png',
            'En la pantalla de diseño elige **Imagen** en la barra **Insertar** (haz clic o arrástrala al lugar deseado de la vista previa) y sube tu logotipo, sello o firma. La imagen se incrusta en el archivo. Ajusta tamaño y posición en el panel derecho.'],
        ['s-banka', '¿Cómo añado datos bancarios / IBAN?', 'banco iban cuenta pago bic datos bancarios',
            'La lista de campos de la pantalla de diseño incluye campos de pago como IBAN, BIC y titular; busca «IBAN» y haz clic o arrastra el campo a la vista previa. Los valores proceden de los datos de pago del XML. Para datos bancarios fijos también puedes insertar un elemento **Texto**.'],
        ['s-editor', '¿Qué puedo hacer en la pantalla de diseño?', 'editor diseno funciones arrastrar soltar tabla columna texto formula deshacer zoom',
            'En la pantalla de diseño puedes:\n- añadir Texto, Imagen, Tabla, Fórmula, Bloque, Código QR y columnas con la barra **Insertar**\n- insertar cualquier campo XML de la lista con un clic o arrastrándolo\n- cambiar fuentes, colores, márgenes y bordes; ocultar o eliminar columnas\n- deshacer (Ctrl+Z) / rehacer (Ctrl+Y), hacer zoom y ajustar al ancho\n- **Guardar**, **Descargar prueba** (gratis), **Aprobar** (1 crédito)'],
        ['s-sablon', '¿Hay plantillas listas para usar?', 'plantilla plantillas listas galeria ejemplo diseno',
            'Sí. Cada tipo de documento europeo tiene una plantilla EN 16931 / Peppol lista, con etiquetas en el idioma del documento y datos de ejemplo del país elegido. Ábrela con un clic en la pantalla de diseño y adáptala a tu empresa.'],
        ['s-uyum', '¿Los diseños cumplen con EN 16931?', 'cumple conformidad en16931 peppol xrechnung schematron valido reglas norma',
            'Las plantillas siguen la estructura UBL de la norma **EN 16931** y los perfiles **Peppol BIS 3** y **XRechnung 3.0**, y se han probado con facturas de ejemplo de varios países. El asistente revisa los XML subidos con las reglas básicas y te avisa.\n\nEstos controles son un subconjunto de las reglas Schematron oficiales y los documentos no se envían a ningún portal; prueba el archivo final en tu sistema con **Descargar prueba**.'],
        ['s-entegrator', '¿Dónde uso el archivo XSLT descargado?', 'donde usar subir xslt punto acceso erp software facturacion',
            'Sube el archivo .xslt donde tu software de facturación, tu ERP o tu proveedor de facturación electrónica (por ejemplo tu punto de acceso Peppol) permita definir un **diseño / hoja de estilo** para las facturas. Prueba primero el archivo de **Descargar prueba**.'],
        ['s-satin', '¿Cómo compro? ¿Cómo funciona el pago?', 'comprar compra pago tarjeta paytr 3d secure paquete pedir pagar',
            `Regístrate e inicia sesión y haz clic en **Comprar paquete** arriba a la derecha de la pantalla de selección.\n- Elige un paquete, introduce tus datos de facturación y pasa al pago. El pago se realiza con **PayTR 3D Secure**; los datos de tu tarjeta nunca llegan a nuestro servidor.\n- Tras el pago, los créditos se añaden automáticamente a tu cuenta.\n\nLos paquetes empiezan en ${from}.`],
        ['s-iade', '¿Hay reembolso? ¿Qué pasa con los créditos no usados?', 'reembolso devolucion dinero cancelar creditos no usados caducan transferir',
            'Los créditos **no caducan** y permanecen en tu cuenta hasta que los uses. Según las condiciones de uso, los créditos comprados no se reembolsan ni se pueden transferir a otras cuentas. Si tuviste un problema con el pago, contacta con soporte.'],
        ['s-odeme-hata', 'Mi pago ha fallado, ¿qué hago?', 'pago fallido error tarjeta rechazada cobrado creditos faltan',
            'Si no se te cobró, vuelve a intentarlo; comprueba el código 3D Secure y que tu tarjeta admita pagos en línea. Si se te cobró pero no recibiste los créditos, contacta con soporte indicando el correo de tu cuenta.'],
        ['s-uyelik', '¿Cómo me registro? ¿Qué necesito?', 'registro registrarse cuenta crear alta',
            'Abre el formulario con **Crear cuenta**: nombre, empresa, correo y contraseña son obligatorios; el teléfono es opcional. Después inicias sesión automáticamente. El registro es gratuito.'],
        ['s-sifre', 'He olvidado mi contraseña, ¿qué hago?', 'contrasena olvidada restablecer no puedo iniciar sesion',
            `Aún no hay restablecimiento automático. Escribe a soporte desde tu correo registrado (${MAIL}); restableceremos tu contraseña tras verificar tu cuenta.`],
        ['s-tasarimlarim', '¿Dónde están mis diseños guardados?', 'mis disenos guardados donde borradores terminados lista encontrar',
            'Tras iniciar sesión, la pantalla de selección muestra:\n- **Diseños en curso:** tus borradores; ábrelos con **Continuar**.\n- **Diseños terminados:** tus diseños aprobados; vista previa y nueva descarga gratis.'],
        ['s-destek', '¿Cómo contacto con soporte?', 'soporte contacto telefono whatsapp correo ayuda atencion cliente',
            `Con la sesión iniciada, usa el botón de soporte abajo a la derecha para abrir una incidencia o pedir soporte en línea en directo. También puedes contactarnos sin iniciar sesión:\n- **Teléfono / WhatsApp:** ${CONTACT}\n- **Correo:** ${MAIL}`],
        ['s-veri', '¿Mis datos están seguros? ¿Dónde se guardan?', 'datos seguridad privacidad rgpd almacenamiento servidor personales',
            'Los datos de usuarios y diseños se guardan en una base de datos PostgreSQL; en los pagos, los datos de tu tarjeta nunca llegan a nuestro servidor (PayTR 3D Secure). Encontrarás los detalles en los enlaces de privacidad y cookies al pie de la página.'],
        ['s-mobil', '¿Puedo usarlo en el móvil o la tableta?', 'movil telefono tableta app instalar navegador',
            'El sitio funciona en el navegador, sin instalar nada. La gestión de la cuenta va bien en el móvil, pero la pantalla de diseño necesita una pantalla ancha, así que recomendamos un ordenador para diseñar.'],
    ],
};

const CREDIT_WORD = {
    en: (n) => (n === 1 ? 'design credit' : 'design credits'),
    de: () => 'Design-Guthaben',
    fr: (n) => (n === 1 ? 'crédit de conception' : 'crédits de conception'),
    es: (n) => (n === 1 ? 'crédito de diseño' : 'créditos de diseño'),
};
const PER_DESIGN = { en: 'per design', de: 'pro Design', fr: 'par conception', es: 'por diseño' };

/** Türkçe dışı dil + para birimi için yerleşik kayıtlar (Türkçe bankayla aynı biçimde). */
export const buildIntlSeedKb = (packages, lang, currency) => {
    const list = Object.values(packages);
    const priceOf = (p) => Number(p.prices?.[currency] ?? p.price);
    const lines = list.map((p) => {
        const per = Math.round((priceOf(p) / p.credits) * 100) / 100;
        return `- **${p.name}:** ${money(lang, currency, priceOf(p))} · ${p.credits} ${CREDIT_WORD[lang](p.credits)} (${money(lang, currency, per)} ${PER_DESIGN[lang]})`;
    }).join('\n');
    const cheapest = list.reduce((a, b) => (priceOf(a) <= priceOf(b) ? a : b));
    return TEXTS[lang]({ list: lines, from: money(lang, currency, priceOf(cheapest)) })
        .map(([id, q, keywords, a]) => ({ id, q, keywords, a, actions: ACTIONS[id] ?? [] }));
};

export const INTL_SUGGESTIONS = {
    en: ['What does this site do?', 'What are the prices?', 'How do I create my first design?', 'When is a design credit used?', 'Which countries and formats are supported?', 'Do I need to know XSLT?'],
    de: ['Wofür ist diese Website?', 'Was kosten die Pakete?', 'Wie erstelle ich mein erstes Design?', 'Wann wird ein Design-Guthaben verbraucht?', 'Welche Länder und Formate werden unterstützt?', 'Muss ich XSLT beherrschen?'],
    fr: ['À quoi sert ce site ?', 'Quels sont les tarifs ?', 'Comment créer ma première conception ?', 'Quand un crédit est-il utilisé ?', 'Quels pays et formats sont pris en charge ?', 'Dois-je connaître XSLT ?'],
    es: ['¿Para qué sirve este sitio?', '¿Cuáles son los precios?', '¿Cómo hago mi primer diseño?', '¿Cuándo se usa un crédito de diseño?', '¿Qué países y formatos se admiten?', '¿Necesito saber XSLT?'],
};
