/**
 * EN 16931 (UBL Invoice / CreditNote) ve Peppol BIS Despatch Advice alan kataloğu.
 * Yol sözdizimi `fieldCatalog.ts` ile aynıdır; etiketler 5 dilde tutulur.
 */
import type { Locale } from '../store/uiStore';
import type { DocLanguage } from '../international/registry/docLanguages';
import { extraDocTextPack } from '../international/docText';
import type { CatalogField, CatalogFormat } from './fieldCatalog';

const en = {
    cat: {
        doc: 'Document',
        refs: 'References',
        seller: 'Seller',
        buyer: 'Buyer',
        payee: 'Payee',
        taxRep: 'Seller tax representative',
        despatchParty: 'Despatch party',
        deliveryParty: 'Delivery party',
        orderParty: 'Buyer (ordering)',
        sellerParty: 'Seller (supplier)',
        delivery: 'Delivery',
        shipment: 'Shipment',
        payment: 'Payment',
        allowances: 'Allowances / charges',
        totals: 'Totals',
        vat: 'VAT',
        lines: 'Line items',
    },
    party: {
        seller: 'Seller',
        buyer: 'Buyer',
        payee: 'Payee',
        taxRep: 'Tax representative',
        despatch: 'Despatcher',
        delivery: 'Recipient',
        order: 'Buyer',
        supplier: 'Supplier',
    },
    field: {
        name: 'Name',
        legalName: 'Legal name',
        vatId: 'VAT ID',
        companyId: 'Registration number',
        endpoint: 'Electronic address',
        partyId: 'Identifier',
        street: 'Street',
        street2: 'Additional street',
        city: 'City',
        postal: 'Postal code',
        region: 'Region',
        country: 'Country',
        contact: 'Contact person',
        phone: 'Phone',
        email: 'E-mail',

        invoiceNo: 'Invoice number',
        creditNoteNo: 'Credit note number',
        despatchNo: 'Despatch advice number',
        issueDate: 'Issue date',
        issueTime: 'Issue time',
        dueDate: 'Due date',
        typeCode: 'Document type code',
        note: 'Note',
        taxPointDate: 'Tax point date',
        currency: 'Currency',
        taxCurrency: 'VAT accounting currency',
        buyerRef: 'Buyer reference',
        accountingCost: 'Buyer accounting reference',
        periodStart: 'Invoicing period start',
        periodEnd: 'Invoicing period end',
        customization: 'Specification identifier',
        profile: 'Business process',

        orderRef: 'Purchase order reference',
        salesOrderRef: 'Sales order reference',
        contractRef: 'Contract reference',
        projectRef: 'Project reference',
        despatchRef: 'Despatch advice reference',
        receiptRef: 'Receiving advice reference',
        precedingInvoice: 'Preceding invoice',
        precedingInvoiceDate: 'Preceding invoice date',
        attachmentId: 'Supporting document',
        attachmentDesc: 'Supporting document description',

        deliveryDate: 'Delivery date',
        deliveryLocation: 'Delivery location ID',
        deliverToName: 'Deliver-to party',
        deliveryStreet: 'Delivery street',
        deliveryCity: 'Delivery city',
        deliveryPostal: 'Delivery postal code',
        deliveryCountry: 'Delivery country',

        paymentMeans: 'Payment means code',
        paymentId: 'Payment reference',
        iban: 'IBAN / account number',
        accountName: 'Account name',
        bic: 'BIC',
        cardNumber: 'Card number',
        mandate: 'Direct debit mandate',
        paymentTerms: 'Payment terms',

        allowanceAmount: 'Allowance amount',
        allowanceReason: 'Allowance reason',
        chargeAmount: 'Charge amount',
        chargeReason: 'Charge reason',

        lineTotal: 'Sum of line net amounts',
        taxExclusive: 'Total without VAT',
        taxInclusive: 'Total with VAT',
        allowanceTotal: 'Sum of allowances',
        chargeTotal: 'Sum of charges',
        prepaid: 'Paid amount',
        rounding: 'Rounding amount',
        payable: 'Amount due',

        vatTotal: 'Total VAT amount',
        vatBase: 'VAT category taxable amount',
        vatAmount: 'VAT category tax amount',
        vatCategory: 'VAT category code',
        vatRate: 'VAT rate (%)',
        vatExemption: 'VAT exemption reason',
        vatExemptionCode: 'VAT exemption reason code',

        lineId: 'Line number',
        lineNote: 'Line note',
        quantity: 'Quantity',
        unit: 'Unit',
        lineNet: 'Line net amount',
        itemName: 'Item name',
        itemDesc: 'Item description',
        sellerItemId: 'Seller item ID',
        buyerItemId: 'Buyer item ID',
        standardItemId: 'Standard item ID (GTIN)',
        originCountry: 'Country of origin',
        classification: 'Item classification',
        lineVatCategory: 'Line VAT category',
        lineVatRate: 'Line VAT rate (%)',
        price: 'Unit price',
        baseQuantity: 'Price base quantity',
        priceDiscount: 'Price discount',
        lineAllowance: 'Line allowance',
        lineAllowanceReason: 'Line allowance reason',
        orderLineRef: 'Order line reference',
        linePeriodStart: 'Line period start',
        linePeriodEnd: 'Line period end',

        shipmentId: 'Shipment ID',
        grossWeight: 'Gross weight',
        grossVolume: 'Gross volume',
        trackingId: 'Tracking number',
        estStartDate: 'Estimated delivery from (date)',
        estStartTime: 'Estimated delivery from (time)',
        estEndDate: 'Estimated delivery until (date)',
        estEndTime: 'Estimated delivery until (time)',
        carrier: 'Carrier',
        despatchDate: 'Despatch date',
        despatchTime: 'Despatch time',
        handlingUnit: 'Transport handling unit (SSCC)',
        handlingUnitType: 'Handling unit type',
        deliveredQty: 'Delivered quantity',
        outstandingQty: 'Outstanding quantity',
        outstandingReason: 'Outstanding reason',
        lot: 'Lot number',
        expiry: 'Best before / expiry date',
        serial: 'Serial number',
    },
};

type Labels = typeof en;
export type IntlLabels = Labels;

const tr: Labels = {
    cat: {
        doc: 'Belge Bilgileri',
        refs: 'Referanslar',
        seller: 'Satıcı',
        buyer: 'Alıcı',
        payee: 'Ödeme Alacaklısı',
        taxRep: 'Satıcının Vergi Temsilcisi',
        despatchParty: 'Gönderen',
        deliveryParty: 'Teslim Alan',
        orderParty: 'Alıcı (Sipariş Veren)',
        sellerParty: 'Satıcı (Tedarikçi)',
        delivery: 'Teslimat',
        shipment: 'Sevkiyat',
        payment: 'Ödeme',
        allowances: 'İskonto / Masraf',
        totals: 'Tutarlar',
        vat: 'KDV',
        lines: 'Satır (Kalem)',
    },
    party: {
        seller: 'Satıcı',
        buyer: 'Alıcı',
        payee: 'Alacaklı',
        taxRep: 'Vergi Temsilcisi',
        despatch: 'Gönderen',
        delivery: 'Teslim Alan',
        order: 'Sipariş Veren',
        supplier: 'Tedarikçi',
    },
    field: {
        name: 'Adı / Unvanı',
        legalName: 'Resmi Unvanı',
        vatId: 'KDV No',
        companyId: 'Sicil No',
        endpoint: 'Elektronik Adres',
        partyId: 'Tanımlayıcı',
        street: 'Cadde/Sokak',
        street2: 'Ek Adres',
        city: 'Şehir',
        postal: 'Posta Kodu',
        region: 'Bölge',
        country: 'Ülke',
        contact: 'İlgili Kişi',
        phone: 'Telefon',
        email: 'E-posta',

        invoiceNo: 'Fatura No',
        creditNoteNo: 'Alacak Dekontu No',
        despatchNo: 'İrsaliye No',
        issueDate: 'Düzenleme Tarihi',
        issueTime: 'Düzenleme Saati',
        dueDate: 'Vade Tarihi',
        typeCode: 'Belge Tipi Kodu',
        note: 'Not',
        taxPointDate: 'Vergi Doğuş Tarihi',
        currency: 'Para Birimi',
        taxCurrency: 'KDV Muhasebe Para Birimi',
        buyerRef: 'Alıcı Referansı',
        accountingCost: 'Alıcı Muhasebe Referansı',
        periodStart: 'Fatura Dönemi Başlangıcı',
        periodEnd: 'Fatura Dönemi Bitişi',
        customization: 'Özelleştirme No',
        profile: 'İş Süreci',

        orderRef: 'Sipariş No',
        salesOrderRef: 'Satış Siparişi No',
        contractRef: 'Sözleşme No',
        projectRef: 'Proje No',
        despatchRef: 'İrsaliye No',
        receiptRef: 'Teslim Alma Belgesi No',
        precedingInvoice: 'Önceki Fatura No',
        precedingInvoiceDate: 'Önceki Fatura Tarihi',
        attachmentId: 'Ek Belge No',
        attachmentDesc: 'Ek Belge Açıklaması',

        deliveryDate: 'Teslim Tarihi',
        deliveryLocation: 'Teslim Yeri Kodu',
        deliverToName: 'Teslim Edilen Taraf',
        deliveryStreet: 'Teslimat Adresi',
        deliveryCity: 'Teslimat Şehri',
        deliveryPostal: 'Teslimat Posta Kodu',
        deliveryCountry: 'Teslimat Ülkesi',

        paymentMeans: 'Ödeme Şekli Kodu',
        paymentId: 'Ödeme Referansı',
        iban: 'IBAN / Hesap No',
        accountName: 'Hesap Adı',
        bic: 'BIC',
        cardNumber: 'Kart No',
        mandate: 'Otomatik Ödeme Talimatı',
        paymentTerms: 'Ödeme Koşulları',

        allowanceAmount: 'İskonto Tutarı',
        allowanceReason: 'İskonto Nedeni',
        chargeAmount: 'Masraf Tutarı',
        chargeReason: 'Masraf Nedeni',

        lineTotal: 'Satır Net Tutarları Toplamı',
        taxExclusive: 'KDV Hariç Toplam',
        taxInclusive: 'KDV Dahil Toplam',
        allowanceTotal: 'Toplam İskonto',
        chargeTotal: 'Toplam Masraf',
        prepaid: 'Ödenmiş Tutar',
        rounding: 'Yuvarlama Tutarı',
        payable: 'Ödenecek Tutar',

        vatTotal: 'Toplam KDV',
        vatBase: 'KDV Matrahı',
        vatAmount: 'KDV Tutarı',
        vatCategory: 'KDV Kategori Kodu',
        vatRate: 'KDV Oranı (%)',
        vatExemption: 'KDV Muafiyet Sebebi',
        vatExemptionCode: 'KDV Muafiyet Kodu',

        lineId: 'Satır No',
        lineNote: 'Satır Notu',
        quantity: 'Miktar',
        unit: 'Birim',
        lineNet: 'Satır Net Tutarı',
        itemName: 'Ürün / Hizmet Adı',
        itemDesc: 'Ürün Açıklaması',
        sellerItemId: 'Satıcı Ürün Kodu',
        buyerItemId: 'Alıcı Ürün Kodu',
        standardItemId: 'Standart Ürün Kodu (GTIN)',
        originCountry: 'Menşe Ülkesi',
        classification: 'Ürün Sınıflandırması',
        lineVatCategory: 'Satır KDV Kategorisi',
        lineVatRate: 'Satır KDV Oranı (%)',
        price: 'Birim Fiyat',
        baseQuantity: 'Fiyat Baz Miktarı',
        priceDiscount: 'Fiyat İndirimi',
        lineAllowance: 'Satır İskontosu',
        lineAllowanceReason: 'Satır İskonto Nedeni',
        orderLineRef: 'Sipariş Satır No',
        linePeriodStart: 'Satır Dönemi Başlangıcı',
        linePeriodEnd: 'Satır Dönemi Bitişi',

        shipmentId: 'Sevkiyat No',
        grossWeight: 'Brüt Ağırlık',
        grossVolume: 'Brüt Hacim',
        trackingId: 'Takip No',
        estStartDate: 'Tahmini Teslim Başlangıcı (tarih)',
        estStartTime: 'Tahmini Teslim Başlangıcı (saat)',
        estEndDate: 'Tahmini Teslim Bitişi (tarih)',
        estEndTime: 'Tahmini Teslim Bitişi (saat)',
        carrier: 'Taşıyıcı',
        despatchDate: 'Sevk Tarihi',
        despatchTime: 'Sevk Saati',
        handlingUnit: 'Taşıma Birimi (SSCC)',
        handlingUnitType: 'Taşıma Birimi Türü',
        deliveredQty: 'Gönderilen Miktar',
        outstandingQty: 'Eksik Miktar',
        outstandingReason: 'Eksik Miktar Nedeni',
        lot: 'Parti No',
        expiry: 'Son Kullanma Tarihi',
        serial: 'Seri No',
    },
};

const de: Labels = {
    cat: {
        doc: 'Dokument',
        refs: 'Referenzen',
        seller: 'Verkäufer',
        buyer: 'Käufer',
        payee: 'Zahlungsempfänger',
        taxRep: 'Steuervertreter des Verkäufers',
        despatchParty: 'Versender',
        deliveryParty: 'Warenempfänger',
        orderParty: 'Käufer (Besteller)',
        sellerParty: 'Verkäufer (Lieferant)',
        delivery: 'Lieferung',
        shipment: 'Sendung',
        payment: 'Zahlung',
        allowances: 'Nachlässe / Zuschläge',
        totals: 'Beträge',
        vat: 'Umsatzsteuer',
        lines: 'Positionen',
    },
    party: {
        seller: 'Verkäufer',
        buyer: 'Käufer',
        payee: 'Zahlungsempfänger',
        taxRep: 'Steuervertreter',
        despatch: 'Versender',
        delivery: 'Empfänger',
        order: 'Besteller',
        supplier: 'Lieferant',
    },
    field: {
        name: 'Name',
        legalName: 'Firmenname',
        vatId: 'USt-IdNr.',
        companyId: 'Registernummer',
        endpoint: 'Elektronische Adresse',
        partyId: 'Kennung',
        street: 'Straße',
        street2: 'Adresszusatz',
        city: 'Ort',
        postal: 'PLZ',
        region: 'Bundesland / Region',
        country: 'Land',
        contact: 'Ansprechpartner',
        phone: 'Telefon',
        email: 'E-Mail',

        invoiceNo: 'Rechnungsnummer',
        creditNoteNo: 'Gutschriftsnummer',
        despatchNo: 'Lieferscheinnummer',
        issueDate: 'Ausstellungsdatum',
        issueTime: 'Ausstellungszeit',
        dueDate: 'Fälligkeitsdatum',
        typeCode: 'Dokumentart-Code',
        note: 'Bemerkung',
        taxPointDate: 'Steuerlicher Leistungszeitpunkt',
        currency: 'Währung',
        taxCurrency: 'Steuerwährung',
        buyerRef: 'Käuferreferenz (Leitweg-ID)',
        accountingCost: 'Buchungsreferenz des Käufers',
        periodStart: 'Leistungszeitraum von',
        periodEnd: 'Leistungszeitraum bis',
        customization: 'Spezifikationskennung',
        profile: 'Geschäftsprozess',

        orderRef: 'Bestellnummer',
        salesOrderRef: 'Auftragsnummer',
        contractRef: 'Vertragsnummer',
        projectRef: 'Projektnummer',
        despatchRef: 'Lieferscheinnummer',
        receiptRef: 'Wareneingangsnummer',
        precedingInvoice: 'Vorherige Rechnung',
        precedingInvoiceDate: 'Datum der vorherigen Rechnung',
        attachmentId: 'Rechnungsbegründendes Dokument',
        attachmentDesc: 'Beschreibung des Dokuments',

        deliveryDate: 'Lieferdatum',
        deliveryLocation: 'Lieferort-Kennung',
        deliverToName: 'Lieferempfänger',
        deliveryStreet: 'Lieferstraße',
        deliveryCity: 'Lieferort',
        deliveryPostal: 'Liefer-PLZ',
        deliveryCountry: 'Lieferland',

        paymentMeans: 'Zahlungsart-Code',
        paymentId: 'Verwendungszweck',
        iban: 'IBAN / Kontonummer',
        accountName: 'Kontoinhaber',
        bic: 'BIC',
        cardNumber: 'Kartennummer',
        mandate: 'Mandatsreferenz',
        paymentTerms: 'Zahlungsbedingungen',

        allowanceAmount: 'Nachlassbetrag',
        allowanceReason: 'Grund des Nachlasses',
        chargeAmount: 'Zuschlagsbetrag',
        chargeReason: 'Grund des Zuschlags',

        lineTotal: 'Summe der Positionen (netto)',
        taxExclusive: 'Gesamtbetrag ohne USt.',
        taxInclusive: 'Gesamtbetrag mit USt.',
        allowanceTotal: 'Summe der Nachlässe',
        chargeTotal: 'Summe der Zuschläge',
        prepaid: 'Gezahlter Betrag',
        rounding: 'Rundungsbetrag',
        payable: 'Zahlbetrag',

        vatTotal: 'USt.-Gesamtbetrag',
        vatBase: 'Steuerbemessungsgrundlage',
        vatAmount: 'Steuerbetrag der Kategorie',
        vatCategory: 'USt.-Kategorie',
        vatRate: 'USt.-Satz (%)',
        vatExemption: 'Befreiungsgrund',
        vatExemptionCode: 'Befreiungsgrund-Code',

        lineId: 'Position',
        lineNote: 'Positionsbemerkung',
        quantity: 'Menge',
        unit: 'Einheit',
        lineNet: 'Nettobetrag',
        itemName: 'Artikelbezeichnung',
        itemDesc: 'Artikelbeschreibung',
        sellerItemId: 'Artikelnummer (Verkäufer)',
        buyerItemId: 'Artikelnummer (Käufer)',
        standardItemId: 'Standard-Artikelnummer (GTIN)',
        originCountry: 'Ursprungsland',
        classification: 'Artikelklassifizierung',
        lineVatCategory: 'USt.-Kategorie der Position',
        lineVatRate: 'USt.-Satz der Position (%)',
        price: 'Einzelpreis',
        baseQuantity: 'Preisbasismenge',
        priceDiscount: 'Preisnachlass',
        lineAllowance: 'Positionsnachlass',
        lineAllowanceReason: 'Grund des Positionsnachlasses',
        orderLineRef: 'Bestellposition',
        linePeriodStart: 'Positionszeitraum von',
        linePeriodEnd: 'Positionszeitraum bis',

        shipmentId: 'Sendungsnummer',
        grossWeight: 'Bruttogewicht',
        grossVolume: 'Bruttovolumen',
        trackingId: 'Sendungsverfolgungsnummer',
        estStartDate: 'Voraussichtliche Lieferung ab (Datum)',
        estStartTime: 'Voraussichtliche Lieferung ab (Uhrzeit)',
        estEndDate: 'Voraussichtliche Lieferung bis (Datum)',
        estEndTime: 'Voraussichtliche Lieferung bis (Uhrzeit)',
        carrier: 'Frachtführer',
        despatchDate: 'Versanddatum',
        despatchTime: 'Versandzeit',
        handlingUnit: 'Packstück (SSCC)',
        handlingUnitType: 'Packstückart',
        deliveredQty: 'Gelieferte Menge',
        outstandingQty: 'Fehlmenge',
        outstandingReason: 'Grund der Fehlmenge',
        lot: 'Chargennummer',
        expiry: 'Mindesthaltbarkeitsdatum',
        serial: 'Seriennummer',
    },
};

const fr: Labels = {
    cat: {
        doc: 'Document',
        refs: 'Références',
        seller: 'Vendeur',
        buyer: 'Acheteur',
        payee: 'Bénéficiaire du paiement',
        taxRep: 'Représentant fiscal du vendeur',
        despatchParty: 'Expéditeur',
        deliveryParty: 'Destinataire',
        orderParty: 'Acheteur (donneur d’ordre)',
        sellerParty: 'Vendeur (fournisseur)',
        delivery: 'Livraison',
        shipment: 'Expédition',
        payment: 'Paiement',
        allowances: 'Remises / frais',
        totals: 'Montants',
        vat: 'TVA',
        lines: 'Lignes',
    },
    party: {
        seller: 'Vendeur',
        buyer: 'Acheteur',
        payee: 'Bénéficiaire',
        taxRep: 'Représentant fiscal',
        despatch: 'Expéditeur',
        delivery: 'Destinataire',
        order: 'Donneur d’ordre',
        supplier: 'Fournisseur',
    },
    field: {
        name: 'Nom',
        legalName: 'Raison sociale',
        vatId: 'N° TVA',
        companyId: 'N° d’immatriculation (SIREN)',
        endpoint: 'Adresse électronique',
        partyId: 'Identifiant',
        street: 'Rue',
        street2: 'Complément d’adresse',
        city: 'Ville',
        postal: 'Code postal',
        region: 'Région',
        country: 'Pays',
        contact: 'Contact',
        phone: 'Téléphone',
        email: 'E-mail',

        invoiceNo: 'N° de facture',
        creditNoteNo: 'N° d’avoir',
        despatchNo: 'N° de bon de livraison',
        issueDate: 'Date d’émission',
        issueTime: 'Heure d’émission',
        dueDate: 'Date d’échéance',
        typeCode: 'Code type de document',
        note: 'Note',
        taxPointDate: 'Date d’exigibilité de la TVA',
        currency: 'Devise',
        taxCurrency: 'Devise de comptabilisation de la TVA',
        buyerRef: 'Référence acheteur',
        accountingCost: 'Référence comptable de l’acheteur',
        periodStart: 'Début de période de facturation',
        periodEnd: 'Fin de période de facturation',
        customization: 'Identifiant de spécification',
        profile: 'Processus métier',

        orderRef: 'N° de commande',
        salesOrderRef: 'N° de commande client',
        contractRef: 'N° de contrat',
        projectRef: 'N° de projet',
        despatchRef: 'N° de bon de livraison',
        receiptRef: 'N° d’avis de réception',
        precedingInvoice: 'Facture précédente',
        precedingInvoiceDate: 'Date de la facture précédente',
        attachmentId: 'Pièce justificative',
        attachmentDesc: 'Description de la pièce justificative',

        deliveryDate: 'Date de livraison',
        deliveryLocation: 'Identifiant du lieu de livraison',
        deliverToName: 'Livré à',
        deliveryStreet: 'Rue de livraison',
        deliveryCity: 'Ville de livraison',
        deliveryPostal: 'Code postal de livraison',
        deliveryCountry: 'Pays de livraison',

        paymentMeans: 'Code moyen de paiement',
        paymentId: 'Référence de paiement',
        iban: 'IBAN / n° de compte',
        accountName: 'Titulaire du compte',
        bic: 'BIC',
        cardNumber: 'N° de carte',
        mandate: 'Référence du mandat',
        paymentTerms: 'Conditions de paiement',

        allowanceAmount: 'Montant de la remise',
        allowanceReason: 'Motif de la remise',
        chargeAmount: 'Montant des frais',
        chargeReason: 'Motif des frais',

        lineTotal: 'Somme des montants nets des lignes',
        taxExclusive: 'Total HT',
        taxInclusive: 'Total TTC',
        allowanceTotal: 'Total des remises',
        chargeTotal: 'Total des frais',
        prepaid: 'Montant déjà payé',
        rounding: 'Arrondi',
        payable: 'Net à payer',

        vatTotal: 'Total TVA',
        vatBase: 'Base imposable',
        vatAmount: 'Montant de TVA',
        vatCategory: 'Code catégorie de TVA',
        vatRate: 'Taux de TVA (%)',
        vatExemption: 'Motif d’exonération',
        vatExemptionCode: 'Code motif d’exonération',

        lineId: 'N° de ligne',
        lineNote: 'Note de ligne',
        quantity: 'Quantité',
        unit: 'Unité',
        lineNet: 'Montant net',
        itemName: 'Désignation',
        itemDesc: 'Description de l’article',
        sellerItemId: 'Réf. article vendeur',
        buyerItemId: 'Réf. article acheteur',
        standardItemId: 'Code article standard (GTIN)',
        originCountry: 'Pays d’origine',
        classification: 'Classification de l’article',
        lineVatCategory: 'Catégorie de TVA de la ligne',
        lineVatRate: 'Taux de TVA de la ligne (%)',
        price: 'Prix unitaire',
        baseQuantity: 'Quantité de base du prix',
        priceDiscount: 'Rabais sur le prix',
        lineAllowance: 'Remise de ligne',
        lineAllowanceReason: 'Motif de la remise de ligne',
        orderLineRef: 'Ligne de commande',
        linePeriodStart: 'Début de période de la ligne',
        linePeriodEnd: 'Fin de période de la ligne',

        shipmentId: 'N° d’expédition',
        grossWeight: 'Poids brut',
        grossVolume: 'Volume brut',
        trackingId: 'N° de suivi',
        estStartDate: 'Livraison prévue à partir du (date)',
        estStartTime: 'Livraison prévue à partir de (heure)',
        estEndDate: 'Livraison prévue jusqu’au (date)',
        estEndTime: 'Livraison prévue jusqu’à (heure)',
        carrier: 'Transporteur',
        despatchDate: 'Date d’expédition',
        despatchTime: 'Heure d’expédition',
        handlingUnit: 'Unité de manutention (SSCC)',
        handlingUnitType: 'Type d’unité de manutention',
        deliveredQty: 'Quantité livrée',
        outstandingQty: 'Quantité restante',
        outstandingReason: 'Motif du reliquat',
        lot: 'N° de lot',
        expiry: 'Date limite / DLUO',
        serial: 'N° de série',
    },
};

const es: Labels = {
    cat: {
        doc: 'Documento',
        refs: 'Referencias',
        seller: 'Vendedor',
        buyer: 'Comprador',
        payee: 'Beneficiario del pago',
        taxRep: 'Representante fiscal del vendedor',
        despatchParty: 'Remitente',
        deliveryParty: 'Destinatario',
        orderParty: 'Comprador (solicitante)',
        sellerParty: 'Vendedor (proveedor)',
        delivery: 'Entrega',
        shipment: 'Envío',
        payment: 'Pago',
        allowances: 'Descuentos / cargos',
        totals: 'Importes',
        vat: 'IVA',
        lines: 'Líneas',
    },
    party: {
        seller: 'Vendedor',
        buyer: 'Comprador',
        payee: 'Beneficiario',
        taxRep: 'Representante fiscal',
        despatch: 'Remitente',
        delivery: 'Destinatario',
        order: 'Solicitante',
        supplier: 'Proveedor',
    },
    field: {
        name: 'Nombre',
        legalName: 'Razón social',
        vatId: 'NIF-IVA',
        companyId: 'N.º de registro',
        endpoint: 'Dirección electrónica',
        partyId: 'Identificador',
        street: 'Calle',
        street2: 'Dirección adicional',
        city: 'Ciudad',
        postal: 'Código postal',
        region: 'Provincia / región',
        country: 'País',
        contact: 'Persona de contacto',
        phone: 'Teléfono',
        email: 'Correo electrónico',

        invoiceNo: 'N.º de factura',
        creditNoteNo: 'N.º de abono',
        despatchNo: 'N.º de albarán',
        issueDate: 'Fecha de emisión',
        issueTime: 'Hora de emisión',
        dueDate: 'Fecha de vencimiento',
        typeCode: 'Código de tipo de documento',
        note: 'Nota',
        taxPointDate: 'Fecha de devengo del IVA',
        currency: 'Moneda',
        taxCurrency: 'Moneda de contabilización del IVA',
        buyerRef: 'Referencia del comprador',
        accountingCost: 'Referencia contable del comprador',
        periodStart: 'Inicio del periodo de facturación',
        periodEnd: 'Fin del periodo de facturación',
        customization: 'Identificador de especificación',
        profile: 'Proceso de negocio',

        orderRef: 'N.º de pedido',
        salesOrderRef: 'N.º de pedido de venta',
        contractRef: 'N.º de contrato',
        projectRef: 'N.º de proyecto',
        despatchRef: 'N.º de albarán',
        receiptRef: 'N.º de aviso de recepción',
        precedingInvoice: 'Factura anterior',
        precedingInvoiceDate: 'Fecha de la factura anterior',
        attachmentId: 'Documento justificativo',
        attachmentDesc: 'Descripción del documento justificativo',

        deliveryDate: 'Fecha de entrega',
        deliveryLocation: 'Identificador del lugar de entrega',
        deliverToName: 'Entregar a',
        deliveryStreet: 'Calle de entrega',
        deliveryCity: 'Ciudad de entrega',
        deliveryPostal: 'Código postal de entrega',
        deliveryCountry: 'País de entrega',

        paymentMeans: 'Código de forma de pago',
        paymentId: 'Referencia de pago',
        iban: 'IBAN / n.º de cuenta',
        accountName: 'Titular de la cuenta',
        bic: 'BIC',
        cardNumber: 'N.º de tarjeta',
        mandate: 'Referencia del mandato',
        paymentTerms: 'Condiciones de pago',

        allowanceAmount: 'Importe del descuento',
        allowanceReason: 'Motivo del descuento',
        chargeAmount: 'Importe del cargo',
        chargeReason: 'Motivo del cargo',

        lineTotal: 'Suma de importes netos de línea',
        taxExclusive: 'Total sin IVA',
        taxInclusive: 'Total con IVA',
        allowanceTotal: 'Total de descuentos',
        chargeTotal: 'Total de cargos',
        prepaid: 'Importe pagado',
        rounding: 'Redondeo',
        payable: 'Importe a pagar',

        vatTotal: 'Total IVA',
        vatBase: 'Base imponible',
        vatAmount: 'Cuota de IVA',
        vatCategory: 'Código de categoría de IVA',
        vatRate: 'Tipo de IVA (%)',
        vatExemption: 'Motivo de exención',
        vatExemptionCode: 'Código de motivo de exención',

        lineId: 'N.º de línea',
        lineNote: 'Nota de línea',
        quantity: 'Cantidad',
        unit: 'Unidad',
        lineNet: 'Importe neto',
        itemName: 'Descripción del artículo',
        itemDesc: 'Detalle del artículo',
        sellerItemId: 'Ref. artículo del vendedor',
        buyerItemId: 'Ref. artículo del comprador',
        standardItemId: 'Código estándar (GTIN)',
        originCountry: 'País de origen',
        classification: 'Clasificación del artículo',
        lineVatCategory: 'Categoría de IVA de la línea',
        lineVatRate: 'Tipo de IVA de la línea (%)',
        price: 'Precio unitario',
        baseQuantity: 'Cantidad base del precio',
        priceDiscount: 'Descuento en precio',
        lineAllowance: 'Descuento de línea',
        lineAllowanceReason: 'Motivo del descuento de línea',
        orderLineRef: 'Línea de pedido',
        linePeriodStart: 'Inicio del periodo de la línea',
        linePeriodEnd: 'Fin del periodo de la línea',

        shipmentId: 'N.º de envío',
        grossWeight: 'Peso bruto',
        grossVolume: 'Volumen bruto',
        trackingId: 'N.º de seguimiento',
        estStartDate: 'Entrega prevista desde (fecha)',
        estStartTime: 'Entrega prevista desde (hora)',
        estEndDate: 'Entrega prevista hasta (fecha)',
        estEndTime: 'Entrega prevista hasta (hora)',
        carrier: 'Transportista',
        despatchDate: 'Fecha de envío',
        despatchTime: 'Hora de envío',
        handlingUnit: 'Unidad de manipulación (SSCC)',
        handlingUnitType: 'Tipo de unidad de manipulación',
        deliveredQty: 'Cantidad entregada',
        outstandingQty: 'Cantidad pendiente',
        outstandingReason: 'Motivo de la cantidad pendiente',
        lot: 'N.º de lote',
        expiry: 'Fecha de caducidad',
        serial: 'N.º de serie',
    },
};

const LABELS: Record<Locale, Labels> = { tr, en, de, fr, es };

type Cat = keyof Labels['cat'];
type Party = keyof Labels['party'];
type Field = keyof Labels['field'];
type Row = [field: Field, path: string, format?: CatalogFormat];
type PartyRow = [party: Party, field: Field, path: string];
type Group = [cat: Cat, rows: (Row | PartyRow)[]];

export type IntlRoot = 'Invoice' | 'CreditNote' | 'DespatchAdvice';

const PARTY_FIELDS: [Field, string][] = [
    ['name', 'PartyName/Name'],
    ['legalName', 'PartyLegalEntity/RegistrationName'],
    ['vatId', 'PartyTaxScheme/CompanyID'],
    ['companyId', 'PartyLegalEntity/CompanyID'],
    ['endpoint', 'EndpointID'],
    ['partyId', 'PartyIdentification/ID'],
    ['street', 'PostalAddress/StreetName'],
    ['street2', 'PostalAddress/AdditionalStreetName'],
    ['city', 'PostalAddress/CityName'],
    ['postal', 'PostalAddress/PostalZone'],
    ['region', 'PostalAddress/CountrySubentity'],
    ['country', 'PostalAddress/Country/IdentificationCode'],
    ['contact', 'Contact/Name'],
    ['phone', 'Contact/Telephone'],
    ['email', 'Contact/ElectronicMail'],
];

/** `base` doğrudan Party tipindeyse (PayeeParty, TaxRepresentativeParty) ara `Party` adımı yoktur. */
const party = (p: Party, base: string, only?: Field[]): PartyRow[] =>
    PARTY_FIELDS.filter(([f]) => !only || only.includes(f)).map(([f, sub]) => [p, f, `${base}/${sub}`]);

function billingGroups(root: 'Invoice' | 'CreditNote'): Group[] {
    const line = root === 'Invoice' ? 'InvoiceLine' : 'CreditNoteLine';
    const qty = root === 'Invoice' ? 'InvoicedQuantity' : 'CreditedQuantity';
    return [
        ['doc', [
            [root === 'Invoice' ? 'invoiceNo' : 'creditNoteNo', 'ID'],
            ['issueDate', 'IssueDate', 'date'],
            ...(root === 'Invoice' ? [['dueDate', 'DueDate', 'date'] as Row] : []),
            ['typeCode', `${root}TypeCode`],
            ['note', 'Note'],
            ['taxPointDate', 'TaxPointDate', 'date'],
            ['currency', 'DocumentCurrencyCode'],
            ['taxCurrency', 'TaxCurrencyCode'],
            ['buyerRef', 'BuyerReference'],
            ['accountingCost', 'AccountingCost'],
            ['periodStart', 'InvoicePeriod/StartDate', 'date'],
            ['periodEnd', 'InvoicePeriod/EndDate', 'date'],
            ['customization', 'CustomizationID'],
            ['profile', 'ProfileID'],
        ]],
        ['refs', [
            ['orderRef', 'OrderReference/ID'],
            ['salesOrderRef', 'OrderReference/SalesOrderID'],
            ['contractRef', 'ContractDocumentReference/ID'],
            ['projectRef', 'ProjectReference/ID'],
            ['despatchRef', 'DespatchDocumentReference/ID'],
            ['receiptRef', 'ReceiptDocumentReference/ID'],
            ['precedingInvoice', 'BillingReference/InvoiceDocumentReference/ID'],
            ['precedingInvoiceDate', 'BillingReference/InvoiceDocumentReference/IssueDate', 'date'],
            ['attachmentId', 'AdditionalDocumentReference/ID'],
            ['attachmentDesc', 'AdditionalDocumentReference/DocumentDescription'],
        ]],
        ['seller', party('seller', 'AccountingSupplierParty/Party')],
        ['buyer', party('buyer', 'AccountingCustomerParty/Party')],
        ['payee', party('payee', 'PayeeParty', ['name', 'partyId', 'companyId'])],
        ['taxRep', party('taxRep', 'TaxRepresentativeParty', ['name', 'vatId', 'street', 'city', 'postal', 'country'])],
        ['delivery', [
            ['deliveryDate', 'Delivery/ActualDeliveryDate', 'date'],
            ['deliveryLocation', 'Delivery/DeliveryLocation/ID'],
            ['deliverToName', 'Delivery/DeliveryParty/PartyName/Name'],
            ['deliveryStreet', 'Delivery/DeliveryLocation/Address/StreetName'],
            ['deliveryCity', 'Delivery/DeliveryLocation/Address/CityName'],
            ['deliveryPostal', 'Delivery/DeliveryLocation/Address/PostalZone'],
            ['deliveryCountry', 'Delivery/DeliveryLocation/Address/Country/IdentificationCode'],
        ]],
        ['payment', [
            ['paymentMeans', 'PaymentMeans/PaymentMeansCode'],
            ['paymentId', 'PaymentMeans/PaymentID'],
            ['iban', 'PaymentMeans/PayeeFinancialAccount/ID'],
            ['accountName', 'PaymentMeans/PayeeFinancialAccount/Name'],
            ['bic', 'PaymentMeans/PayeeFinancialAccount/FinancialInstitutionBranch/ID'],
            ['cardNumber', 'PaymentMeans/CardAccount/PrimaryAccountNumberID'],
            ['mandate', 'PaymentMeans/PaymentMandate/ID'],
            ['paymentTerms', 'PaymentTerms/Note'],
        ]],
        ['allowances', [
            ['allowanceAmount', "AllowanceCharge[ChargeIndicator='false']/Amount", 'amount'],
            ['allowanceReason', "AllowanceCharge[ChargeIndicator='false']/AllowanceChargeReason"],
            ['chargeAmount', "AllowanceCharge[ChargeIndicator='true']/Amount", 'amount'],
            ['chargeReason', "AllowanceCharge[ChargeIndicator='true']/AllowanceChargeReason"],
        ]],
        ['totals', [
            ['lineTotal', 'LegalMonetaryTotal/LineExtensionAmount', 'amount'],
            ['taxExclusive', 'LegalMonetaryTotal/TaxExclusiveAmount', 'amount'],
            ['taxInclusive', 'LegalMonetaryTotal/TaxInclusiveAmount', 'amount'],
            ['allowanceTotal', 'LegalMonetaryTotal/AllowanceTotalAmount', 'amount'],
            ['chargeTotal', 'LegalMonetaryTotal/ChargeTotalAmount', 'amount'],
            ['prepaid', 'LegalMonetaryTotal/PrepaidAmount', 'amount'],
            ['rounding', 'LegalMonetaryTotal/PayableRoundingAmount', 'amount'],
            ['payable', 'LegalMonetaryTotal/PayableAmount', 'amount'],
        ]],
        ['vat', [
            ['vatTotal', 'TaxTotal/TaxAmount', 'amount'],
            ['vatBase', 'TaxTotal/TaxSubtotal/TaxableAmount', 'amount'],
            ['vatAmount', 'TaxTotal/TaxSubtotal/TaxAmount', 'amount'],
            ['vatCategory', 'TaxTotal/TaxSubtotal/TaxCategory/ID'],
            ['vatRate', 'TaxTotal/TaxSubtotal/TaxCategory/Percent', 'number'],
            ['vatExemption', 'TaxTotal/TaxSubtotal/TaxCategory/TaxExemptionReason'],
            ['vatExemptionCode', 'TaxTotal/TaxSubtotal/TaxCategory/TaxExemptionReasonCode'],
        ]],
        ['lines', [
            ['lineId', `${line}/ID`],
            ['itemName', `${line}/Item/Name`],
            ['itemDesc', `${line}/Item/Description`],
            ['quantity', `${line}/${qty}`, 'number'],
            ['unit', `${line}/${qty}/@unitCode`],
            ['price', `${line}/Price/PriceAmount`, 'amount'],
            ['baseQuantity', `${line}/Price/BaseQuantity`, 'number'],
            ['priceDiscount', `${line}/Price/AllowanceCharge/Amount`, 'amount'],
            ['lineAllowance', `${line}/AllowanceCharge/Amount`, 'amount'],
            ['lineAllowanceReason', `${line}/AllowanceCharge/AllowanceChargeReason`],
            ['lineNet', `${line}/LineExtensionAmount`, 'amount'],
            ['lineVatCategory', `${line}/Item/ClassifiedTaxCategory/ID`],
            ['lineVatRate', `${line}/Item/ClassifiedTaxCategory/Percent`, 'number'],
            ['sellerItemId', `${line}/Item/SellersItemIdentification/ID`],
            ['buyerItemId', `${line}/Item/BuyersItemIdentification/ID`],
            ['standardItemId', `${line}/Item/StandardItemIdentification/ID`],
            ['classification', `${line}/Item/CommodityClassification/ItemClassificationCode`],
            ['originCountry', `${line}/Item/OriginCountry/IdentificationCode`],
            ['orderLineRef', `${line}/OrderLineReference/LineID`],
            ['lineNote', `${line}/Note`],
            ['linePeriodStart', `${line}/InvoicePeriod/StartDate`, 'date'],
            ['linePeriodEnd', `${line}/InvoicePeriod/EndDate`, 'date'],
        ]],
    ];
}

const DESPATCH_GROUPS: Group[] = [
    ['doc', [
        ['despatchNo', 'ID'],
        ['issueDate', 'IssueDate', 'date'],
        ['issueTime', 'IssueTime'],
        ['note', 'Note'],
        ['orderRef', 'OrderReference/ID'],
        ['customization', 'CustomizationID'],
        ['profile', 'ProfileID'],
    ]],
    ['despatchParty', party('despatch', 'DespatchSupplierParty/Party')],
    ['deliveryParty', party('delivery', 'DeliveryCustomerParty/Party')],
    ['orderParty', party('order', 'BuyerCustomerParty/Party', ['name', 'legalName', 'partyId', 'street', 'city', 'postal', 'country'])],
    ['sellerParty', party('supplier', 'SellerSupplierParty/Party', ['name', 'legalName', 'partyId', 'street', 'city', 'postal', 'country'])],
    ['shipment', [
        ['shipmentId', 'Shipment/ID'],
        ['grossWeight', 'Shipment/GrossWeightMeasure', 'number'],
        ['grossVolume', 'Shipment/GrossVolumeMeasure', 'number'],
        ['trackingId', 'Shipment/Delivery/TrackingID'],
        ['despatchDate', 'Shipment/Delivery/Despatch/ActualDespatchDate', 'date'],
        ['despatchTime', 'Shipment/Delivery/Despatch/ActualDespatchTime'],
        ['estStartDate', 'Shipment/Delivery/EstimatedDeliveryPeriod/StartDate', 'date'],
        ['estStartTime', 'Shipment/Delivery/EstimatedDeliveryPeriod/StartTime'],
        ['estEndDate', 'Shipment/Delivery/EstimatedDeliveryPeriod/EndDate', 'date'],
        ['estEndTime', 'Shipment/Delivery/EstimatedDeliveryPeriod/EndTime'],
        ['carrier', 'Shipment/Delivery/CarrierParty/PartyName/Name'],
        ['deliveryStreet', 'Shipment/Delivery/DeliveryAddress/StreetName'],
        ['deliveryCity', 'Shipment/Delivery/DeliveryAddress/CityName'],
        ['deliveryPostal', 'Shipment/Delivery/DeliveryAddress/PostalZone'],
        ['deliveryCountry', 'Shipment/Delivery/DeliveryAddress/Country/IdentificationCode'],
        ['handlingUnit', 'Shipment/TransportHandlingUnit/ID'],
        ['handlingUnitType', 'Shipment/TransportHandlingUnit/TransportHandlingUnitTypeCode'],
    ]],
    ['lines', [
        ['lineId', 'DespatchLine/ID'],
        ['itemName', 'DespatchLine/Item/Name'],
        ['itemDesc', 'DespatchLine/Item/Description'],
        ['deliveredQty', 'DespatchLine/DeliveredQuantity', 'number'],
        ['unit', 'DespatchLine/DeliveredQuantity/@unitCode'],
        ['outstandingQty', 'DespatchLine/OutstandingQuantity', 'number'],
        ['outstandingReason', 'DespatchLine/OutstandingReason'],
        ['orderLineRef', 'DespatchLine/OrderLineReference/LineID'],
        ['sellerItemId', 'DespatchLine/Item/SellersItemIdentification/ID'],
        ['buyerItemId', 'DespatchLine/Item/BuyersItemIdentification/ID'],
        ['standardItemId', 'DespatchLine/Item/StandardItemIdentification/ID'],
        ['lot', 'DespatchLine/Item/ItemInstance/LotIdentification/LotNumberID'],
        ['expiry', 'DespatchLine/Item/ItemInstance/LotIdentification/ExpiryDate', 'date'],
        ['serial', 'DespatchLine/Item/ItemInstance/SerialID'],
        ['originCountry', 'DespatchLine/Item/OriginCountry/IdentificationCode'],
        ['lineNote', 'DespatchLine/Note'],
    ]],
];

const isPartyRow = (r: Row | PartyRow): r is PartyRow => r.length === 3 && r[0] in en.party && r[1] in en.field;

const GROUPS: Record<IntlRoot, Group[]> = {
    Invoice: billingGroups('Invoice'),
    CreditNote: billingGroups('CreditNote'),
    DespatchAdvice: DESPATCH_GROUPS,
};

const cache = new Map<string, CatalogField[]>();

export function intlCatalog(root: IntlRoot, lang: DocLanguage): CatalogField[] {
    const id = `${root}:${lang}`;
    const hit = cache.get(id);
    if (hit) return hit;
    const L = (LABELS as Partial<Record<DocLanguage, Labels>>)[lang] ?? extraDocTextPack(lang)?.catalog ?? en;
    const fields = GROUPS[root].flatMap(([cat, rows]) => rows.map((r): CatalogField => {
        const [label, path, format] = isPartyRow(r)
            ? [`${L.party[r[0]]} – ${L.field[r[1]]}`, r[2], 'text' as CatalogFormat]
            : [L.field[r[0]], r[1], r[2] ?? 'text'];
        return { key: `${root}/${path}`, label, category: L.cat[cat], path: `${root}/${path}`, format };
    }));
    cache.set(id, fields);
    return fields;
}
