import type { UiLanguage } from './countryProfiles';
import { findCountryRules, type DocumentFamily } from './documentProfiles';

type NoteKey = `${string}.${DocumentFamily}`;

/** `countryDocumentRules` notlarının çevirileri; Türkçe asıl metin kayıtta durur. */
const NOTES: Record<Exclude<UiLanguage, 'tr'>, Record<NoteKey, string>> = {
    en: {
        'DE.invoice': 'Receiving since 2025; issuing from 2027 for large businesses, from 2028 for all.',
        'DE.archive': 'Cash register system (KassenSichV/TSE) applies; not an XML invoice.',
        'AT.archive': 'RKSV cash receipt; individual sales are not transmitted.',
        'CH.invoice': 'swissDIGIN/eCH-0069 field rules; no legally mandated syntax.',
        'FR.invoice': 'From 1.9.2026 all businesses must receive and large/mid-sized ones issue; small businesses from 1.9.2027. Factur-X additionally requires PDF/A-3.',
        'FR.archive': 'B2C e-reporting (Flux 10.3) via an approved platform; schema not added yet.',
        'BE.invoice': 'Domestic B2B since 1.1.2026.',
        'ES.invoice': 'B2B mandate from 2027 onwards.',
        'ES.archive': 'VeriFactu record XML + QR; BOE date 2027.',
        'ES.despatch': 'Digital DeCA mandatory since 5.10.2026, but as PDF+QR, not XML.',
        'PT.archive': 'All invoices are reported to the AT with ATCUD + QR.',
        'PT.despatch': 'Transport documents are reported to the AT before shipping (MovementOfGoods).',
        'IT.invoice': 'SdI also accepts EN 16931 UBL for public-sector (B2G) invoices; B2B/B2C requires FatturaPA.',
        'IT.archive': 'B2C: CodiceDestinatario 0000000, via SdI.',
        'IT.despatch': 'DDT is free-form; Peppol is mandatory in Emilia-Romagna healthcare.',
        'FI.invoice': 'Eligible businesses can request B2B e-invoices.',
        'NO.invoice': 'EHF = Peppol BIS 3; B2B issuing from 1.1.2027.',
        'IS.invoice': 'TS-236 = Peppol BIS 3 Icelandic CIUS.',
        'EE.invoice': 'A registered buyer can request B2B EN 16931 invoices.',
        'LV.invoice': 'B2B from 1.1.2028.',
        'LT.archive': 'i.SAF monthly invoice reporting; schema not added yet.',
        'LT.despatch': 'Domestic road shipments are reported to i.VAZ.',
        'PL.invoice': 'KSeF 2026; smallest businesses from 1.1.2027. Peppol only for the public sector (PEF).',
        'PL.archive': 'Consumer invoices may be sent to KSeF voluntarily.',
        'PL.despatch': 'Sensitive goods only (SENT).',
        'SK.invoice': 'B2B and B2G from 1.1.2027.',
        'HU.archive': 'All invoices (including to private persons) are reported to NAV.',
        'HU.despatch': 'EKAER for risky goods.',
        'RO.archive': 'B2C since 2025; 13 zeros for buyers without an ID.',
        'RO.despatch': 'Risky goods, and international road transport from 2026.',
        'BG.despatch': 'Goods with high fiscal risk (УНП).',
        'GR.invoice': 'myDATA tax e-invoice phased in during 2026; Peppol for the public sector.',
        'GR.archive': 'Retail documents (11.x) are reported to myDATA.',
        'GR.despatch': 'Digital delivery note since 1.12.2025; accompanies the shipment with MARK + QR.',
        'HR.invoice': 'VAT-registered businesses from 1.1.2026.',
        'HR.archive': 'B2C fiskalizacija (JIR) message; schema not added yet.',
        'SI.invoice': 'B2B in 2028.',
        'GB.invoice': 'B2B mandate for VAT invoices in April 2029; Peppol mandatory in the NHS.',
    },
    de: {
        'DE.invoice': 'Empfang seit 2025; Ausstellung ab 2027 für große Unternehmen, ab 2028 für alle.',
        'DE.archive': 'Kassensystem (KassenSichV/TSE); keine XML-Rechnung.',
        'AT.archive': 'RKSV-Kassenbeleg; einzelne Verkäufe werden nicht übermittelt.',
        'CH.invoice': 'Feldregeln nach swissDIGIN/eCH-0069; keine gesetzlich vorgeschriebene Syntax.',
        'FR.invoice': 'Ab 1.9.2026 Empfang für alle, Ausstellung für große/mittlere Unternehmen; kleine ab 1.9.2027. Factur-X erfordert zusätzlich PDF/A-3.',
        'FR.archive': 'B2C-E-Reporting (Flux 10.3) über eine zugelassene Plattform; Schema noch nicht hinzugefügt.',
        'BE.invoice': 'Inländisches B2B seit 1.1.2026.',
        'ES.invoice': 'B2B-Pflicht ab 2027.',
        'ES.archive': 'VeriFactu-Datensatz-XML + QR; BOE-Termin 2027.',
        'ES.despatch': 'Digitales DeCA seit 5.10.2026 Pflicht, jedoch als PDF+QR, nicht XML.',
        'PT.archive': 'Alle Rechnungen werden mit ATCUD + QR an die AT gemeldet.',
        'PT.despatch': 'Transportdokumente werden vor dem Versand an die AT gemeldet (MovementOfGoods).',
        'IT.invoice': 'SdI akzeptiert für öffentliche Auftraggeber (B2G) auch EN 16931 UBL; B2B/B2C erfordert FatturaPA.',
        'IT.archive': 'B2C: CodiceDestinatario 0000000, über SdI.',
        'IT.despatch': 'DDT formfrei; Peppol im Gesundheitswesen der Emilia-Romagna Pflicht.',
        'FI.invoice': 'Berechtigte Unternehmen können B2B-E-Rechnungen verlangen.',
        'NO.invoice': 'EHF = Peppol BIS 3; B2B-Ausstellung ab 1.1.2027.',
        'IS.invoice': 'TS-236 = isländische CIUS von Peppol BIS 3.',
        'EE.invoice': 'Ein registrierter Empfänger kann B2B-Rechnungen nach EN 16931 verlangen.',
        'LV.invoice': 'B2B ab 1.1.2028.',
        'LT.archive': 'Monatliche i.SAF-Rechnungsmeldung; Schema noch nicht hinzugefügt.',
        'LT.despatch': 'Inländische Straßentransporte werden an i.VAZ gemeldet.',
        'PL.invoice': 'KSeF 2026; Kleinstunternehmen ab 1.1.2027. Peppol nur für den öffentlichen Sektor (PEF).',
        'PL.archive': 'Verbraucherrechnungen können freiwillig an KSeF gesendet werden.',
        'PL.despatch': 'Nur sensible Waren (SENT).',
        'SK.invoice': 'B2B und B2G ab 1.1.2027.',
        'HU.archive': 'Alle Rechnungen (auch an Privatpersonen) werden an die NAV gemeldet.',
        'HU.despatch': 'EKAER bei Risikowaren.',
        'RO.archive': 'B2C seit 2025; 13 Nullen bei Käufern ohne Kennung.',
        'RO.despatch': 'Risikowaren sowie ab 2026 internationaler Straßentransport.',
        'BG.despatch': 'Waren mit hohem Steuerrisiko (УНП).',
        'GR.invoice': 'myDATA-Steuer-E-Rechnung 2026 stufenweise; Peppol für den öffentlichen Sektor.',
        'GR.archive': 'Einzelhandelsbelege (11.x) werden an myDATA gemeldet.',
        'GR.despatch': 'Digitaler Lieferschein seit 1.12.2025; begleitet die Sendung mit MARK + QR.',
        'HR.invoice': 'Umsatzsteuerpflichtige ab 1.1.2026.',
        'HR.archive': 'B2C-Fiskalizacija-Nachricht (JIR); Schema noch nicht hinzugefügt.',
        'SI.invoice': 'B2B 2028.',
        'GB.invoice': 'B2B-Pflicht für Umsatzsteuerrechnungen ab April 2029; Peppol im NHS Pflicht.',
    },
    fr: {
        'DE.invoice': 'Réception depuis 2025 ; émission dès 2027 pour les grandes entreprises, dès 2028 pour toutes.',
        'DE.archive': 'Système de caisse (KassenSichV/TSE) ; pas de facture XML.',
        'AT.archive': 'Ticket de caisse RKSV ; les ventes ne sont pas transmises une à une.',
        'CH.invoice': 'Règles de champs swissDIGIN/eCH-0069 ; aucune syntaxe légalement imposée.',
        'FR.invoice': 'Au 1.9.2026, réception pour toutes les entreprises, émission pour les grandes et ETI ; PME au 1.9.2027. Factur-X exige en plus un PDF/A-3.',
        'FR.archive': 'E-reporting B2C (Flux 10.3) via une plateforme agréée ; schéma pas encore ajouté.',
        'BE.invoice': 'B2B national depuis le 1.1.2026.',
        'ES.invoice': 'Obligation B2B à partir de 2027.',
        'ES.archive': 'XML d’enregistrement VeriFactu + QR ; échéance BOE 2027.',
        'ES.despatch': 'DeCA numérique obligatoire depuis le 5.10.2026, mais en PDF+QR, pas en XML.',
        'PT.archive': 'Toutes les factures sont déclarées à l’AT avec ATCUD + QR.',
        'PT.despatch': 'Les documents de transport sont déclarés à l’AT avant l’expédition (MovementOfGoods).',
        'IT.invoice': 'Le SdI accepte aussi l’EN 16931 UBL pour le secteur public (B2G) ; le B2B/B2C exige FatturaPA.',
        'IT.archive': 'B2C : CodiceDestinatario 0000000, via le SdI.',
        'IT.despatch': 'DDT en format libre ; Peppol obligatoire dans la santé en Émilie-Romagne.',
        'FI.invoice': 'Les entreprises éligibles peuvent exiger des factures électroniques B2B.',
        'NO.invoice': 'EHF = Peppol BIS 3 ; émission B2B au 1.1.2027.',
        'IS.invoice': 'TS-236 = CIUS islandaise de Peppol BIS 3.',
        'EE.invoice': 'Un acheteur enregistré peut exiger des factures B2B EN 16931.',
        'LV.invoice': 'B2B au 1.1.2028.',
        'LT.archive': 'Déclaration mensuelle des factures i.SAF ; schéma pas encore ajouté.',
        'LT.despatch': 'Les transports routiers nationaux sont déclarés à i.VAZ.',
        'PL.invoice': 'KSeF 2026 ; micro-entreprises au 1.1.2027. Peppol uniquement pour le secteur public (PEF).',
        'PL.archive': 'Les factures aux consommateurs peuvent être envoyées à KSeF volontairement.',
        'PL.despatch': 'Marchandises sensibles uniquement (SENT).',
        'SK.invoice': 'B2B et B2G au 1.1.2027.',
        'HU.archive': 'Toutes les factures (y compris aux particuliers) sont déclarées à la NAV.',
        'HU.despatch': 'EKAER pour les marchandises à risque.',
        'RO.archive': 'B2C depuis 2025 ; 13 zéros pour un acheteur sans identifiant.',
        'RO.despatch': 'Marchandises à risque et, dès 2026, transport routier international.',
        'BG.despatch': 'Marchandises à haut risque fiscal (УНП).',
        'GR.invoice': 'E-facture fiscale myDATA progressive en 2026 ; Peppol pour le secteur public.',
        'GR.archive': 'Les documents de vente au détail (11.x) sont déclarés à myDATA.',
        'GR.despatch': 'Bon de livraison numérique depuis le 1.12.2025 ; accompagne l’envoi avec MARK + QR.',
        'HR.invoice': 'Assujettis à la TVA au 1.1.2026.',
        'HR.archive': 'Message fiskalizacija B2C (JIR) ; schéma pas encore ajouté.',
        'SI.invoice': 'B2B en 2028.',
        'GB.invoice': 'Obligation B2B pour les factures avec TVA en avril 2029 ; Peppol obligatoire au NHS.',
    },
    es: {
        'DE.invoice': 'Recepción desde 2025; emisión desde 2027 para grandes empresas y desde 2028 para todas.',
        'DE.archive': 'Sistema de caja (KassenSichV/TSE); no es una factura XML.',
        'AT.archive': 'Recibo de caja RKSV; las ventas no se transmiten una a una.',
        'CH.invoice': 'Reglas de campos swissDIGIN/eCH-0069; sin sintaxis legalmente obligatoria.',
        'FR.invoice': 'Desde el 1.9.2026 todas las empresas reciben y las grandes/medianas emiten; las pequeñas desde el 1.9.2027. Factur-X requiere además PDF/A-3.',
        'FR.archive': 'E-reporting B2C (Flux 10.3) mediante plataforma autorizada; esquema aún no añadido.',
        'BE.invoice': 'B2B nacional desde el 1.1.2026.',
        'ES.invoice': 'Obligación B2B a partir de 2027.',
        'ES.archive': 'XML de registro VeriFactu + QR; fecha BOE 2027.',
        'ES.despatch': 'DeCA digital obligatorio desde el 5.10.2026, pero en PDF+QR, no XML.',
        'PT.archive': 'Todas las facturas se comunican a la AT con ATCUD + QR.',
        'PT.despatch': 'Los documentos de transporte se comunican a la AT antes del envío (MovementOfGoods).',
        'IT.invoice': 'El SdI también acepta EN 16931 UBL para el sector público (B2G); B2B/B2C exige FatturaPA.',
        'IT.archive': 'B2C: CodiceDestinatario 0000000, a través del SdI.',
        'IT.despatch': 'DDT de formato libre; Peppol obligatorio en la sanidad de Emilia-Romaña.',
        'FI.invoice': 'Las empresas elegibles pueden exigir facturas electrónicas B2B.',
        'NO.invoice': 'EHF = Peppol BIS 3; emisión B2B desde el 1.1.2027.',
        'IS.invoice': 'TS-236 = CIUS islandés de Peppol BIS 3.',
        'EE.invoice': 'Un comprador registrado puede exigir facturas B2B EN 16931.',
        'LV.invoice': 'B2B desde el 1.1.2028.',
        'LT.archive': 'Declaración mensual de facturas i.SAF; esquema aún no añadido.',
        'LT.despatch': 'Los transportes nacionales por carretera se comunican a i.VAZ.',
        'PL.invoice': 'KSeF 2026; microempresas desde el 1.1.2027. Peppol solo para el sector público (PEF).',
        'PL.archive': 'Las facturas a consumidores pueden enviarse a KSeF de forma voluntaria.',
        'PL.despatch': 'Solo mercancías sensibles (SENT).',
        'SK.invoice': 'B2B y B2G desde el 1.1.2027.',
        'HU.archive': 'Todas las facturas (incluidas las de particulares) se comunican a la NAV.',
        'HU.despatch': 'EKAER para mercancías de riesgo.',
        'RO.archive': 'B2C desde 2025; 13 ceros si el comprador no tiene identificación.',
        'RO.despatch': 'Mercancías de riesgo y, desde 2026, transporte internacional por carretera.',
        'BG.despatch': 'Mercancías de alto riesgo fiscal (УНП).',
        'GR.invoice': 'E-factura fiscal myDATA escalonada en 2026; Peppol para el sector público.',
        'GR.archive': 'Los documentos de venta minorista (11.x) se comunican a myDATA.',
        'GR.despatch': 'Albarán digital desde el 1.12.2025; acompaña al envío con MARK + QR.',
        'HR.invoice': 'Sujetos pasivos de IVA desde el 1.1.2026.',
        'HR.archive': 'Mensaje de fiskalizacija B2C (JIR); esquema aún no añadido.',
        'SI.invoice': 'B2B en 2028.',
        'GB.invoice': 'Obligación B2B para facturas con IVA en abril de 2029; Peppol obligatorio en el NHS.',
    },
};

/** Ülke + belge ailesi notu arayüz dilinde; çeviri yoksa Türkçe kayıt notu. */
export const countryNote = (country: string, family: DocumentFamily, lang: UiLanguage): string | undefined => {
    const note = findCountryRules(country)?.[family].note;
    if (!note || lang === 'tr') return note;
    return NOTES[lang][`${country}.${family}`] ?? note;
};
