import type { GibDict } from './types';

const de: GibDict = {
    tpl: {
        party: '{{party}}: {{field}}',
        line: 'Position: {{label}}',
        amount: '{{name}} – Betrag',
        base: '{{name}} – Bemessungsgrundlage',
        rate: '{{name}} – Satz (%)',
    },
    parties: {
        'Sipariş Veren': 'Besteller',
        'Asıl Alıcı': 'Tatsächlicher Käufer',
        'Teslim Alan': 'Empfänger',
        'Düzenleyen': 'Aussteller',
        'Gönderen': 'Absender',
        'Satıcı': 'Verkäufer',
        'Alıcı': 'Käufer',
        'Çiftçi': 'Landwirt',
    },
    partyFields: {
        'Unvanı': 'Name',
        'Resmi Unvanı': 'Firmenname (amtlich)',
        'Adı (şahıs)': 'Vorname (Person)',
        'Soyadı (şahıs)': 'Nachname (Person)',
        'Kimlik No (VKN/TCKN vb.)': 'Identifikationsnummer (VKN/TCKN usw.)',
        'Kimlik Türü': 'Identifikationsart',
        'VKN': 'Steuernummer (VKN)',
        'TCKN': 'Personalausweisnummer (TCKN)',
        'MERSİS No': 'MERSİS-Nr.',
        'Ticaret Sicil No': 'Handelsregisternummer',
        'Vergi Dairesi': 'Finanzamt',
        'Cadde/Sokak': 'Straße',
        'Bina Adı': 'Gebäudename',
        'Kapı No': 'Hausnummer',
        'İlçe': 'Bezirk',
        'İl': 'Provinz',
        'İli': 'Provinz',
        'Bölge / Semt': 'Region / Stadtteil',
        'Posta Kodu': 'Postleitzahl',
        'Ülke': 'Land',
        'Ülkesi': 'Land',
        'Telefon': 'Telefon',
        'Faks': 'Fax',
        'E-posta': 'E-Mail',
        'Web Sitesi': 'Website',
        'İlgili Kişi': 'Ansprechpartner',
        'Mahalle': 'Stadtviertel',
        'Daire / Oda No': 'Wohnungs- / Zimmernummer',
        'Şube No': 'Filialnummer',
        'EPDK No': 'EPDK-Lizenznummer',
        'Sevkiyat No (IDIS)': 'Sendungsnummer (IDIS)',
        'Müşteri No': 'Kundennummer',
        'Abone No': 'Teilnehmernummer',
        'Tesisat No': 'Anlagennummer',
        'Sayaç No': 'Zählernummer',
        'Hasta No': 'Patientennummer',
        'Dosya No': 'Aktenzeichen',
        'Araç Plakası (şarj)': 'Kfz-Kennzeichen (Ladevorgang)',
        'Araç Kimlik No (şarj)': 'Fahrzeug-ID (Ladevorgang)',
        'SMS Kodu': 'SMS-Code',
        'SMS Telefonu': 'SMS-Telefonnummer',
        'TCKN / YKN': 'Ausweisnummer (TCKN / YKN)',
    },
    taxes: {
        'KDV': 'USt.',
        'Konaklama Vergisi': 'Beherbergungssteuer',
        'ÖTV 1. Liste (petrol/doğalgaz)': 'Sonderverbrauchsteuer (ÖTV) Liste I (Mineralöl/Erdgas)',
        'ÖTV 2. Liste (motorlu taşıt)': 'Sonderverbrauchsteuer (ÖTV) Liste II (Kraftfahrzeuge)',
        'ÖTV 3. Liste': 'Sonderverbrauchsteuer (ÖTV) Liste III',
        'ÖTV 3A (alkollü içecek)': 'Sonderverbrauchsteuer (ÖTV) III-A (alkoholische Getränke)',
        'ÖTV 3B (tütün)': 'Sonderverbrauchsteuer (ÖTV) III-B (Tabak)',
        'ÖTV 3C (kolalı gazoz)': 'Sonderverbrauchsteuer (ÖTV) III-C (Colagetränke)',
        'ÖTV 4. Liste (dayanıklı tüketim)': 'Sonderverbrauchsteuer (ÖTV) Liste IV (langlebige Gebrauchsgüter)',
        'Petrol-Doğalgaz ÖTV Tevkifatı': 'ÖTV-Einbehalt Mineralöl/Erdgas',
        'Damga Vergisi': 'Stempelsteuer',
        '5035 SK Damga Vergisi': 'Stempelsteuer (Gesetz 5035)',
        'Özel İletişim Vergisi': 'Sonderkommunikationssteuer',
        '5035 SK Özel İletişim Vergisi': 'Sonderkommunikationssteuer (Gesetz 5035)',
        'Elektrik ve Havagazı Tüketim Vergisi': 'Strom- und Gasverbrauchsteuer',
        'Elektrik Tüketim Vergisi': 'Stromverbrauchsteuer',
        'TRT Payı': 'TRT-Abgabe',
        'Enerji Fonu': 'Energiefonds',
        'Borsa Tescil Ücreti': 'Börsenregistrierungsgebühr',
        'Telsiz Kullanım Ücreti': 'Funknutzungsgebühr',
        'Telsiz Ruhsat Ücreti': 'Funklizenzgebühr',
        'Çevre Temizlik Vergisi': 'Umweltreinigungssteuer',
        'Belediye Hal Rüsumu': 'Städtische Markthallengebühr',
        'Mera Fonu': 'Weidefonds',
        'Gelir Vergisi Stopajı': 'Einkommensteuer-Quellenabzug',
        'Kurumlar Vergisi Stopajı': 'Körperschaftsteuer-Quellenabzug',
        'Banka Muameleleri Vergisi': 'Bankgeschäftssteuer',
        'Sigorta Muameleleri Vergisi': 'Versicherungsgeschäftssteuer',
        '4961 Banka Sigorta Muameleleri Vergisi': 'Bank- und Versicherungsgeschäftssteuer (Gesetz 4961)',
        'KKDF Kesintisi': 'KKDF-Abzug',
        'GV Stopajı': 'Einkommensteuer-Quellenabzug',
        'SGK Prim Kesintisi': 'Sozialversicherungsbeitragsabzug (SGK)',
        'BSMV': 'Bank- und Versicherungssteuer (BSMV)',
    },
    labels: {
        // Kategoriler
        'Belge Bilgileri': 'Belegangaben',
        'Satıcı': 'Verkäufer',
        'Alıcı': 'Käufer',
        'Asıl Alıcı (İhracat / Yolcu Beraber)': 'Tatsächlicher Käufer (Ausfuhr / Tax-free)',
        'Tutarlar': 'Beträge',
        'Vergiler': 'Steuern',
        'Vergi Türleri': 'Steuerarten',
        'Serbest Meslek Makbuzu (e-SMM)': 'Honorarquittung für Freiberufler (e-SMM)',
        'Döviz / Kur': 'Währung / Wechselkurs',
        'Ödeme': 'Zahlung',
        'Referanslar': 'Referenzen',
        'Teslimat / İhracat': 'Lieferung / Ausfuhr',
        'İnternet Satışı (e-Arşiv)': 'Online-Verkauf (e-Archiv)',
        'Satır (Kalem)': 'Positionen',
        'Satır · Özel Senaryolar': 'Position · Sonderszenarien',
        'Ek Belge / Matbu İrsaliye': 'Zusatzdokument / gedruckter Lieferschein',
        'Gönderen': 'Absender',
        'Satıcı (Zincir Teslim)': 'Verkäufer (Reihengeschäft)',
        'Alıcı / Sipariş Veren (Zincir Teslim)': 'Käufer / Besteller (Reihengeschäft)',
        'Asıl Alıcı (Zincir Teslim)': 'Tatsächlicher Käufer (Reihengeschäft)',
        'Sevkiyat': 'Versand',
        'Yanıtlanan İrsaliye': 'Beantworteter Lieferschein',
        'Teslim Alan (Yanıtlayan)': 'Empfänger (Antwortender)',
        'Teslimat': 'Lieferung',
        'Makbuzu Düzenleyen (Malı Satın Alan)': 'Quittungsaussteller (Käufer der Ware)',
        'Üretici / Çiftçi (Malı Satan)': 'Erzeuger / Landwirt (Verkäufer der Ware)',
        'Kesintiler (Vergi ve Fonlar)': 'Abzüge (Steuern und Fonds)',
        'Satır (Mal Bilgileri)': 'Positionen (Warenangaben)',
        'Vergiler (KDV / BSMV)': 'Steuern (USt. / BSMV)',
        'Gider Pusulası': 'Ausgabenbeleg',
        'Döviz / Kıymetli Maden': 'Devisen / Edelmetalle',
        'Döviz Kuru (USD / TL Karşılığı)': 'Wechselkurs (USD / TRY-Gegenwert)',
        'Dekont': 'Bankbeleg',
        'Sigorta Komisyon': 'Versicherungsprovision',
        'Rapor Bilgileri': 'Berichtsangaben',
        'Bilet': 'Ticket',
        'Etkinlik Yeri / Organizatör': 'Veranstaltungsort / Veranstalter',
        'Hizmet / Gider Gösteren': 'Leistung / Aufwandsträger',
        'Diğer Vergiler': 'Sonstige Steuern',
        'İptal Edilen Bilet': 'Storniertes Ticket',
        'Sefer': 'Fahrt',
        'Taşıtı İşleten': 'Fahrzeughalter',
        'Koltuk / Yolcu': 'Sitzplatz / Fahrgast',

        // Fatura — belge
        'Fatura No': 'Rechnungsnummer',
        'Fatura Tarihi': 'Rechnungsdatum',
        'Fatura Saati': 'Rechnungsuhrzeit',
        'Fatura Tipi': 'Rechnungsart',
        'Senaryo (Profil)': 'Szenario (Profil)',
        'ETTN (UUID)': 'ETTN (UUID)',
        'Para Birimi': 'Währung',
        'Fatura Notu': 'Rechnungsvermerk',
        'Satır Sayısı': 'Anzahl der Positionen',
        'Fatura Dönemi Başlangıcı': 'Beginn des Abrechnungszeitraums',
        'Fatura Dönemi Başlangıç Saati': 'Beginn des Abrechnungszeitraums (Uhrzeit)',
        'Fatura Dönemi Bitişi': 'Ende des Abrechnungszeitraums',
        'Fatura Dönemi Bitiş Saati': 'Ende des Abrechnungszeitraums (Uhrzeit)',
        'Fatura Dönemi Açıklaması': 'Beschreibung des Abrechnungszeitraums',
        'Muhasebe Maliyet Kodu (SGK)': 'Kostenstellencode (SGK)',
        // Asıl alıcı / turist
        'Alıcı Tipi (EXPORT / TAXFREE)': 'Käuferart (EXPORT / TAXFREE)',
        'Asıl Alıcı TCKN': 'Tatsächlicher Käufer – Ausweisnummer (TCKN)',
        'Hastane Protokol No': 'Krankenhaus-Protokollnummer',
        'Turist Adı': 'Vorname des Touristen',
        'Turist Soyadı': 'Nachname des Touristen',
        'Turist Uyruğu': 'Staatsangehörigkeit des Touristen',
        'Pasaport No': 'Reisepassnummer',
        'Pasaport Tarihi': 'Ausstellungsdatum des Reisepasses',
        'Turist Banka Hesap No': 'Bankkontonummer des Touristen',
        'Turist Bankası': 'Bank des Touristen',
        'Asıl Alıcı İli': 'Tatsächlicher Käufer – Provinz',
        'Asıl Alıcı Ülkesi': 'Tatsächlicher Käufer – Land',
        'Aracı Kurum VKN': 'Vermittler – Steuernummer (VKN)',
        'Aracı Kurum Etiketi': 'Vermittler – Kennung',
        'Aracı Kurum Unvanı': 'Vermittler – Name',
        'Aracı Kurum İli': 'Vermittler – Provinz',
        // Tutarlar
        'Mal Hizmet Toplam Tutarı': 'Gesamtbetrag Waren/Leistungen',
        'Vergiler Hariç Toplam': 'Gesamtbetrag ohne Steuern',
        'Vergiler Dahil Toplam': 'Gesamtbetrag inkl. Steuern',
        'Toplam İskonto': 'Rabatt gesamt',
        'Toplam Masraf': 'Zuschläge gesamt',
        'Yuvarlama Tutarı': 'Rundungsbetrag',
        'Ödenecek Tutar': 'Zahlbetrag',
        'Fatura İskonto Oranı': 'Rechnungsrabatt (%)',
        'Fatura İskonto Tutarı': 'Rechnungsrabatt (Betrag)',
        'İskonto Açıklaması': 'Rabattbeschreibung',
        // Vergiler
        'Hesaplanan Vergiler (toplam)': 'Berechnete Steuern (gesamt)',
        'Vergi Matrahı': 'Steuerbemessungsgrundlage',
        'Vergi Tutarı': 'Steuerbetrag',
        'Vergi Oranı (%)': 'Steuersatz (%)',
        'Vergi Adı': 'Steuerbezeichnung',
        'Vergi Kodu': 'Steuercode',
        'Muafiyet Sebebi': 'Befreiungsgrund',
        'Muafiyet Kodu': 'Befreiungscode',
        'Tevkifat Tutarı': 'Einbehaltungsbetrag',
        'Tevkifat Oranı (%)': 'Einbehaltungssatz (%)',
        'Tevkifat Kodu': 'Einbehaltungscode',
        'Tevkifat Adı': 'Einbehaltungsbezeichnung',
        'Tevkifat Matrahı': 'Bemessungsgrundlage des Einbehalts',
        // e-SMM
        'Serbest Meslek Erbabı Mesleği / Unvanı': 'Beruf / Titel des Freiberuflers',
        'GV Stopajı Matrahı': 'Einkommensteuer-Quellenabzug – Bemessungsgrundlage',
        'GV Stopajı Oranı (%)': 'Einkommensteuer-Quellenabzug – Satz (%)',
        'KV Stopajı Oranı (%)': 'Körperschaftsteuer-Quellenabzug – Satz (%)',
        'GV Stopajı Tutarı (tevkifat bölümünde)': 'Einkommensteuer-Quellenabzug – Betrag (Einbehaltsbereich)',
        'GV Stopajı Oranı (tevkifat bölümünde, %)': 'Einkommensteuer-Quellenabzug – Satz (Einbehaltsbereich, %)',
        'KDV Tevkifatı Tutarı (9015, eski kullanım)': 'USt.-Einbehalt – Betrag (9015, veraltet)',
        // Döviz
        'Döviz Kuru': 'Wechselkurs',
        'Kaynak Para Birimi': 'Ausgangswährung',
        'Hedef Para Birimi': 'Zielwährung',
        'Kur Tarihi': 'Kursdatum',
        'Fiyatlandırma Para Birimi': 'Preiswährung',
        'Vergi Para Birimi': 'Steuerwährung',
        // Ödeme
        'Ödeme Şekli Kodu': 'Code der Zahlungsart',
        'Son Ödeme Tarihi': 'Zahlungsfrist',
        'Ödeme Kanalı': 'Zahlungskanal',
        'IBAN': 'IBAN',
        'Hesap Para Birimi': 'Kontowährung',
        'Banka / Şube': 'Bank / Filiale',
        'Ödeme Notu': 'Zahlungsvermerk',
        'Hesap Açıklaması': 'Kontovermerk',
        'Ödeme Koşulu': 'Zahlungsbedingungen',
        'Gecikme Faizi (%)': 'Verzugszinsen (%)',
        'Vade Tarihi': 'Fälligkeitsdatum',
        // Referanslar
        'İrsaliye No': 'Lieferscheinnummer',
        'İrsaliye Tarihi': 'Lieferscheindatum',
        'Sipariş No': 'Bestellnummer',
        'Sipariş Tarihi': 'Bestelldatum',
        'İade Edilen Fatura No': 'Nummer der zurückgegebenen Rechnung',
        'İade Edilen Fatura Tarihi': 'Datum der zurückgegebenen Rechnung',
        'Ek Belge No': 'Zusatzdokument-Nr.',
        'Ek Belge Tarihi': 'Zusatzdokument-Datum',
        'Ek Belge Türü': 'Zusatzdokument-Art',
        'İade Edilen Belge Tipi': 'Art des zurückgegebenen Belegs',
        'ESÜ Rapor ID (şarj)': 'Ladestations-Berichts-ID (ESÜ)',
        'Yatırım Teşvik Belge No': 'Investitionsförderbescheinigung – Nr.',
        'Yatırım Teşvik Belge Tarihi': 'Investitionsförderbescheinigung – Datum',
        'Sözleşme No': 'Vertragsnummer',
        // Teslimat
        'Teslim Şartı (Incoterms)': 'Lieferbedingungen (Incoterms)',
        'Gönderim Şekli': 'Versandart',
        'Teslim Tarihi': 'Lieferdatum',
        'Teslimat Adresi': 'Lieferadresse',
        'Teslimat İli': 'Lieferprovinz',
        'Teslimat Ülkesi': 'Lieferland',
        'Gönderiyi Taşıyan Unvanı': 'Frachtführer – Name',
        'Gönderiyi Taşıyan Adı': 'Frachtführer – Vorname',
        'Gönderiyi Taşıyan Soyadı': 'Frachtführer – Nachname',
        'Gönderiyi Taşıyan VKN/TCKN': 'Frachtführer – Steuer-ID (VKN/TCKN)',
        'Gönderim Tarihi': 'Versanddatum',
        'Gönderim Saati': 'Versanduhrzeit',
        // Satır
        'Ürün / Hizmet Adı': 'Artikel- / Leistungsbezeichnung',
        'Ürün Açıklaması': 'Artikelbeschreibung',
        'Satıcı Ürün Kodu': 'Artikelnummer des Verkäufers',
        'Alıcı Ürün Kodu': 'Artikelnummer des Käufers',
        'Marka': 'Marke',
        'Model': 'Modell',
        'Miktar': 'Menge',
        'Birim': 'Einheit',
        'Birim Fiyat': 'Einzelpreis',
        'Satır İskonto Oranı': 'Positionsrabatt (%)',
        'Satır İskonto Tutarı': 'Positionsrabatt (Betrag)',
        'Satır Tutarı': 'Positionsbetrag',
        'Satır Vergi Oranı (%)': 'Positions-Steuersatz (%)',
        'Satır Vergi Tutarı': 'Positions-Steuerbetrag',
        'GTİP No': 'Zolltarifnummer (GTİP)',
        'Satır Notu': 'Positionsvermerk',
        'Satır Muafiyet Kodu': 'Positions-Befreiungscode',
        'Satır Muafiyet Sebebi': 'Positions-Befreiungsgrund',
        'Satır Tevkifat Tutarı': 'Positions-Einbehaltungsbetrag',
        'Satır Tevkifat Oranı (%)': 'Positions-Einbehaltungssatz (%)',
        'Satır Tevkifat Kodu': 'Positions-Einbehaltungscode',
        'Künye No (HKS)': 'Herkunftskennzeichen-Nr. (HKS)',
        'Etiket No (IDIS)': 'Etikettennummer (IDIS)',
        'İlaç Seri No': 'Arzneimittel-Seriennummer',
        'Tıbbi Cihaz Seri No': 'Medizinprodukt-Seriennummer',
        'Diğer Ürün (İlaç/Tıbbi Cihaz)': 'Sonstiges Produkt (Arzneimittel/Medizinprodukt)',
        'Telefon IMEI (Teknoloji Destek)': 'Telefon-IMEI (Technologieförderung)',
        'Tablet PC (Teknoloji Destek)': 'Tablet-PC (Technologieförderung)',
        'Harcama Tipi (Yatırım Teşvik)': 'Ausgabenart (Investitionsförderung)',
        'Makine Teçhizat Sıra No (YTB)': 'Maschinen-/Anlagen-Positionsnr. (YTB)',
        'Seri No / Makine ID': 'Seriennummer / Maschinen-ID',
        'Satır Teslim Şartı': 'Positions-Lieferbedingungen',
        'Satır Gönderim Şekli': 'Positions-Versandart',
        'Kap Cinsi': 'Packstückart',
        'Kap No': 'Packstücknummer',
        'Kap Adedi': 'Anzahl der Packstücke',
        'Satıcı DİİB Satır Kodu (İhraç Kayıtlı)': 'DİİB-Positionscode des Verkäufers (Ausfuhrvermerk, aktive Veredelung)',
        'Alıcı DİİB Satır Kodu (İhraç Kayıtlı)': 'DİİB-Positionscode des Käufers (Ausfuhrvermerk, aktive Veredelung)',
        'Satır Teslim Adresi': 'Positions-Lieferadresse',
        'Satır Teslim İli': 'Positions-Lieferprovinz',
        // İrsaliye
        'İrsaliye Saati': 'Lieferscheinuhrzeit',
        'İrsaliye Tipi': 'Lieferscheinart',
        'İrsaliye Notu': 'Lieferscheinvermerk',
        'Ek Belge No (matbu irsaliye / fatura)': 'Zusatzdokument-Nr. (gedruckter Lieferschein / Rechnung)',
        'Ek Belge Tür Kodu': 'Zusatzdokument-Artcode',
        'Ek Belge Açıklaması': 'Zusatzdokument-Beschreibung',
        'Malın Çıktığı Yer Kodu': 'Versandort – Code',
        'Malın Çıktığı Yer Adresi': 'Versandort – Adresse',
        'Malın Çıktığı Yer İlçe': 'Versandort – Bezirk',
        'Malın Çıktığı Yer İl': 'Versandort – Provinz',
        'Kargo / Sevkiyat No': 'Fracht- / Sendungsnummer',
        'Toplam Mal Değeri': 'Gesamtwarenwert',
        'Fiili Sevk Tarihi': 'Tatsächliches Versanddatum',
        'Fiili Sevk Saati': 'Tatsächliche Versanduhrzeit',
        'Araç Plakası': 'Kfz-Kennzeichen',
        'Araç Plaka Türü (PLAKA/YABANCIPLAKA)': 'Kennzeichenart (PLAKA/YABANCIPLAKA)',
        'Dorse Plakası': 'Anhängerkennzeichen',
        'Dorse Türü (DORSE/DORSEPLAKA/YABANCI...)': 'Anhängerart (DORSE/DORSEPLAKA/YABANCI...)',
        'Sürücü Adı': 'Vorname des Fahrers',
        'Sürücü Soyadı': 'Nachname des Fahrers',
        'Sürücü TCKN': 'Ausweisnummer des Fahrers (TCKN)',
        'Sürücü Unvanı / Görevi': 'Titel / Funktion des Fahrers',
        'Taşıyıcı Unvanı': 'Frachtführer – Name',
        'Taşıyıcı VKN': 'Frachtführer – Steuernummer (VKN)',
        'Taşıyıcı İlçe': 'Frachtführer – Bezirk',
        'Taşıyıcı İl': 'Frachtführer – Provinz',
        'Teslimat Kapı No': 'Lieferadresse – Hausnummer',
        'Teslimat İlçesi': 'Lieferadresse – Bezirk',
        'Teslimat Posta Kodu': 'Lieferadresse – Postleitzahl',
        'Satır No': 'Positionsnummer',
        'Gönderilen Miktar': 'Gelieferte Menge',
        'Eksik Miktar': 'Fehlmenge',
        'Eksik Miktar Nedeni': 'Grund der Fehlmenge',
        'Sipariş Satır No': 'Bestellpositionsnummer',
        // İrsaliye yanıtı
        'Yanıt No': 'Antwortnummer',
        'Yanıt Tarihi': 'Antwortdatum',
        'Yanıt Saati': 'Antwortuhrzeit',
        'Yanıt Tipi': 'Antwortart',
        'Yanıt Notu': 'Antwortvermerk',
        'Fiili Teslim Tarihi': 'Tatsächliches Lieferdatum',
        'Fiili Teslim Saati': 'Tatsächliche Lieferuhrzeit',
        'Ürün Adı': 'Artikelbezeichnung',
        'Teslim Alınan Miktar': 'Empfangene Menge',
        'Reddedilen Miktar': 'Abgelehnte Menge',
        'Red Nedeni': 'Ablehnungsgrund',
        'Fazla Miktar': 'Mehrmenge',
        'Zamanlama Şikayeti (geç teslim)': 'Terminreklamation (verspätete Lieferung)',
        'İrsaliye Satır No': 'Lieferscheinpositionsnummer',
        // Müstahsil / CreditNote
        'Makbuz No': 'Quittungsnummer',
        'Düzenleme Tarihi': 'Ausstellungsdatum',
        'Düzenleme Zamanı': 'Ausstellungszeit',
        'Belge Tipi (CreditNoteTypeCode)': 'Belegart (CreditNoteTypeCode)',
        'Özelleştirme No': 'Anpassungskennung (CustomizationID)',
        'Asıl / Suret (CopyIndicator)': 'Original / Kopie (CopyIndicator)',
        'Makbuz Notu': 'Quittungsvermerk',
        'SMS Operatörü (uygulama adı)': 'SMS-Betreiber (Anwendungsname)',
        'SMS Operatörü VKN': 'SMS-Betreiber – Steuernummer (VKN)',
        'Mal Hizmet Toplam Tutarı (brüt)': 'Gesamtbetrag Waren/Leistungen (brutto)',
        'Ödenecek Tutar (net)': 'Zahlbetrag (netto)',
        'Toplam Kesinti': 'Abzüge gesamt',
        'Kesinti Adı': 'Abzugsbezeichnung',
        'Kesinti Kodu': 'Abzugscode',
        'Kesinti Tutarı': 'Abzugsbetrag',
        'Kesinti Oranı (%)': 'Abzugssatz (%)',
        'Malın Cinsi': 'Warenart',
        'Mal Açıklaması': 'Warenbeschreibung',
        'Tutar (Bedel)': 'Betrag (Entgelt)',
        'Satır Kesinti Toplamı': 'Positionsabzüge gesamt',
        // Gider pusulası
        'İade Edilen Belge No': 'Nummer des zurückgegebenen Belegs',
        'İade Edilen Belge Türü (EARSIV_FATURA / SATIS_FISI / BELGESIZ)': 'Art des zurückgegebenen Belegs (EARSIV_FATURA / SATIS_FISI / BELGESIZ)',
        'İade Edilen Belge Tarihi': 'Datum des zurückgegebenen Belegs',
        'Kod Türü (SMS / IADEKODU)': 'Codeart (SMS / IADEKODU)',
        'SMS / İade Kodu': 'SMS- / Rückgabecode',
        'Kodun Gönderildiği Telefon': 'Telefonnummer, an die der Code gesendet wurde',
        'İade Kodu Uygulaması': 'Rückgabecode-Anwendung',
        'İade Kodu Uygulaması VKN': 'Rückgabecode-Anwendung – Steuernummer (VKN)',
        'Adına İade Yapılan Adı': 'Erstattungsempfänger – Vorname',
        'Adına İade Yapılan Soyadı': 'Erstattungsempfänger – Nachname',
        'Adına İade Yapılan Unvanı': 'Erstattungsempfänger – Name',
        'Adına İade Yapılan TCKN': 'Erstattungsempfänger – Ausweisnummer (TCKN)',
        'Adına İade Yapılan SMS / İade Kodu': 'Erstattungsempfänger – SMS- / Rückgabecode',
        'Adına İade Yapılan Telefon': 'Erstattungsempfänger – Telefon',
        'Kargo Firması Unvanı': 'Kurierdienst – Name',
        'Kargo Firması VKN': 'Kurierdienst – Steuernummer (VKN)',
        'Kargo Yetki Belgesi No': 'Kurierdienst – Lizenznummer',
        'Kargo Firması İl': 'Kurierdienst – Provinz',
        // Döviz / kıymetli maden
        'Yetkili Müessese Şube No (SUBENO)': 'Filialnummer des zugelassenen Instituts (SUBENO)',
        'Müşteri Türü (MUSTERITURU)': 'Kundenart (MUSTERITURU)',
        'Müşteri Pasaport No': 'Reisepassnummer des Kunden',
        'Müşteri Uyruğu': 'Staatsangehörigkeit des Kunden',
        'Döviz / Maden Kodu (kaynak)': 'Währungs- / Metallcode (Ausgang)',
        'Karşılık Para Birimi (hedef)': 'Gegenwährung (Ziel)',
        'Uygulanan Kur / Birim Fiyat': 'Angewandter Kurs / Einzelpreis',
        'Ödeme Şekli Kodu (10 / 55 / 46 / 68)': 'Code der Zahlungsart (10 / 55 / 46 / 68)',
        'Müşteri Hesap No': 'Kontonummer des Kunden',
        'Müessese Hesap No (IBAN)': 'Kontonummer des Instituts (IBAN)',
        'İstatistik No': 'Statistiknummer',
        'Dövizin Geldiği Ülke': 'Herkunftsland der Devisen',
        'Dövizin Geliş Nedeni': 'Grund des Devisenzuflusses',
        'Gümrük Beyanname No': 'Zollanmeldungsnummer',
        'Gümrük Beyanname Tarihi': 'Datum der Zollanmeldung',
        'Döviz Beyan Tutanağı Sayısı': 'Nummer des Devisenerklärungsprotokolls',
        'Gümrük Teyit Yazısı Sayısı': 'Nummer der Zollbestätigung',
        'İlgili Fatura No': 'Zugehörige Rechnungsnummer',
        'Kur: Kaynak Para Birimi': 'Kurs: Ausgangswährung',
        'Kur: Hedef Para Birimi': 'Kurs: Zielwährung',
        'Kur Oranı': 'Wechselkurs',
        // Dekont
        'Şube Kodu': 'Filialcode',
        'Şube Adı': 'Filialname',
        'İşlemi Yapan Personel Adı': 'Sachbearbeiter – Vorname',
        'İşlemi Yapan Personel Soyadı': 'Sachbearbeiter – Nachname',
        'İşlemi Yapan Personel Sicil No': 'Sachbearbeiter – Personalnummer',
        'Müşteri No': 'Kundennummer',
        'Müşteri IBAN': 'IBAN des Kunden',
        'Abone No': 'Teilnehmernummer',
        'İşlemi Yapan (Gönderen) Unvanı': 'Auftraggeber (Absender) – Name',
        'İşlemi Yapan (Gönderen) Kimlik No': 'Auftraggeber (Absender) – Identifikationsnummer',
        'Referans Belge No': 'Referenzbeleg-Nr.',
        'Referans Belge Tarihi': 'Referenzbeleg-Datum',
        'Referans Belge Kodu': 'Referenzbeleg-Code',
        'Referans Belge Açıklaması': 'Referenzbeleg-Beschreibung',
        'Tahsil Alındısı No (BELGENO)': 'Einzahlungsquittung-Nr. (BELGENO)',
        'Ek Belge Açıklaması (VTA / GVTA vb.)': 'Zusatzdokument-Beschreibung (VTA / GVTA usw.)',
        'İşlem Referans No': 'Transaktionsreferenz',
        'İşlem Kanalı': 'Transaktionskanal',
        'Banka Provizyon No': 'Bank-Autorisierungsnummer',
        'Vergilendirme Dönemi': 'Besteuerungszeitraum',
        'Tahsil Eden Vergi Dairesi': 'Erhebendes Finanzamt',
        'Tahsil Eden Vergi Dairesi Kodu': 'Code des erhebenden Finanzamts',
        'Gümrük Müdürlüğü Kodu': 'Zollamtscode',
        'Gümrük Müdürlüğü Adı': 'Zollamtsname',
        'Gümrük Saymanlığı Adı': 'Zollkasse – Name',
        'Gümrük Saymanlığı Kodu / VKN': 'Zollkasse – Code / Steuernummer',
        'Saymanlık Banka Şube Kodu': 'Zollkasse – Bankfilialcode',
        'Saymanlık Banka Şube Adı': 'Zollkasse – Bankfilialname',
        'Ödeme Kanalı Kodu': 'Zahlungskanalcode',
        'Sanal POS Kodu': 'Virtueller POS-Code',
        'İşlem Tarihi': 'Transaktionsdatum',
        'İşlem Saati': 'Transaktionsuhrzeit',
        'Valör Tarihi': 'Wertstellungsdatum',
        'Valör Saati': 'Wertstellungsuhrzeit',
        'İşlem Kodu (SerialID)': 'Transaktionscode (SerialID)',
        'İşlem Değeri (açıklama)': 'Transaktionswert (Beschreibung)',
        'Satır Masraf / Kesinti Nedeni': 'Positions-Gebühren- / Abzugsgrund',
        'Satır Masraf / Kesinti Tutarı': 'Positions-Gebühren- / Abzugsbetrag',
        // Sigorta komisyon
        'Komisyon Dönemi Başlangıcı': 'Beginn des Provisionszeitraums',
        'Komisyon Dönemi Bitişi': 'Ende des Provisionszeitraums',
        'Komisyon Dönemi Açıklaması': 'Beschreibung des Provisionszeitraums',
        'İstihsal Komisyonu Toplamı': 'Abschlussprovision gesamt',
        'İptal Komisyonu Toplamı': 'Stornoprovision gesamt',
        'Satır İstihsal Komisyonu': 'Positions-Abschlussprovision',
        'Satır İptal Komisyonu': 'Positions-Stornoprovision',
        'Satır Komisyon Nedeni': 'Positions-Provisionsgrund',
        'Branş / Sigorta Ürünü': 'Sparte / Versicherungsprodukt',
        // e-Bilet
        'Gönderen VKN': 'Absender – Steuernummer (VKN)',
        'Gönderen TCKN': 'Absender – Ausweisnummer (TCKN)',
        'Rapor Dönemi Başlangıcı': 'Beginn des Berichtszeitraums',
        'Rapor Dönemi Bitişi': 'Ende des Berichtszeitraums',
        'Rapor Versiyonu': 'Berichtsversion',
        'Rapor UUID': 'Berichts-UUID',
        'İmza Zamanı': 'Signaturzeitpunkt',
        'Bilet No': 'Ticketnummer',
        'Belge Tipi (SATIS / IADE)': 'Belegart (SATIS / IADE)',
        'Özet Değer (SHA-256)': 'Hashwert (SHA-256)',
        'Düzenlenme Tarihi': 'Ausstellungsdatum',
        'Sefer Zamanı': 'Abfahrtszeit',
        'Etkinlik Zamanı': 'Veranstaltungszeit',
        'Ödeme Şekli': 'Zahlungsart',
        'Bilet Tutarı': 'Ticketbetrag',
        'KDV Tutarı': 'USt.-Betrag',
        'e-Bilet URL': 'e-Ticket-URL',
        'Etkinlik Yeri İl Kodu': 'Veranstaltungsort – Provinzcode',
        'Etkinlik Yeri Belediyesi': 'Veranstaltungsort – Gemeinde',
        'Etkinlik Yeri Açıklaması': 'Veranstaltungsort – Beschreibung',
        'Organizatör VKN/TCKN': 'Veranstalter – Steuer-ID (VKN/TCKN)',
        'Hizmetin Nevi': 'Leistungsart',
        'Hizmet Açıklaması': 'Leistungsbeschreibung',
        'Gider Gösteren VKN': 'Aufwandsträger – Steuernummer (VKN)',
        'Gider Gösteren TCKN': 'Aufwandsträger – Ausweisnummer (TCKN)',
        'Referans Açıklaması': 'Referenzbeschreibung',
        'Referans No (asıl bilet)': 'Referenznummer (Originalticket)',
        'Diğer Vergi Kodu': 'Sonstige Steuer – Code',
        'Diğer Vergi Adı': 'Sonstige Steuer – Bezeichnung',
        'Diğer Vergi Oranı (%)': 'Sonstige Steuer – Satz (%)',
        'Diğer Vergi Tutarı': 'Sonstige Steuer – Betrag',
        'Eğlence Vergisi Tutarı (9142)': 'Vergnügungssteuer – Betrag (9142)',
        'İptal Edilen Bilet No': 'Nummer des stornierten Tickets',
        'İptal Zamanı': 'Stornierungszeitpunkt',
        'İptal Tutarı': 'Stornobetrag',
        'İptal KDV Tutarı': 'Storno-USt.-Betrag',
        // e-Yolcu listesi
        'Yolcu Listesi No': 'Fahrgastlisten-Nr.',
        'Liste Özet Değeri': 'Hashwert der Liste',
        'Hareket Zamanı': 'Abfahrtszeit',
        'Hareket Noktası': 'Abfahrtsort',
        'Sefer Numarası': 'Fahrtnummer',
        'Sefer Tarihi': 'Fahrtdatum',
        'Toplam Hasılat (KDV dahil)': 'Gesamterlös (inkl. USt.)',
        'Taşıtı İşleten VKN': 'Fahrzeughalter – Steuernummer (VKN)',
        'Taşıtı İşleten TCKN': 'Fahrzeughalter – Ausweisnummer (TCKN)',
        'Komisyon Tutarı': 'Provisionsbetrag',
        'Komisyon KDV Tutarı': 'USt. auf Provision',
        'Koltuk No': 'Sitzplatznummer',
        'Yolcu Adı Soyadı': 'Vollständiger Name des Fahrgasts',
        'Yolcu TCKN / YKN': 'Ausweisnummer des Fahrgasts (TCKN / YKN)',
        'Yolcu Pasaport No': 'Reisepassnummer des Fahrgasts',
    },
};

export default de;
