import type { GibDict } from './types';

const en: GibDict = {
    tpl: {
        party: '{{party}} {{field}}',
        line: 'Line {{label}}',
        amount: '{{name}} amount',
        base: '{{name}} base',
        rate: '{{name}} rate (%)',
    },
    parties: {
        'Sipariş Veren': 'Ordering party',
        'Asıl Alıcı': 'Actual buyer',
        'Teslim Alan': 'Recipient',
        'Düzenleyen': 'Issuer',
        'Gönderen': 'Sender',
        'Satıcı': 'Seller',
        'Alıcı': 'Buyer',
        'Çiftçi': 'Farmer',
    },
    partyFields: {
        'Unvanı': 'name',
        'Resmi Unvanı': 'legal name',
        'Adı (şahıs)': 'first name (person)',
        'Soyadı (şahıs)': 'last name (person)',
        'Kimlik No (VKN/TCKN vb.)': 'ID number (VKN/TCKN etc.)',
        'Kimlik Türü': 'ID type',
        'VKN': 'tax no. (VKN)',
        'TCKN': 'national ID (TCKN)',
        'MERSİS No': 'MERSIS no.',
        'Ticaret Sicil No': 'trade registry no.',
        'Vergi Dairesi': 'tax office',
        'Cadde/Sokak': 'street',
        'Bina Adı': 'building name',
        'Kapı No': 'building no.',
        'İlçe': 'district',
        'İl': 'province',
        'İli': 'province',
        'Bölge / Semt': 'region / neighbourhood',
        'Posta Kodu': 'postal code',
        'Ülke': 'country',
        'Ülkesi': 'country',
        'Telefon': 'phone',
        'Faks': 'fax',
        'E-posta': 'e-mail',
        'Web Sitesi': 'website',
        'İlgili Kişi': 'contact person',
        'Mahalle': 'neighbourhood',
        'Daire / Oda No': 'flat / room no.',
        'Şube No': 'branch no.',
        'EPDK No': 'EPDK licence no.',
        'Sevkiyat No (IDIS)': 'shipment no. (IDIS)',
        'Müşteri No': 'customer no.',
        'Abone No': 'subscriber no.',
        'Tesisat No': 'installation no.',
        'Sayaç No': 'meter no.',
        'Hasta No': 'patient no.',
        'Dosya No': 'file no.',
        'Araç Plakası (şarj)': 'vehicle plate (charging)',
        'Araç Kimlik No (şarj)': 'vehicle ID (charging)',
        'SMS Kodu': 'SMS code',
        'SMS Telefonu': 'SMS phone',
        'TCKN / YKN': 'national ID / foreigner ID',
    },
    taxes: {
        'KDV': 'VAT',
        'Konaklama Vergisi': 'Accommodation tax',
        'ÖTV 1. Liste (petrol/doğalgaz)': 'SCT list I (petroleum/natural gas)',
        'ÖTV 2. Liste (motorlu taşıt)': 'SCT list II (motor vehicles)',
        'ÖTV 3. Liste': 'SCT list III',
        'ÖTV 3A (alkollü içecek)': 'SCT III-A (alcoholic beverages)',
        'ÖTV 3B (tütün)': 'SCT III-B (tobacco)',
        'ÖTV 3C (kolalı gazoz)': 'SCT III-C (cola drinks)',
        'ÖTV 4. Liste (dayanıklı tüketim)': 'SCT list IV (durable goods)',
        'Petrol-Doğalgaz ÖTV Tevkifatı': 'Petroleum/natural gas SCT withholding',
        'Damga Vergisi': 'Stamp duty',
        '5035 SK Damga Vergisi': 'Stamp duty (Law 5035)',
        'Özel İletişim Vergisi': 'Special communication tax',
        '5035 SK Özel İletişim Vergisi': 'Special communication tax (Law 5035)',
        'Elektrik ve Havagazı Tüketim Vergisi': 'Electricity and gas consumption tax',
        'Elektrik Tüketim Vergisi': 'Electricity consumption tax',
        'TRT Payı': 'TRT share',
        'Enerji Fonu': 'Energy fund',
        'Borsa Tescil Ücreti': 'Exchange registration fee',
        'Telsiz Kullanım Ücreti': 'Radio usage fee',
        'Telsiz Ruhsat Ücreti': 'Radio licence fee',
        'Çevre Temizlik Vergisi': 'Environmental cleaning tax',
        'Belediye Hal Rüsumu': 'Municipal market hall fee',
        'Mera Fonu': 'Pasture fund',
        'Gelir Vergisi Stopajı': 'Income tax withholding',
        'Kurumlar Vergisi Stopajı': 'Corporate tax withholding',
        'Banka Muameleleri Vergisi': 'Banking transactions tax',
        'Sigorta Muameleleri Vergisi': 'Insurance transactions tax',
        '4961 Banka Sigorta Muameleleri Vergisi': 'Banking and insurance transactions tax (Law 4961)',
        'KKDF Kesintisi': 'KKDF levy',
        'GV Stopajı': 'Income tax withholding',
        'SGK Prim Kesintisi': 'Social security premium deduction',
        'BSMV': 'BITT',
    },
    labels: {
        // Kategoriler
        'Belge Bilgileri': 'Document details',
        'Satıcı': 'Seller',
        'Alıcı': 'Buyer',
        'Asıl Alıcı (İhracat / Yolcu Beraber)': 'Actual buyer (export / tax-free)',
        'Tutarlar': 'Amounts',
        'Vergiler': 'Taxes',
        'Vergi Türleri': 'Tax types',
        'Serbest Meslek Makbuzu (e-SMM)': 'Self-employment receipt (e-SMM)',
        'Döviz / Kur': 'Currency / exchange rate',
        'Ödeme': 'Payment',
        'Referanslar': 'References',
        'Teslimat / İhracat': 'Delivery / export',
        'İnternet Satışı (e-Arşiv)': 'Online sale (e-Archive)',
        'Satır (Kalem)': 'Line items',
        'Satır · Özel Senaryolar': 'Line · special scenarios',
        'Ek Belge / Matbu İrsaliye': 'Additional document / printed despatch note',
        'Gönderen': 'Sender',
        'Satıcı (Zincir Teslim)': 'Seller (chain delivery)',
        'Alıcı / Sipariş Veren (Zincir Teslim)': 'Buyer / ordering party (chain delivery)',
        'Asıl Alıcı (Zincir Teslim)': 'Actual buyer (chain delivery)',
        'Sevkiyat': 'Shipment',
        'Yanıtlanan İrsaliye': 'Despatch advice responded to',
        'Teslim Alan (Yanıtlayan)': 'Recipient (responder)',
        'Teslimat': 'Delivery',
        'Makbuzu Düzenleyen (Malı Satın Alan)': 'Receipt issuer (purchaser of goods)',
        'Üretici / Çiftçi (Malı Satan)': 'Producer / farmer (seller of goods)',
        'Kesintiler (Vergi ve Fonlar)': 'Deductions (taxes and funds)',
        'Satır (Mal Bilgileri)': 'Lines (goods)',
        'Vergiler (KDV / BSMV)': 'Taxes (VAT / BITT)',
        'Gider Pusulası': 'Expense voucher',
        'Döviz / Kıymetli Maden': 'Foreign currency / precious metals',
        'Döviz Kuru (USD / TL Karşılığı)': 'Exchange rate (USD / TRY equivalent)',
        'Dekont': 'Bank receipt',
        'Sigorta Komisyon': 'Insurance commission',
        'Rapor Bilgileri': 'Report details',
        'Bilet': 'Ticket',
        'Etkinlik Yeri / Organizatör': 'Venue / organizer',
        'Hizmet / Gider Gösteren': 'Service / expense claimant',
        'Diğer Vergiler': 'Other taxes',
        'İptal Edilen Bilet': 'Cancelled ticket',
        'Sefer': 'Trip',
        'Taşıtı İşleten': 'Vehicle operator',
        'Koltuk / Yolcu': 'Seat / passenger',

        // Fatura — belge
        'Fatura No': 'Invoice no.',
        'Fatura Tarihi': 'Invoice date',
        'Fatura Saati': 'Invoice time',
        'Fatura Tipi': 'Invoice type',
        'Senaryo (Profil)': 'Scenario (profile)',
        'ETTN (UUID)': 'UUID',
        'Para Birimi': 'Currency',
        'Fatura Notu': 'Invoice note',
        'Satır Sayısı': 'Line count',
        'Fatura Dönemi Başlangıcı': 'Invoice period start',
        'Fatura Dönemi Başlangıç Saati': 'Invoice period start time',
        'Fatura Dönemi Bitişi': 'Invoice period end',
        'Fatura Dönemi Bitiş Saati': 'Invoice period end time',
        'Fatura Dönemi Açıklaması': 'Invoice period description',
        'Muhasebe Maliyet Kodu (SGK)': 'Accounting cost code (SGK)',
        // Asıl alıcı / turist
        'Alıcı Tipi (EXPORT / TAXFREE)': 'Buyer type (EXPORT / TAXFREE)',
        'Asıl Alıcı TCKN': 'Actual buyer national ID (TCKN)',
        'Hastane Protokol No': 'Hospital protocol no.',
        'Turist Adı': 'Tourist first name',
        'Turist Soyadı': 'Tourist last name',
        'Turist Uyruğu': 'Tourist nationality',
        'Pasaport No': 'Passport no.',
        'Pasaport Tarihi': 'Passport date',
        'Turist Banka Hesap No': 'Tourist bank account no.',
        'Turist Bankası': 'Tourist bank',
        'Asıl Alıcı İli': 'Actual buyer province',
        'Asıl Alıcı Ülkesi': 'Actual buyer country',
        'Aracı Kurum VKN': 'Intermediary tax no. (VKN)',
        'Aracı Kurum Etiketi': 'Intermediary label',
        'Aracı Kurum Unvanı': 'Intermediary name',
        'Aracı Kurum İli': 'Intermediary province',
        // Tutarlar
        'Mal Hizmet Toplam Tutarı': 'Total goods/services amount',
        'Vergiler Hariç Toplam': 'Total excluding taxes',
        'Vergiler Dahil Toplam': 'Total including taxes',
        'Toplam İskonto': 'Total discount',
        'Toplam Masraf': 'Total charges',
        'Yuvarlama Tutarı': 'Rounding amount',
        'Ödenecek Tutar': 'Amount payable',
        'Fatura İskonto Oranı': 'Invoice discount rate',
        'Fatura İskonto Tutarı': 'Invoice discount amount',
        'İskonto Açıklaması': 'Discount description',
        // Vergiler
        'Hesaplanan Vergiler (toplam)': 'Calculated taxes (total)',
        'Vergi Matrahı': 'Taxable amount',
        'Vergi Tutarı': 'Tax amount',
        'Vergi Oranı (%)': 'Tax rate (%)',
        'Vergi Adı': 'Tax name',
        'Vergi Kodu': 'Tax code',
        'Muafiyet Sebebi': 'Exemption reason',
        'Muafiyet Kodu': 'Exemption code',
        'Tevkifat Tutarı': 'Withholding amount',
        'Tevkifat Oranı (%)': 'Withholding rate (%)',
        'Tevkifat Kodu': 'Withholding code',
        'Tevkifat Adı': 'Withholding name',
        'Tevkifat Matrahı': 'Withholding base',
        // e-SMM
        'Serbest Meslek Erbabı Mesleği / Unvanı': 'Professional’s occupation / title',
        'GV Stopajı Matrahı': 'Income tax withholding base',
        'GV Stopajı Oranı (%)': 'Income tax withholding rate (%)',
        'KV Stopajı Oranı (%)': 'Corporate tax withholding rate (%)',
        'GV Stopajı Tutarı (tevkifat bölümünde)': 'Income tax withholding amount (withholding section)',
        'GV Stopajı Oranı (tevkifat bölümünde, %)': 'Income tax withholding rate (withholding section, %)',
        'KDV Tevkifatı Tutarı (9015, eski kullanım)': 'VAT withholding amount (9015, legacy)',
        // Döviz
        'Döviz Kuru': 'Exchange rate',
        'Kaynak Para Birimi': 'Source currency',
        'Hedef Para Birimi': 'Target currency',
        'Kur Tarihi': 'Exchange rate date',
        'Fiyatlandırma Para Birimi': 'Pricing currency',
        'Vergi Para Birimi': 'Tax currency',
        // Ödeme
        'Ödeme Şekli Kodu': 'Payment means code',
        'Son Ödeme Tarihi': 'Payment due date',
        'Ödeme Kanalı': 'Payment channel',
        'IBAN': 'IBAN',
        'Hesap Para Birimi': 'Account currency',
        'Banka / Şube': 'Bank / branch',
        'Ödeme Notu': 'Payment note',
        'Hesap Açıklaması': 'Account note',
        'Ödeme Koşulu': 'Payment terms',
        'Gecikme Faizi (%)': 'Late payment interest (%)',
        'Vade Tarihi': 'Due date',
        // Referanslar
        'İrsaliye No': 'Despatch note no.',
        'İrsaliye Tarihi': 'Despatch note date',
        'Sipariş No': 'Order no.',
        'Sipariş Tarihi': 'Order date',
        'İade Edilen Fatura No': 'Returned invoice no.',
        'İade Edilen Fatura Tarihi': 'Returned invoice date',
        'Ek Belge No': 'Additional document no.',
        'Ek Belge Tarihi': 'Additional document date',
        'Ek Belge Türü': 'Additional document type',
        'İade Edilen Belge Tipi': 'Returned document type',
        'ESÜ Rapor ID (şarj)': 'Charging unit report ID',
        'Yatırım Teşvik Belge No': 'Investment incentive certificate no.',
        'Yatırım Teşvik Belge Tarihi': 'Investment incentive certificate date',
        'Sözleşme No': 'Contract no.',
        // Teslimat
        'Teslim Şartı (Incoterms)': 'Delivery terms (Incoterms)',
        'Gönderim Şekli': 'Transport mode',
        'Teslim Tarihi': 'Delivery date',
        'Teslimat Adresi': 'Delivery address',
        'Teslimat İli': 'Delivery province',
        'Teslimat Ülkesi': 'Delivery country',
        'Gönderiyi Taşıyan Unvanı': 'Carrier name',
        'Gönderiyi Taşıyan Adı': 'Carrier first name',
        'Gönderiyi Taşıyan Soyadı': 'Carrier last name',
        'Gönderiyi Taşıyan VKN/TCKN': 'Carrier tax ID (VKN/TCKN)',
        'Gönderim Tarihi': 'Dispatch date',
        'Gönderim Saati': 'Dispatch time',
        // Satır
        'Ürün / Hizmet Adı': 'Product / service name',
        'Ürün Açıklaması': 'Product description',
        'Satıcı Ürün Kodu': 'Seller item code',
        'Alıcı Ürün Kodu': 'Buyer item code',
        'Marka': 'Brand',
        'Model': 'Model',
        'Miktar': 'Quantity',
        'Birim': 'Unit',
        'Birim Fiyat': 'Unit price',
        'Satır İskonto Oranı': 'Line discount rate',
        'Satır İskonto Tutarı': 'Line discount amount',
        'Satır Tutarı': 'Line amount',
        'Satır Vergi Oranı (%)': 'Line tax rate (%)',
        'Satır Vergi Tutarı': 'Line tax amount',
        'GTİP No': 'HS code (GTİP)',
        'Satır Notu': 'Line note',
        'Satır Muafiyet Kodu': 'Line exemption code',
        'Satır Muafiyet Sebebi': 'Line exemption reason',
        'Satır Tevkifat Tutarı': 'Line withholding amount',
        'Satır Tevkifat Oranı (%)': 'Line withholding rate (%)',
        'Satır Tevkifat Kodu': 'Line withholding code',
        'Künye No (HKS)': 'Produce tag no. (HKS)',
        'Etiket No (IDIS)': 'Label no. (IDIS)',
        'İlaç Seri No': 'Medicine serial no.',
        'Tıbbi Cihaz Seri No': 'Medical device serial no.',
        'Diğer Ürün (İlaç/Tıbbi Cihaz)': 'Other product (medicine/medical device)',
        'Telefon IMEI (Teknoloji Destek)': 'Phone IMEI (technology support)',
        'Tablet PC (Teknoloji Destek)': 'Tablet PC (technology support)',
        'Harcama Tipi (Yatırım Teşvik)': 'Expense type (investment incentive)',
        'Makine Teçhizat Sıra No (YTB)': 'Machinery/equipment item no. (YTB)',
        'Seri No / Makine ID': 'Serial no. / machine ID',
        'Satır Teslim Şartı': 'Line delivery terms',
        'Satır Gönderim Şekli': 'Line transport mode',
        'Kap Cinsi': 'Package type',
        'Kap No': 'Package no.',
        'Kap Adedi': 'Package count',
        'Satıcı DİİB Satır Kodu (İhraç Kayıtlı)': 'Seller inward processing line code (export-registered)',
        'Alıcı DİİB Satır Kodu (İhraç Kayıtlı)': 'Buyer inward processing line code (export-registered)',
        'Satır Teslim Adresi': 'Line delivery address',
        'Satır Teslim İli': 'Line delivery province',
        // İrsaliye
        'İrsaliye Saati': 'Despatch note time',
        'İrsaliye Tipi': 'Despatch note type',
        'İrsaliye Notu': 'Despatch note remark',
        'Ek Belge No (matbu irsaliye / fatura)': 'Additional document no. (printed despatch note / invoice)',
        'Ek Belge Tür Kodu': 'Additional document type code',
        'Ek Belge Açıklaması': 'Additional document description',
        'Malın Çıktığı Yer Kodu': 'Place of dispatch code',
        'Malın Çıktığı Yer Adresi': 'Place of dispatch address',
        'Malın Çıktığı Yer İlçe': 'Place of dispatch district',
        'Malın Çıktığı Yer İl': 'Place of dispatch province',
        'Kargo / Sevkiyat No': 'Cargo / shipment no.',
        'Toplam Mal Değeri': 'Total goods value',
        'Fiili Sevk Tarihi': 'Actual despatch date',
        'Fiili Sevk Saati': 'Actual despatch time',
        'Araç Plakası': 'Vehicle plate',
        'Araç Plaka Türü (PLAKA/YABANCIPLAKA)': 'Vehicle plate type (PLAKA/YABANCIPLAKA)',
        'Dorse Plakası': 'Trailer plate',
        'Dorse Türü (DORSE/DORSEPLAKA/YABANCI...)': 'Trailer type (DORSE/DORSEPLAKA/YABANCI...)',
        'Sürücü Adı': 'Driver first name',
        'Sürücü Soyadı': 'Driver last name',
        'Sürücü TCKN': 'Driver national ID (TCKN)',
        'Sürücü Unvanı / Görevi': 'Driver title / role',
        'Taşıyıcı Unvanı': 'Carrier name',
        'Taşıyıcı VKN': 'Carrier tax no. (VKN)',
        'Taşıyıcı İlçe': 'Carrier district',
        'Taşıyıcı İl': 'Carrier province',
        'Teslimat Kapı No': 'Delivery building no.',
        'Teslimat İlçesi': 'Delivery district',
        'Teslimat Posta Kodu': 'Delivery postal code',
        'Satır No': 'Line no.',
        'Gönderilen Miktar': 'Despatched quantity',
        'Eksik Miktar': 'Outstanding quantity',
        'Eksik Miktar Nedeni': 'Outstanding quantity reason',
        'Sipariş Satır No': 'Order line no.',
        // İrsaliye yanıtı
        'Yanıt No': 'Response no.',
        'Yanıt Tarihi': 'Response date',
        'Yanıt Saati': 'Response time',
        'Yanıt Tipi': 'Response type',
        'Yanıt Notu': 'Response note',
        'Fiili Teslim Tarihi': 'Actual delivery date',
        'Fiili Teslim Saati': 'Actual delivery time',
        'Ürün Adı': 'Product name',
        'Teslim Alınan Miktar': 'Received quantity',
        'Reddedilen Miktar': 'Rejected quantity',
        'Red Nedeni': 'Rejection reason',
        'Fazla Miktar': 'Oversupplied quantity',
        'Zamanlama Şikayeti (geç teslim)': 'Timing complaint (late delivery)',
        'İrsaliye Satır No': 'Despatch line no.',
        // Müstahsil / CreditNote
        'Makbuz No': 'Receipt no.',
        'Düzenleme Tarihi': 'Issue date',
        'Düzenleme Zamanı': 'Issue time',
        'Belge Tipi (CreditNoteTypeCode)': 'Document type (CreditNoteTypeCode)',
        'Özelleştirme No': 'Customization ID',
        'Asıl / Suret (CopyIndicator)': 'Original / copy (CopyIndicator)',
        'Makbuz Notu': 'Receipt note',
        'SMS Operatörü (uygulama adı)': 'SMS operator (application name)',
        'SMS Operatörü VKN': 'SMS operator tax no. (VKN)',
        'Mal Hizmet Toplam Tutarı (brüt)': 'Total goods/services amount (gross)',
        'Ödenecek Tutar (net)': 'Amount payable (net)',
        'Toplam Kesinti': 'Total deductions',
        'Kesinti Adı': 'Deduction name',
        'Kesinti Kodu': 'Deduction code',
        'Kesinti Tutarı': 'Deduction amount',
        'Kesinti Oranı (%)': 'Deduction rate (%)',
        'Malın Cinsi': 'Type of goods',
        'Mal Açıklaması': 'Goods description',
        'Tutar (Bedel)': 'Amount (price)',
        'Satır Kesinti Toplamı': 'Line deductions total',
        // Gider pusulası
        'İade Edilen Belge No': 'Returned document no.',
        'İade Edilen Belge Türü (EARSIV_FATURA / SATIS_FISI / BELGESIZ)': 'Returned document type (EARSIV_FATURA / SATIS_FISI / BELGESIZ)',
        'İade Edilen Belge Tarihi': 'Returned document date',
        'Kod Türü (SMS / IADEKODU)': 'Code type (SMS / IADEKODU)',
        'SMS / İade Kodu': 'SMS / return code',
        'Kodun Gönderildiği Telefon': 'Phone the code was sent to',
        'İade Kodu Uygulaması': 'Return code application',
        'İade Kodu Uygulaması VKN': 'Return code application tax no. (VKN)',
        'Adına İade Yapılan Adı': 'Refund beneficiary first name',
        'Adına İade Yapılan Soyadı': 'Refund beneficiary last name',
        'Adına İade Yapılan Unvanı': 'Refund beneficiary name',
        'Adına İade Yapılan TCKN': 'Refund beneficiary national ID (TCKN)',
        'Adına İade Yapılan SMS / İade Kodu': 'Refund beneficiary SMS / return code',
        'Adına İade Yapılan Telefon': 'Refund beneficiary phone',
        'Kargo Firması Unvanı': 'Courier company name',
        'Kargo Firması VKN': 'Courier company tax no. (VKN)',
        'Kargo Yetki Belgesi No': 'Courier licence no.',
        'Kargo Firması İl': 'Courier company province',
        // Döviz / kıymetli maden
        'Yetkili Müessese Şube No (SUBENO)': 'Authorized institution branch no. (SUBENO)',
        'Müşteri Türü (MUSTERITURU)': 'Customer type (MUSTERITURU)',
        'Müşteri Pasaport No': 'Customer passport no.',
        'Müşteri Uyruğu': 'Customer nationality',
        'Döviz / Maden Kodu (kaynak)': 'Currency / metal code (source)',
        'Karşılık Para Birimi (hedef)': 'Counter currency (target)',
        'Uygulanan Kur / Birim Fiyat': 'Applied rate / unit price',
        'Ödeme Şekli Kodu (10 / 55 / 46 / 68)': 'Payment means code (10 / 55 / 46 / 68)',
        'Müşteri Hesap No': 'Customer account no.',
        'Müessese Hesap No (IBAN)': 'Institution account no. (IBAN)',
        'İstatistik No': 'Statistics no.',
        'Dövizin Geldiği Ülke': 'Country of currency origin',
        'Dövizin Geliş Nedeni': 'Reason for currency inflow',
        'Gümrük Beyanname No': 'Customs declaration no.',
        'Gümrük Beyanname Tarihi': 'Customs declaration date',
        'Döviz Beyan Tutanağı Sayısı': 'Currency declaration record no.',
        'Gümrük Teyit Yazısı Sayısı': 'Customs confirmation letter no.',
        'İlgili Fatura No': 'Related invoice no.',
        'Kur: Kaynak Para Birimi': 'Rate: source currency',
        'Kur: Hedef Para Birimi': 'Rate: target currency',
        'Kur Oranı': 'Exchange rate',
        // Dekont
        'Şube Kodu': 'Branch code',
        'Şube Adı': 'Branch name',
        'İşlemi Yapan Personel Adı': 'Processing staff first name',
        'İşlemi Yapan Personel Soyadı': 'Processing staff last name',
        'İşlemi Yapan Personel Sicil No': 'Processing staff registry no.',
        'Müşteri No': 'Customer no.',
        'Müşteri IBAN': 'Customer IBAN',
        'Abone No': 'Subscriber no.',
        'İşlemi Yapan (Gönderen) Unvanı': 'Originator (sender) name',
        'İşlemi Yapan (Gönderen) Kimlik No': 'Originator (sender) ID no.',
        'Referans Belge No': 'Reference document no.',
        'Referans Belge Tarihi': 'Reference document date',
        'Referans Belge Kodu': 'Reference document code',
        'Referans Belge Açıklaması': 'Reference document description',
        'Tahsil Alındısı No (BELGENO)': 'Collection receipt no. (BELGENO)',
        'Ek Belge Açıklaması (VTA / GVTA vb.)': 'Additional document description (VTA / GVTA etc.)',
        'İşlem Referans No': 'Transaction reference no.',
        'İşlem Kanalı': 'Transaction channel',
        'Banka Provizyon No': 'Bank authorization no.',
        'Vergilendirme Dönemi': 'Tax period',
        'Tahsil Eden Vergi Dairesi': 'Collecting tax office',
        'Tahsil Eden Vergi Dairesi Kodu': 'Collecting tax office code',
        'Gümrük Müdürlüğü Kodu': 'Customs office code',
        'Gümrük Müdürlüğü Adı': 'Customs office name',
        'Gümrük Saymanlığı Adı': 'Customs accounting office name',
        'Gümrük Saymanlığı Kodu / VKN': 'Customs accounting office code / tax no.',
        'Saymanlık Banka Şube Kodu': 'Accounting office bank branch code',
        'Saymanlık Banka Şube Adı': 'Accounting office bank branch name',
        'Ödeme Kanalı Kodu': 'Payment channel code',
        'Sanal POS Kodu': 'Virtual POS code',
        'İşlem Tarihi': 'Transaction date',
        'İşlem Saati': 'Transaction time',
        'Valör Tarihi': 'Value date',
        'Valör Saati': 'Value time',
        'İşlem Kodu (SerialID)': 'Transaction code (SerialID)',
        'İşlem Değeri (açıklama)': 'Transaction value (description)',
        'Satır Masraf / Kesinti Nedeni': 'Line charge / deduction reason',
        'Satır Masraf / Kesinti Tutarı': 'Line charge / deduction amount',
        // Sigorta komisyon
        'Komisyon Dönemi Başlangıcı': 'Commission period start',
        'Komisyon Dönemi Bitişi': 'Commission period end',
        'Komisyon Dönemi Açıklaması': 'Commission period description',
        'İstihsal Komisyonu Toplamı': 'Production commission total',
        'İptal Komisyonu Toplamı': 'Cancellation commission total',
        'Satır İstihsal Komisyonu': 'Line production commission',
        'Satır İptal Komisyonu': 'Line cancellation commission',
        'Satır Komisyon Nedeni': 'Line commission reason',
        'Branş / Sigorta Ürünü': 'Branch / insurance product',
        // e-Bilet
        'Gönderen VKN': 'Sender tax no. (VKN)',
        'Gönderen TCKN': 'Sender national ID (TCKN)',
        'Rapor Dönemi Başlangıcı': 'Report period start',
        'Rapor Dönemi Bitişi': 'Report period end',
        'Rapor Versiyonu': 'Report version',
        'Rapor UUID': 'Report UUID',
        'İmza Zamanı': 'Signing time',
        'Bilet No': 'Ticket no.',
        'Belge Tipi (SATIS / IADE)': 'Document type (SATIS / IADE)',
        'Özet Değer (SHA-256)': 'Digest value (SHA-256)',
        'Düzenlenme Tarihi': 'Issue date',
        'Sefer Zamanı': 'Departure time',
        'Etkinlik Zamanı': 'Event time',
        'Ödeme Şekli': 'Payment method',
        'Bilet Tutarı': 'Ticket amount',
        'KDV Tutarı': 'VAT amount',
        'e-Bilet URL': 'e-Ticket URL',
        'Etkinlik Yeri İl Kodu': 'Venue province code',
        'Etkinlik Yeri Belediyesi': 'Venue municipality',
        'Etkinlik Yeri Açıklaması': 'Venue description',
        'Organizatör VKN/TCKN': 'Organizer tax ID (VKN/TCKN)',
        'Hizmetin Nevi': 'Type of service',
        'Hizmet Açıklaması': 'Service description',
        'Gider Gösteren VKN': 'Expense claimant tax no. (VKN)',
        'Gider Gösteren TCKN': 'Expense claimant national ID (TCKN)',
        'Referans Açıklaması': 'Reference description',
        'Referans No (asıl bilet)': 'Reference no. (original ticket)',
        'Diğer Vergi Kodu': 'Other tax code',
        'Diğer Vergi Adı': 'Other tax name',
        'Diğer Vergi Oranı (%)': 'Other tax rate (%)',
        'Diğer Vergi Tutarı': 'Other tax amount',
        'Eğlence Vergisi Tutarı (9142)': 'Entertainment tax amount (9142)',
        'İptal Edilen Bilet No': 'Cancelled ticket no.',
        'İptal Zamanı': 'Cancellation time',
        'İptal Tutarı': 'Cancellation amount',
        'İptal KDV Tutarı': 'Cancellation VAT amount',
        // e-Yolcu listesi
        'Yolcu Listesi No': 'Passenger list no.',
        'Liste Özet Değeri': 'List digest value',
        'Hareket Zamanı': 'Departure time',
        'Hareket Noktası': 'Departure point',
        'Sefer Numarası': 'Trip number',
        'Sefer Tarihi': 'Trip date',
        'Toplam Hasılat (KDV dahil)': 'Total revenue (incl. VAT)',
        'Taşıtı İşleten VKN': 'Vehicle operator tax no. (VKN)',
        'Taşıtı İşleten TCKN': 'Vehicle operator national ID (TCKN)',
        'Komisyon Tutarı': 'Commission amount',
        'Komisyon KDV Tutarı': 'Commission VAT amount',
        'Koltuk No': 'Seat no.',
        'Yolcu Adı Soyadı': 'Passenger full name',
        'Yolcu TCKN / YKN': 'Passenger national ID / foreigner ID',
        'Yolcu Pasaport No': 'Passenger passport no.',
    },
};

export default en;
