import type { GibDict } from './types';

const es: GibDict = {
    tpl: {
        party: '{{field}} ({{party}})',
        line: '{{label}} (línea)',
        amount: 'Importe {{name}}',
        base: 'Base {{name}}',
        rate: 'Tipo {{name}} (%)',
    },
    parties: {
        'Sipariş Veren': 'ordenante del pedido',
        'Asıl Alıcı': 'comprador real',
        'Teslim Alan': 'receptor',
        'Düzenleyen': 'emisor',
        'Gönderen': 'remitente',
        'Satıcı': 'vendedor',
        'Alıcı': 'comprador',
        'Çiftçi': 'agricultor',
    },
    partyFields: {
        'Unvanı': 'Razón social',
        'Resmi Unvanı': 'Denominación oficial',
        'Adı (şahıs)': 'Nombre (persona física)',
        'Soyadı (şahıs)': 'Apellidos (persona física)',
        'Kimlik No (VKN/TCKN vb.)': 'N.º de identificación (VKN/TCKN, etc.)',
        'Kimlik Türü': 'Tipo de identificación',
        'VKN': 'N.º fiscal (VKN)',
        'TCKN': 'N.º de identidad (TCKN)',
        'MERSİS No': 'N.º MERSİS',
        'Ticaret Sicil No': 'N.º de registro mercantil',
        'Vergi Dairesi': 'Oficina tributaria',
        'Cadde/Sokak': 'Calle',
        'Bina Adı': 'Nombre del edificio',
        'Kapı No': 'N.º de portal',
        'İlçe': 'Distrito',
        'İl': 'Provincia',
        'İli': 'Provincia',
        'Bölge / Semt': 'Zona / barrio',
        'Posta Kodu': 'Código postal',
        'Ülke': 'País',
        'Ülkesi': 'País',
        'Telefon': 'Teléfono',
        'Faks': 'Fax',
        'E-posta': 'Correo electrónico',
        'Web Sitesi': 'Sitio web',
        'İlgili Kişi': 'Persona de contacto',
        'Mahalle': 'Barrio',
        'Daire / Oda No': 'N.º de piso / habitación',
        'Şube No': 'N.º de sucursal',
        'EPDK No': 'N.º de licencia EPDK',
        'Sevkiyat No (IDIS)': 'N.º de envío (IDIS)',
        'Müşteri No': 'N.º de cliente',
        'Abone No': 'N.º de abonado',
        'Tesisat No': 'N.º de instalación',
        'Sayaç No': 'N.º de contador',
        'Hasta No': 'N.º de paciente',
        'Dosya No': 'N.º de expediente',
        'Araç Plakası (şarj)': 'Matrícula del vehículo (recarga)',
        'Araç Kimlik No (şarj)': 'ID del vehículo (recarga)',
        'SMS Kodu': 'Código SMS',
        'SMS Telefonu': 'Teléfono SMS',
        'TCKN / YKN': 'N.º de identidad / de extranjero (TCKN / YKN)',
    },
    taxes: {
        'KDV': 'IVA',
        'Konaklama Vergisi': 'impuesto sobre alojamiento',
        'ÖTV 1. Liste (petrol/doğalgaz)': 'impuesto especial lista I (petróleo/gas natural)',
        'ÖTV 2. Liste (motorlu taşıt)': 'impuesto especial lista II (vehículos de motor)',
        'ÖTV 3. Liste': 'impuesto especial lista III',
        'ÖTV 3A (alkollü içecek)': 'impuesto especial III-A (bebidas alcohólicas)',
        'ÖTV 3B (tütün)': 'impuesto especial III-B (tabaco)',
        'ÖTV 3C (kolalı gazoz)': 'impuesto especial III-C (bebidas de cola)',
        'ÖTV 4. Liste (dayanıklı tüketim)': 'impuesto especial lista IV (bienes de consumo duradero)',
        'Petrol-Doğalgaz ÖTV Tevkifatı': 'retención del impuesto especial sobre petróleo/gas natural',
        'Damga Vergisi': 'impuesto de timbre',
        '5035 SK Damga Vergisi': 'impuesto de timbre (Ley 5035)',
        'Özel İletişim Vergisi': 'impuesto especial sobre comunicaciones',
        '5035 SK Özel İletişim Vergisi': 'impuesto especial sobre comunicaciones (Ley 5035)',
        'Elektrik ve Havagazı Tüketim Vergisi': 'impuesto sobre el consumo de electricidad y gas',
        'Elektrik Tüketim Vergisi': 'impuesto sobre el consumo de electricidad',
        'TRT Payı': 'cuota TRT',
        'Enerji Fonu': 'fondo de energía',
        'Borsa Tescil Ücreti': 'tasa de registro en bolsa',
        'Telsiz Kullanım Ücreti': 'tasa de uso de radiocomunicaciones',
        'Telsiz Ruhsat Ücreti': 'tasa de licencia de radiocomunicaciones',
        'Çevre Temizlik Vergisi': 'impuesto de limpieza ambiental',
        'Belediye Hal Rüsumu': 'tasa municipal de mercado mayorista',
        'Mera Fonu': 'fondo de pastos',
        'Gelir Vergisi Stopajı': 'retención del impuesto sobre la renta',
        'Kurumlar Vergisi Stopajı': 'retención del impuesto sobre sociedades',
        'Banka Muameleleri Vergisi': 'impuesto sobre operaciones bancarias',
        'Sigorta Muameleleri Vergisi': 'impuesto sobre operaciones de seguros',
        '4961 Banka Sigorta Muameleleri Vergisi': 'impuesto sobre operaciones bancarias y de seguros (Ley 4961)',
        'KKDF Kesintisi': 'gravamen KKDF',
        'GV Stopajı': 'retención del impuesto sobre la renta',
        'SGK Prim Kesintisi': 'deducción de cotizaciones a la Seguridad Social (SGK)',
        'BSMV': 'BSMV',
    },
    labels: {
        // Kategoriler
        'Belge Bilgileri': 'Datos del documento',
        'Satıcı': 'Vendedor',
        'Alıcı': 'Comprador',
        'Asıl Alıcı (İhracat / Yolcu Beraber)': 'Comprador real (exportación / viajero tax-free)',
        'Tutarlar': 'Importes',
        'Vergiler': 'Impuestos',
        'Vergi Türleri': 'Tipos de impuesto',
        'Serbest Meslek Makbuzu (e-SMM)': 'Recibo de profesional independiente (e-SMM)',
        'Döviz / Kur': 'Divisa / tipo de cambio',
        'Ödeme': 'Pago',
        'Referanslar': 'Referencias',
        'Teslimat / İhracat': 'Entrega / exportación',
        'İnternet Satışı (e-Arşiv)': 'Venta por internet (e-Archivo)',
        'Satır (Kalem)': 'Líneas (partidas)',
        'Satır · Özel Senaryolar': 'Línea · escenarios especiales',
        'Ek Belge / Matbu İrsaliye': 'Documento adicional / albarán impreso',
        'Gönderen': 'Remitente',
        'Satıcı (Zincir Teslim)': 'Vendedor (entrega en cadena)',
        'Alıcı / Sipariş Veren (Zincir Teslim)': 'Comprador / ordenante del pedido (entrega en cadena)',
        'Asıl Alıcı (Zincir Teslim)': 'Comprador real (entrega en cadena)',
        'Sevkiyat': 'Expedición',
        'Yanıtlanan İrsaliye': 'Albarán respondido',
        'Teslim Alan (Yanıtlayan)': 'Receptor (quien responde)',
        'Teslimat': 'Entrega',
        'Makbuzu Düzenleyen (Malı Satın Alan)': 'Emisor del recibo (comprador de la mercancía)',
        'Üretici / Çiftçi (Malı Satan)': 'Productor / agricultor (vendedor de la mercancía)',
        'Kesintiler (Vergi ve Fonlar)': 'Deducciones (impuestos y fondos)',
        'Satır (Mal Bilgileri)': 'Líneas (mercancías)',
        'Vergiler (KDV / BSMV)': 'Impuestos (IVA / BSMV)',
        'Gider Pusulası': 'Nota de gastos',
        'Döviz / Kıymetli Maden': 'Divisas / metales preciosos',
        'Döviz Kuru (USD / TL Karşılığı)': 'Tipo de cambio (contravalor USD / TRY)',
        'Dekont': 'Comprobante bancario',
        'Sigorta Komisyon': 'Comisión de seguros',
        'Rapor Bilgileri': 'Datos del informe',
        'Bilet': 'Billete / entrada',
        'Etkinlik Yeri / Organizatör': 'Recinto / organizador',
        'Hizmet / Gider Gösteren': 'Servicio / declarante del gasto',
        'Diğer Vergiler': 'Otros impuestos',
        'İptal Edilen Bilet': 'Billete anulado',
        'Sefer': 'Trayecto',
        'Taşıtı İşleten': 'Operador del vehículo',
        'Koltuk / Yolcu': 'Asiento / pasajero',

        // Fatura — belge
        'Fatura No': 'N.º de factura',
        'Fatura Tarihi': 'Fecha de la factura',
        'Fatura Saati': 'Hora de la factura',
        'Fatura Tipi': 'Tipo de factura',
        'Senaryo (Profil)': 'Escenario (perfil)',
        'ETTN (UUID)': 'Identificador único (ETTN / UUID)',
        'Para Birimi': 'Moneda',
        'Fatura Notu': 'Nota de la factura',
        'Satır Sayısı': 'N.º de líneas',
        'Fatura Dönemi Başlangıcı': 'Inicio del período de facturación',
        'Fatura Dönemi Başlangıç Saati': 'Hora de inicio del período de facturación',
        'Fatura Dönemi Bitişi': 'Fin del período de facturación',
        'Fatura Dönemi Bitiş Saati': 'Hora de fin del período de facturación',
        'Fatura Dönemi Açıklaması': 'Descripción del período de facturación',
        'Muhasebe Maliyet Kodu (SGK)': 'Código de coste contable (SGK)',
        // Asıl alıcı / turist
        'Alıcı Tipi (EXPORT / TAXFREE)': 'Tipo de comprador (EXPORT / TAXFREE)',
        'Asıl Alıcı TCKN': 'N.º de identidad del comprador real (TCKN)',
        'Hastane Protokol No': 'N.º de protocolo hospitalario',
        'Turist Adı': 'Nombre del turista',
        'Turist Soyadı': 'Apellidos del turista',
        'Turist Uyruğu': 'Nacionalidad del turista',
        'Pasaport No': 'N.º de pasaporte',
        'Pasaport Tarihi': 'Fecha del pasaporte',
        'Turist Banka Hesap No': 'N.º de cuenta bancaria del turista',
        'Turist Bankası': 'Banco del turista',
        'Asıl Alıcı İli': 'Provincia del comprador real',
        'Asıl Alıcı Ülkesi': 'País del comprador real',
        'Aracı Kurum VKN': 'N.º fiscal de la entidad intermediaria (VKN)',
        'Aracı Kurum Etiketi': 'Etiqueta de la entidad intermediaria',
        'Aracı Kurum Unvanı': 'Razón social de la entidad intermediaria',
        'Aracı Kurum İli': 'Provincia de la entidad intermediaria',
        // Tutarlar
        'Mal Hizmet Toplam Tutarı': 'Importe total de bienes/servicios',
        'Vergiler Hariç Toplam': 'Total sin impuestos',
        'Vergiler Dahil Toplam': 'Total con impuestos',
        'Toplam İskonto': 'Descuento total',
        'Toplam Masraf': 'Total de recargos',
        'Yuvarlama Tutarı': 'Importe de redondeo',
        'Ödenecek Tutar': 'Importe a pagar',
        'Fatura İskonto Oranı': 'Porcentaje de descuento de la factura',
        'Fatura İskonto Tutarı': 'Importe del descuento de la factura',
        'İskonto Açıklaması': 'Descripción del descuento',
        // Vergiler
        'Hesaplanan Vergiler (toplam)': 'Impuestos calculados (total)',
        'Vergi Matrahı': 'Base imponible',
        'Vergi Tutarı': 'Importe del impuesto',
        'Vergi Oranı (%)': 'Tipo impositivo (%)',
        'Vergi Adı': 'Nombre del impuesto',
        'Vergi Kodu': 'Código del impuesto',
        'Muafiyet Sebebi': 'Motivo de exención',
        'Muafiyet Kodu': 'Código de exención',
        'Tevkifat Tutarı': 'Importe de la retención',
        'Tevkifat Oranı (%)': 'Tipo de retención (%)',
        'Tevkifat Kodu': 'Código de retención',
        'Tevkifat Adı': 'Nombre de la retención',
        'Tevkifat Matrahı': 'Base de la retención',
        // e-SMM
        'Serbest Meslek Erbabı Mesleği / Unvanı': 'Profesión / título del profesional',
        'GV Stopajı Matrahı': 'Base de retención del impuesto sobre la renta',
        'GV Stopajı Oranı (%)': 'Tipo de retención del impuesto sobre la renta (%)',
        'KV Stopajı Oranı (%)': 'Tipo de retención del impuesto sobre sociedades (%)',
        'GV Stopajı Tutarı (tevkifat bölümünde)': 'Importe de retención del impuesto sobre la renta (sección de retenciones)',
        'GV Stopajı Oranı (tevkifat bölümünde, %)': 'Tipo de retención del impuesto sobre la renta (sección de retenciones, %)',
        'KDV Tevkifatı Tutarı (9015, eski kullanım)': 'Importe de retención de IVA (9015, uso antiguo)',
        // Döviz
        'Döviz Kuru': 'Tipo de cambio',
        'Kaynak Para Birimi': 'Moneda de origen',
        'Hedef Para Birimi': 'Moneda de destino',
        'Kur Tarihi': 'Fecha del tipo de cambio',
        'Fiyatlandırma Para Birimi': 'Moneda de los precios',
        'Vergi Para Birimi': 'Moneda de los impuestos',
        // Ödeme
        'Ödeme Şekli Kodu': 'Código del medio de pago',
        'Son Ödeme Tarihi': 'Fecha límite de pago',
        'Ödeme Kanalı': 'Canal de pago',
        'IBAN': 'IBAN',
        'Hesap Para Birimi': 'Moneda de la cuenta',
        'Banka / Şube': 'Banco / sucursal',
        'Ödeme Notu': 'Nota de pago',
        'Hesap Açıklaması': 'Descripción de la cuenta',
        'Ödeme Koşulu': 'Condiciones de pago',
        'Gecikme Faizi (%)': 'Interés de demora (%)',
        'Vade Tarihi': 'Fecha de vencimiento',
        // Referanslar
        'İrsaliye No': 'N.º de albarán',
        'İrsaliye Tarihi': 'Fecha del albarán',
        'Sipariş No': 'N.º de pedido',
        'Sipariş Tarihi': 'Fecha del pedido',
        'İade Edilen Fatura No': 'N.º de la factura devuelta',
        'İade Edilen Fatura Tarihi': 'Fecha de la factura devuelta',
        'Ek Belge No': 'N.º de documento adicional',
        'Ek Belge Tarihi': 'Fecha del documento adicional',
        'Ek Belge Türü': 'Tipo de documento adicional',
        'İade Edilen Belge Tipi': 'Tipo del documento devuelto',
        'ESÜ Rapor ID (şarj)': 'ID de informe de la unidad de recarga (ESÜ)',
        'Yatırım Teşvik Belge No': 'N.º de certificado de incentivo a la inversión',
        'Yatırım Teşvik Belge Tarihi': 'Fecha del certificado de incentivo a la inversión',
        'Sözleşme No': 'N.º de contrato',
        // Teslimat
        'Teslim Şartı (Incoterms)': 'Condiciones de entrega (Incoterms)',
        'Gönderim Şekli': 'Modo de transporte',
        'Teslim Tarihi': 'Fecha de entrega',
        'Teslimat Adresi': 'Dirección de entrega',
        'Teslimat İli': 'Provincia de entrega',
        'Teslimat Ülkesi': 'País de entrega',
        'Gönderiyi Taşıyan Unvanı': 'Razón social del transportista',
        'Gönderiyi Taşıyan Adı': 'Nombre del transportista',
        'Gönderiyi Taşıyan Soyadı': 'Apellidos del transportista',
        'Gönderiyi Taşıyan VKN/TCKN': 'N.º fiscal del transportista (VKN/TCKN)',
        'Gönderim Tarihi': 'Fecha de envío',
        'Gönderim Saati': 'Hora de envío',
        // Satır
        'Ürün / Hizmet Adı': 'Nombre del producto / servicio',
        'Ürün Açıklaması': 'Descripción del producto',
        'Satıcı Ürün Kodu': 'Código de artículo del vendedor',
        'Alıcı Ürün Kodu': 'Código de artículo del comprador',
        'Marka': 'Marca',
        'Model': 'Modelo',
        'Miktar': 'Cantidad',
        'Birim': 'Unidad',
        'Birim Fiyat': 'Precio unitario',
        'Satır İskonto Oranı': 'Porcentaje de descuento de la línea',
        'Satır İskonto Tutarı': 'Importe del descuento de la línea',
        'Satır Tutarı': 'Importe de la línea',
        'Satır Vergi Oranı (%)': 'Tipo impositivo de la línea (%)',
        'Satır Vergi Tutarı': 'Importe del impuesto de la línea',
        'GTİP No': 'Código arancelario (GTİP)',
        'Satır Notu': 'Nota de la línea',
        'Satır Muafiyet Kodu': 'Código de exención de la línea',
        'Satır Muafiyet Sebebi': 'Motivo de exención de la línea',
        'Satır Tevkifat Tutarı': 'Importe de la retención de la línea',
        'Satır Tevkifat Oranı (%)': 'Tipo de retención de la línea (%)',
        'Satır Tevkifat Kodu': 'Código de retención de la línea',
        'Künye No (HKS)': 'N.º de etiqueta del producto (HKS)',
        'Etiket No (IDIS)': 'N.º de etiqueta (IDIS)',
        'İlaç Seri No': 'N.º de serie del medicamento',
        'Tıbbi Cihaz Seri No': 'N.º de serie del producto sanitario',
        'Diğer Ürün (İlaç/Tıbbi Cihaz)': 'Otro producto (medicamento/producto sanitario)',
        'Telefon IMEI (Teknoloji Destek)': 'IMEI del teléfono (ayuda tecnológica)',
        'Tablet PC (Teknoloji Destek)': 'Tableta (ayuda tecnológica)',
        'Harcama Tipi (Yatırım Teşvik)': 'Tipo de gasto (incentivo a la inversión)',
        'Makine Teçhizat Sıra No (YTB)': 'N.º de orden de maquinaria/equipo (YTB)',
        'Seri No / Makine ID': 'N.º de serie / ID de máquina',
        'Satır Teslim Şartı': 'Condiciones de entrega de la línea',
        'Satır Gönderim Şekli': 'Modo de transporte de la línea',
        'Kap Cinsi': 'Tipo de bulto',
        'Kap No': 'N.º de bulto',
        'Kap Adedi': 'Número de bultos',
        'Satıcı DİİB Satır Kodu (İhraç Kayıtlı)': 'Código de línea de perfeccionamiento activo del vendedor (DİİB, exportación registrada)',
        'Alıcı DİİB Satır Kodu (İhraç Kayıtlı)': 'Código de línea de perfeccionamiento activo del comprador (DİİB, exportación registrada)',
        'Satır Teslim Adresi': 'Dirección de entrega de la línea',
        'Satır Teslim İli': 'Provincia de entrega de la línea',
        // İrsaliye
        'İrsaliye Saati': 'Hora del albarán',
        'İrsaliye Tipi': 'Tipo de albarán',
        'İrsaliye Notu': 'Observaciones del albarán',
        'Ek Belge No (matbu irsaliye / fatura)': 'N.º de documento adicional (albarán / factura impresos)',
        'Ek Belge Tür Kodu': 'Código de tipo de documento adicional',
        'Ek Belge Açıklaması': 'Descripción del documento adicional',
        'Malın Çıktığı Yer Kodu': 'Código del lugar de expedición',
        'Malın Çıktığı Yer Adresi': 'Dirección del lugar de expedición',
        'Malın Çıktığı Yer İlçe': 'Distrito del lugar de expedición',
        'Malın Çıktığı Yer İl': 'Provincia del lugar de expedición',
        'Kargo / Sevkiyat No': 'N.º de envío / expedición',
        'Toplam Mal Değeri': 'Valor total de la mercancía',
        'Fiili Sevk Tarihi': 'Fecha real de expedición',
        'Fiili Sevk Saati': 'Hora real de expedición',
        'Araç Plakası': 'Matrícula del vehículo',
        'Araç Plaka Türü (PLAKA/YABANCIPLAKA)': 'Tipo de matrícula del vehículo (PLAKA/YABANCIPLAKA)',
        'Dorse Plakası': 'Matrícula del remolque',
        'Dorse Türü (DORSE/DORSEPLAKA/YABANCI...)': 'Tipo de remolque (DORSE/DORSEPLAKA/YABANCI...)',
        'Sürücü Adı': 'Nombre del conductor',
        'Sürücü Soyadı': 'Apellidos del conductor',
        'Sürücü TCKN': 'N.º de identidad del conductor (TCKN)',
        'Sürücü Unvanı / Görevi': 'Cargo / función del conductor',
        'Taşıyıcı Unvanı': 'Razón social del transportista',
        'Taşıyıcı VKN': 'N.º fiscal del transportista (VKN)',
        'Taşıyıcı İlçe': 'Distrito del transportista',
        'Taşıyıcı İl': 'Provincia del transportista',
        'Teslimat Kapı No': 'N.º de portal de entrega',
        'Teslimat İlçesi': 'Distrito de entrega',
        'Teslimat Posta Kodu': 'Código postal de entrega',
        'Satır No': 'N.º de línea',
        'Gönderilen Miktar': 'Cantidad enviada',
        'Eksik Miktar': 'Cantidad pendiente',
        'Eksik Miktar Nedeni': 'Motivo de la cantidad pendiente',
        'Sipariş Satır No': 'N.º de línea del pedido',
        // İrsaliye yanıtı
        'Yanıt No': 'N.º de respuesta',
        'Yanıt Tarihi': 'Fecha de respuesta',
        'Yanıt Saati': 'Hora de respuesta',
        'Yanıt Tipi': 'Tipo de respuesta',
        'Yanıt Notu': 'Nota de respuesta',
        'Fiili Teslim Tarihi': 'Fecha real de entrega',
        'Fiili Teslim Saati': 'Hora real de entrega',
        'Ürün Adı': 'Nombre del producto',
        'Teslim Alınan Miktar': 'Cantidad recibida',
        'Reddedilen Miktar': 'Cantidad rechazada',
        'Red Nedeni': 'Motivo del rechazo',
        'Fazla Miktar': 'Cantidad en exceso',
        'Zamanlama Şikayeti (geç teslim)': 'Reclamación por plazo (entrega tardía)',
        'İrsaliye Satır No': 'N.º de línea del albarán',
        // Müstahsil / CreditNote
        'Makbuz No': 'N.º de recibo',
        'Düzenleme Tarihi': 'Fecha de emisión',
        'Düzenleme Zamanı': 'Hora de emisión',
        'Belge Tipi (CreditNoteTypeCode)': 'Tipo de documento (CreditNoteTypeCode)',
        'Özelleştirme No': 'ID de personalización',
        'Asıl / Suret (CopyIndicator)': 'Original / copia (CopyIndicator)',
        'Makbuz Notu': 'Nota del recibo',
        'SMS Operatörü (uygulama adı)': 'Operador SMS (nombre de la aplicación)',
        'SMS Operatörü VKN': 'N.º fiscal del operador SMS (VKN)',
        'Mal Hizmet Toplam Tutarı (brüt)': 'Importe total de bienes/servicios (bruto)',
        'Ödenecek Tutar (net)': 'Importe a pagar (neto)',
        'Toplam Kesinti': 'Total de deducciones',
        'Kesinti Adı': 'Nombre de la deducción',
        'Kesinti Kodu': 'Código de la deducción',
        'Kesinti Tutarı': 'Importe de la deducción',
        'Kesinti Oranı (%)': 'Tipo de la deducción (%)',
        'Malın Cinsi': 'Tipo de mercancía',
        'Mal Açıklaması': 'Descripción de la mercancía',
        'Tutar (Bedel)': 'Importe (precio)',
        'Satır Kesinti Toplamı': 'Total de deducciones de la línea',
        // Gider pusulası
        'İade Edilen Belge No': 'N.º del documento devuelto',
        'İade Edilen Belge Türü (EARSIV_FATURA / SATIS_FISI / BELGESIZ)': 'Tipo del documento devuelto (EARSIV_FATURA / SATIS_FISI / BELGESIZ)',
        'İade Edilen Belge Tarihi': 'Fecha del documento devuelto',
        'Kod Türü (SMS / IADEKODU)': 'Tipo de código (SMS / IADEKODU)',
        'SMS / İade Kodu': 'Código SMS / de devolución',
        'Kodun Gönderildiği Telefon': 'Teléfono al que se envió el código',
        'İade Kodu Uygulaması': 'Aplicación del código de devolución',
        'İade Kodu Uygulaması VKN': 'N.º fiscal de la aplicación del código de devolución (VKN)',
        'Adına İade Yapılan Adı': 'Nombre del beneficiario de la devolución',
        'Adına İade Yapılan Soyadı': 'Apellidos del beneficiario de la devolución',
        'Adına İade Yapılan Unvanı': 'Razón social del beneficiario de la devolución',
        'Adına İade Yapılan TCKN': 'N.º de identidad del beneficiario de la devolución (TCKN)',
        'Adına İade Yapılan SMS / İade Kodu': 'Código SMS / de devolución del beneficiario',
        'Adına İade Yapılan Telefon': 'Teléfono del beneficiario de la devolución',
        'Kargo Firması Unvanı': 'Razón social de la empresa de mensajería',
        'Kargo Firması VKN': 'N.º fiscal de la empresa de mensajería (VKN)',
        'Kargo Yetki Belgesi No': 'N.º de licencia de mensajería',
        'Kargo Firması İl': 'Provincia de la empresa de mensajería',
        // Döviz / kıymetli maden
        'Yetkili Müessese Şube No (SUBENO)': 'N.º de sucursal de la entidad autorizada (SUBENO)',
        'Müşteri Türü (MUSTERITURU)': 'Tipo de cliente (MUSTERITURU)',
        'Müşteri Pasaport No': 'N.º de pasaporte del cliente',
        'Müşteri Uyruğu': 'Nacionalidad del cliente',
        'Döviz / Maden Kodu (kaynak)': 'Código de divisa / metal (origen)',
        'Karşılık Para Birimi (hedef)': 'Moneda de contravalor (destino)',
        'Uygulanan Kur / Birim Fiyat': 'Tipo aplicado / precio unitario',
        'Ödeme Şekli Kodu (10 / 55 / 46 / 68)': 'Código del medio de pago (10 / 55 / 46 / 68)',
        'Müşteri Hesap No': 'N.º de cuenta del cliente',
        'Müessese Hesap No (IBAN)': 'N.º de cuenta de la entidad (IBAN)',
        'İstatistik No': 'N.º estadístico',
        'Dövizin Geldiği Ülke': 'País de procedencia de la divisa',
        'Dövizin Geliş Nedeni': 'Motivo de entrada de la divisa',
        'Gümrük Beyanname No': 'N.º de declaración aduanera',
        'Gümrük Beyanname Tarihi': 'Fecha de la declaración aduanera',
        'Döviz Beyan Tutanağı Sayısı': 'N.º de acta de declaración de divisas',
        'Gümrük Teyit Yazısı Sayısı': 'N.º de escrito de confirmación aduanera',
        'İlgili Fatura No': 'N.º de factura relacionada',
        'Kur: Kaynak Para Birimi': 'Cambio: moneda de origen',
        'Kur: Hedef Para Birimi': 'Cambio: moneda de destino',
        'Kur Oranı': 'Tipo de cambio',
        // Dekont
        'Şube Kodu': 'Código de sucursal',
        'Şube Adı': 'Nombre de la sucursal',
        'İşlemi Yapan Personel Adı': 'Nombre del empleado que realiza la operación',
        'İşlemi Yapan Personel Soyadı': 'Apellidos del empleado que realiza la operación',
        'İşlemi Yapan Personel Sicil No': 'N.º de empleado que realiza la operación',
        'Müşteri No': 'N.º de cliente',
        'Müşteri IBAN': 'IBAN del cliente',
        'Abone No': 'N.º de abonado',
        'İşlemi Yapan (Gönderen) Unvanı': 'Razón social del ordenante (remitente)',
        'İşlemi Yapan (Gönderen) Kimlik No': 'N.º de identificación del ordenante (remitente)',
        'Referans Belge No': 'N.º del documento de referencia',
        'Referans Belge Tarihi': 'Fecha del documento de referencia',
        'Referans Belge Kodu': 'Código del documento de referencia',
        'Referans Belge Açıklaması': 'Descripción del documento de referencia',
        'Tahsil Alındısı No (BELGENO)': 'N.º de recibo de cobro (BELGENO)',
        'Ek Belge Açıklaması (VTA / GVTA vb.)': 'Descripción del documento adicional (VTA / GVTA, etc.)',
        'İşlem Referans No': 'N.º de referencia de la operación',
        'İşlem Kanalı': 'Canal de la operación',
        'Banka Provizyon No': 'N.º de autorización bancaria',
        'Vergilendirme Dönemi': 'Período impositivo',
        'Tahsil Eden Vergi Dairesi': 'Oficina tributaria recaudadora',
        'Tahsil Eden Vergi Dairesi Kodu': 'Código de la oficina tributaria recaudadora',
        'Gümrük Müdürlüğü Kodu': 'Código de la aduana',
        'Gümrük Müdürlüğü Adı': 'Nombre de la aduana',
        'Gümrük Saymanlığı Adı': 'Nombre de la oficina contable de aduanas',
        'Gümrük Saymanlığı Kodu / VKN': 'Código / n.º fiscal (VKN) de la oficina contable de aduanas',
        'Saymanlık Banka Şube Kodu': 'Código de la sucursal bancaria de la oficina contable',
        'Saymanlık Banka Şube Adı': 'Nombre de la sucursal bancaria de la oficina contable',
        'Ödeme Kanalı Kodu': 'Código del canal de pago',
        'Sanal POS Kodu': 'Código de TPV virtual',
        'İşlem Tarihi': 'Fecha de la operación',
        'İşlem Saati': 'Hora de la operación',
        'Valör Tarihi': 'Fecha valor',
        'Valör Saati': 'Hora valor',
        'İşlem Kodu (SerialID)': 'Código de la operación (SerialID)',
        'İşlem Değeri (açıklama)': 'Valor de la operación (descripción)',
        'Satır Masraf / Kesinti Nedeni': 'Motivo del gasto / deducción de la línea',
        'Satır Masraf / Kesinti Tutarı': 'Importe del gasto / deducción de la línea',
        // Sigorta komisyon
        'Komisyon Dönemi Başlangıcı': 'Inicio del período de comisión',
        'Komisyon Dönemi Bitişi': 'Fin del período de comisión',
        'Komisyon Dönemi Açıklaması': 'Descripción del período de comisión',
        'İstihsal Komisyonu Toplamı': 'Total de comisiones de producción',
        'İptal Komisyonu Toplamı': 'Total de comisiones de anulación',
        'Satır İstihsal Komisyonu': 'Comisión de producción de la línea',
        'Satır İptal Komisyonu': 'Comisión de anulación de la línea',
        'Satır Komisyon Nedeni': 'Motivo de la comisión de la línea',
        'Branş / Sigorta Ürünü': 'Ramo / producto de seguro',
        // e-Bilet
        'Gönderen VKN': 'N.º fiscal del remitente (VKN)',
        'Gönderen TCKN': 'N.º de identidad del remitente (TCKN)',
        'Rapor Dönemi Başlangıcı': 'Inicio del período del informe',
        'Rapor Dönemi Bitişi': 'Fin del período del informe',
        'Rapor Versiyonu': 'Versión del informe',
        'Rapor UUID': 'UUID del informe',
        'İmza Zamanı': 'Hora de la firma',
        'Bilet No': 'N.º de billete',
        'Belge Tipi (SATIS / IADE)': 'Tipo de documento (SATIS / IADE)',
        'Özet Değer (SHA-256)': 'Valor hash (SHA-256)',
        'Düzenlenme Tarihi': 'Fecha de emisión',
        'Sefer Zamanı': 'Hora de salida',
        'Etkinlik Zamanı': 'Fecha y hora del evento',
        'Ödeme Şekli': 'Forma de pago',
        'Bilet Tutarı': 'Importe del billete',
        'KDV Tutarı': 'Importe del IVA',
        'e-Bilet URL': 'URL del billete electrónico',
        'Etkinlik Yeri İl Kodu': 'Código de provincia del recinto',
        'Etkinlik Yeri Belediyesi': 'Municipio del recinto',
        'Etkinlik Yeri Açıklaması': 'Descripción del recinto',
        'Organizatör VKN/TCKN': 'N.º fiscal del organizador (VKN/TCKN)',
        'Hizmetin Nevi': 'Tipo de servicio',
        'Hizmet Açıklaması': 'Descripción del servicio',
        'Gider Gösteren VKN': 'N.º fiscal del declarante del gasto (VKN)',
        'Gider Gösteren TCKN': 'N.º de identidad del declarante del gasto (TCKN)',
        'Referans Açıklaması': 'Descripción de la referencia',
        'Referans No (asıl bilet)': 'N.º de referencia (billete original)',
        'Diğer Vergi Kodu': 'Código de otro impuesto',
        'Diğer Vergi Adı': 'Nombre de otro impuesto',
        'Diğer Vergi Oranı (%)': 'Tipo de otro impuesto (%)',
        'Diğer Vergi Tutarı': 'Importe de otro impuesto',
        'Eğlence Vergisi Tutarı (9142)': 'Importe del impuesto sobre espectáculos (9142)',
        'İptal Edilen Bilet No': 'N.º del billete anulado',
        'İptal Zamanı': 'Hora de anulación',
        'İptal Tutarı': 'Importe anulado',
        'İptal KDV Tutarı': 'IVA anulado',
        // e-Yolcu listesi
        'Yolcu Listesi No': 'N.º de lista de pasajeros',
        'Liste Özet Değeri': 'Valor hash de la lista',
        'Hareket Zamanı': 'Hora de salida',
        'Hareket Noktası': 'Punto de salida',
        'Sefer Numarası': 'Número de trayecto',
        'Sefer Tarihi': 'Fecha del trayecto',
        'Toplam Hasılat (KDV dahil)': 'Ingresos totales (IVA incluido)',
        'Taşıtı İşleten VKN': 'N.º fiscal del operador del vehículo (VKN)',
        'Taşıtı İşleten TCKN': 'N.º de identidad del operador del vehículo (TCKN)',
        'Komisyon Tutarı': 'Importe de la comisión',
        'Komisyon KDV Tutarı': 'IVA de la comisión',
        'Koltuk No': 'N.º de asiento',
        'Yolcu Adı Soyadı': 'Nombre y apellidos del pasajero',
        'Yolcu TCKN / YKN': 'N.º de identidad / de extranjero del pasajero (TCKN / YKN)',
        'Yolcu Pasaport No': 'N.º de pasaporte del pasajero',
    },
};

export default es;
