import type { GibDict } from './types';

const fr: GibDict = {
    tpl: {
        party: '{{party}} – {{field}}',
        line: '{{label}} (ligne)',
        amount: 'Montant – {{name}}',
        base: 'Base imposable – {{name}}',
        rate: 'Taux – {{name}} (%)',
    },
    parties: {
        'Sipariş Veren': 'Donneur d’ordre',
        'Asıl Alıcı': 'Acheteur effectif',
        'Teslim Alan': 'Destinataire',
        'Düzenleyen': 'Émetteur',
        'Gönderen': 'Expéditeur',
        'Satıcı': 'Vendeur',
        'Alıcı': 'Acheteur',
        'Çiftçi': 'Agriculteur',
    },
    partyFields: {
        'Unvanı': 'Raison sociale',
        'Resmi Unvanı': 'Dénomination légale',
        'Adı (şahıs)': 'Prénom (personne physique)',
        'Soyadı (şahıs)': 'Nom (personne physique)',
        'Kimlik No (VKN/TCKN vb.)': 'N° d’identification (VKN/TCKN, etc.)',
        'Kimlik Türü': 'Type d’identifiant',
        'VKN': 'N° fiscal (VKN)',
        'TCKN': 'N° d’identité national (TCKN)',
        'MERSİS No': 'N° MERSİS',
        'Ticaret Sicil No': 'N° au registre du commerce',
        'Vergi Dairesi': 'Centre des impôts',
        'Cadde/Sokak': 'Rue / voie',
        'Bina Adı': 'Nom du bâtiment',
        'Kapı No': 'N° de voie',
        'İlçe': 'District',
        'İl': 'Province',
        'İli': 'Province',
        'Bölge / Semt': 'Région / quartier',
        'Posta Kodu': 'Code postal',
        'Ülke': 'Pays',
        'Ülkesi': 'Pays',
        'Telefon': 'Téléphone',
        'Faks': 'Fax',
        'E-posta': 'E-mail',
        'Web Sitesi': 'Site web',
        'İlgili Kişi': 'Personne à contacter',
        'Mahalle': 'Quartier',
        'Daire / Oda No': 'N° d’appartement / de bureau',
        'Şube No': 'N° de succursale',
        'EPDK No': 'N° de licence EPDK',
        'Sevkiyat No (IDIS)': 'N° d’expédition (IDIS)',
        'Müşteri No': 'N° client',
        'Abone No': 'N° d’abonné',
        'Tesisat No': 'N° d’installation',
        'Sayaç No': 'N° de compteur',
        'Hasta No': 'N° de patient',
        'Dosya No': 'N° de dossier',
        'Araç Plakası (şarj)': 'Immatriculation du véhicule (recharge)',
        'Araç Kimlik No (şarj)': 'Identifiant du véhicule (recharge)',
        'SMS Kodu': 'Code SMS',
        'SMS Telefonu': 'Téléphone SMS',
        'TCKN / YKN': 'N° d’identité national / étranger (TCKN / YKN)',
    },
    taxes: {
        'KDV': 'TVA',
        'Konaklama Vergisi': 'Taxe d’hébergement',
        'ÖTV 1. Liste (petrol/doğalgaz)': 'Accise ÖTV liste I (pétrole/gaz naturel)',
        'ÖTV 2. Liste (motorlu taşıt)': 'Accise ÖTV liste II (véhicules à moteur)',
        'ÖTV 3. Liste': 'Accise ÖTV liste III',
        'ÖTV 3A (alkollü içecek)': 'Accise ÖTV III-A (boissons alcoolisées)',
        'ÖTV 3B (tütün)': 'Accise ÖTV III-B (tabac)',
        'ÖTV 3C (kolalı gazoz)': 'Accise ÖTV III-C (boissons au cola)',
        'ÖTV 4. Liste (dayanıklı tüketim)': 'Accise ÖTV liste IV (biens durables)',
        'Petrol-Doğalgaz ÖTV Tevkifatı': 'Retenue à la source d’accise ÖTV (pétrole/gaz naturel)',
        'Damga Vergisi': 'Droit de timbre',
        '5035 SK Damga Vergisi': 'Droit de timbre (loi 5035)',
        'Özel İletişim Vergisi': 'Taxe spéciale sur les communications',
        '5035 SK Özel İletişim Vergisi': 'Taxe spéciale sur les communications (loi 5035)',
        'Elektrik ve Havagazı Tüketim Vergisi': 'Taxe sur la consommation d’électricité et de gaz',
        'Elektrik Tüketim Vergisi': 'Taxe sur la consommation d’électricité',
        'TRT Payı': 'Redevance TRT',
        'Enerji Fonu': 'Fonds de l’énergie',
        'Borsa Tescil Ücreti': 'Frais d’enregistrement en bourse',
        'Telsiz Kullanım Ücreti': 'Redevance d’utilisation radio',
        'Telsiz Ruhsat Ücreti': 'Redevance de licence radio',
        'Çevre Temizlik Vergisi': 'Taxe de nettoyage environnemental',
        'Belediye Hal Rüsumu': 'Droit de halle municipal',
        'Mera Fonu': 'Fonds des pâturages',
        'Gelir Vergisi Stopajı': 'Retenue à la source de l’impôt sur le revenu',
        'Kurumlar Vergisi Stopajı': 'Retenue à la source de l’impôt sur les sociétés',
        'Banka Muameleleri Vergisi': 'Taxe sur les opérations bancaires',
        'Sigorta Muameleleri Vergisi': 'Taxe sur les opérations d’assurance',
        '4961 Banka Sigorta Muameleleri Vergisi': 'Taxe sur les opérations bancaires et d’assurance (loi 4961)',
        'KKDF Kesintisi': 'Prélèvement KKDF',
        'GV Stopajı': 'Retenue à la source de l’impôt sur le revenu',
        'SGK Prim Kesintisi': 'Retenue de cotisations sociales (SGK)',
        'BSMV': 'Taxe sur les opérations bancaires et d’assurance (BSMV)',
    },
    labels: {
        // Kategoriler
        'Belge Bilgileri': 'Informations du document',
        'Satıcı': 'Vendeur',
        'Alıcı': 'Acheteur',
        'Asıl Alıcı (İhracat / Yolcu Beraber)': 'Acheteur effectif (export / détaxe voyageur)',
        'Tutarlar': 'Montants',
        'Vergiler': 'Taxes',
        'Vergi Türleri': 'Types de taxes',
        'Serbest Meslek Makbuzu (e-SMM)': 'Reçu de profession libérale (e-SMM)',
        'Döviz / Kur': 'Devise / taux de change',
        'Ödeme': 'Paiement',
        'Referanslar': 'Références',
        'Teslimat / İhracat': 'Livraison / export',
        'İnternet Satışı (e-Arşiv)': 'Vente en ligne (e-Archive)',
        'Satır (Kalem)': 'Lignes (articles)',
        'Satır · Özel Senaryolar': 'Ligne · scénarios particuliers',
        'Ek Belge / Matbu İrsaliye': 'Document annexe / bon de livraison imprimé',
        'Gönderen': 'Expéditeur',
        'Satıcı (Zincir Teslim)': 'Vendeur (livraison en chaîne)',
        'Alıcı / Sipariş Veren (Zincir Teslim)': 'Acheteur / donneur d’ordre (livraison en chaîne)',
        'Asıl Alıcı (Zincir Teslim)': 'Acheteur effectif (livraison en chaîne)',
        'Sevkiyat': 'Expédition',
        'Yanıtlanan İrsaliye': 'Bon de livraison concerné par la réponse',
        'Teslim Alan (Yanıtlayan)': 'Destinataire (répondant)',
        'Teslimat': 'Livraison',
        'Makbuzu Düzenleyen (Malı Satın Alan)': 'Émetteur du reçu (acheteur des marchandises)',
        'Üretici / Çiftçi (Malı Satan)': 'Producteur / agriculteur (vendeur des marchandises)',
        'Kesintiler (Vergi ve Fonlar)': 'Retenues (taxes et fonds)',
        'Satır (Mal Bilgileri)': 'Lignes (marchandises)',
        'Vergiler (KDV / BSMV)': 'Taxes (TVA / BSMV)',
        'Gider Pusulası': 'Bordereau de dépenses',
        'Döviz / Kıymetli Maden': 'Devises / métaux précieux',
        'Döviz Kuru (USD / TL Karşılığı)': 'Taux de change (contre-valeur USD / TRY)',
        'Dekont': 'Avis d’opération bancaire',
        'Sigorta Komisyon': 'Commission d’assurance',
        'Rapor Bilgileri': 'Informations du rapport',
        'Bilet': 'Billet',
        'Etkinlik Yeri / Organizatör': 'Lieu de l’événement / organisateur',
        'Hizmet / Gider Gösteren': 'Prestation / déclarant de la dépense',
        'Diğer Vergiler': 'Autres taxes',
        'İptal Edilen Bilet': 'Billet annulé',
        'Sefer': 'Trajet',
        'Taşıtı İşleten': 'Exploitant du véhicule',
        'Koltuk / Yolcu': 'Siège / passager',

        // Fatura — belge
        'Fatura No': 'N° de facture',
        'Fatura Tarihi': 'Date de facture',
        'Fatura Saati': 'Heure de facture',
        'Fatura Tipi': 'Type de facture',
        'Senaryo (Profil)': 'Scénario (profil)',
        'ETTN (UUID)': 'ETTN (UUID)',
        'Para Birimi': 'Devise',
        'Fatura Notu': 'Note de facture',
        'Satır Sayısı': 'Nombre de lignes',
        'Fatura Dönemi Başlangıcı': 'Début de la période de facturation',
        'Fatura Dönemi Başlangıç Saati': 'Heure de début de la période de facturation',
        'Fatura Dönemi Bitişi': 'Fin de la période de facturation',
        'Fatura Dönemi Bitiş Saati': 'Heure de fin de la période de facturation',
        'Fatura Dönemi Açıklaması': 'Description de la période de facturation',
        'Muhasebe Maliyet Kodu (SGK)': 'Code analytique comptable (SGK)',
        // Asıl alıcı / turist
        'Alıcı Tipi (EXPORT / TAXFREE)': 'Type d’acheteur (EXPORT / TAXFREE)',
        'Asıl Alıcı TCKN': 'Acheteur effectif – N° d’identité national (TCKN)',
        'Hastane Protokol No': 'N° de protocole hospitalier',
        'Turist Adı': 'Prénom du touriste',
        'Turist Soyadı': 'Nom du touriste',
        'Turist Uyruğu': 'Nationalité du touriste',
        'Pasaport No': 'N° de passeport',
        'Pasaport Tarihi': 'Date du passeport',
        'Turist Banka Hesap No': 'N° de compte bancaire du touriste',
        'Turist Bankası': 'Banque du touriste',
        'Asıl Alıcı İli': 'Acheteur effectif – Province',
        'Asıl Alıcı Ülkesi': 'Acheteur effectif – Pays',
        'Aracı Kurum VKN': 'Intermédiaire – N° fiscal (VKN)',
        'Aracı Kurum Etiketi': 'Intermédiaire – Étiquette',
        'Aracı Kurum Unvanı': 'Intermédiaire – Raison sociale',
        'Aracı Kurum İli': 'Intermédiaire – Province',
        // Tutarlar
        'Mal Hizmet Toplam Tutarı': 'Montant total des biens/services',
        'Vergiler Hariç Toplam': 'Total hors taxes',
        'Vergiler Dahil Toplam': 'Total toutes taxes comprises',
        'Toplam İskonto': 'Total des remises',
        'Toplam Masraf': 'Total des frais',
        'Yuvarlama Tutarı': 'Montant d’arrondi',
        'Ödenecek Tutar': 'Montant à payer',
        'Fatura İskonto Oranı': 'Taux de remise de la facture',
        'Fatura İskonto Tutarı': 'Montant de remise de la facture',
        'İskonto Açıklaması': 'Motif de la remise',
        // Vergiler
        'Hesaplanan Vergiler (toplam)': 'Taxes calculées (total)',
        'Vergi Matrahı': 'Base imposable',
        'Vergi Tutarı': 'Montant de la taxe',
        'Vergi Oranı (%)': 'Taux de taxe (%)',
        'Vergi Adı': 'Nom de la taxe',
        'Vergi Kodu': 'Code de la taxe',
        'Muafiyet Sebebi': 'Motif d’exonération',
        'Muafiyet Kodu': 'Code d’exonération',
        'Tevkifat Tutarı': 'Montant de la retenue à la source',
        'Tevkifat Oranı (%)': 'Taux de retenue à la source (%)',
        'Tevkifat Kodu': 'Code de retenue à la source',
        'Tevkifat Adı': 'Libellé de la retenue à la source',
        'Tevkifat Matrahı': 'Base de la retenue à la source',
        // e-SMM
        'Serbest Meslek Erbabı Mesleği / Unvanı': 'Profession / titre du professionnel libéral',
        'GV Stopajı Matrahı': 'Base de la retenue d’impôt sur le revenu',
        'GV Stopajı Oranı (%)': 'Taux de retenue d’impôt sur le revenu (%)',
        'KV Stopajı Oranı (%)': 'Taux de retenue d’impôt sur les sociétés (%)',
        'GV Stopajı Tutarı (tevkifat bölümünde)': 'Montant de la retenue d’impôt sur le revenu (section retenues)',
        'GV Stopajı Oranı (tevkifat bölümünde, %)': 'Taux de retenue d’impôt sur le revenu (section retenues, %)',
        'KDV Tevkifatı Tutarı (9015, eski kullanım)': 'Montant de TVA retenue à la source (9015, ancien usage)',
        // Döviz
        'Döviz Kuru': 'Taux de change',
        'Kaynak Para Birimi': 'Devise source',
        'Hedef Para Birimi': 'Devise cible',
        'Kur Tarihi': 'Date du taux de change',
        'Fiyatlandırma Para Birimi': 'Devise de tarification',
        'Vergi Para Birimi': 'Devise des taxes',
        // Ödeme
        'Ödeme Şekli Kodu': 'Code du moyen de paiement',
        'Son Ödeme Tarihi': 'Date limite de paiement',
        'Ödeme Kanalı': 'Canal de paiement',
        'IBAN': 'IBAN',
        'Hesap Para Birimi': 'Devise du compte',
        'Banka / Şube': 'Banque / agence',
        'Ödeme Notu': 'Note de paiement',
        'Hesap Açıklaması': 'Libellé du compte',
        'Ödeme Koşulu': 'Conditions de paiement',
        'Gecikme Faizi (%)': 'Intérêts de retard (%)',
        'Vade Tarihi': 'Date d’échéance',
        // Referanslar
        'İrsaliye No': 'N° de bon de livraison',
        'İrsaliye Tarihi': 'Date du bon de livraison',
        'Sipariş No': 'N° de commande',
        'Sipariş Tarihi': 'Date de commande',
        'İade Edilen Fatura No': 'N° de la facture retournée',
        'İade Edilen Fatura Tarihi': 'Date de la facture retournée',
        'Ek Belge No': 'N° de document annexe',
        'Ek Belge Tarihi': 'Date du document annexe',
        'Ek Belge Türü': 'Type de document annexe',
        'İade Edilen Belge Tipi': 'Type de document retourné',
        'ESÜ Rapor ID (şarj)': 'ID du rapport de borne de recharge (ESÜ)',
        'Yatırım Teşvik Belge No': 'N° de certificat d’incitation à l’investissement',
        'Yatırım Teşvik Belge Tarihi': 'Date du certificat d’incitation à l’investissement',
        'Sözleşme No': 'N° de contrat',
        // Teslimat
        'Teslim Şartı (Incoterms)': 'Conditions de livraison (Incoterms)',
        'Gönderim Şekli': 'Mode de transport',
        'Teslim Tarihi': 'Date de livraison',
        'Teslimat Adresi': 'Adresse de livraison',
        'Teslimat İli': 'Province de livraison',
        'Teslimat Ülkesi': 'Pays de livraison',
        'Gönderiyi Taşıyan Unvanı': 'Raison sociale du transporteur',
        'Gönderiyi Taşıyan Adı': 'Prénom du transporteur',
        'Gönderiyi Taşıyan Soyadı': 'Nom du transporteur',
        'Gönderiyi Taşıyan VKN/TCKN': 'Identifiant fiscal du transporteur (VKN/TCKN)',
        'Gönderim Tarihi': 'Date d’expédition',
        'Gönderim Saati': 'Heure d’expédition',
        // Satır
        'Ürün / Hizmet Adı': 'Désignation du produit / service',
        'Ürün Açıklaması': 'Description du produit',
        'Satıcı Ürün Kodu': 'Référence article vendeur',
        'Alıcı Ürün Kodu': 'Référence article acheteur',
        'Marka': 'Marque',
        'Model': 'Modèle',
        'Miktar': 'Quantité',
        'Birim': 'Unité',
        'Birim Fiyat': 'Prix unitaire',
        'Satır İskonto Oranı': 'Taux de remise de la ligne',
        'Satır İskonto Tutarı': 'Montant de remise de la ligne',
        'Satır Tutarı': 'Montant de la ligne',
        'Satır Vergi Oranı (%)': 'Taux de taxe de la ligne (%)',
        'Satır Vergi Tutarı': 'Montant de taxe de la ligne',
        'GTİP No': 'Code SH (GTİP)',
        'Satır Notu': 'Note de ligne',
        'Satır Muafiyet Kodu': 'Code d’exonération de la ligne',
        'Satır Muafiyet Sebebi': 'Motif d’exonération de la ligne',
        'Satır Tevkifat Tutarı': 'Montant de retenue à la source de la ligne',
        'Satır Tevkifat Oranı (%)': 'Taux de retenue à la source de la ligne (%)',
        'Satır Tevkifat Kodu': 'Code de retenue à la source de la ligne',
        'Künye No (HKS)': 'N° d’étiquette produit (HKS)',
        'Etiket No (IDIS)': 'N° d’étiquette (IDIS)',
        'İlaç Seri No': 'N° de série du médicament',
        'Tıbbi Cihaz Seri No': 'N° de série du dispositif médical',
        'Diğer Ürün (İlaç/Tıbbi Cihaz)': 'Autre produit (médicament/dispositif médical)',
        'Telefon IMEI (Teknoloji Destek)': 'IMEI du téléphone (aide technologique)',
        'Tablet PC (Teknoloji Destek)': 'Tablette PC (aide technologique)',
        'Harcama Tipi (Yatırım Teşvik)': 'Type de dépense (incitation à l’investissement)',
        'Makine Teçhizat Sıra No (YTB)': 'N° d’ordre machine/équipement (YTB)',
        'Seri No / Makine ID': 'N° de série / ID machine',
        'Satır Teslim Şartı': 'Conditions de livraison de la ligne',
        'Satır Gönderim Şekli': 'Mode de transport de la ligne',
        'Kap Cinsi': 'Type d’emballage',
        'Kap No': 'N° de colis',
        'Kap Adedi': 'Nombre de colis',
        'Satıcı DİİB Satır Kodu (İhraç Kayıtlı)': 'Code de ligne de perfectionnement actif (DİİB) du vendeur, vente en vue de l’export',
        'Alıcı DİİB Satır Kodu (İhraç Kayıtlı)': 'Code de ligne de perfectionnement actif (DİİB) de l’acheteur, vente en vue de l’export',
        'Satır Teslim Adresi': 'Adresse de livraison de la ligne',
        'Satır Teslim İli': 'Province de livraison de la ligne',
        // İrsaliye
        'İrsaliye Saati': 'Heure du bon de livraison',
        'İrsaliye Tipi': 'Type de bon de livraison',
        'İrsaliye Notu': 'Note du bon de livraison',
        'Ek Belge No (matbu irsaliye / fatura)': 'N° de document annexe (bon de livraison / facture imprimé)',
        'Ek Belge Tür Kodu': 'Code du type de document annexe',
        'Ek Belge Açıklaması': 'Description du document annexe',
        'Malın Çıktığı Yer Kodu': 'Code du lieu d’expédition',
        'Malın Çıktığı Yer Adresi': 'Adresse du lieu d’expédition',
        'Malın Çıktığı Yer İlçe': 'District du lieu d’expédition',
        'Malın Çıktığı Yer İl': 'Province du lieu d’expédition',
        'Kargo / Sevkiyat No': 'N° de colis / d’expédition',
        'Toplam Mal Değeri': 'Valeur totale des marchandises',
        'Fiili Sevk Tarihi': 'Date d’expédition effective',
        'Fiili Sevk Saati': 'Heure d’expédition effective',
        'Araç Plakası': 'Immatriculation du véhicule',
        'Araç Plaka Türü (PLAKA/YABANCIPLAKA)': 'Type d’immatriculation du véhicule (PLAKA/YABANCIPLAKA)',
        'Dorse Plakası': 'Immatriculation de la remorque',
        'Dorse Türü (DORSE/DORSEPLAKA/YABANCI...)': 'Type de remorque (DORSE/DORSEPLAKA/YABANCI...)',
        'Sürücü Adı': 'Prénom du chauffeur',
        'Sürücü Soyadı': 'Nom du chauffeur',
        'Sürücü TCKN': 'N° d’identité national du chauffeur (TCKN)',
        'Sürücü Unvanı / Görevi': 'Titre / fonction du chauffeur',
        'Taşıyıcı Unvanı': 'Raison sociale du transporteur',
        'Taşıyıcı VKN': 'N° fiscal du transporteur (VKN)',
        'Taşıyıcı İlçe': 'District du transporteur',
        'Taşıyıcı İl': 'Province du transporteur',
        'Teslimat Kapı No': 'N° de voie (livraison)',
        'Teslimat İlçesi': 'District de livraison',
        'Teslimat Posta Kodu': 'Code postal de livraison',
        'Satır No': 'N° de ligne',
        'Gönderilen Miktar': 'Quantité expédiée',
        'Eksik Miktar': 'Quantité manquante',
        'Eksik Miktar Nedeni': 'Motif de la quantité manquante',
        'Sipariş Satır No': 'N° de ligne de commande',
        // İrsaliye yanıtı
        'Yanıt No': 'N° de réponse',
        'Yanıt Tarihi': 'Date de réponse',
        'Yanıt Saati': 'Heure de réponse',
        'Yanıt Tipi': 'Type de réponse',
        'Yanıt Notu': 'Note de réponse',
        'Fiili Teslim Tarihi': 'Date de livraison effective',
        'Fiili Teslim Saati': 'Heure de livraison effective',
        'Ürün Adı': 'Désignation du produit',
        'Teslim Alınan Miktar': 'Quantité reçue',
        'Reddedilen Miktar': 'Quantité refusée',
        'Red Nedeni': 'Motif du refus',
        'Fazla Miktar': 'Quantité excédentaire',
        'Zamanlama Şikayeti (geç teslim)': 'Réclamation sur le délai (livraison tardive)',
        'İrsaliye Satır No': 'N° de ligne du bon de livraison',
        // Müstahsil / CreditNote
        'Makbuz No': 'N° de reçu',
        'Düzenleme Tarihi': 'Date d’émission',
        'Düzenleme Zamanı': 'Heure d’émission',
        'Belge Tipi (CreditNoteTypeCode)': 'Type de document (CreditNoteTypeCode)',
        'Özelleştirme No': 'Identifiant de personnalisation',
        'Asıl / Suret (CopyIndicator)': 'Original / copie (CopyIndicator)',
        'Makbuz Notu': 'Note du reçu',
        'SMS Operatörü (uygulama adı)': 'Opérateur SMS (nom de l’application)',
        'SMS Operatörü VKN': 'N° fiscal de l’opérateur SMS (VKN)',
        'Mal Hizmet Toplam Tutarı (brüt)': 'Montant total des biens/services (brut)',
        'Ödenecek Tutar (net)': 'Montant à payer (net)',
        'Toplam Kesinti': 'Total des retenues',
        'Kesinti Adı': 'Libellé de la retenue',
        'Kesinti Kodu': 'Code de la retenue',
        'Kesinti Tutarı': 'Montant de la retenue',
        'Kesinti Oranı (%)': 'Taux de retenue (%)',
        'Malın Cinsi': 'Nature de la marchandise',
        'Mal Açıklaması': 'Description de la marchandise',
        'Tutar (Bedel)': 'Montant (prix)',
        'Satır Kesinti Toplamı': 'Total des retenues de la ligne',
        // Gider pusulası
        'İade Edilen Belge No': 'N° du document retourné',
        'İade Edilen Belge Türü (EARSIV_FATURA / SATIS_FISI / BELGESIZ)': 'Type de document retourné (EARSIV_FATURA / SATIS_FISI / BELGESIZ)',
        'İade Edilen Belge Tarihi': 'Date du document retourné',
        'Kod Türü (SMS / IADEKODU)': 'Type de code (SMS / IADEKODU)',
        'SMS / İade Kodu': 'Code SMS / code de retour',
        'Kodun Gönderildiği Telefon': 'Téléphone de réception du code',
        'İade Kodu Uygulaması': 'Application de code de retour',
        'İade Kodu Uygulaması VKN': 'N° fiscal de l’application de code de retour (VKN)',
        'Adına İade Yapılan Adı': 'Prénom du bénéficiaire du remboursement',
        'Adına İade Yapılan Soyadı': 'Nom du bénéficiaire du remboursement',
        'Adına İade Yapılan Unvanı': 'Raison sociale du bénéficiaire du remboursement',
        'Adına İade Yapılan TCKN': 'N° d’identité national du bénéficiaire du remboursement (TCKN)',
        'Adına İade Yapılan SMS / İade Kodu': 'Code SMS / code de retour du bénéficiaire du remboursement',
        'Adına İade Yapılan Telefon': 'Téléphone du bénéficiaire du remboursement',
        'Kargo Firması Unvanı': 'Raison sociale de la société de messagerie',
        'Kargo Firması VKN': 'N° fiscal de la société de messagerie (VKN)',
        'Kargo Yetki Belgesi No': 'N° de licence de messagerie',
        'Kargo Firması İl': 'Province de la société de messagerie',
        // Döviz / kıymetli maden
        'Yetkili Müessese Şube No (SUBENO)': 'N° d’agence de l’établissement agréé (SUBENO)',
        'Müşteri Türü (MUSTERITURU)': 'Type de client (MUSTERITURU)',
        'Müşteri Pasaport No': 'N° de passeport du client',
        'Müşteri Uyruğu': 'Nationalité du client',
        'Döviz / Maden Kodu (kaynak)': 'Code devise / métal (source)',
        'Karşılık Para Birimi (hedef)': 'Devise de contrepartie (cible)',
        'Uygulanan Kur / Birim Fiyat': 'Taux appliqué / prix unitaire',
        'Ödeme Şekli Kodu (10 / 55 / 46 / 68)': 'Code du moyen de paiement (10 / 55 / 46 / 68)',
        'Müşteri Hesap No': 'N° de compte du client',
        'Müessese Hesap No (IBAN)': 'N° de compte de l’établissement (IBAN)',
        'İstatistik No': 'N° statistique',
        'Dövizin Geldiği Ülke': 'Pays d’origine des devises',
        'Dövizin Geliş Nedeni': 'Motif de l’entrée des devises',
        'Gümrük Beyanname No': 'N° de déclaration en douane',
        'Gümrük Beyanname Tarihi': 'Date de la déclaration en douane',
        'Döviz Beyan Tutanağı Sayısı': 'N° du procès-verbal de déclaration de devises',
        'Gümrük Teyit Yazısı Sayısı': 'N° de la lettre de confirmation douanière',
        'İlgili Fatura No': 'N° de la facture associée',
        'Kur: Kaynak Para Birimi': 'Taux : devise source',
        'Kur: Hedef Para Birimi': 'Taux : devise cible',
        'Kur Oranı': 'Taux de change',
        // Dekont
        'Şube Kodu': 'Code agence',
        'Şube Adı': 'Nom de l’agence',
        'İşlemi Yapan Personel Adı': 'Prénom de l’agent ayant effectué l’opération',
        'İşlemi Yapan Personel Soyadı': 'Nom de l’agent ayant effectué l’opération',
        'İşlemi Yapan Personel Sicil No': 'Matricule de l’agent ayant effectué l’opération',
        'Müşteri No': 'N° client',
        'Müşteri IBAN': 'IBAN du client',
        'Abone No': 'N° d’abonné',
        'İşlemi Yapan (Gönderen) Unvanı': 'Raison sociale du donneur d’ordre (expéditeur)',
        'İşlemi Yapan (Gönderen) Kimlik No': 'N° d’identification du donneur d’ordre (expéditeur)',
        'Referans Belge No': 'N° du document de référence',
        'Referans Belge Tarihi': 'Date du document de référence',
        'Referans Belge Kodu': 'Code du document de référence',
        'Referans Belge Açıklaması': 'Description du document de référence',
        'Tahsil Alındısı No (BELGENO)': 'N° de quittance d’encaissement (BELGENO)',
        'Ek Belge Açıklaması (VTA / GVTA vb.)': 'Description du document annexe (VTA / GVTA, etc.)',
        'İşlem Referans No': 'N° de référence de l’opération',
        'İşlem Kanalı': 'Canal de l’opération',
        'Banka Provizyon No': 'N° d’autorisation bancaire',
        'Vergilendirme Dönemi': 'Période d’imposition',
        'Tahsil Eden Vergi Dairesi': 'Service des impôts encaisseur',
        'Tahsil Eden Vergi Dairesi Kodu': 'Code du service des impôts encaisseur',
        'Gümrük Müdürlüğü Kodu': 'Code du bureau de douane',
        'Gümrük Müdürlüğü Adı': 'Nom du bureau de douane',
        'Gümrük Saymanlığı Adı': 'Nom de la recette des douanes',
        'Gümrük Saymanlığı Kodu / VKN': 'Code / n° fiscal de la recette des douanes (VKN)',
        'Saymanlık Banka Şube Kodu': 'Code de l’agence bancaire de la recette',
        'Saymanlık Banka Şube Adı': 'Nom de l’agence bancaire de la recette',
        'Ödeme Kanalı Kodu': 'Code du canal de paiement',
        'Sanal POS Kodu': 'Code du TPE virtuel',
        'İşlem Tarihi': 'Date de l’opération',
        'İşlem Saati': 'Heure de l’opération',
        'Valör Tarihi': 'Date de valeur',
        'Valör Saati': 'Heure de valeur',
        'İşlem Kodu (SerialID)': 'Code de l’opération (SerialID)',
        'İşlem Değeri (açıklama)': 'Valeur de l’opération (description)',
        'Satır Masraf / Kesinti Nedeni': 'Motif des frais / de la retenue de la ligne',
        'Satır Masraf / Kesinti Tutarı': 'Montant des frais / de la retenue de la ligne',
        // Sigorta komisyon
        'Komisyon Dönemi Başlangıcı': 'Début de la période de commission',
        'Komisyon Dönemi Bitişi': 'Fin de la période de commission',
        'Komisyon Dönemi Açıklaması': 'Description de la période de commission',
        'İstihsal Komisyonu Toplamı': 'Total des commissions de production',
        'İptal Komisyonu Toplamı': 'Total des commissions d’annulation',
        'Satır İstihsal Komisyonu': 'Commission de production de la ligne',
        'Satır İptal Komisyonu': 'Commission d’annulation de la ligne',
        'Satır Komisyon Nedeni': 'Motif de la commission de la ligne',
        'Branş / Sigorta Ürünü': 'Branche / produit d’assurance',
        // e-Bilet
        'Gönderen VKN': 'Expéditeur – N° fiscal (VKN)',
        'Gönderen TCKN': 'Expéditeur – N° d’identité national (TCKN)',
        'Rapor Dönemi Başlangıcı': 'Début de la période du rapport',
        'Rapor Dönemi Bitişi': 'Fin de la période du rapport',
        'Rapor Versiyonu': 'Version du rapport',
        'Rapor UUID': 'UUID du rapport',
        'İmza Zamanı': 'Date et heure de signature',
        'Bilet No': 'N° de billet',
        'Belge Tipi (SATIS / IADE)': 'Type de document (SATIS / IADE)',
        'Özet Değer (SHA-256)': 'Empreinte (SHA-256)',
        'Düzenlenme Tarihi': 'Date d’émission',
        'Sefer Zamanı': 'Heure de départ',
        'Etkinlik Zamanı': 'Date et heure de l’événement',
        'Ödeme Şekli': 'Mode de paiement',
        'Bilet Tutarı': 'Montant du billet',
        'KDV Tutarı': 'Montant de TVA',
        'e-Bilet URL': 'URL du e-billet',
        'Etkinlik Yeri İl Kodu': 'Code de province du lieu de l’événement',
        'Etkinlik Yeri Belediyesi': 'Commune du lieu de l’événement',
        'Etkinlik Yeri Açıklaması': 'Description du lieu de l’événement',
        'Organizatör VKN/TCKN': 'Identifiant fiscal de l’organisateur (VKN/TCKN)',
        'Hizmetin Nevi': 'Nature de la prestation',
        'Hizmet Açıklaması': 'Description de la prestation',
        'Gider Gösteren VKN': 'N° fiscal du déclarant de la dépense (VKN)',
        'Gider Gösteren TCKN': 'N° d’identité national du déclarant de la dépense (TCKN)',
        'Referans Açıklaması': 'Description de la référence',
        'Referans No (asıl bilet)': 'N° de référence (billet d’origine)',
        'Diğer Vergi Kodu': 'Code de l’autre taxe',
        'Diğer Vergi Adı': 'Nom de l’autre taxe',
        'Diğer Vergi Oranı (%)': 'Taux de l’autre taxe (%)',
        'Diğer Vergi Tutarı': 'Montant de l’autre taxe',
        'Eğlence Vergisi Tutarı (9142)': 'Montant de la taxe sur les spectacles (9142)',
        'İptal Edilen Bilet No': 'N° du billet annulé',
        'İptal Zamanı': 'Date et heure d’annulation',
        'İptal Tutarı': 'Montant annulé',
        'İptal KDV Tutarı': 'Montant de TVA annulé',
        // e-Yolcu listesi
        'Yolcu Listesi No': 'N° de liste des passagers',
        'Liste Özet Değeri': 'Empreinte de la liste',
        'Hareket Zamanı': 'Heure de départ',
        'Hareket Noktası': 'Point de départ',
        'Sefer Numarası': 'N° de trajet',
        'Sefer Tarihi': 'Date du trajet',
        'Toplam Hasılat (KDV dahil)': 'Recette totale (TVA comprise)',
        'Taşıtı İşleten VKN': 'N° fiscal de l’exploitant du véhicule (VKN)',
        'Taşıtı İşleten TCKN': 'N° d’identité national de l’exploitant du véhicule (TCKN)',
        'Komisyon Tutarı': 'Montant de la commission',
        'Komisyon KDV Tutarı': 'Montant de TVA sur la commission',
        'Koltuk No': 'N° de siège',
        'Yolcu Adı Soyadı': 'Nom et prénom du passager',
        'Yolcu TCKN / YKN': 'N° d’identité national / étranger du passager (TCKN / YKN)',
        'Yolcu Pasaport No': 'N° de passeport du passager',
    },
};

export default fr;
