import type { ExtraDocTextPack } from './types';

const bg: ExtraDocTextPack = {
    titles: {
        invoice: 'Фактура',
        credit: 'Кредитно известие',
        corrected: 'Коригирана фактура',
        prepayment: 'Авансова фактура',
        partial: 'Частична фактура',
        selfbilled: 'Фактура (самофактуриране)',
        despatch: 'Стокова разписка',
    },
    sample: {
        note: 'Благодарим Ви за доверието.',
        paymentTerms: 'Платима в срок от 30 дни без удръжки.',
        creditNote: 'Кредит за един върнат артикул (повреден при транспортиране).',
        correctedNote: 'Тази фактура коригира единичната цена от първоначалната фактура.',
        prepaymentNote: 'Авансово плащане по поръчка {{order}}; ще бъде приспаднато от окончателната фактура.',
        partialNote: 'Частична фактура за първия етап на проекта.',
        prepaymentItem: 'Авансово плащане ({{pct}}%)',
        discount: 'Отстъпка за лоялност',
        product: 'Ергономичен офис стол',
        productDesc: 'Черна мрежеста облегалка, регулируеми подлакътници',
        service: 'Монтаж и настройка',
        accessory: 'Предпазна подложка за под',
        despatchNote: 'Моля, доставете до входа за стоки.',
        backorderReason: 'Временно няма наличност; ще бъде доставено следващата седмица.',
    },
    objects: {
        newText: 'Нов текст',
        header: 'Заглавие {{n}}',
        cell: 'Клетка {{n}}',
        fieldName: 'Име на поле',
        image: 'Изображение',
        chooseImage: 'Изберете изображение',
        newColumn: 'Нова колона',
        computed: 'Изчислено',
        formulaLabel: 'Аванс (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Документ',
            refs: 'Препратки',
            seller: 'Доставчик',
            buyer: 'Получател',
            payee: 'Получател на плащането',
            taxRep: 'Данъчен представител на доставчика',
            despatchParty: 'Изпращач',
            deliveryParty: 'Получател на стоката',
            orderParty: 'Получател (възложител)',
            sellerParty: 'Доставчик (продавач)',
            delivery: 'Доставка',
            shipment: 'Пратка',
            payment: 'Плащане',
            allowances: 'Отстъпки / надбавки',
            totals: 'Суми',
            vat: 'ДДС',
            lines: 'Редове',
        },
        party: {
            seller: 'Доставчик',
            buyer: 'Получател',
            payee: 'Получател на плащането',
            taxRep: 'Данъчен представител',
            despatch: 'Изпращач',
            delivery: 'Получател на стоката',
            order: 'Възложител',
            supplier: 'Доставчик',
        },
        field: {
            name: 'Наименование',
            legalName: 'Юридическо наименование',
            vatId: 'ДДС номер',
            companyId: 'ЕИК',
            endpoint: 'Електронен адрес',
            partyId: 'Идентификатор',
            street: 'Улица',
            street2: 'Допълнителен адрес',
            city: 'Град',
            postal: 'Пощенски код',
            region: 'Област',
            country: 'Държава',
            contact: 'Лице за контакт',
            phone: 'Телефон',
            email: 'Имейл',

            invoiceNo: 'Номер на фактура',
            creditNoteNo: 'Номер на кредитно известие',
            despatchNo: 'Номер на известие за експедиция',
            issueDate: 'Дата на издаване',
            issueTime: 'Час на издаване',
            dueDate: 'Срок за плащане',
            typeCode: 'Код на вида документ',
            note: 'Забележка',
            taxPointDate: 'Дата на данъчното събитие',
            currency: 'Валута',
            taxCurrency: 'Валута за отчитане на ДДС',
            buyerRef: 'Референция на получателя',
            accountingCost: 'Счетоводна референция на получателя',
            periodStart: 'Начало на периода на фактуриране',
            periodEnd: 'Край на периода на фактуриране',
            customization: 'Идентификатор на спецификацията',
            profile: 'Бизнес процес',

            orderRef: 'Номер на поръчка',
            salesOrderRef: 'Номер на поръчка за продажба',
            contractRef: 'Номер на договор',
            projectRef: 'Номер на проект',
            despatchRef: 'Номер на известие за експедиция',
            receiptRef: 'Номер на известие за получаване',
            precedingInvoice: 'Първоначална фактура',
            precedingInvoiceDate: 'Дата на първоначалната фактура',
            attachmentId: 'Придружаващ документ',
            attachmentDesc: 'Описание на придружаващия документ',

            deliveryDate: 'Дата на доставка',
            deliveryLocation: 'Идентификатор на мястото на доставка',
            deliverToName: 'Получател на доставката',
            deliveryStreet: 'Улица на доставка',
            deliveryCity: 'Град на доставка',
            deliveryPostal: 'Пощенски код на доставка',
            deliveryCountry: 'Държава на доставка',

            paymentMeans: 'Код на начина на плащане',
            paymentId: 'Основание за плащане',
            iban: 'IBAN / номер на сметка',
            accountName: 'Титуляр на сметката',
            bic: 'BIC',
            cardNumber: 'Номер на карта',
            mandate: 'Мандат за директен дебит',
            paymentTerms: 'Условия за плащане',

            allowanceAmount: 'Размер на отстъпката',
            allowanceReason: 'Основание за отстъпка',
            chargeAmount: 'Размер на надбавката',
            chargeReason: 'Основание за надбавка',

            lineTotal: 'Сума на нетните стойности по редове',
            taxExclusive: 'Общо без ДДС',
            taxInclusive: 'Общо с ДДС',
            allowanceTotal: 'Сума на отстъпките',
            chargeTotal: 'Сума на надбавките',
            prepaid: 'Платена сума',
            rounding: 'Закръгляне',
            payable: 'Сума за плащане',

            vatTotal: 'Общо ДДС',
            vatBase: 'Данъчна основа по категория ДДС',
            vatAmount: 'ДДС по категория',
            vatCategory: 'Код на категорията ДДС',
            vatRate: 'Ставка на ДДС (%)',
            vatExemption: 'Основание за освобождаване от ДДС',
            vatExemptionCode: 'Код на основанието за освобождаване от ДДС',

            lineId: 'Номер на ред',
            lineNote: 'Забележка към реда',
            quantity: 'Количество',
            unit: 'Мярка',
            lineNet: 'Нетна стойност на реда',
            itemName: 'Наименование на стоката или услугата',
            itemDesc: 'Описание на стоката или услугата',
            sellerItemId: 'Код на доставчика',
            buyerItemId: 'Код на получателя',
            standardItemId: 'Стандартен код (GTIN)',
            originCountry: 'Държава на произход',
            classification: 'Класификация на стоката',
            lineVatCategory: 'Категория ДДС на реда',
            lineVatRate: 'Ставка ДДС на реда (%)',
            price: 'Единична цена',
            baseQuantity: 'Базово количество за цената',
            priceDiscount: 'Отстъпка от цената',
            lineAllowance: 'Отстъпка по реда',
            lineAllowanceReason: 'Основание за отстъпка по реда',
            orderLineRef: 'Ред от поръчката',
            linePeriodStart: 'Начало на периода на реда',
            linePeriodEnd: 'Край на периода на реда',

            shipmentId: 'Идентификатор на пратката',
            grossWeight: 'Бруто тегло',
            grossVolume: 'Бруто обем',
            trackingId: 'Номер за проследяване',
            estStartDate: 'Очаквана доставка от (дата)',
            estStartTime: 'Очаквана доставка от (час)',
            estEndDate: 'Очаквана доставка до (дата)',
            estEndTime: 'Очаквана доставка до (час)',
            carrier: 'Превозвач',
            despatchDate: 'Дата на експедиция',
            despatchTime: 'Час на експедиция',
            handlingUnit: 'Транспортна единица (SSCC)',
            handlingUnitType: 'Вид транспортна единица',
            deliveredQty: 'Доставено количество',
            outstandingQty: 'Недоставено количество',
            outstandingReason: 'Причина за недоставяне',
            lot: 'Партиден номер',
            expiry: 'Най-добър до / срок на годност',
            serial: 'Сериен номер',
        },
    },
};

export default bg;
