import type { ExtraDocTextPack } from './types';

const ca: ExtraDocTextPack = {
    titles: {
        invoice: 'Factura',
        credit: 'Factura rectificativa (abonament)',
        corrected: 'Factura rectificativa',
        prepayment: 'Factura de bestreta',
        partial: 'Factura parcial',
        selfbilled: 'Autofactura',
        despatch: 'Albarà',
    },
    sample: {
        note: 'Gràcies per la vostra confiança.',
        paymentTerms: 'Pagament a 30 dies, sense descompte.',
        creditNote: 'Abonament per un article retornat (danyat durant el transport).',
        correctedNote: 'Aquesta factura rectifica el preu unitari de la factura original.',
        prepaymentNote: 'Bestreta de la comanda {{order}}; es descomptarà de la factura final.',
        partialNote: 'Factura parcial de la primera fase del projecte.',
        prepaymentItem: 'Bestreta ({{pct}} %)',
        discount: 'Descompte per fidelitat',
        product: 'Cadira d’oficina ergonòmica',
        productDesc: 'Respatller de malla negre, reposabraços regulables',
        service: 'Instal·lació i posada en marxa',
        accessory: 'Estora protectora de terra',
        despatchNote: 'Lliureu-ho a l’entrada de mercaderies.',
        backorderReason: 'Temporalment sense estoc; s’enviarà la setmana vinent.',
    },
    objects: {
        newText: 'Text nou',
        header: 'Capçalera {{n}}',
        cell: 'Cel·la {{n}}',
        fieldName: 'Nom del camp',
        image: 'Imatge',
        chooseImage: 'Trieu una imatge',
        newColumn: 'Columna nova',
        computed: 'Calculat',
        formulaLabel: 'Bestreta (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Document',
            refs: 'Referències',
            seller: 'Venedor',
            buyer: 'Comprador',
            payee: 'Beneficiari',
            taxRep: 'Representant fiscal del venedor',
            despatchParty: 'Expedidor',
            deliveryParty: 'Destinatari',
            orderParty: 'Comprador (sol·licitant)',
            sellerParty: 'Venedor (proveïdor)',
            delivery: 'Lliurament',
            shipment: 'Enviament',
            payment: 'Pagament',
            allowances: 'Descomptes / càrrecs',
            totals: 'Totals',
            vat: 'IVA',
            lines: 'Línies',
        },
        party: {
            seller: 'Venedor',
            buyer: 'Comprador',
            payee: 'Beneficiari',
            taxRep: 'Representant fiscal',
            despatch: 'Expedidor',
            delivery: 'Destinatari',
            order: 'Comprador',
            supplier: 'Proveïdor',
        },
        field: {
            name: 'Nom',
            legalName: 'Raó social',
            vatId: 'NIF-IVA',
            companyId: 'Número de registre',
            endpoint: 'Adreça electrònica',
            partyId: 'Identificador',
            street: 'Carrer',
            street2: 'Adreça addicional',
            city: 'Població',
            postal: 'Codi postal',
            region: 'Província',
            country: 'País',
            contact: 'Persona de contacte',
            phone: 'Telèfon',
            email: 'Correu electrònic',

            invoiceNo: 'Número de factura',
            creditNoteNo: 'Número de factura rectificativa',
            despatchNo: 'Número d’albarà',
            issueDate: 'Data d’emissió',
            issueTime: 'Hora d’emissió',
            dueDate: 'Data de venciment',
            typeCode: 'Codi de tipus de document',
            note: 'Nota',
            taxPointDate: 'Data de meritació de l’IVA',
            currency: 'Moneda',
            taxCurrency: 'Moneda de comptabilització de l’IVA',
            buyerRef: 'Referència del comprador',
            accountingCost: 'Referència comptable del comprador',
            periodStart: 'Inici del període de facturació',
            periodEnd: 'Fi del període de facturació',
            customization: 'Identificador de l’especificació',
            profile: 'Procés de negoci',

            orderRef: 'Referència de la comanda de compra',
            salesOrderRef: 'Referència de la comanda de venda',
            contractRef: 'Referència del contracte',
            projectRef: 'Referència del projecte',
            despatchRef: 'Referència de l’albarà',
            receiptRef: 'Referència de l’avís de recepció',
            precedingInvoice: 'Factura anterior',
            precedingInvoiceDate: 'Data de la factura anterior',
            attachmentId: 'Document adjunt',
            attachmentDesc: 'Descripció del document adjunt',

            deliveryDate: 'Data de lliurament',
            deliveryLocation: 'ID del lloc de lliurament',
            deliverToName: 'Destinatari del lliurament',
            deliveryStreet: 'Carrer de lliurament',
            deliveryCity: 'Població de lliurament',
            deliveryPostal: 'Codi postal de lliurament',
            deliveryCountry: 'País de lliurament',

            paymentMeans: 'Codi del mitjà de pagament',
            paymentId: 'Referència de pagament',
            iban: 'IBAN / número de compte',
            accountName: 'Titular del compte',
            bic: 'BIC',
            cardNumber: 'Número de targeta',
            mandate: 'Mandat de domiciliació bancària',
            paymentTerms: 'Condicions de pagament',

            allowanceAmount: 'Import del descompte',
            allowanceReason: 'Motiu del descompte',
            chargeAmount: 'Import del càrrec',
            chargeReason: 'Motiu del càrrec',

            lineTotal: 'Suma dels imports nets de les línies',
            taxExclusive: 'Total sense IVA',
            taxInclusive: 'Total amb IVA',
            allowanceTotal: 'Total de descomptes',
            chargeTotal: 'Total de càrrecs',
            prepaid: 'Import pagat',
            rounding: 'Arrodoniment',
            payable: 'Import a pagar',

            vatTotal: 'Quota total d’IVA',
            vatBase: 'Base imposable per categoria d’IVA',
            vatAmount: 'Quota per categoria d’IVA',
            vatCategory: 'Codi de categoria d’IVA',
            vatRate: 'Tipus d’IVA (%)',
            vatExemption: 'Motiu d’exempció d’IVA',
            vatExemptionCode: 'Codi del motiu d’exempció d’IVA',

            lineId: 'Número de línia',
            lineNote: 'Nota de línia',
            quantity: 'Quantitat',
            unit: 'Unitat de mesura',
            lineNet: 'Import net de la línia',
            itemName: 'Nom de l’article',
            itemDesc: 'Descripció de l’article',
            sellerItemId: 'Codi d’article del venedor',
            buyerItemId: 'Codi d’article del comprador',
            standardItemId: 'Codi estàndard de l’article (GTIN)',
            originCountry: 'País d’origen',
            classification: 'Classificació de l’article',
            lineVatCategory: 'Categoria d’IVA de la línia',
            lineVatRate: 'Tipus d’IVA de la línia (%)',
            price: 'Preu unitari',
            baseQuantity: 'Quantitat base del preu',
            priceDiscount: 'Descompte sobre el preu',
            lineAllowance: 'Descompte de línia',
            lineAllowanceReason: 'Motiu del descompte de línia',
            orderLineRef: 'Referència de la línia de comanda',
            linePeriodStart: 'Inici del període de la línia',
            linePeriodEnd: 'Fi del període de la línia',

            shipmentId: 'ID de l’enviament',
            grossWeight: 'Pes brut',
            grossVolume: 'Volum brut',
            trackingId: 'Número de seguiment',
            estStartDate: 'Lliurament previst des de (data)',
            estStartTime: 'Lliurament previst des de (hora)',
            estEndDate: 'Lliurament previst fins a (data)',
            estEndTime: 'Lliurament previst fins a (hora)',
            carrier: 'Transportista',
            despatchDate: 'Data d’expedició',
            despatchTime: 'Hora d’expedició',
            handlingUnit: 'Unitat de manipulació (SSCC)',
            handlingUnitType: 'Tipus d’unitat de manipulació',
            deliveredQty: 'Quantitat lliurada',
            outstandingQty: 'Quantitat pendent',
            outstandingReason: 'Motiu de la quantitat pendent',
            lot: 'Número de lot',
            expiry: 'Consum preferent / data de caducitat',
            serial: 'Número de sèrie',
        },
    },
};

export default ca;
