import type { ExtraDocTextPack } from './types';

const cs: ExtraDocTextPack = {
    titles: {
        invoice: 'Faktura – daňový doklad',
        credit: 'Opravný daňový doklad (dobropis)',
        corrected: 'Opravný daňový doklad',
        prepayment: 'Zálohová faktura',
        partial: 'Dílčí faktura',
        selfbilled: 'Daňový doklad vystavený odběratelem',
        despatch: 'Dodací list',
    },
    sample: {
        note: 'Děkujeme za spolupráci.',
        paymentTerms: 'Splatné do 30 dnů bez srážek.',
        creditNote: 'Dobropis za jeden vrácený kus (poškozený při přepravě).',
        correctedNote: 'Tento doklad opravuje jednotkovou cenu původní faktury.',
        prepaymentNote: 'Záloha na objednávku {{order}}; bude odečtena v konečné faktuře.',
        partialNote: 'Dílčí faktura za první etapu projektu.',
        prepaymentItem: 'Záloha ({{pct}} %)',
        discount: 'Věrnostní sleva',
        product: 'Ergonomická kancelářská židle',
        productDesc: 'Černé síťované opěradlo, nastavitelné područky',
        service: 'Montáž a nastavení',
        accessory: 'Ochranná podložka na podlahu',
        despatchNote: 'Prosíme o doručení ke vchodu pro zásobování.',
        backorderReason: 'Dočasně není skladem; dodáme příští týden.',
    },
    objects: {
        newText: 'Nový text',
        header: 'Záhlaví {{n}}',
        cell: 'Buňka {{n}}',
        fieldName: 'Název pole',
        image: 'Obrázek',
        chooseImage: 'Vyberte obrázek',
        newColumn: 'Nový sloupec',
        computed: 'Vypočteno',
        formulaLabel: 'Záloha (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Doklad',
            refs: 'Odkazy',
            seller: 'Dodavatel',
            buyer: 'Odběratel',
            payee: 'Příjemce platby',
            taxRep: 'Daňový zástupce dodavatele',
            despatchParty: 'Odesílatel',
            deliveryParty: 'Příjemce zásilky',
            orderParty: 'Odběratel (objednatel)',
            sellerParty: 'Dodavatel (prodávající)',
            delivery: 'Dodání',
            shipment: 'Zásilka',
            payment: 'Platba',
            allowances: 'Slevy / příplatky',
            totals: 'Součty',
            vat: 'DPH',
            lines: 'Položky',
        },
        party: {
            seller: 'Dodavatel',
            buyer: 'Odběratel',
            payee: 'Příjemce platby',
            taxRep: 'Daňový zástupce',
            despatch: 'Odesílatel',
            delivery: 'Příjemce',
            order: 'Odběratel',
            supplier: 'Dodavatel',
        },
        field: {
            name: 'Název',
            legalName: 'Obchodní firma',
            vatId: 'DIČ',
            companyId: 'IČO',
            endpoint: 'Elektronická adresa',
            partyId: 'Identifikátor',
            street: 'Ulice',
            street2: 'Doplňující adresa',
            city: 'Město',
            postal: 'PSČ',
            region: 'Kraj',
            country: 'Stát',
            contact: 'Kontaktní osoba',
            phone: 'Telefon',
            email: 'E-mail',

            invoiceNo: 'Číslo faktury',
            creditNoteNo: 'Číslo dobropisu',
            despatchNo: 'Číslo avíza o odeslání',
            issueDate: 'Datum vystavení',
            issueTime: 'Čas vystavení',
            dueDate: 'Datum splatnosti',
            typeCode: 'Kód typu dokladu',
            note: 'Poznámka',
            taxPointDate: 'Datum uskutečnění zdanitelného plnění',
            currency: 'Měna',
            taxCurrency: 'Měna pro vyúčtování DPH',
            buyerRef: 'Reference odběratele',
            accountingCost: 'Účetní reference odběratele',
            periodStart: 'Začátek fakturačního období',
            periodEnd: 'Konec fakturačního období',
            customization: 'Identifikátor specifikace',
            profile: 'Obchodní proces',

            orderRef: 'Číslo objednávky',
            salesOrderRef: 'Číslo prodejní objednávky',
            contractRef: 'Číslo smlouvy',
            projectRef: 'Číslo projektu',
            despatchRef: 'Číslo avíza o odeslání',
            receiptRef: 'Číslo příjemky',
            precedingInvoice: 'Původní faktura',
            precedingInvoiceDate: 'Datum původní faktury',
            attachmentId: 'Podpůrný doklad',
            attachmentDesc: 'Popis podpůrného dokladu',

            deliveryDate: 'Datum dodání',
            deliveryLocation: 'ID místa dodání',
            deliverToName: 'Příjemce dodávky',
            deliveryStreet: 'Ulice dodání',
            deliveryCity: 'Město dodání',
            deliveryPostal: 'PSČ dodání',
            deliveryCountry: 'Stát dodání',

            paymentMeans: 'Kód způsobu platby',
            paymentId: 'Variabilní symbol',
            iban: 'IBAN / číslo účtu',
            accountName: 'Název účtu',
            bic: 'BIC',
            cardNumber: 'Číslo karty',
            mandate: 'Mandát k inkasu',
            paymentTerms: 'Platební podmínky',

            allowanceAmount: 'Částka slevy',
            allowanceReason: 'Důvod slevy',
            chargeAmount: 'Částka příplatku',
            chargeReason: 'Důvod příplatku',

            lineTotal: 'Součet položek bez DPH',
            taxExclusive: 'Celkem bez DPH',
            taxInclusive: 'Celkem s DPH',
            allowanceTotal: 'Součet slev',
            chargeTotal: 'Součet příplatků',
            prepaid: 'Uhrazeno',
            rounding: 'Zaokrouhlení',
            payable: 'K úhradě',

            vatTotal: 'DPH celkem',
            vatBase: 'Základ daně v kategorii DPH',
            vatAmount: 'Výše DPH v kategorii',
            vatCategory: 'Kód kategorie DPH',
            vatRate: 'Sazba DPH (%)',
            vatExemption: 'Důvod osvobození od DPH',
            vatExemptionCode: 'Kód důvodu osvobození od DPH',

            lineId: 'Číslo řádku',
            lineNote: 'Poznámka k položce',
            quantity: 'Množství',
            unit: 'Měrná jednotka',
            lineNet: 'Cena položky bez DPH',
            itemName: 'Název položky',
            itemDesc: 'Popis položky',
            sellerItemId: 'Kód zboží dodavatele',
            buyerItemId: 'Kód zboží odběratele',
            standardItemId: 'Standardní kód zboží (GTIN)',
            originCountry: 'Země původu',
            classification: 'Klasifikace zboží',
            lineVatCategory: 'Kategorie DPH položky',
            lineVatRate: 'Sazba DPH položky (%)',
            price: 'Jednotková cena',
            baseQuantity: 'Základní množství pro cenu',
            priceDiscount: 'Sleva z ceny',
            lineAllowance: 'Sleva na položce',
            lineAllowanceReason: 'Důvod slevy na položce',
            orderLineRef: 'Řádek objednávky',
            linePeriodStart: 'Začátek období položky',
            linePeriodEnd: 'Konec období položky',

            shipmentId: 'ID zásilky',
            grossWeight: 'Hmotnost brutto',
            grossVolume: 'Objem brutto',
            trackingId: 'Sledovací číslo',
            estStartDate: 'Předpokládané dodání od (datum)',
            estStartTime: 'Předpokládané dodání od (čas)',
            estEndDate: 'Předpokládané dodání do (datum)',
            estEndTime: 'Předpokládané dodání do (čas)',
            carrier: 'Dopravce',
            despatchDate: 'Datum odeslání',
            despatchTime: 'Čas odeslání',
            handlingUnit: 'Přepravní jednotka (SSCC)',
            handlingUnitType: 'Typ přepravní jednotky',
            deliveredQty: 'Dodané množství',
            outstandingQty: 'Nedodané množství',
            outstandingReason: 'Důvod nedodání',
            lot: 'Číslo šarže',
            expiry: 'Minimální trvanlivost / spotřebujte do',
            serial: 'Sériové číslo',
        },
    },
};

export default cs;
