import type { ExtraDocTextPack } from './types';

const da: ExtraDocTextPack = {
    titles: {
        invoice: 'Faktura',
        credit: 'Kreditnota',
        corrected: 'Korrigeret faktura',
        prepayment: 'Forudbetalingsfaktura',
        partial: 'Acontofaktura',
        selfbilled: 'Selvfaktureret faktura',
        despatch: 'Følgeseddel',
    },
    sample: {
        note: 'Tak for handlen.',
        paymentTerms: 'Betales netto inden 30 dage.',
        creditNote: 'Kreditering af én returneret vare (beskadiget under transport).',
        correctedNote: 'Denne faktura korrigerer enhedsprisen på den oprindelige faktura.',
        prepaymentNote: 'Forudbetaling for ordre {{order}}; beløbet modregnes i slutfakturaen.',
        partialNote: 'Acontofaktura for projektets første fase.',
        prepaymentItem: 'Forudbetaling ({{pct}} %)',
        discount: 'Kunderabat',
        product: 'Ergonomisk kontorstol',
        productDesc: 'Sort netryg, justerbare armlæn',
        service: 'Montering og opsætning',
        accessory: 'Gulvbeskyttelsesmåtte',
        despatchNote: 'Leveres venligst ved varemodtagelsen.',
        backorderReason: 'Midlertidigt udsolgt; eftersendes i næste uge.',
    },
    objects: {
        newText: 'Ny tekst',
        header: 'Overskrift {{n}}',
        cell: 'Celle {{n}}',
        fieldName: 'Feltnavn',
        image: 'Billede',
        chooseImage: 'Vælg et billede',
        newColumn: 'Ny kolonne',
        computed: 'Beregnet',
        formulaLabel: 'Forudbetaling (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Dokument',
            refs: 'Referencer',
            seller: 'Sælger',
            buyer: 'Køber',
            payee: 'Betalingsmodtager',
            taxRep: 'Sælgers momsrepræsentant',
            despatchParty: 'Afsender',
            deliveryParty: 'Modtager',
            orderParty: 'Køber (bestiller)',
            sellerParty: 'Sælger (leverandør)',
            delivery: 'Levering',
            shipment: 'Forsendelse',
            payment: 'Betaling',
            allowances: 'Rabatter / gebyrer',
            totals: 'Totaler',
            vat: 'Moms',
            lines: 'Linjer',
        },
        party: {
            seller: 'Sælger',
            buyer: 'Køber',
            payee: 'Betalingsmodtager',
            taxRep: 'Momsrepræsentant',
            despatch: 'Afsender',
            delivery: 'Modtager',
            order: 'Køber',
            supplier: 'Leverandør',
        },
        field: {
            name: 'Navn',
            legalName: 'Juridisk navn',
            vatId: 'Momsnummer',
            companyId: 'Registreringsnummer (CVR)',
            endpoint: 'Elektronisk adresse',
            partyId: 'Identifikator',
            street: 'Gade',
            street2: 'Supplerende adresselinje',
            city: 'By',
            postal: 'Postnummer',
            region: 'Region',
            country: 'Land',
            contact: 'Kontaktperson',
            phone: 'Telefon',
            email: 'E-mail',

            invoiceNo: 'Fakturanummer',
            creditNoteNo: 'Kreditnotanummer',
            despatchNo: 'Følgeseddelnummer',
            issueDate: 'Udstedelsesdato',
            issueTime: 'Udstedelsestidspunkt',
            dueDate: 'Forfaldsdato',
            typeCode: 'Dokumenttypekode',
            note: 'Bemærkning',
            taxPointDate: 'Momspligtsdato',
            currency: 'Valuta',
            taxCurrency: 'Momsregnskabsvaluta',
            buyerRef: 'Købers reference',
            accountingCost: 'Købers konteringsreference',
            periodStart: 'Faktureringsperiode start',
            periodEnd: 'Faktureringsperiode slut',
            customization: 'Specifikations-ID',
            profile: 'Forretningsproces',

            orderRef: 'Indkøbsordrereference',
            salesOrderRef: 'Salgsordrereference',
            contractRef: 'Kontraktreference',
            projectRef: 'Projektreference',
            despatchRef: 'Følgeseddelreference',
            receiptRef: 'Modtagelsesreference',
            precedingInvoice: 'Tidligere faktura',
            precedingInvoiceDate: 'Dato for tidligere faktura',
            attachmentId: 'Bilag',
            attachmentDesc: 'Bilagsbeskrivelse',

            deliveryDate: 'Leveringsdato',
            deliveryLocation: 'Leveringssted-ID',
            deliverToName: 'Leveres til',
            deliveryStreet: 'Leveringsadresse, gade',
            deliveryCity: 'Leveringsadresse, by',
            deliveryPostal: 'Leveringsadresse, postnr.',
            deliveryCountry: 'Leveringsland',

            paymentMeans: 'Betalingsformkode',
            paymentId: 'Betalingsreference',
            iban: 'IBAN / kontonummer',
            accountName: 'Kontonavn',
            bic: 'BIC',
            cardNumber: 'Kortnummer',
            mandate: 'Mandat for direkte debitering',
            paymentTerms: 'Betalingsbetingelser',

            allowanceAmount: 'Rabatbeløb',
            allowanceReason: 'Rabatårsag',
            chargeAmount: 'Gebyrbeløb',
            chargeReason: 'Gebyrårsag',

            lineTotal: 'Sum af linjebeløb netto',
            taxExclusive: 'I alt ekskl. moms',
            taxInclusive: 'I alt inkl. moms',
            allowanceTotal: 'Sum af rabatter',
            chargeTotal: 'Sum af gebyrer',
            prepaid: 'Betalt beløb',
            rounding: 'Afrundingsbeløb',
            payable: 'Beløb til betaling',

            vatTotal: 'Momsbeløb i alt',
            vatBase: 'Momsgrundlag pr. kategori',
            vatAmount: 'Momsbeløb pr. kategori',
            vatCategory: 'Momskategorikode',
            vatRate: 'Momssats (%)',
            vatExemption: 'Årsag til momsfritagelse',
            vatExemptionCode: 'Kode for momsfritagelse',

            lineId: 'Linjenummer',
            lineNote: 'Linjebemærkning',
            quantity: 'Antal',
            unit: 'Enhed',
            lineNet: 'Linjebeløb netto',
            itemName: 'Varenavn',
            itemDesc: 'Varebeskrivelse',
            sellerItemId: 'Sælgers varenummer',
            buyerItemId: 'Købers varenummer',
            standardItemId: 'Standardvare-ID (GTIN)',
            originCountry: 'Oprindelsesland',
            classification: 'Vareklassifikation',
            lineVatCategory: 'Linjens momskategori',
            lineVatRate: 'Linjens momssats (%)',
            price: 'Enhedspris',
            baseQuantity: 'Prisens basismængde',
            priceDiscount: 'Prisrabat',
            lineAllowance: 'Linjerabat',
            lineAllowanceReason: 'Årsag til linjerabat',
            orderLineRef: 'Ordrelinjereference',
            linePeriodStart: 'Linjeperiode start',
            linePeriodEnd: 'Linjeperiode slut',

            shipmentId: 'Forsendelses-ID',
            grossWeight: 'Bruttovægt',
            grossVolume: 'Bruttovolumen',
            trackingId: 'Sporingsnummer',
            estStartDate: 'Forventet levering fra (dato)',
            estStartTime: 'Forventet levering fra (tid)',
            estEndDate: 'Forventet levering til (dato)',
            estEndTime: 'Forventet levering til (tid)',
            carrier: 'Transportør',
            despatchDate: 'Afsendelsesdato',
            despatchTime: 'Afsendelsestidspunkt',
            handlingUnit: 'Transportenhed (SSCC)',
            handlingUnitType: 'Type af transportenhed',
            deliveredQty: 'Leveret antal',
            outstandingQty: 'Udestående antal',
            outstandingReason: 'Årsag til restordre',
            lot: 'Batchnummer',
            expiry: 'Bedst før / udløbsdato',
            serial: 'Serienummer',
        },
    },
};

export default da;
