import type { ExtraDocTextPack } from './types';

const el: ExtraDocTextPack = {
    titles: {
        invoice: 'Τιμολόγιο',
        credit: 'Πιστωτικό τιμολόγιο',
        corrected: 'Διορθωτικό τιμολόγιο',
        prepayment: 'Τιμολόγιο προκαταβολής',
        partial: 'Μερικό τιμολόγιο',
        selfbilled: 'Τιμολόγιο αυτοτιμολόγησης',
        despatch: 'Δελτίο αποστολής',
    },
    sample: {
        note: 'Σας ευχαριστούμε για την προτίμησή σας.',
        paymentTerms: 'Εξόφληση εντός 30 ημερών χωρίς έκπτωση.',
        creditNote: 'Πίστωση για ένα επιστραφέν είδος (φθορά κατά τη μεταφορά).',
        correctedNote: 'Το παρόν τιμολόγιο διορθώνει την τιμή μονάδας του αρχικού τιμολογίου.',
        prepaymentNote: 'Προκαταβολή για την παραγγελία {{order}}, η οποία θα αφαιρεθεί από το τελικό τιμολόγιο.',
        partialNote: 'Μερικό τιμολόγιο για την πρώτη φάση του έργου.',
        prepaymentItem: 'Προκαταβολή ({{pct}}%)',
        discount: 'Έκπτωση πιστότητας',
        product: 'Εργονομική καρέκλα γραφείου',
        productDesc: 'Μαύρη διχτυωτή πλάτη, ρυθμιζόμενα μπράτσα',
        service: 'Συναρμολόγηση και εγκατάσταση',
        accessory: 'Προστατευτικό χαλί δαπέδου',
        despatchNote: 'Παρακαλούμε παραδώστε στην είσοδο παραλαβής εμπορευμάτων.',
        backorderReason: 'Προσωρινά μη διαθέσιμο, θα αποσταλεί την επόμενη εβδομάδα.',
    },
    objects: {
        newText: 'Νέο κείμενο',
        header: 'Κεφαλίδα {{n}}',
        cell: 'Κελί {{n}}',
        fieldName: 'Όνομα πεδίου',
        image: 'Εικόνα',
        chooseImage: 'Επιλέξτε εικόνα',
        newColumn: 'Νέα στήλη',
        computed: 'Υπολογιζόμενο',
        formulaLabel: 'Προκαταβολή (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Παραστατικό',
            refs: 'Αναφορές',
            seller: 'Πωλητής',
            buyer: 'Αγοραστής',
            payee: 'Δικαιούχος πληρωμής',
            taxRep: 'Φορολογικός εκπρόσωπος πωλητή',
            despatchParty: 'Αποστολέας',
            deliveryParty: 'Παραλήπτης',
            orderParty: 'Αγοραστής (παραγγελία)',
            sellerParty: 'Πωλητής (προμηθευτής)',
            delivery: 'Παράδοση',
            shipment: 'Αποστολή',
            payment: 'Πληρωμή',
            allowances: 'Εκπτώσεις / επιβαρύνσεις',
            totals: 'Σύνολα',
            vat: 'ΦΠΑ',
            lines: 'Γραμμές',
        },
        party: {
            seller: 'Πωλητής',
            buyer: 'Αγοραστής',
            payee: 'Δικαιούχος πληρωμής',
            taxRep: 'Φορολογικός εκπρόσωπος',
            despatch: 'Αποστολέας',
            delivery: 'Παραλήπτης',
            order: 'Αγοραστής',
            supplier: 'Προμηθευτής',
        },
        field: {
            name: 'Όνομα',
            legalName: 'Επωνυμία',
            vatId: 'Αριθμός ΦΠΑ (ΑΦΜ)',
            companyId: 'Αριθμός μητρώου',
            endpoint: 'Ηλεκτρονική διεύθυνση',
            partyId: 'Αναγνωριστικό',
            street: 'Οδός',
            street2: 'Συμπληρωματική διεύθυνση',
            city: 'Πόλη',
            postal: 'Ταχυδρομικός κώδικας',
            region: 'Περιφέρεια',
            country: 'Χώρα',
            contact: 'Υπεύθυνος επικοινωνίας',
            phone: 'Τηλέφωνο',
            email: 'E-mail',

            invoiceNo: 'Αριθμός τιμολογίου',
            creditNoteNo: 'Αριθμός πιστωτικού τιμολογίου',
            despatchNo: 'Αριθμός δελτίου αποστολής',
            issueDate: 'Ημερομηνία έκδοσης',
            issueTime: 'Ώρα έκδοσης',
            dueDate: 'Ημερομηνία λήξης',
            typeCode: 'Κωδικός τύπου παραστατικού',
            note: 'Σημείωση',
            taxPointDate: 'Ημερομηνία γένεσης φορολογικής υποχρέωσης',
            currency: 'Νόμισμα',
            taxCurrency: 'Νόμισμα λογιστικοποίησης ΦΠΑ',
            buyerRef: 'Αναφορά αγοραστή',
            accountingCost: 'Λογιστική αναφορά αγοραστή',
            periodStart: 'Έναρξη περιόδου τιμολόγησης',
            periodEnd: 'Λήξη περιόδου τιμολόγησης',
            customization: 'Αναγνωριστικό προδιαγραφής',
            profile: 'Επιχειρηματική διαδικασία',

            orderRef: 'Αναφορά παραγγελίας αγοράς',
            salesOrderRef: 'Αναφορά παραγγελίας πώλησης',
            contractRef: 'Αναφορά σύμβασης',
            projectRef: 'Αναφορά έργου',
            despatchRef: 'Αναφορά δελτίου αποστολής',
            receiptRef: 'Αναφορά δελτίου παραλαβής',
            precedingInvoice: 'Προηγούμενο τιμολόγιο',
            precedingInvoiceDate: 'Ημερομηνία προηγούμενου τιμολογίου',
            attachmentId: 'Συνοδευτικό έγγραφο',
            attachmentDesc: 'Περιγραφή συνοδευτικού εγγράφου',

            deliveryDate: 'Ημερομηνία παράδοσης',
            deliveryLocation: 'Κωδικός τόπου παράδοσης',
            deliverToName: 'Παραλήπτης παράδοσης',
            deliveryStreet: 'Οδός παράδοσης',
            deliveryCity: 'Πόλη παράδοσης',
            deliveryPostal: 'Τ.Κ. παράδοσης',
            deliveryCountry: 'Χώρα παράδοσης',

            paymentMeans: 'Κωδικός τρόπου πληρωμής',
            paymentId: 'Αναφορά πληρωμής',
            iban: 'IBAN / αριθμός λογαριασμού',
            accountName: 'Δικαιούχος λογαριασμού',
            bic: 'BIC',
            cardNumber: 'Αριθμός κάρτας',
            mandate: 'Εντολή άμεσης χρέωσης',
            paymentTerms: 'Όροι πληρωμής',

            allowanceAmount: 'Ποσό έκπτωσης',
            allowanceReason: 'Αιτία έκπτωσης',
            chargeAmount: 'Ποσό επιβάρυνσης',
            chargeReason: 'Αιτία επιβάρυνσης',

            lineTotal: 'Άθροισμα καθαρών ποσών γραμμών',
            taxExclusive: 'Σύνολο χωρίς ΦΠΑ',
            taxInclusive: 'Σύνολο με ΦΠΑ',
            allowanceTotal: 'Σύνολο εκπτώσεων',
            chargeTotal: 'Σύνολο επιβαρύνσεων',
            prepaid: 'Καταβληθέν ποσό',
            rounding: 'Στρογγυλοποίηση',
            payable: 'Πληρωτέο ποσό',

            vatTotal: 'Συνολικό ποσό ΦΠΑ',
            vatBase: 'Φορολογητέα αξία κατηγορίας ΦΠΑ',
            vatAmount: 'Ποσό ΦΠΑ κατηγορίας',
            vatCategory: 'Κωδικός κατηγορίας ΦΠΑ',
            vatRate: 'Συντελεστής ΦΠΑ (%)',
            vatExemption: 'Αιτία απαλλαγής ΦΠΑ',
            vatExemptionCode: 'Κωδικός αιτίας απαλλαγής ΦΠΑ',

            lineId: 'Αριθμός γραμμής',
            lineNote: 'Σημείωση γραμμής',
            quantity: 'Ποσότητα',
            unit: 'Μονάδα μέτρησης',
            lineNet: 'Καθαρή αξία γραμμής',
            itemName: 'Ονομασία είδους',
            itemDesc: 'Περιγραφή είδους',
            sellerItemId: 'Κωδικός είδους πωλητή',
            buyerItemId: 'Κωδικός είδους αγοραστή',
            standardItemId: 'Τυποποιημένος κωδικός είδους (GTIN)',
            originCountry: 'Χώρα προέλευσης',
            classification: 'Ταξινόμηση είδους',
            lineVatCategory: 'Κατηγορία ΦΠΑ γραμμής',
            lineVatRate: 'Συντελεστής ΦΠΑ γραμμής (%)',
            price: 'Τιμή μονάδας',
            baseQuantity: 'Βασική ποσότητα τιμής',
            priceDiscount: 'Έκπτωση τιμής',
            lineAllowance: 'Έκπτωση γραμμής',
            lineAllowanceReason: 'Αιτία έκπτωσης γραμμής',
            orderLineRef: 'Αναφορά γραμμής παραγγελίας',
            linePeriodStart: 'Έναρξη περιόδου γραμμής',
            linePeriodEnd: 'Λήξη περιόδου γραμμής',

            shipmentId: 'Κωδικός αποστολής',
            grossWeight: 'Μικτό βάρος',
            grossVolume: 'Μικτός όγκος',
            trackingId: 'Αριθμός παρακολούθησης',
            estStartDate: 'Εκτιμώμενη παράδοση από (ημερομηνία)',
            estStartTime: 'Εκτιμώμενη παράδοση από (ώρα)',
            estEndDate: 'Εκτιμώμενη παράδοση έως (ημερομηνία)',
            estEndTime: 'Εκτιμώμενη παράδοση έως (ώρα)',
            carrier: 'Μεταφορέας',
            despatchDate: 'Ημερομηνία αποστολής',
            despatchTime: 'Ώρα αποστολής',
            handlingUnit: 'Μονάδα μεταφοράς (SSCC)',
            handlingUnitType: 'Τύπος μονάδας μεταφοράς',
            deliveredQty: 'Παραδοθείσα ποσότητα',
            outstandingQty: 'Εκκρεμής ποσότητα',
            outstandingReason: 'Αιτία εκκρεμούς ποσότητας',
            lot: 'Αριθμός παρτίδας',
            expiry: 'Ανάλωση κατά προτίμηση πριν / λήξη',
            serial: 'Σειριακός αριθμός',
        },
    },
};

export default el;
