import type { ExtraDocTextPack } from './types';

const et: ExtraDocTextPack = {
    titles: {
        invoice: 'Arve',
        credit: 'Kreeditarve',
        corrected: 'Parandatud arve',
        prepayment: 'Ettemaksuarve',
        partial: 'Osaarve',
        selfbilled: 'Ostja koostatud arve',
        despatch: 'Saateleht',
    },
    sample: {
        note: 'Täname koostöö eest!',
        paymentTerms: 'Maksetähtaeg 30 päeva, ilma mahaarvamisteta.',
        creditNote: 'Kreedit ühe tagastatud toote eest (kahjustatud transpordil).',
        correctedNote: 'Käesolev arve parandab algse arve ühikuhinda.',
        prepaymentNote: 'Ettemaks tellimuse {{order}} eest; arvestatakse maha lõpparvest.',
        partialNote: 'Osaarve projekti esimese etapi eest.',
        prepaymentItem: 'Ettemaks ({{pct}} %)',
        discount: 'Püsikliendi allahindlus',
        product: 'Ergonoomiline kontoritool',
        productDesc: 'Must võrkseljatugi, reguleeritavad käetoed',
        service: 'Paigaldus ja seadistamine',
        accessory: 'Põrandakaitsematt',
        despatchNote: 'Palun toimetada kaubavastuvõttu.',
        backorderReason: 'Ajutiselt laost otsas; saabub järgmisel nädalal.',
    },
    objects: {
        newText: 'Uus tekst',
        header: 'Päis {{n}}',
        cell: 'Lahter {{n}}',
        fieldName: 'Välja nimi',
        image: 'Pilt',
        chooseImage: 'Vali pilt',
        newColumn: 'Uus veerg',
        computed: 'Arvutatud',
        formulaLabel: 'Ettemaks (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Dokument',
            refs: 'Viited',
            seller: 'Müüja',
            buyer: 'Ostja',
            payee: 'Makse saaja',
            taxRep: 'Müüja maksuesindaja',
            despatchParty: 'Saatja',
            deliveryParty: 'Kauba saaja',
            orderParty: 'Ostja (tellija)',
            sellerParty: 'Müüja (tarnija)',
            delivery: 'Tarne',
            shipment: 'Saadetis',
            payment: 'Makse',
            allowances: 'Allahindlused / lisatasud',
            totals: 'Kokkuvõte',
            vat: 'KM',
            lines: 'Arveread',
        },
        party: {
            seller: 'Müüja',
            buyer: 'Ostja',
            payee: 'Makse saaja',
            taxRep: 'Maksuesindaja',
            despatch: 'Saatja',
            delivery: 'Saaja',
            order: 'Ostja',
            supplier: 'Tarnija',
        },
        field: {
            name: 'Nimi',
            legalName: 'Ametlik nimi',
            vatId: 'KMKR nr',
            companyId: 'Registrikood',
            endpoint: 'E-arve aadress',
            partyId: 'Tunnus',
            street: 'Tänav',
            street2: 'Aadressi lisarida',
            city: 'Linn',
            postal: 'Postiindeks',
            region: 'Maakond',
            country: 'Riik',
            contact: 'Kontaktisik',
            phone: 'Telefon',
            email: 'E-post',

            invoiceNo: 'Arve number',
            creditNoteNo: 'Kreeditarve number',
            despatchNo: 'Saatelehe number',
            issueDate: 'Väljastamise kuupäev',
            issueTime: 'Väljastamise kellaaeg',
            dueDate: 'Maksetähtaeg',
            typeCode: 'Dokumendi tüübi kood',
            note: 'Märkus',
            taxPointDate: 'Maksustamise kuupäev',
            currency: 'Valuuta',
            taxCurrency: 'KM arvestusvaluuta',
            buyerRef: 'Ostja viide',
            accountingCost: 'Ostja raamatupidamise viide',
            periodStart: 'Arveldusperioodi algus',
            periodEnd: 'Arveldusperioodi lõpp',
            customization: 'Spetsifikatsiooni tunnus',
            profile: 'Äriprotsess',

            orderRef: 'Ostutellimuse viide',
            salesOrderRef: 'Müügitellimuse viide',
            contractRef: 'Lepingu viide',
            projectRef: 'Projekti viide',
            despatchRef: 'Saatelehe viide',
            receiptRef: 'Vastuvõtuteatise viide',
            precedingInvoice: 'Eelnev arve',
            precedingInvoiceDate: 'Eelneva arve kuupäev',
            attachmentId: 'Lisadokument',
            attachmentDesc: 'Lisadokumendi kirjeldus',

            deliveryDate: 'Tarnekuupäev',
            deliveryLocation: 'Tarnekoha tunnus',
            deliverToName: 'Kauba saaja',
            deliveryStreet: 'Tarneaadressi tänav',
            deliveryCity: 'Tarneaadressi linn',
            deliveryPostal: 'Tarneaadressi postiindeks',
            deliveryCountry: 'Tarneriik',

            paymentMeans: 'Makseviisi kood',
            paymentId: 'Viitenumber',
            iban: 'IBAN / kontonumber',
            accountName: 'Konto nimi',
            bic: 'BIC',
            cardNumber: 'Kaardi number',
            mandate: 'Otsekorralduse volitus',
            paymentTerms: 'Maksetingimused',

            allowanceAmount: 'Allahindluse summa',
            allowanceReason: 'Allahindluse põhjus',
            chargeAmount: 'Lisatasu summa',
            chargeReason: 'Lisatasu põhjus',

            lineTotal: 'Arveridade netosummad kokku',
            taxExclusive: 'Kokku käibemaksuta',
            taxInclusive: 'Kokku käibemaksuga',
            allowanceTotal: 'Allahindlused kokku',
            chargeTotal: 'Lisatasud kokku',
            prepaid: 'Tasutud summa',
            rounding: 'Ümardus',
            payable: 'Tasumisele kuuluv summa',

            vatTotal: 'Käibemaks kokku',
            vatBase: 'KM kategooria maksustatav summa',
            vatAmount: 'KM kategooria maksusumma',
            vatCategory: 'KM kategooria kood',
            vatRate: 'KM määr (%)',
            vatExemption: 'KM vabastuse põhjus',
            vatExemptionCode: 'KM vabastuse põhjuse kood',

            lineId: 'Rea number',
            lineNote: 'Rea märkus',
            quantity: 'Kogus',
            unit: 'Ühik',
            lineNet: 'Rea netosumma',
            itemName: 'Kauba nimetus',
            itemDesc: 'Kauba kirjeldus',
            sellerItemId: 'Müüja tootekood',
            buyerItemId: 'Ostja tootekood',
            standardItemId: 'Standardne tootekood (GTIN)',
            originCountry: 'Päritoluriik',
            classification: 'Kauba klassifikatsioon',
            lineVatCategory: 'Rea KM kategooria',
            lineVatRate: 'Rea KM määr (%)',
            price: 'Ühikuhind',
            baseQuantity: 'Hinna baaskogus',
            priceDiscount: 'Hinnaallahindlus',
            lineAllowance: 'Rea allahindlus',
            lineAllowanceReason: 'Rea allahindluse põhjus',
            orderLineRef: 'Tellimuse rea viide',
            linePeriodStart: 'Rea perioodi algus',
            linePeriodEnd: 'Rea perioodi lõpp',

            shipmentId: 'Saadetise tunnus',
            grossWeight: 'Brutokaal',
            grossVolume: 'Brutomaht',
            trackingId: 'Jälgimisnumber',
            estStartDate: 'Eeldatav tarne alates (kuupäev)',
            estStartTime: 'Eeldatav tarne alates (kellaaeg)',
            estEndDate: 'Eeldatav tarne kuni (kuupäev)',
            estEndTime: 'Eeldatav tarne kuni (kellaaeg)',
            carrier: 'Vedaja',
            despatchDate: 'Lähetamise kuupäev',
            despatchTime: 'Lähetamise kellaaeg',
            handlingUnit: 'Transpordiühik (SSCC)',
            handlingUnitType: 'Transpordiühiku tüüp',
            deliveredQty: 'Tarnitud kogus',
            outstandingQty: 'Tarnimata kogus',
            outstandingReason: 'Tarnimata jäämise põhjus',
            lot: 'Partii number',
            expiry: 'Parim enne / kõlblik kuni',
            serial: 'Seerianumber',
        },
    },
};

export default et;
