import type { ExtraDocTextPack } from './types';

const eu: ExtraDocTextPack = {
    titles: {
        invoice: 'Faktura',
        credit: 'Faktura zuzentzailea (abonua)',
        corrected: 'Faktura zuzentzailea',
        prepayment: 'Aurrerakin-faktura',
        partial: 'Faktura partziala',
        selfbilled: 'Autofaktura',
        despatch: 'Albarana',
    },
    sample: {
        note: 'Eskerrik asko zuen konfiantzagatik.',
        paymentTerms: 'Ordainketa 30 egunera, deskonturik gabe.',
        creditNote: 'Itzulitako artikulu baten abonua (garraioan kaltetua).',
        correctedNote: 'Faktura honek jatorrizko fakturaren unitate-prezioa zuzentzen du.',
        prepaymentNote: '{{order}} eskaeraren aurrerakina; azken fakturatik kenduko da.',
        partialNote: 'Proiektuaren lehen faseko faktura partziala.',
        prepaymentItem: 'Aurrerakina ({{pct}} %)',
        discount: 'Leialtasun-deskontua',
        product: 'Bulegoko aulki ergonomikoa',
        productDesc: 'Sare beltzeko bizkarraldea, beso-euskarri erregulagarriak',
        service: 'Instalazioa eta abiaraztea',
        accessory: 'Zorua babesteko alfonbra',
        despatchNote: 'Mesedez, entregatu salgaien sarreran.',
        backorderReason: 'Aldi baterako stockik gabe; datorren astean bidaliko da.',
    },
    objects: {
        newText: 'Testu berria',
        header: 'Goiburua {{n}}',
        cell: 'Gelaxka {{n}}',
        fieldName: 'Eremuaren izena',
        image: 'Irudia',
        chooseImage: 'Aukeratu irudi bat',
        newColumn: 'Zutabe berria',
        computed: 'Kalkulatua',
        formulaLabel: 'Aurrerakina (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Dokumentua',
            refs: 'Erreferentziak',
            seller: 'Saltzailea',
            buyer: 'Eroslea',
            payee: 'Onuraduna',
            taxRep: 'Saltzailearen ordezkari fiskala',
            despatchParty: 'Bidaltzailea',
            deliveryParty: 'Hartzailea',
            orderParty: 'Eroslea (eskatzailea)',
            sellerParty: 'Saltzailea (hornitzailea)',
            delivery: 'Entrega',
            shipment: 'Bidalketa',
            payment: 'Ordainketa',
            allowances: 'Deskontuak / kargak',
            totals: 'Guztizkoak',
            vat: 'BEZ',
            lines: 'Lerroak',
        },
        party: {
            seller: 'Saltzailea',
            buyer: 'Eroslea',
            payee: 'Onuraduna',
            taxRep: 'Ordezkari fiskala',
            despatch: 'Bidaltzailea',
            delivery: 'Hartzailea',
            order: 'Eroslea',
            supplier: 'Hornitzailea',
        },
        field: {
            name: 'Izena',
            legalName: 'Izen soziala',
            vatId: 'BEZ identifikazio-zenbakia',
            companyId: 'Erregistro-zenbakia',
            endpoint: 'Helbide elektronikoa',
            partyId: 'Identifikatzailea',
            street: 'Kalea',
            street2: 'Helbide osagarria',
            city: 'Herria',
            postal: 'Posta-kodea',
            region: 'Probintzia',
            country: 'Herrialdea',
            contact: 'Harremanetarako pertsona',
            phone: 'Telefonoa',
            email: 'Posta elektronikoa',

            invoiceNo: 'Faktura-zenbakia',
            creditNoteNo: 'Faktura zuzentzailearen zenbakia',
            despatchNo: 'Albaran-zenbakia',
            issueDate: 'Jaulkipen-data',
            issueTime: 'Jaulkipen-ordua',
            dueDate: 'Muga-eguna',
            typeCode: 'Dokumentu-motaren kodea',
            note: 'Oharra',
            taxPointDate: 'BEZaren sortzapen-data',
            currency: 'Moneta',
            taxCurrency: 'BEZa kontabilizatzeko moneta',
            buyerRef: 'Eroslearen erreferentzia',
            accountingCost: 'Eroslearen kontabilitate-erreferentzia',
            periodStart: 'Fakturazio-aldiaren hasiera',
            periodEnd: 'Fakturazio-aldiaren amaiera',
            customization: 'Espezifikazioaren identifikatzailea',
            profile: 'Negozio-prozesua',

            orderRef: 'Erosketa-eskaeraren erreferentzia',
            salesOrderRef: 'Salmenta-eskaeraren erreferentzia',
            contractRef: 'Kontratuaren erreferentzia',
            projectRef: 'Proiektuaren erreferentzia',
            despatchRef: 'Albaranaren erreferentzia',
            receiptRef: 'Harrera-abisuaren erreferentzia',
            precedingInvoice: 'Aurreko faktura',
            precedingInvoiceDate: 'Aurreko fakturaren data',
            attachmentId: 'Erantsitako dokumentua',
            attachmentDesc: 'Erantsitako dokumentuaren deskribapena',

            deliveryDate: 'Entrega-data',
            deliveryLocation: 'Entrega-lekuaren IDa',
            deliverToName: 'Entregaren hartzailea',
            deliveryStreet: 'Entrega-kalea',
            deliveryCity: 'Entrega-herria',
            deliveryPostal: 'Entregako posta-kodea',
            deliveryCountry: 'Entrega-herrialdea',

            paymentMeans: 'Ordainbidearen kodea',
            paymentId: 'Ordainketa-erreferentzia',
            iban: 'IBAN / kontu-zenbakia',
            accountName: 'Kontuaren titularra',
            bic: 'BIC',
            cardNumber: 'Txartel-zenbakia',
            mandate: 'Helbideratze-agindua',
            paymentTerms: 'Ordainketa-baldintzak',

            allowanceAmount: 'Deskontuaren zenbatekoa',
            allowanceReason: 'Deskontuaren arrazoia',
            chargeAmount: 'Kargaren zenbatekoa',
            chargeReason: 'Kargaren arrazoia',

            lineTotal: 'Lerroen zenbateko garbien batura',
            taxExclusive: 'Guztira BEZik gabe',
            taxInclusive: 'Guztira BEZa barne',
            allowanceTotal: 'Deskontuak guztira',
            chargeTotal: 'Kargak guztira',
            prepaid: 'Ordaindutako zenbatekoa',
            rounding: 'Biribiltzea',
            payable: 'Ordaintzeko zenbatekoa',

            vatTotal: 'BEZ kuota guztira',
            vatBase: 'Zerga-oinarria BEZ kategoriaka',
            vatAmount: 'Kuota BEZ kategoriaka',
            vatCategory: 'BEZ kategoriaren kodea',
            vatRate: 'BEZ tasa (%)',
            vatExemption: 'BEZ salbuespenaren arrazoia',
            vatExemptionCode: 'BEZ salbuespenaren arrazoiaren kodea',

            lineId: 'Lerro-zenbakia',
            lineNote: 'Lerroko oharra',
            quantity: 'Kantitatea',
            unit: 'Neurri-unitatea',
            lineNet: 'Lerroaren zenbateko garbia',
            itemName: 'Artikuluaren izena',
            itemDesc: 'Artikuluaren deskribapena',
            sellerItemId: 'Saltzailearen artikulu-kodea',
            buyerItemId: 'Eroslearen artikulu-kodea',
            standardItemId: 'Artikuluaren kode estandarra (GTIN)',
            originCountry: 'Jatorrizko herrialdea',
            classification: 'Artikuluaren sailkapena',
            lineVatCategory: 'Lerroaren BEZ kategoria',
            lineVatRate: 'Lerroaren BEZ tasa (%)',
            price: 'Unitate-prezioa',
            baseQuantity: 'Prezioaren oinarrizko kantitatea',
            priceDiscount: 'Prezioaren gaineko deskontua',
            lineAllowance: 'Lerroko deskontua',
            lineAllowanceReason: 'Lerroko deskontuaren arrazoia',
            orderLineRef: 'Eskaera-lerroaren erreferentzia',
            linePeriodStart: 'Lerroaren aldiaren hasiera',
            linePeriodEnd: 'Lerroaren aldiaren amaiera',

            shipmentId: 'Bidalketaren IDa',
            grossWeight: 'Pisu gordina',
            grossVolume: 'Bolumen gordina',
            trackingId: 'Jarraipen-zenbakia',
            estStartDate: 'Aurreikusitako entrega noiztik (data)',
            estStartTime: 'Aurreikusitako entrega noiztik (ordua)',
            estEndDate: 'Aurreikusitako entrega noiz arte (data)',
            estEndTime: 'Aurreikusitako entrega noiz arte (ordua)',
            carrier: 'Garraiolaria',
            despatchDate: 'Bidalketa-data',
            despatchTime: 'Bidalketa-ordua',
            handlingUnit: 'Manipulazio-unitatea (SSCC)',
            handlingUnitType: 'Manipulazio-unitatearen mota',
            deliveredQty: 'Entregatutako kantitatea',
            outstandingQty: 'Zain dagoen kantitatea',
            outstandingReason: 'Zain dagoen kantitatearen arrazoia',
            lot: 'Lote-zenbakia',
            expiry: 'Kontsumo lehenetsia / iraungitze-data',
            serial: 'Serie-zenbakia',
        },
    },
};

export default eu;
