import type { ExtraDocTextPack } from './types';

const fi: ExtraDocTextPack = {
    titles: {
        invoice: 'Lasku',
        credit: 'Hyvityslasku',
        corrected: 'Korjattu lasku',
        prepayment: 'Ennakkolasku',
        partial: 'Osalasku',
        selfbilled: 'Itselaskutus',
        despatch: 'Lähete',
    },
    sample: {
        note: 'Kiitos kaupasta!',
        paymentTerms: 'Maksuehto 30 päivää netto.',
        creditNote: 'Hyvitys yhdestä palautetusta tuotteesta (vaurioitunut kuljetuksessa).',
        correctedNote: 'Tämä lasku korjaa alkuperäisen laskun yksikköhinnan.',
        prepaymentNote: 'Ennakkomaksu tilauksesta {{order}}; vähennetään loppulaskusta.',
        partialNote: 'Osalasku projektin ensimmäisestä vaiheesta.',
        prepaymentItem: 'Ennakkomaksu ({{pct}} %)',
        discount: 'Kanta-asiakasalennus',
        product: 'Ergonominen toimistotuoli',
        productDesc: 'Musta verkkoselkänoja, säädettävät käsinojat',
        service: 'Asennus ja käyttöönotto',
        accessory: 'Lattiansuojamatto',
        despatchNote: 'Toimitus tavaravastaanottoon.',
        backorderReason: 'Tilapäisesti loppu varastosta; toimitetaan ensi viikolla.',
    },
    objects: {
        newText: 'Uusi teksti',
        header: 'Otsikko {{n}}',
        cell: 'Solu {{n}}',
        fieldName: 'Kentän nimi',
        image: 'Kuva',
        chooseImage: 'Valitse kuva',
        newColumn: 'Uusi sarake',
        computed: 'Laskettu',
        formulaLabel: 'Ennakkomaksu (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Asiakirja',
            refs: 'Viitteet',
            seller: 'Myyjä',
            buyer: 'Ostaja',
            payee: 'Maksunsaaja',
            taxRep: 'Myyjän veroedustaja',
            despatchParty: 'Lähettäjä',
            deliveryParty: 'Toimituksen vastaanottaja',
            orderParty: 'Ostaja (tilaaja)',
            sellerParty: 'Myyjä (toimittaja)',
            delivery: 'Toimitus',
            shipment: 'Lähetys',
            payment: 'Maksu',
            allowances: 'Alennukset / lisämaksut',
            totals: 'Yhteissummat',
            vat: 'ALV',
            lines: 'Laskurivit',
        },
        party: {
            seller: 'Myyjä',
            buyer: 'Ostaja',
            payee: 'Maksunsaaja',
            taxRep: 'Veroedustaja',
            despatch: 'Lähettäjä',
            delivery: 'Vastaanottaja',
            order: 'Ostaja',
            supplier: 'Toimittaja',
        },
        field: {
            name: 'Nimi',
            legalName: 'Virallinen nimi',
            vatId: 'ALV-tunniste',
            companyId: 'Y-tunnus',
            endpoint: 'Sähköinen osoite',
            partyId: 'Tunniste',
            street: 'Katuosoite',
            street2: 'Lisäosoite',
            city: 'Postitoimipaikka',
            postal: 'Postinumero',
            region: 'Alue',
            country: 'Maa',
            contact: 'Yhteyshenkilö',
            phone: 'Puhelin',
            email: 'Sähköposti',

            invoiceNo: 'Laskun numero',
            creditNoteNo: 'Hyvityslaskun numero',
            despatchNo: 'Lähetysilmoituksen numero',
            issueDate: 'Päivämäärä',
            issueTime: 'Kellonaika',
            dueDate: 'Eräpäivä',
            typeCode: 'Asiakirjatyypin koodi',
            note: 'Huomautus',
            taxPointDate: 'Veron suoritusperusteen päivä',
            currency: 'Valuutta',
            taxCurrency: 'ALV:n kirjanpitovaluutta',
            buyerRef: 'Ostajan viite',
            accountingCost: 'Ostajan kirjanpitoviite',
            periodStart: 'Laskutuskauden alku',
            periodEnd: 'Laskutuskauden loppu',
            customization: 'Määrittelyn tunniste',
            profile: 'Liiketoimintaprosessi',

            orderRef: 'Ostotilauksen viite',
            salesOrderRef: 'Myyntitilauksen viite',
            contractRef: 'Sopimusviite',
            projectRef: 'Projektiviite',
            despatchRef: 'Lähetysilmoituksen viite',
            receiptRef: 'Vastaanottoilmoituksen viite',
            precedingInvoice: 'Aiempi lasku',
            precedingInvoiceDate: 'Aiemman laskun päivämäärä',
            attachmentId: 'Liiteasiakirja',
            attachmentDesc: 'Liiteasiakirjan kuvaus',

            deliveryDate: 'Toimituspäivä',
            deliveryLocation: 'Toimituspaikan tunniste',
            deliverToName: 'Toimituksen vastaanottaja',
            deliveryStreet: 'Toimitusosoite',
            deliveryCity: 'Toimituksen postitoimipaikka',
            deliveryPostal: 'Toimituksen postinumero',
            deliveryCountry: 'Toimitusmaa',

            paymentMeans: 'Maksutavan koodi',
            paymentId: 'Viitenumero',
            iban: 'IBAN / tilinumero',
            accountName: 'Tilin nimi',
            bic: 'BIC',
            cardNumber: 'Kortin numero',
            mandate: 'Suoraveloitusvaltuutus',
            paymentTerms: 'Maksuehdot',

            allowanceAmount: 'Alennuksen määrä',
            allowanceReason: 'Alennuksen syy',
            chargeAmount: 'Lisämaksun määrä',
            chargeReason: 'Lisämaksun syy',

            lineTotal: 'Rivien nettosummat yhteensä',
            taxExclusive: 'Yhteensä ilman ALV:tä',
            taxInclusive: 'Yhteensä sis. ALV',
            allowanceTotal: 'Alennukset yhteensä',
            chargeTotal: 'Lisämaksut yhteensä',
            prepaid: 'Maksettu summa',
            rounding: 'Pyöristys',
            payable: 'Maksettava',

            vatTotal: 'ALV yhteensä',
            vatBase: 'ALV-luokan veron peruste',
            vatAmount: 'ALV-luokan veron määrä',
            vatCategory: 'ALV-luokan koodi',
            vatRate: 'ALV-kanta (%)',
            vatExemption: 'ALV-vapautuksen syy',
            vatExemptionCode: 'ALV-vapautuksen syykoodi',

            lineId: 'Rivinumero',
            lineNote: 'Rivin huomautus',
            quantity: 'Määrä',
            unit: 'Yksikkö',
            lineNet: 'Rivin nettosumma',
            itemName: 'Tuotteen nimi',
            itemDesc: 'Tuotteen kuvaus',
            sellerItemId: 'Myyjän tuotetunniste',
            buyerItemId: 'Ostajan tuotetunniste',
            standardItemId: 'Vakiotuotetunniste (GTIN)',
            originCountry: 'Alkuperämaa',
            classification: 'Tuoteluokitus',
            lineVatCategory: 'Rivin ALV-luokka',
            lineVatRate: 'Rivin ALV-kanta (%)',
            price: 'Yksikköhinta',
            baseQuantity: 'Hinnan perusmäärä',
            priceDiscount: 'Hinnan alennus',
            lineAllowance: 'Rivin alennus',
            lineAllowanceReason: 'Rivin alennuksen syy',
            orderLineRef: 'Tilausrivin viite',
            linePeriodStart: 'Rivin jakson alku',
            linePeriodEnd: 'Rivin jakson loppu',

            shipmentId: 'Lähetyksen tunniste',
            grossWeight: 'Bruttopaino',
            grossVolume: 'Bruttotilavuus',
            trackingId: 'Seurantanumero',
            estStartDate: 'Arvioitu toimitus alkaen (pvm)',
            estStartTime: 'Arvioitu toimitus alkaen (klo)',
            estEndDate: 'Arvioitu toimitus viimeistään (pvm)',
            estEndTime: 'Arvioitu toimitus viimeistään (klo)',
            carrier: 'Kuljetusliike',
            despatchDate: 'Lähetyspäivä',
            despatchTime: 'Lähetysaika',
            handlingUnit: 'Kuljetusyksikkö (SSCC)',
            handlingUnitType: 'Kuljetusyksikön tyyppi',
            deliveredQty: 'Toimitettu määrä',
            outstandingQty: 'Toimittamatta oleva määrä',
            outstandingReason: 'Toimittamatta jäämisen syy',
            lot: 'Eränumero',
            expiry: 'Parasta ennen / viimeinen käyttöpäivä',
            serial: 'Sarjanumero',
        },
    },
};

export default fi;
