import type { ExtraDocTextPack } from './types';

const ga: ExtraDocTextPack = {
    titles: {
        invoice: 'Sonrasc',
        credit: 'Nóta creidmheasa',
        corrected: 'Sonrasc ceartaithe',
        prepayment: 'Sonrasc réamhíocaíochta',
        partial: 'Sonrasc páirteach',
        selfbilled: 'Sonrasc féinbhillithe',
        despatch: 'Nóta seachadta',
    },
    sample: {
        note: 'Go raibh maith agat as do ghnó.',
        paymentTerms: 'Iníoctha laistigh de 30 lá gan asbhaint.',
        creditNote: 'Creidmheas as earra amháin a seoladh ar ais (damáiste le linn iompair).',
        correctedNote: 'Ceartaíonn an sonrasc seo praghas aonaid an tsonraisc bhunaidh.',
        prepaymentNote: 'Réamhíocaíocht don ordú {{order}}; asbhainfear í ón sonrasc deiridh.',
        partialNote: 'Sonrasc páirteach do chéad chéim an tionscadail.',
        prepaymentItem: 'Réamhíocaíocht ({{pct}}%)',
        discount: 'Lascaine dílseachta',
        product: 'Cathaoir oifige eirgeanamaíoch',
        productDesc: 'Droim mogalra dubh, tacaí uillinne inchoigeartaithe',
        service: 'Suiteáil agus socrú',
        accessory: 'Mata cosanta urláir',
        despatchNote: 'Seachaid chuig bealach isteach na n-earraí, le do thoil.',
        backorderReason: 'As stoc go sealadach; seolfar an tseachtain seo chugainn é.',
    },
    objects: {
        newText: 'Téacs nua',
        header: 'Ceanntásc {{n}}',
        cell: 'Cill {{n}}',
        fieldName: 'Ainm réimse',
        image: 'Íomhá',
        chooseImage: 'Roghnaigh íomhá',
        newColumn: 'Colún nua',
        computed: 'Ríofa',
        formulaLabel: 'Réamhíocaíocht (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Doiciméad',
            refs: 'Tagairtí',
            seller: 'Díoltóir',
            buyer: 'Ceannaitheoir',
            payee: 'Íocaí',
            taxRep: 'Ionadaí cánach an díoltóra',
            despatchParty: 'Páirtí seolta',
            deliveryParty: 'Páirtí seachadta',
            orderParty: 'Ceannaitheoir (ordaitheoir)',
            sellerParty: 'Díoltóir (soláthraí)',
            delivery: 'Seachadadh',
            shipment: 'Lastas',
            payment: 'Íocaíocht',
            allowances: 'Lascainí / muirir',
            totals: 'Iomláin',
            vat: 'CBL',
            lines: 'Míreanna líne',
        },
        party: {
            seller: 'Díoltóir',
            buyer: 'Ceannaitheoir',
            payee: 'Íocaí',
            taxRep: 'Ionadaí cánach',
            despatch: 'Seoltóir',
            delivery: 'Faighteoir',
            order: 'Ceannaitheoir',
            supplier: 'Soláthraí',
        },
        field: {
            name: 'Ainm',
            legalName: 'Ainm dlíthiúil',
            vatId: 'Uimhir CBL',
            companyId: 'Uimhir chláraithe',
            endpoint: 'Seoladh leictreonach',
            partyId: 'Aitheantóir',
            street: 'Sráid',
            street2: 'Líne bhreise seolta',
            city: 'Baile / cathair',
            postal: 'Cód poist',
            region: 'Réigiún',
            country: 'Tír',
            contact: 'Duine teagmhála',
            phone: 'Teileafón',
            email: 'Ríomhphost',

            invoiceNo: 'Uimhir an tsonraisc',
            creditNoteNo: 'Uimhir an nóta creidmheasa',
            despatchNo: 'Uimhir an fhógra seolta',
            issueDate: 'Dáta eisiúna',
            issueTime: 'Am eisiúna',
            dueDate: 'Dáta dlite',
            typeCode: 'Cód chineál an doiciméid',
            note: 'Nóta',
            taxPointDate: 'Dáta an phointe cánach',
            currency: 'Airgeadra',
            taxCurrency: 'Airgeadra cuntasaíochta CBL',
            buyerRef: 'Tagairt an cheannaitheora',
            accountingCost: 'Tagairt chuntasaíochta an cheannaitheora',
            periodStart: 'Tús na tréimhse sonrascaithe',
            periodEnd: 'Deireadh na tréimhse sonrascaithe',
            customization: 'Aitheantóir sonraíochta',
            profile: 'Próiseas gnó',

            orderRef: 'Tagairt an ordaithe ceannaigh',
            salesOrderRef: 'Tagairt an ordaithe díolacháin',
            contractRef: 'Tagairt an chonartha',
            projectRef: 'Tagairt an tionscadail',
            despatchRef: 'Tagairt an fhógra seolta',
            receiptRef: 'Tagairt an fhógra glactha',
            precedingInvoice: 'Sonrasc roimhe seo',
            precedingInvoiceDate: 'Dáta an tsonraisc roimhe seo',
            attachmentId: 'Doiciméad tacaíochta',
            attachmentDesc: 'Cur síos ar an doiciméad tacaíochta',

            deliveryDate: 'Dáta seachadta',
            deliveryLocation: 'ID na láthrach seachadta',
            deliverToName: 'Faighteoir an tseachadta',
            deliveryStreet: 'Sráid seachadta',
            deliveryCity: 'Baile / cathair seachadta',
            deliveryPostal: 'Cód poist seachadta',
            deliveryCountry: 'Tír seachadta',

            paymentMeans: 'Cód mhodh íocaíochta',
            paymentId: 'Tagairt íocaíochta',
            iban: 'IBAN / uimhir chuntais',
            accountName: 'Ainm an chuntais',
            bic: 'BIC',
            cardNumber: 'Uimhir an chárta',
            mandate: 'Sainordú dochair dhírigh',
            paymentTerms: 'Téarmaí íocaíochta',

            allowanceAmount: 'Méid an lascaine',
            allowanceReason: 'Cúis an lascaine',
            chargeAmount: 'Méid an mhuirir',
            chargeReason: 'Cúis an mhuirir',

            lineTotal: 'Suim na nglanmhéideanna líne',
            taxExclusive: 'Iomlán gan CBL',
            taxInclusive: 'Iomlán le CBL',
            allowanceTotal: 'Suim na lascainí',
            chargeTotal: 'Suim na muirear',
            prepaid: 'Méid íoctha',
            rounding: 'Méid slánaithe',
            payable: 'Méid dlite',

            vatTotal: 'Méid iomlán CBL',
            vatBase: 'Méid incháinithe de réir chatagóir CBL',
            vatAmount: 'Méid cánach de réir chatagóir CBL',
            vatCategory: 'Cód chatagóir CBL',
            vatRate: 'Ráta CBL (%)',
            vatExemption: 'Cúis díolúine ó CBL',
            vatExemptionCode: 'Cód chúis díolúine ó CBL',

            lineId: 'Uimhir líne',
            lineNote: 'Nóta líne',
            quantity: 'Cainníocht',
            unit: 'Aonad',
            lineNet: 'Glanmhéid líne',
            itemName: 'Ainm na míre',
            itemDesc: 'Cur síos ar an mír',
            sellerItemId: 'ID míre an díoltóra',
            buyerItemId: 'ID míre an cheannaitheora',
            standardItemId: 'ID caighdeánach míre (GTIN)',
            originCountry: 'Tír thionscnaimh',
            classification: 'Aicmiú míre',
            lineVatCategory: 'Catagóir CBL na líne',
            lineVatRate: 'Ráta CBL na líne (%)',
            price: 'Praghas aonaid',
            baseQuantity: 'Bunchainníocht praghais',
            priceDiscount: 'Lascaine praghais',
            lineAllowance: 'Lascaine líne',
            lineAllowanceReason: 'Cúis lascaine líne',
            orderLineRef: 'Tagairt líne ordaithe',
            linePeriodStart: 'Tús thréimhse na líne',
            linePeriodEnd: 'Deireadh thréimhse na líne',

            shipmentId: 'ID an lastais',
            grossWeight: 'Meáchan comhlán',
            grossVolume: 'Toirt chomhlán',
            trackingId: 'Uimhir rianaithe',
            estStartDate: 'Seachadadh measta ó (dáta)',
            estStartTime: 'Seachadadh measta ó (am)',
            estEndDate: 'Seachadadh measta go dtí (dáta)',
            estEndTime: 'Seachadadh measta go dtí (am)',
            carrier: 'Iompróir',
            despatchDate: 'Dáta seolta',
            despatchTime: 'Am seolta',
            handlingUnit: 'Aonad láimhseála iompair (SSCC)',
            handlingUnitType: 'Cineál aonaid láimhseála',
            deliveredQty: 'Cainníocht seachadta',
            outstandingQty: 'Cainníocht fós le seachadadh',
            outstandingReason: 'Cúis na cainníochta atá fós le seachadadh',
            lot: 'Uimhir baisce',
            expiry: 'Is fearr roimh / dáta éaga',
            serial: 'Sraithuimhir',
        },
    },
};

export default ga;
