import type { ExtraDocTextPack } from './types';

const gl: ExtraDocTextPack = {
    titles: {
        invoice: 'Factura',
        credit: 'Factura rectificativa (abono)',
        corrected: 'Factura rectificativa',
        prepayment: 'Factura de anticipo',
        partial: 'Factura parcial',
        selfbilled: 'Autofactura',
        despatch: 'Albará',
    },
    sample: {
        note: 'Grazas pola súa confianza.',
        paymentTerms: 'Pagamento a 30 días, sen desconto.',
        creditNote: 'Abono por un artigo devolto (danado durante o transporte).',
        correctedNote: 'Esta factura rectifica o prezo unitario da factura orixinal.',
        prepaymentNote: 'Anticipo do pedido {{order}}; descontarase da factura final.',
        partialNote: 'Factura parcial da primeira fase do proxecto.',
        prepaymentItem: 'Anticipo ({{pct}} %)',
        discount: 'Desconto por fidelidade',
        product: 'Cadeira de oficina ergonómica',
        productDesc: 'Respaldo de malla negro, apoiabrazos regulables',
        service: 'Instalación e posta en marcha',
        accessory: 'Alfombra protectora do chan',
        despatchNote: 'Entregar na entrada de mercadorías.',
        backorderReason: 'Sen existencias temporalmente; envíase a próxima semana.',
    },
    objects: {
        newText: 'Texto novo',
        header: 'Cabeceira {{n}}',
        cell: 'Cela {{n}}',
        fieldName: 'Nome do campo',
        image: 'Imaxe',
        chooseImage: 'Escolla unha imaxe',
        newColumn: 'Columna nova',
        computed: 'Calculado',
        formulaLabel: 'Anticipo (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Documento',
            refs: 'Referencias',
            seller: 'Vendedor',
            buyer: 'Comprador',
            payee: 'Beneficiario',
            taxRep: 'Representante fiscal do vendedor',
            despatchParty: 'Expedidor',
            deliveryParty: 'Destinatario',
            orderParty: 'Comprador (solicitante)',
            sellerParty: 'Vendedor (provedor)',
            delivery: 'Entrega',
            shipment: 'Envío',
            payment: 'Pagamento',
            allowances: 'Descontos / cargos',
            totals: 'Totais',
            vat: 'IVE',
            lines: 'Liñas',
        },
        party: {
            seller: 'Vendedor',
            buyer: 'Comprador',
            payee: 'Beneficiario',
            taxRep: 'Representante fiscal',
            despatch: 'Expedidor',
            delivery: 'Destinatario',
            order: 'Comprador',
            supplier: 'Provedor',
        },
        field: {
            name: 'Nome',
            legalName: 'Razón social',
            vatId: 'NIF-IVE',
            companyId: 'Número de rexistro',
            endpoint: 'Enderezo electrónico',
            partyId: 'Identificador',
            street: 'Rúa',
            street2: 'Enderezo adicional',
            city: 'Localidade',
            postal: 'Código postal',
            region: 'Provincia',
            country: 'País',
            contact: 'Persoa de contacto',
            phone: 'Teléfono',
            email: 'Correo electrónico',

            invoiceNo: 'Número de factura',
            creditNoteNo: 'Número de factura rectificativa',
            despatchNo: 'Número de albará',
            issueDate: 'Data de emisión',
            issueTime: 'Hora de emisión',
            dueDate: 'Data de vencemento',
            typeCode: 'Código de tipo de documento',
            note: 'Nota',
            taxPointDate: 'Data de devindicación do IVE',
            currency: 'Moeda',
            taxCurrency: 'Moeda de contabilización do IVE',
            buyerRef: 'Referencia do comprador',
            accountingCost: 'Referencia contable do comprador',
            periodStart: 'Inicio do período de facturación',
            periodEnd: 'Fin do período de facturación',
            customization: 'Identificador da especificación',
            profile: 'Proceso de negocio',

            orderRef: 'Referencia do pedido de compra',
            salesOrderRef: 'Referencia do pedido de venda',
            contractRef: 'Referencia do contrato',
            projectRef: 'Referencia do proxecto',
            despatchRef: 'Referencia do albará',
            receiptRef: 'Referencia do aviso de recepción',
            precedingInvoice: 'Factura anterior',
            precedingInvoiceDate: 'Data da factura anterior',
            attachmentId: 'Documento anexo',
            attachmentDesc: 'Descrición do documento anexo',

            deliveryDate: 'Data de entrega',
            deliveryLocation: 'ID do lugar de entrega',
            deliverToName: 'Destinatario da entrega',
            deliveryStreet: 'Rúa de entrega',
            deliveryCity: 'Localidade de entrega',
            deliveryPostal: 'Código postal de entrega',
            deliveryCountry: 'País de entrega',

            paymentMeans: 'Código do medio de pagamento',
            paymentId: 'Referencia de pagamento',
            iban: 'IBAN / número de conta',
            accountName: 'Titular da conta',
            bic: 'BIC',
            cardNumber: 'Número de tarxeta',
            mandate: 'Mandato de domiciliación bancaria',
            paymentTerms: 'Condicións de pagamento',

            allowanceAmount: 'Importe do desconto',
            allowanceReason: 'Motivo do desconto',
            chargeAmount: 'Importe do cargo',
            chargeReason: 'Motivo do cargo',

            lineTotal: 'Suma dos importes netos das liñas',
            taxExclusive: 'Total sen IVE',
            taxInclusive: 'Total con IVE',
            allowanceTotal: 'Total de descontos',
            chargeTotal: 'Total de cargos',
            prepaid: 'Importe pagado',
            rounding: 'Arredondamento',
            payable: 'Importe a pagar',

            vatTotal: 'Cota total de IVE',
            vatBase: 'Base impoñible por categoría de IVE',
            vatAmount: 'Cota por categoría de IVE',
            vatCategory: 'Código de categoría de IVE',
            vatRate: 'Tipo de IVE (%)',
            vatExemption: 'Motivo de exención de IVE',
            vatExemptionCode: 'Código do motivo de exención de IVE',

            lineId: 'Número de liña',
            lineNote: 'Nota da liña',
            quantity: 'Cantidade',
            unit: 'Unidade de medida',
            lineNet: 'Importe neto da liña',
            itemName: 'Nome do artigo',
            itemDesc: 'Descrición do artigo',
            sellerItemId: 'Código de artigo do vendedor',
            buyerItemId: 'Código de artigo do comprador',
            standardItemId: 'Código estándar do artigo (GTIN)',
            originCountry: 'País de orixe',
            classification: 'Clasificación do artigo',
            lineVatCategory: 'Categoría de IVE da liña',
            lineVatRate: 'Tipo de IVE da liña (%)',
            price: 'Prezo unitario',
            baseQuantity: 'Cantidade base do prezo',
            priceDiscount: 'Desconto sobre o prezo',
            lineAllowance: 'Desconto de liña',
            lineAllowanceReason: 'Motivo do desconto de liña',
            orderLineRef: 'Referencia da liña de pedido',
            linePeriodStart: 'Inicio do período da liña',
            linePeriodEnd: 'Fin do período da liña',

            shipmentId: 'ID do envío',
            grossWeight: 'Peso bruto',
            grossVolume: 'Volume bruto',
            trackingId: 'Número de seguimento',
            estStartDate: 'Entrega prevista desde (data)',
            estStartTime: 'Entrega prevista desde (hora)',
            estEndDate: 'Entrega prevista ata (data)',
            estEndTime: 'Entrega prevista ata (hora)',
            carrier: 'Transportista',
            despatchDate: 'Data de expedición',
            despatchTime: 'Hora de expedición',
            handlingUnit: 'Unidade de manipulación (SSCC)',
            handlingUnitType: 'Tipo de unidade de manipulación',
            deliveredQty: 'Cantidade entregada',
            outstandingQty: 'Cantidade pendente',
            outstandingReason: 'Motivo da cantidade pendente',
            lot: 'Número de lote',
            expiry: 'Consumo preferente / data de caducidade',
            serial: 'Número de serie',
        },
    },
};

export default gl;
