import type { ExtraDocTextPack } from './types';

const hr: ExtraDocTextPack = {
    titles: {
        invoice: 'Račun',
        credit: 'Knjižno odobrenje',
        corrected: 'Ispravak računa',
        prepayment: 'Račun za predujam',
        partial: 'Djelomični račun',
        selfbilled: 'Račun (samoizdavanje)',
        despatch: 'Otpremnica',
    },
    sample: {
        note: 'Zahvaljujemo na suradnji.',
        paymentTerms: 'Plativo u roku od 30 dana bez odbitka.',
        creditNote: 'Odobrenje za jedan vraćeni artikl (oštećen u prijevozu).',
        correctedNote: 'Ovaj račun ispravlja jediničnu cijenu izvornog računa.',
        prepaymentNote: 'Predujam za narudžbu {{order}}; bit će odbijen od konačnog računa.',
        partialNote: 'Djelomični račun za prvu fazu projekta.',
        prepaymentItem: 'Predujam ({{pct}} %)',
        discount: 'Popust za vjerne kupce',
        product: 'Ergonomska uredska stolica',
        productDesc: 'Crni mrežasti naslon, podesivi naslonjači za ruke',
        service: 'Montaža i postavljanje',
        accessory: 'Zaštitna podloga za pod',
        despatchNote: 'Molimo dostavite na ulaz za robu.',
        backorderReason: 'Privremeno nema na zalihi; stiže sljedeći tjedan.',
    },
    objects: {
        newText: 'Novi tekst',
        header: 'Zaglavlje {{n}}',
        cell: 'Ćelija {{n}}',
        fieldName: 'Naziv polja',
        image: 'Slika',
        chooseImage: 'Odaberite sliku',
        newColumn: 'Novi stupac',
        computed: 'Izračunato',
        formulaLabel: 'Predujam (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Dokument',
            refs: 'Reference',
            seller: 'Prodavatelj',
            buyer: 'Kupac',
            payee: 'Primatelj plaćanja',
            taxRep: 'Porezni zastupnik prodavatelja',
            despatchParty: 'Pošiljatelj',
            deliveryParty: 'Primatelj robe',
            orderParty: 'Kupac (naručitelj)',
            sellerParty: 'Prodavatelj (dobavljač)',
            delivery: 'Isporuka',
            shipment: 'Pošiljka',
            payment: 'Plaćanje',
            allowances: 'Popusti / dodatni troškovi',
            totals: 'Ukupni iznosi',
            vat: 'PDV',
            lines: 'Stavke',
        },
        party: {
            seller: 'Prodavatelj',
            buyer: 'Kupac',
            payee: 'Primatelj plaćanja',
            taxRep: 'Porezni zastupnik',
            despatch: 'Pošiljatelj',
            delivery: 'Primatelj',
            order: 'Kupac',
            supplier: 'Dobavljač',
        },
        field: {
            name: 'Naziv',
            legalName: 'Pravni naziv',
            vatId: 'PDV identifikacijski broj',
            companyId: 'Matični broj',
            endpoint: 'Elektronička adresa',
            partyId: 'Identifikator',
            street: 'Ulica',
            street2: 'Dodatna adresa',
            city: 'Grad',
            postal: 'Poštanski broj',
            region: 'Regija',
            country: 'Država',
            contact: 'Kontakt osoba',
            phone: 'Telefon',
            email: 'E-pošta',

            invoiceNo: 'Broj računa',
            creditNoteNo: 'Broj knjižnog odobrenja',
            despatchNo: 'Broj otpremnice',
            issueDate: 'Datum izdavanja',
            issueTime: 'Vrijeme izdavanja',
            dueDate: 'Datum dospijeća',
            typeCode: 'Šifra vrste dokumenta',
            note: 'Napomena',
            taxPointDate: 'Datum nastanka porezne obveze',
            currency: 'Valuta',
            taxCurrency: 'Valuta obračuna PDV-a',
            buyerRef: 'Referenca kupca',
            accountingCost: 'Računovodstvena referenca kupca',
            periodStart: 'Početak obračunskog razdoblja',
            periodEnd: 'Kraj obračunskog razdoblja',
            customization: 'Identifikator specifikacije',
            profile: 'Poslovni proces',

            orderRef: 'Referenca narudžbenice',
            salesOrderRef: 'Referenca prodajnog naloga',
            contractRef: 'Referenca ugovora',
            projectRef: 'Referenca projekta',
            despatchRef: 'Referenca otpremnice',
            receiptRef: 'Referenca primke',
            precedingInvoice: 'Prethodni račun',
            precedingInvoiceDate: 'Datum prethodnog računa',
            attachmentId: 'Prateći dokument',
            attachmentDesc: 'Opis pratećeg dokumenta',

            deliveryDate: 'Datum isporuke',
            deliveryLocation: 'ID mjesta isporuke',
            deliverToName: 'Primatelj isporuke',
            deliveryStreet: 'Ulica isporuke',
            deliveryCity: 'Grad isporuke',
            deliveryPostal: 'Poštanski broj isporuke',
            deliveryCountry: 'Država isporuke',

            paymentMeans: 'Šifra načina plaćanja',
            paymentId: 'Poziv na broj',
            iban: 'IBAN / broj računa',
            accountName: 'Vlasnik računa',
            bic: 'BIC',
            cardNumber: 'Broj kartice',
            mandate: 'Suglasnost za izravno terećenje',
            paymentTerms: 'Uvjeti plaćanja',

            allowanceAmount: 'Iznos popusta',
            allowanceReason: 'Razlog popusta',
            chargeAmount: 'Iznos dodatnog troška',
            chargeReason: 'Razlog dodatnog troška',

            lineTotal: 'Zbroj neto iznosa stavki',
            taxExclusive: 'Ukupno bez PDV-a',
            taxInclusive: 'Ukupno s PDV-om',
            allowanceTotal: 'Zbroj popusta',
            chargeTotal: 'Zbroj dodatnih troškova',
            prepaid: 'Plaćeni iznos',
            rounding: 'Iznos zaokruživanja',
            payable: 'Iznos za plaćanje',

            vatTotal: 'Ukupni iznos PDV-a',
            vatBase: 'Porezna osnovica kategorije PDV-a',
            vatAmount: 'Iznos PDV-a kategorije',
            vatCategory: 'Šifra kategorije PDV-a',
            vatRate: 'Stopa PDV-a (%)',
            vatExemption: 'Razlog oslobođenja od PDV-a',
            vatExemptionCode: 'Šifra razloga oslobođenja od PDV-a',

            lineId: 'Broj stavke',
            lineNote: 'Napomena stavke',
            quantity: 'Količina',
            unit: 'Jedinica mjere',
            lineNet: 'Neto iznos stavke',
            itemName: 'Naziv artikla',
            itemDesc: 'Opis artikla',
            sellerItemId: 'Šifra artikla prodavatelja',
            buyerItemId: 'Šifra artikla kupca',
            standardItemId: 'Standardna šifra artikla (GTIN)',
            originCountry: 'Zemlja podrijetla',
            classification: 'Klasifikacija artikla',
            lineVatCategory: 'Kategorija PDV-a stavke',
            lineVatRate: 'Stopa PDV-a stavke (%)',
            price: 'Jedinična cijena',
            baseQuantity: 'Osnovna količina cijene',
            priceDiscount: 'Popust na cijenu',
            lineAllowance: 'Popust na stavku',
            lineAllowanceReason: 'Razlog popusta na stavku',
            orderLineRef: 'Referenca stavke narudžbe',
            linePeriodStart: 'Početak razdoblja stavke',
            linePeriodEnd: 'Kraj razdoblja stavke',

            shipmentId: 'ID pošiljke',
            grossWeight: 'Bruto težina',
            grossVolume: 'Bruto volumen',
            trackingId: 'Broj za praćenje',
            estStartDate: 'Očekivana isporuka od (datum)',
            estStartTime: 'Očekivana isporuka od (vrijeme)',
            estEndDate: 'Očekivana isporuka do (datum)',
            estEndTime: 'Očekivana isporuka do (vrijeme)',
            carrier: 'Prijevoznik',
            despatchDate: 'Datum otpreme',
            despatchTime: 'Vrijeme otpreme',
            handlingUnit: 'Transportna jedinica (SSCC)',
            handlingUnitType: 'Vrsta transportne jedinice',
            deliveredQty: 'Isporučena količina',
            outstandingQty: 'Neisporučena količina',
            outstandingReason: 'Razlog neisporučene količine',
            lot: 'Broj serije (lot)',
            expiry: 'Najbolje upotrijebiti do / rok trajanja',
            serial: 'Serijski broj',
        },
    },
};

export default hr;
