import type { ExtraDocTextPack } from './types';

const hu: ExtraDocTextPack = {
    titles: {
        invoice: 'Számla',
        credit: 'Jóváíró számla',
        corrected: 'Helyesbítő számla',
        prepayment: 'Előlegszámla',
        partial: 'Részszámla',
        selfbilled: 'Számla (önszámlázás)',
        despatch: 'Szállítólevél',
    },
    sample: {
        note: 'Köszönjük, hogy minket választott.',
        paymentTerms: 'Fizetendő 30 napon belül, levonás nélkül.',
        creditNote: 'Jóváírás egy visszaküldött termékért (szállítás közben megsérült).',
        correctedNote: 'Ez a számla az eredeti számla egységárát helyesbíti.',
        prepaymentNote: 'Előleg a(z) {{order}} számú megrendelésre; a végszámlából levonásra kerül.',
        partialNote: 'Részszámla a projekt első szakaszára.',
        prepaymentItem: 'Előleg ({{pct}}%)',
        discount: 'Hűségkedvezmény',
        product: 'Ergonomikus irodai szék',
        productDesc: 'Fekete hálós háttámla, állítható karfák',
        service: 'Összeszerelés és beállítás',
        accessory: 'Padlóvédő szőnyeg',
        despatchNote: 'Kérjük, az áruátvételi bejárathoz szállítsák.',
        backorderReason: 'Átmenetileg nincs készleten; a jövő héten érkezik.',
    },
    objects: {
        newText: 'Új szöveg',
        header: 'Fejléc {{n}}',
        cell: 'Cella {{n}}',
        fieldName: 'Mezőnév',
        image: 'Kép',
        chooseImage: 'Válasszon képet',
        newColumn: 'Új oszlop',
        computed: 'Számított',
        formulaLabel: 'Előleg (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Dokumentum',
            refs: 'Hivatkozások',
            seller: 'Eladó',
            buyer: 'Vevő',
            payee: 'Kedvezményezett',
            taxRep: 'Eladó adóképviselője',
            despatchParty: 'Feladó',
            deliveryParty: 'Átvevő',
            orderParty: 'Vevő (megrendelő)',
            sellerParty: 'Eladó (szállító)',
            delivery: 'Szállítás',
            shipment: 'Küldemény',
            payment: 'Fizetés',
            allowances: 'Engedmények / felárak',
            totals: 'Összesítők',
            vat: 'ÁFA',
            lines: 'Tételek',
        },
        party: {
            seller: 'Eladó',
            buyer: 'Vevő',
            payee: 'Kedvezményezett',
            taxRep: 'Adóképviselő',
            despatch: 'Feladó',
            delivery: 'Átvevő',
            order: 'Vevő',
            supplier: 'Szállító',
        },
        field: {
            name: 'Név',
            legalName: 'Hivatalos név',
            vatId: 'Közösségi adószám',
            companyId: 'Cégjegyzékszám',
            endpoint: 'Elektronikus cím',
            partyId: 'Azonosító',
            street: 'Utca, házszám',
            street2: 'Kiegészítő cím',
            city: 'Település',
            postal: 'Irányítószám',
            region: 'Régió',
            country: 'Ország',
            contact: 'Kapcsolattartó',
            phone: 'Telefon',
            email: 'E-mail',

            invoiceNo: 'Számlaszám',
            creditNoteNo: 'Jóváíró számla száma',
            despatchNo: 'Szállítólevél száma',
            issueDate: 'Kiállítás dátuma',
            issueTime: 'Kiállítás időpontja',
            dueDate: 'Fizetési határidő',
            typeCode: 'Bizonylattípus kódja',
            note: 'Megjegyzés',
            taxPointDate: 'Teljesítés dátuma',
            currency: 'Pénznem',
            taxCurrency: 'ÁFA elszámolási pénzneme',
            buyerRef: 'Vevői hivatkozás',
            accountingCost: 'Vevő könyvelési hivatkozása',
            periodStart: 'Elszámolási időszak kezdete',
            periodEnd: 'Elszámolási időszak vége',
            customization: 'Specifikáció azonosítója',
            profile: 'Üzleti folyamat',

            orderRef: 'Megrendelés hivatkozása',
            salesOrderRef: 'Eladói rendelés hivatkozása',
            contractRef: 'Szerződés hivatkozása',
            projectRef: 'Projekt hivatkozása',
            despatchRef: 'Szállítólevél hivatkozása',
            receiptRef: 'Átvételi elismervény hivatkozása',
            precedingInvoice: 'Előzmény számla',
            precedingInvoiceDate: 'Előzmény számla dátuma',
            attachmentId: 'Kísérő dokumentum',
            attachmentDesc: 'Kísérő dokumentum leírása',

            deliveryDate: 'Szállítás dátuma',
            deliveryLocation: 'Szállítási hely azonosítója',
            deliverToName: 'Szállítási címzett',
            deliveryStreet: 'Szállítási cím (utca)',
            deliveryCity: 'Szállítási cím (település)',
            deliveryPostal: 'Szállítási cím (irányítószám)',
            deliveryCountry: 'Szállítási cím (ország)',

            paymentMeans: 'Fizetési mód kódja',
            paymentId: 'Fizetési hivatkozás',
            iban: 'IBAN / bankszámlaszám',
            accountName: 'Számlatulajdonos',
            bic: 'BIC',
            cardNumber: 'Kártyaszám',
            mandate: 'Beszedési megbízás',
            paymentTerms: 'Fizetési feltételek',

            allowanceAmount: 'Engedmény összege',
            allowanceReason: 'Engedmény oka',
            chargeAmount: 'Felár összege',
            chargeReason: 'Felár oka',

            lineTotal: 'Tételek nettó összege',
            taxExclusive: 'Összesen ÁFA nélkül',
            taxInclusive: 'Összesen ÁFÁ-val',
            allowanceTotal: 'Engedmények összege',
            chargeTotal: 'Felárak összege',
            prepaid: 'Kifizetett összeg',
            rounding: 'Kerekítés összege',
            payable: 'Fizetendő összeg',

            vatTotal: 'ÁFA összesen',
            vatBase: 'ÁFA-kategória adóalapja',
            vatAmount: 'ÁFA-kategória adóösszege',
            vatCategory: 'ÁFA-kategória kódja',
            vatRate: 'ÁFA-kulcs (%)',
            vatExemption: 'ÁFA-mentesség oka',
            vatExemptionCode: 'ÁFA-mentesség okának kódja',

            lineId: 'Tételszám',
            lineNote: 'Tétel megjegyzése',
            quantity: 'Mennyiség',
            unit: 'Mennyiségi egység',
            lineNet: 'Tétel nettó összege',
            itemName: 'Termék megnevezése',
            itemDesc: 'Termék leírása',
            sellerItemId: 'Eladói cikkszám',
            buyerItemId: 'Vevői cikkszám',
            standardItemId: 'Szabványos termékazonosító (GTIN)',
            originCountry: 'Származási ország',
            classification: 'Termékbesorolás',
            lineVatCategory: 'Tétel ÁFA-kategóriája',
            lineVatRate: 'Tétel ÁFA-kulcsa (%)',
            price: 'Egységár',
            baseQuantity: 'Ár alapmennyisége',
            priceDiscount: 'Árengedmény',
            lineAllowance: 'Tételengedmény',
            lineAllowanceReason: 'Tételengedmény oka',
            orderLineRef: 'Megrendelési tétel hivatkozása',
            linePeriodStart: 'Tétel időszakának kezdete',
            linePeriodEnd: 'Tétel időszakának vége',

            shipmentId: 'Küldeményazonosító',
            grossWeight: 'Bruttó tömeg',
            grossVolume: 'Bruttó térfogat',
            trackingId: 'Nyomkövetési szám',
            estStartDate: 'Várható szállítás ettől (dátum)',
            estStartTime: 'Várható szállítás ettől (időpont)',
            estEndDate: 'Várható szállítás eddig (dátum)',
            estEndTime: 'Várható szállítás eddig (időpont)',
            carrier: 'Fuvarozó',
            despatchDate: 'Feladás dátuma',
            despatchTime: 'Feladás időpontja',
            handlingUnit: 'Szállítási egység (SSCC)',
            handlingUnitType: 'Szállítási egység típusa',
            deliveredQty: 'Szállított mennyiség',
            outstandingQty: 'Hátralékos mennyiség',
            outstandingReason: 'Hátralék oka',
            lot: 'Gyártási tételszám (sarzs)',
            expiry: 'Minőségmegőrzési / lejárati idő',
            serial: 'Sorozatszám',
        },
    },
};

export default hu;
