import type { ExtraDocTextPack } from './types';

const isl: ExtraDocTextPack = {
    titles: {
        invoice: 'Reikningur',
        credit: 'Kreditreikningur',
        corrected: 'Leiðréttur reikningur',
        prepayment: 'Fyrirframgreiðslureikningur',
        partial: 'Hlutareikningur',
        selfbilled: 'Reikningur útgefinn af kaupanda',
        despatch: 'Fylgiseðill',
    },
    sample: {
        note: 'Takk fyrir viðskiptin.',
        paymentTerms: 'Greiðist innan 30 daga án frádráttar.',
        creditNote: 'Kreditfærsla vegna einnar vöru sem var skilað (skemmdist í flutningi).',
        correctedNote: 'Þessi reikningur leiðréttir einingarverð upprunalega reikningsins.',
        prepaymentNote: 'Fyrirframgreiðsla vegna pöntunar {{order}}; dregst frá lokareikningi.',
        partialNote: 'Hlutareikningur fyrir fyrsta áfanga verkefnisins.',
        prepaymentItem: 'Fyrirframgreiðsla ({{pct}}%)',
        discount: 'Tryggðarafsláttur',
        product: 'Vinnuvistvænn skrifstofustóll',
        productDesc: 'Svart netbak, stillanlegar armhvílur',
        service: 'Uppsetning og stilling',
        accessory: 'Gólfvarnarmotta',
        despatchNote: 'Vinsamlegast afhendið við vörumóttöku.',
        backorderReason: 'Tímabundið uppselt; kemur í næstu viku.',
    },
    objects: {
        newText: 'Nýr texti',
        header: 'Fyrirsögn {{n}}',
        cell: 'Reitur {{n}}',
        fieldName: 'Heiti svæðis',
        image: 'Mynd',
        chooseImage: 'Veldu mynd',
        newColumn: 'Nýr dálkur',
        computed: 'Reiknað',
        formulaLabel: 'Fyrirframgreiðsla (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Skjal',
            refs: 'Tilvísanir',
            seller: 'Seljandi',
            buyer: 'Kaupandi',
            payee: 'Greiðsluviðtakandi',
            taxRep: 'Skattfulltrúi seljanda',
            despatchParty: 'Sendandi',
            deliveryParty: 'Viðtakandi',
            orderParty: 'Kaupandi (pantandi)',
            sellerParty: 'Seljandi (birgir)',
            delivery: 'Afhending',
            shipment: 'Sending',
            payment: 'Greiðsla',
            allowances: 'Afslættir / gjöld',
            totals: 'Samtölur',
            vat: 'VSK',
            lines: 'Línur',
        },
        party: {
            seller: 'Seljandi',
            buyer: 'Kaupandi',
            payee: 'Greiðsluviðtakandi',
            taxRep: 'Skattfulltrúi',
            despatch: 'Sendandi',
            delivery: 'Viðtakandi',
            order: 'Kaupandi',
            supplier: 'Birgir',
        },
        field: {
            name: 'Nafn',
            legalName: 'Skráð nafn',
            vatId: 'VSK-númer',
            companyId: 'Kennitala',
            endpoint: 'Rafrænt heimilisfang',
            partyId: 'Auðkenni',
            street: 'Heimilisfang',
            street2: 'Viðbótarheimilisfang',
            city: 'Staður',
            postal: 'Póstnúmer',
            region: 'Landshluti',
            country: 'Land',
            contact: 'Tengiliður',
            phone: 'Sími',
            email: 'Netfang',

            invoiceNo: 'Reikningsnúmer',
            creditNoteNo: 'Númer kreditreiknings',
            despatchNo: 'Númer fylgiseðils',
            issueDate: 'Útgáfudagur',
            issueTime: 'Útgáfutími',
            dueDate: 'Gjalddagi',
            typeCode: 'Tegundarkóði skjals',
            note: 'Athugasemd',
            taxPointDate: 'Dagsetning skattskyldu',
            currency: 'Gjaldmiðill',
            taxCurrency: 'Uppgjörsgjaldmiðill VSK',
            buyerRef: 'Tilvísun kaupanda',
            accountingCost: 'Bókhaldstilvísun kaupanda',
            periodStart: 'Upphaf reikningstímabils',
            periodEnd: 'Lok reikningstímabils',
            customization: 'Auðkenni forskriftar',
            profile: 'Viðskiptaferli',

            orderRef: 'Tilvísun í innkaupapöntun',
            salesOrderRef: 'Tilvísun í sölupöntun',
            contractRef: 'Tilvísun í samning',
            projectRef: 'Tilvísun í verkefni',
            despatchRef: 'Tilvísun í fylgiseðil',
            receiptRef: 'Tilvísun í móttökukvittun',
            precedingInvoice: 'Fyrri reikningur',
            precedingInvoiceDate: 'Dagsetning fyrri reiknings',
            attachmentId: 'Fylgiskjal',
            attachmentDesc: 'Lýsing fylgiskjals',

            deliveryDate: 'Afhendingardagur',
            deliveryLocation: 'Auðkenni afhendingarstaðar',
            deliverToName: 'Viðtakandi sendingar',
            deliveryStreet: 'Heimilisfang afhendingar',
            deliveryCity: 'Staður afhendingar',
            deliveryPostal: 'Póstnúmer afhendingar',
            deliveryCountry: 'Land afhendingar',

            paymentMeans: 'Kóði greiðslumáta',
            paymentId: 'Greiðslutilvísun',
            iban: 'IBAN / bankareikningur',
            accountName: 'Nafn reikningseiganda',
            bic: 'BIC',
            cardNumber: 'Kortanúmer',
            mandate: 'Beingreiðsluheimild',
            paymentTerms: 'Greiðsluskilmálar',

            allowanceAmount: 'Upphæð afsláttar',
            allowanceReason: 'Ástæða afsláttar',
            chargeAmount: 'Upphæð gjalds',
            chargeReason: 'Ástæða gjalds',

            lineTotal: 'Samtala nettóupphæða lína',
            taxExclusive: 'Samtals án VSK',
            taxInclusive: 'Samtals með VSK',
            allowanceTotal: 'Samtala afslátta',
            chargeTotal: 'Samtala gjalda',
            prepaid: 'Greidd upphæð',
            rounding: 'Námundun',
            payable: 'Upphæð til greiðslu',

            vatTotal: 'Heildarupphæð VSK',
            vatBase: 'Skattstofn VSK-flokks',
            vatAmount: 'VSK-upphæð flokks',
            vatCategory: 'Kóði VSK-flokks',
            vatRate: 'VSK-hlutfall (%)',
            vatExemption: 'Ástæða undanþágu frá VSK',
            vatExemptionCode: 'Kóði ástæðu undanþágu frá VSK',

            lineId: 'Línunúmer',
            lineNote: 'Athugasemd línu',
            quantity: 'Magn',
            unit: 'Eining',
            lineNet: 'Nettóupphæð línu',
            itemName: 'Vöruheiti',
            itemDesc: 'Vörulýsing',
            sellerItemId: 'Vörunúmer seljanda',
            buyerItemId: 'Vörunúmer kaupanda',
            standardItemId: 'Staðlað vörunúmer (GTIN)',
            originCountry: 'Upprunaland',
            classification: 'Vöruflokkun',
            lineVatCategory: 'VSK-flokkur línu',
            lineVatRate: 'VSK-hlutfall línu (%)',
            price: 'Einingarverð',
            baseQuantity: 'Grunnmagn verðs',
            priceDiscount: 'Verðafsláttur',
            lineAllowance: 'Línuafsláttur',
            lineAllowanceReason: 'Ástæða línuafsláttar',
            orderLineRef: 'Tilvísun í pöntunarlínu',
            linePeriodStart: 'Upphaf tímabils línu',
            linePeriodEnd: 'Lok tímabils línu',

            shipmentId: 'Auðkenni sendingar',
            grossWeight: 'Brúttóþyngd',
            grossVolume: 'Brúttórúmmál',
            trackingId: 'Rakningarnúmer',
            estStartDate: 'Áætluð afhending frá (dagsetning)',
            estStartTime: 'Áætluð afhending frá (tími)',
            estEndDate: 'Áætluð afhending til (dagsetning)',
            estEndTime: 'Áætluð afhending til (tími)',
            carrier: 'Flutningsaðili',
            despatchDate: 'Sendingardagur',
            despatchTime: 'Sendingartími',
            handlingUnit: 'Flutningseining (SSCC)',
            handlingUnitType: 'Tegund flutningseiningar',
            deliveredQty: 'Afhent magn',
            outstandingQty: 'Óafgreitt magn',
            outstandingReason: 'Ástæða óafgreidds magns',
            lot: 'Lotunúmer',
            expiry: 'Best fyrir / síðasti notkunardagur',
            serial: 'Raðnúmer',
        },
    },
};

export default isl;
