import type { ExtraDocTextPack } from './types';

const it: ExtraDocTextPack = {
    titles: {
        invoice: 'Fattura',
        credit: 'Nota di credito',
        corrected: 'Fattura rettificativa',
        prepayment: 'Fattura di acconto',
        partial: 'Fattura parziale',
        selfbilled: 'Autofattura',
        despatch: 'Documento di trasporto (DDT)',
    },
    sample: {
        note: 'Grazie per averci scelto.',
        paymentTerms: 'Pagamento entro 30 giorni data fattura, senza sconto.',
        creditNote: 'Accredito per un articolo reso (danneggiato durante il trasporto).',
        correctedNote: 'La presente fattura rettifica il prezzo unitario della fattura originale.',
        prepaymentNote: 'Acconto sull’ordine {{order}}; sarà detratto dalla fattura a saldo.',
        partialNote: 'Fattura parziale per la prima fase del progetto.',
        prepaymentItem: 'Acconto ({{pct}}%)',
        discount: 'Sconto fedeltà',
        product: 'Sedia da ufficio ergonomica',
        productDesc: 'Schienale in rete nera, braccioli regolabili',
        service: 'Montaggio e installazione',
        accessory: 'Tappetino salvapavimento',
        despatchNote: 'Si prega di consegnare all’ingresso merci.',
        backorderReason: 'Temporaneamente non disponibile; in consegna la prossima settimana.',
    },
    objects: {
        newText: 'Nuovo testo',
        header: 'Intestazione {{n}}',
        cell: 'Cella {{n}}',
        fieldName: 'Nome campo',
        image: 'Immagine',
        chooseImage: 'Scegli un’immagine',
        newColumn: 'Nuova colonna',
        computed: 'Calcolato',
        formulaLabel: 'Acconto (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Documento',
            refs: 'Riferimenti',
            seller: 'Venditore',
            buyer: 'Acquirente',
            payee: 'Beneficiario',
            taxRep: 'Rappresentante fiscale del venditore',
            despatchParty: 'Mittente',
            deliveryParty: 'Destinatario',
            orderParty: 'Acquirente (ordinante)',
            sellerParty: 'Venditore (fornitore)',
            delivery: 'Consegna',
            shipment: 'Spedizione',
            payment: 'Pagamento',
            allowances: 'Sconti / maggiorazioni',
            totals: 'Totali',
            vat: 'IVA',
            lines: 'Righe',
        },
        party: {
            seller: 'Venditore',
            buyer: 'Acquirente',
            payee: 'Beneficiario',
            taxRep: 'Rappresentante fiscale',
            despatch: 'Mittente',
            delivery: 'Destinatario',
            order: 'Acquirente',
            supplier: 'Fornitore',
        },
        field: {
            name: 'Nome',
            legalName: 'Ragione sociale',
            vatId: 'Partita IVA',
            companyId: 'Numero di iscrizione',
            endpoint: 'Indirizzo elettronico',
            partyId: 'Identificativo',
            street: 'Via',
            street2: 'Indirizzo aggiuntivo',
            city: 'Città',
            postal: 'CAP',
            region: 'Provincia',
            country: 'Paese',
            contact: 'Referente',
            phone: 'Telefono',
            email: 'E-mail',

            invoiceNo: 'Numero fattura',
            creditNoteNo: 'Numero nota di credito',
            despatchNo: 'Numero DDT',
            issueDate: 'Data di emissione',
            issueTime: 'Ora di emissione',
            dueDate: 'Data di scadenza',
            typeCode: 'Codice tipo documento',
            note: 'Nota',
            taxPointDate: 'Data di esigibilità IVA',
            currency: 'Valuta',
            taxCurrency: 'Valuta di contabilizzazione IVA',
            buyerRef: 'Riferimento acquirente',
            accountingCost: 'Riferimento contabile acquirente',
            periodStart: 'Inizio periodo di fatturazione',
            periodEnd: 'Fine periodo di fatturazione',
            customization: 'Identificativo della specifica',
            profile: 'Processo commerciale',

            orderRef: 'Riferimento ordine d’acquisto',
            salesOrderRef: 'Riferimento ordine di vendita',
            contractRef: 'Riferimento contratto',
            projectRef: 'Riferimento progetto',
            despatchRef: 'Riferimento DDT',
            receiptRef: 'Riferimento avviso di ricevimento',
            precedingInvoice: 'Fattura precedente',
            precedingInvoiceDate: 'Data fattura precedente',
            attachmentId: 'Documento allegato',
            attachmentDesc: 'Descrizione documento allegato',

            deliveryDate: 'Data di consegna',
            deliveryLocation: 'ID luogo di consegna',
            deliverToName: 'Destinatario della consegna',
            deliveryStreet: 'Via di consegna',
            deliveryCity: 'Città di consegna',
            deliveryPostal: 'CAP di consegna',
            deliveryCountry: 'Paese di consegna',

            paymentMeans: 'Codice modalità di pagamento',
            paymentId: 'Riferimento pagamento',
            iban: 'IBAN / numero di conto',
            accountName: 'Intestatario del conto',
            bic: 'BIC',
            cardNumber: 'Numero carta',
            mandate: 'Mandato di addebito diretto',
            paymentTerms: 'Condizioni di pagamento',

            allowanceAmount: 'Importo sconto',
            allowanceReason: 'Motivo sconto',
            chargeAmount: 'Importo maggiorazione',
            chargeReason: 'Motivo maggiorazione',

            lineTotal: 'Totale importi netti delle righe',
            taxExclusive: 'Totale IVA esclusa',
            taxInclusive: 'Totale IVA inclusa',
            allowanceTotal: 'Totale sconti',
            chargeTotal: 'Totale maggiorazioni',
            prepaid: 'Importo pagato',
            rounding: 'Arrotondamento',
            payable: 'Importo da pagare',

            vatTotal: 'Totale IVA',
            vatBase: 'Imponibile per categoria IVA',
            vatAmount: 'Imposta per categoria IVA',
            vatCategory: 'Codice categoria IVA',
            vatRate: 'Aliquota IVA (%)',
            vatExemption: 'Motivo esenzione IVA',
            vatExemptionCode: 'Codice motivo esenzione IVA',

            lineId: 'Numero riga',
            lineNote: 'Nota di riga',
            quantity: 'Quantità',
            unit: 'Unità di misura',
            lineNet: 'Importo netto riga',
            itemName: 'Denominazione articolo',
            itemDesc: 'Descrizione articolo',
            sellerItemId: 'Codice articolo venditore',
            buyerItemId: 'Codice articolo acquirente',
            standardItemId: 'Codice standard articolo (GTIN)',
            originCountry: 'Paese di origine',
            classification: 'Classificazione articolo',
            lineVatCategory: 'Categoria IVA riga',
            lineVatRate: 'Aliquota IVA riga (%)',
            price: 'Prezzo unitario',
            baseQuantity: 'Quantità di base del prezzo',
            priceDiscount: 'Sconto sul prezzo',
            lineAllowance: 'Sconto di riga',
            lineAllowanceReason: 'Motivo sconto di riga',
            orderLineRef: 'Riferimento riga ordine',
            linePeriodStart: 'Inizio periodo riga',
            linePeriodEnd: 'Fine periodo riga',

            shipmentId: 'ID spedizione',
            grossWeight: 'Peso lordo',
            grossVolume: 'Volume lordo',
            trackingId: 'Numero di tracciamento',
            estStartDate: 'Consegna prevista dal (data)',
            estStartTime: 'Consegna prevista dalle (ora)',
            estEndDate: 'Consegna prevista entro il (data)',
            estEndTime: 'Consegna prevista entro le (ora)',
            carrier: 'Vettore',
            despatchDate: 'Data di spedizione',
            despatchTime: 'Ora di spedizione',
            handlingUnit: 'Unità di movimentazione (SSCC)',
            handlingUnitType: 'Tipo unità di movimentazione',
            deliveredQty: 'Quantità consegnata',
            outstandingQty: 'Quantità inevasa',
            outstandingReason: 'Motivo quantità inevasa',
            lot: 'Numero di lotto',
            expiry: 'Da consumarsi entro / scadenza',
            serial: 'Numero di serie',
        },
    },
};

export default it;
