import type { ExtraDocTextPack } from './types';

const lt: ExtraDocTextPack = {
    titles: {
        invoice: 'PVM sąskaita faktūra',
        credit: 'Kreditinė PVM sąskaita faktūra',
        corrected: 'Patikslinta PVM sąskaita faktūra',
        prepayment: 'Išankstinė sąskaita faktūra',
        partial: 'Dalinė PVM sąskaita faktūra',
        selfbilled: 'Pirkėjo išrašyta PVM sąskaita faktūra',
        despatch: 'Važtaraštis',
    },
    sample: {
        note: 'Dėkojame, kad renkatės mus.',
        paymentTerms: 'Apmokėti per 30 dienų be atskaitymų.',
        creditNote: 'Kreditas už vieną grąžintą prekę (pažeista transportuojant).',
        correctedNote: 'Ši sąskaita faktūra patikslina pradinės sąskaitos faktūros vieneto kainą.',
        prepaymentNote: 'Išankstinis mokėjimas už užsakymą {{order}}; bus įskaitytas galutinėje sąskaitoje faktūroje.',
        partialNote: 'Dalinė sąskaita faktūra už pirmąjį projekto etapą.',
        prepaymentItem: 'Išankstinis mokėjimas ({{pct}} %)',
        discount: 'Nuolatinio kliento nuolaida',
        product: 'Ergonomiška biuro kėdė',
        productDesc: 'Juodas tinklinis atlošas, reguliuojami porankiai',
        service: 'Montavimas ir paruošimas naudoti',
        accessory: 'Grindų apsauginis kilimėlis',
        despatchNote: 'Prašome pristatyti į prekių priėmimo vietą.',
        backorderReason: 'Laikinai nėra sandėlyje; bus pristatyta kitą savaitę.',
    },
    objects: {
        newText: 'Naujas tekstas',
        header: 'Antraštė {{n}}',
        cell: 'Langelis {{n}}',
        fieldName: 'Lauko pavadinimas',
        image: 'Paveikslėlis',
        chooseImage: 'Pasirinkite paveikslėlį',
        newColumn: 'Naujas stulpelis',
        computed: 'Apskaičiuota',
        formulaLabel: 'Išankstinis mokėjimas (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Dokumentas',
            refs: 'Nuorodos',
            seller: 'Pardavėjas',
            buyer: 'Pirkėjas',
            payee: 'Mokėjimo gavėjas',
            taxRep: 'Pardavėjo mokesčių atstovas',
            despatchParty: 'Siuntėjas',
            deliveryParty: 'Krovinio gavėjas',
            orderParty: 'Pirkėjas (užsakovas)',
            sellerParty: 'Pardavėjas (tiekėjas)',
            delivery: 'Pristatymas',
            shipment: 'Siunta',
            payment: 'Mokėjimas',
            allowances: 'Nuolaidos / priemokos',
            totals: 'Sumos',
            vat: 'PVM',
            lines: 'Eilutės',
        },
        party: {
            seller: 'Pardavėjas',
            buyer: 'Pirkėjas',
            payee: 'Mokėjimo gavėjas',
            taxRep: 'Mokesčių atstovas',
            despatch: 'Siuntėjas',
            delivery: 'Gavėjas',
            order: 'Pirkėjas',
            supplier: 'Tiekėjas',
        },
        field: {
            name: 'Pavadinimas',
            legalName: 'Teisinis pavadinimas',
            vatId: 'PVM mokėtojo kodas',
            companyId: 'Įmonės kodas',
            endpoint: 'Elektroninis adresas',
            partyId: 'Identifikatorius',
            street: 'Gatvė',
            street2: 'Papildoma adreso eilutė',
            city: 'Miestas',
            postal: 'Pašto kodas',
            region: 'Regionas',
            country: 'Šalis',
            contact: 'Kontaktinis asmuo',
            phone: 'Telefonas',
            email: 'El. paštas',

            invoiceNo: 'Sąskaitos faktūros numeris',
            creditNoteNo: 'Kreditinės sąskaitos faktūros numeris',
            despatchNo: 'Važtaraščio numeris',
            issueDate: 'Išrašymo data',
            issueTime: 'Išrašymo laikas',
            dueDate: 'Apmokėjimo terminas',
            typeCode: 'Dokumento tipo kodas',
            note: 'Pastaba',
            taxPointDate: 'PVM apskaičiavimo data',
            currency: 'Valiuta',
            taxCurrency: 'PVM apskaitos valiuta',
            buyerRef: 'Pirkėjo nuoroda',
            accountingCost: 'Pirkėjo apskaitos nuoroda',
            periodStart: 'Atsiskaitymo laikotarpio pradžia',
            periodEnd: 'Atsiskaitymo laikotarpio pabaiga',
            customization: 'Specifikacijos identifikatorius',
            profile: 'Verslo procesas',

            orderRef: 'Pirkimo užsakymo nuoroda',
            salesOrderRef: 'Pardavimo užsakymo nuoroda',
            contractRef: 'Sutarties nuoroda',
            projectRef: 'Projekto nuoroda',
            despatchRef: 'Važtaraščio nuoroda',
            receiptRef: 'Priėmimo pranešimo nuoroda',
            precedingInvoice: 'Ankstesnė sąskaita faktūra',
            precedingInvoiceDate: 'Ankstesnės sąskaitos faktūros data',
            attachmentId: 'Pagrindžiantis dokumentas',
            attachmentDesc: 'Pagrindžiančio dokumento aprašymas',

            deliveryDate: 'Pristatymo data',
            deliveryLocation: 'Pristatymo vietos ID',
            deliverToName: 'Prekių gavėjas',
            deliveryStreet: 'Pristatymo gatvė',
            deliveryCity: 'Pristatymo miestas',
            deliveryPostal: 'Pristatymo pašto kodas',
            deliveryCountry: 'Pristatymo šalis',

            paymentMeans: 'Mokėjimo būdo kodas',
            paymentId: 'Mokėjimo paskirtis',
            iban: 'IBAN / sąskaitos numeris',
            accountName: 'Sąskaitos savininkas',
            bic: 'BIC',
            cardNumber: 'Kortelės numeris',
            mandate: 'Tiesioginio debeto sutikimas',
            paymentTerms: 'Mokėjimo sąlygos',

            allowanceAmount: 'Nuolaidos suma',
            allowanceReason: 'Nuolaidos priežastis',
            chargeAmount: 'Priemokos suma',
            chargeReason: 'Priemokos priežastis',

            lineTotal: 'Eilučių sumų be PVM suma',
            taxExclusive: 'Iš viso be PVM',
            taxInclusive: 'Iš viso su PVM',
            allowanceTotal: 'Nuolaidų suma',
            chargeTotal: 'Priemokų suma',
            prepaid: 'Sumokėta suma',
            rounding: 'Apvalinimas',
            payable: 'Mokėtina suma',

            vatTotal: 'PVM suma iš viso',
            vatBase: 'PVM kategorijos apmokestinamoji vertė',
            vatAmount: 'PVM kategorijos mokesčio suma',
            vatCategory: 'PVM kategorijos kodas',
            vatRate: 'PVM tarifas (%)',
            vatExemption: 'PVM neapmokestinimo priežastis',
            vatExemptionCode: 'PVM neapmokestinimo priežasties kodas',

            lineId: 'Eilutės numeris',
            lineNote: 'Eilutės pastaba',
            quantity: 'Kiekis',
            unit: 'Mato vienetas',
            lineNet: 'Eilutės suma be PVM',
            itemName: 'Prekės pavadinimas',
            itemDesc: 'Prekės aprašymas',
            sellerItemId: 'Pardavėjo prekės kodas',
            buyerItemId: 'Pirkėjo prekės kodas',
            standardItemId: 'Standartinis prekės kodas (GTIN)',
            originCountry: 'Kilmės šalis',
            classification: 'Prekės klasifikacija',
            lineVatCategory: 'Eilutės PVM kategorija',
            lineVatRate: 'Eilutės PVM tarifas (%)',
            price: 'Vieneto kaina',
            baseQuantity: 'Kainos bazinis kiekis',
            priceDiscount: 'Kainos nuolaida',
            lineAllowance: 'Eilutės nuolaida',
            lineAllowanceReason: 'Eilutės nuolaidos priežastis',
            orderLineRef: 'Užsakymo eilutės nuoroda',
            linePeriodStart: 'Eilutės laikotarpio pradžia',
            linePeriodEnd: 'Eilutės laikotarpio pabaiga',

            shipmentId: 'Siuntos ID',
            grossWeight: 'Bruto svoris',
            grossVolume: 'Bruto tūris',
            trackingId: 'Sekimo numeris',
            estStartDate: 'Numatomas pristatymas nuo (data)',
            estStartTime: 'Numatomas pristatymas nuo (laikas)',
            estEndDate: 'Numatomas pristatymas iki (data)',
            estEndTime: 'Numatomas pristatymas iki (laikas)',
            carrier: 'Vežėjas',
            despatchDate: 'Išsiuntimo data',
            despatchTime: 'Išsiuntimo laikas',
            handlingUnit: 'Transporto vienetas (SSCC)',
            handlingUnitType: 'Transporto vieneto tipas',
            deliveredQty: 'Pristatytas kiekis',
            outstandingQty: 'Nepristatytas kiekis',
            outstandingReason: 'Nepristatymo priežastis',
            lot: 'Partijos numeris',
            expiry: 'Geriausias iki / tinka vartoti iki',
            serial: 'Serijos numeris',
        },
    },
};

export default lt;
