import type { ExtraDocTextPack } from './types';

const lv: ExtraDocTextPack = {
    titles: {
        invoice: 'Rēķins',
        credit: 'Kredītrēķins',
        corrected: 'Labots rēķins',
        prepayment: 'Avansa rēķins',
        partial: 'Daļējs rēķins',
        selfbilled: 'Pašaprēķina rēķins',
        despatch: 'Pavadzīme',
    },
    sample: {
        note: 'Paldies par sadarbību!',
        paymentTerms: 'Apmaksas termiņš – 30 dienas bez ieturējumiem.',
        creditNote: 'Kredīts par vienu atgrieztu preci (bojāta transportēšanas laikā).',
        correctedNote: 'Šis rēķins labo sākotnējā rēķina vienības cenu.',
        prepaymentNote: 'Avanss par pasūtījumu {{order}}; tiks ieskaitīts gala rēķinā.',
        partialNote: 'Daļējs rēķins par projekta pirmo posmu.',
        prepaymentItem: 'Avansa maksājums ({{pct}} %)',
        discount: 'Pastāvīgā klienta atlaide',
        product: 'Ergonomisks biroja krēsls',
        productDesc: 'Melna sieta atzveltne, regulējami roku balsti',
        service: 'Uzstādīšana un iestatīšana',
        accessory: 'Grīdas aizsargpaklājs',
        despatchNote: 'Lūdzu, piegādāt preču pieņemšanas vietā.',
        backorderReason: 'Īslaicīgi nav noliktavā; tiks piegādāts nākamnedēļ.',
    },
    objects: {
        newText: 'Jauns teksts',
        header: 'Virsraksts {{n}}',
        cell: 'Šūna {{n}}',
        fieldName: 'Lauka nosaukums',
        image: 'Attēls',
        chooseImage: 'Izvēlieties attēlu',
        newColumn: 'Jauna kolonna',
        computed: 'Aprēķināts',
        formulaLabel: 'Avanss (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Dokuments',
            refs: 'Atsauces',
            seller: 'Pārdevējs',
            buyer: 'Pircējs',
            payee: 'Maksājuma saņēmējs',
            taxRep: 'Pārdevēja nodokļu pārstāvis',
            despatchParty: 'Nosūtītājs',
            deliveryParty: 'Kravas saņēmējs',
            orderParty: 'Pircējs (pasūtītājs)',
            sellerParty: 'Pārdevējs (piegādātājs)',
            delivery: 'Piegāde',
            shipment: 'Sūtījums',
            payment: 'Maksājums',
            allowances: 'Atlaides / piemaksas',
            totals: 'Kopsummas',
            vat: 'PVN',
            lines: 'Rēķina rindas',
        },
        party: {
            seller: 'Pārdevējs',
            buyer: 'Pircējs',
            payee: 'Maksājuma saņēmējs',
            taxRep: 'Nodokļu pārstāvis',
            despatch: 'Nosūtītājs',
            delivery: 'Saņēmējs',
            order: 'Pircējs',
            supplier: 'Piegādātājs',
        },
        field: {
            name: 'Nosaukums',
            legalName: 'Juridiskais nosaukums',
            vatId: 'PVN reģ. nr.',
            companyId: 'Reģistrācijas numurs',
            endpoint: 'Elektroniskā adrese',
            partyId: 'Identifikators',
            street: 'Iela',
            street2: 'Papildu adreses rinda',
            city: 'Pilsēta',
            postal: 'Pasta indekss',
            region: 'Reģions',
            country: 'Valsts',
            contact: 'Kontaktpersona',
            phone: 'Tālrunis',
            email: 'E-pasts',

            invoiceNo: 'Rēķina numurs',
            creditNoteNo: 'Kredītrēķina numurs',
            despatchNo: 'Pavadzīmes numurs',
            issueDate: 'Izrakstīšanas datums',
            issueTime: 'Izrakstīšanas laiks',
            dueDate: 'Apmaksas termiņš',
            typeCode: 'Dokumenta veida kods',
            note: 'Piezīme',
            taxPointDate: 'Nodokļa saistību rašanās datums',
            currency: 'Valūta',
            taxCurrency: 'PVN uzskaites valūta',
            buyerRef: 'Pircēja atsauce',
            accountingCost: 'Pircēja grāmatvedības atsauce',
            periodStart: 'Norēķinu perioda sākums',
            periodEnd: 'Norēķinu perioda beigas',
            customization: 'Specifikācijas identifikators',
            profile: 'Biznesa process',

            orderRef: 'Pirkuma pasūtījuma atsauce',
            salesOrderRef: 'Pārdošanas pasūtījuma atsauce',
            contractRef: 'Līguma atsauce',
            projectRef: 'Projekta atsauce',
            despatchRef: 'Pavadzīmes atsauce',
            receiptRef: 'Pieņemšanas paziņojuma atsauce',
            precedingInvoice: 'Iepriekšējais rēķins',
            precedingInvoiceDate: 'Iepriekšējā rēķina datums',
            attachmentId: 'Pamatojuma dokuments',
            attachmentDesc: 'Pamatojuma dokumenta apraksts',

            deliveryDate: 'Piegādes datums',
            deliveryLocation: 'Piegādes vietas ID',
            deliverToName: 'Preču saņēmējs',
            deliveryStreet: 'Piegādes adreses iela',
            deliveryCity: 'Piegādes pilsēta',
            deliveryPostal: 'Piegādes pasta indekss',
            deliveryCountry: 'Piegādes valsts',

            paymentMeans: 'Maksājuma veida kods',
            paymentId: 'Maksājuma mērķis',
            iban: 'IBAN / konta numurs',
            accountName: 'Konta nosaukums',
            bic: 'BIC',
            cardNumber: 'Kartes numurs',
            mandate: 'Tiešā debeta pilnvara',
            paymentTerms: 'Apmaksas noteikumi',

            allowanceAmount: 'Atlaides summa',
            allowanceReason: 'Atlaides iemesls',
            chargeAmount: 'Piemaksas summa',
            chargeReason: 'Piemaksas iemesls',

            lineTotal: 'Rindu neto summu kopsumma',
            taxExclusive: 'Kopā bez PVN',
            taxInclusive: 'Kopā ar PVN',
            allowanceTotal: 'Atlaižu kopsumma',
            chargeTotal: 'Piemaksu kopsumma',
            prepaid: 'Samaksātā summa',
            rounding: 'Noapaļošana',
            payable: 'Summa apmaksai',

            vatTotal: 'PVN kopsumma',
            vatBase: 'PVN kategorijas apliekamā summa',
            vatAmount: 'PVN kategorijas nodokļa summa',
            vatCategory: 'PVN kategorijas kods',
            vatRate: 'PVN likme (%)',
            vatExemption: 'PVN atbrīvojuma iemesls',
            vatExemptionCode: 'PVN atbrīvojuma iemesla kods',

            lineId: 'Rindas numurs',
            lineNote: 'Rindas piezīme',
            quantity: 'Daudzums',
            unit: 'Mērvienība',
            lineNet: 'Rindas neto summa',
            itemName: 'Preces nosaukums',
            itemDesc: 'Preces apraksts',
            sellerItemId: 'Pārdevēja preces kods',
            buyerItemId: 'Pircēja preces kods',
            standardItemId: 'Standarta preces kods (GTIN)',
            originCountry: 'Izcelsmes valsts',
            classification: 'Preces klasifikācija',
            lineVatCategory: 'Rindas PVN kategorija',
            lineVatRate: 'Rindas PVN likme (%)',
            price: 'Vienības cena',
            baseQuantity: 'Cenas bāzes daudzums',
            priceDiscount: 'Cenas atlaide',
            lineAllowance: 'Rindas atlaide',
            lineAllowanceReason: 'Rindas atlaides iemesls',
            orderLineRef: 'Pasūtījuma rindas atsauce',
            linePeriodStart: 'Rindas perioda sākums',
            linePeriodEnd: 'Rindas perioda beigas',

            shipmentId: 'Sūtījuma ID',
            grossWeight: 'Bruto svars',
            grossVolume: 'Bruto tilpums',
            trackingId: 'Izsekošanas numurs',
            estStartDate: 'Paredzamā piegāde no (datums)',
            estStartTime: 'Paredzamā piegāde no (laiks)',
            estEndDate: 'Paredzamā piegāde līdz (datums)',
            estEndTime: 'Paredzamā piegāde līdz (laiks)',
            carrier: 'Pārvadātājs',
            despatchDate: 'Nosūtīšanas datums',
            despatchTime: 'Nosūtīšanas laiks',
            handlingUnit: 'Transporta vienība (SSCC)',
            handlingUnitType: 'Transporta vienības veids',
            deliveredQty: 'Piegādātais daudzums',
            outstandingQty: 'Nepiegādātais daudzums',
            outstandingReason: 'Nepiegādāšanas iemesls',
            lot: 'Partijas numurs',
            expiry: 'Ieteicams līdz / derīgs līdz',
            serial: 'Sērijas numurs',
        },
    },
};

export default lv;
