import type { ExtraDocTextPack } from './types';

const mt: ExtraDocTextPack = {
    titles: {
        invoice: 'Fattura',
        credit: 'Nota ta’ kreditu',
        corrected: 'Fattura korretta',
        prepayment: 'Fattura ta’ ħlas bil-quddiem',
        partial: 'Fattura parzjali',
        selfbilled: 'Fattura ta’ awtofatturazzjoni',
        despatch: 'Nota tal-kunsinna',
    },
    sample: {
        note: 'Grazzi tan-negozju tagħkom.',
        paymentTerms: 'Pagabbli fi żmien 30 jum mingħajr tnaqqis.',
        creditNote: 'Kreditu għal oġġett wieħed irritornat (ġarrab ħsara waqt it-trasport).',
        correctedNote: 'Din il-fattura tikkoreġi l-prezz unitarju tal-fattura oriġinali.',
        prepaymentNote: 'Ħlas bil-quddiem għall-ordni {{order}}; se jitnaqqas mill-fattura finali.',
        partialNote: 'Fattura parzjali għall-ewwel fażi tal-proġett.',
        prepaymentItem: 'Ħlas bil-quddiem ({{pct}}%)',
        discount: 'Skont tal-lealtà',
        product: 'Siġġu tal-uffiċċju ergonomiku',
        productDesc: 'Dahar tal-malja sewda, poġġamani aġġustabbli',
        service: 'Installazzjoni u konfigurazzjoni',
        accessory: 'Tapit għall-protezzjoni tal-art',
        despatchNote: 'Jekk jogħġbok ikkunsinna fid-daħla tal-merkanzija.',
        backorderReason: 'Temporanjament mhux disponibbli; jasal il-ġimgħa d-dieħla.',
    },
    objects: {
        newText: 'Test ġdid',
        header: 'Intestatura {{n}}',
        cell: 'Ċellola {{n}}',
        fieldName: 'Isem tal-qasam',
        image: 'Immaġni',
        chooseImage: 'Agħżel immaġni',
        newColumn: 'Kolonna ġdida',
        computed: 'Ikkalkulat',
        formulaLabel: 'Ħlas bil-quddiem (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Dokument',
            refs: 'Referenzi',
            seller: 'Bejjiegħ',
            buyer: 'Xerrej',
            payee: 'Benefiċjarju',
            taxRep: 'Rappreżentant fiskali tal-bejjiegħ',
            despatchParty: 'Mittent',
            deliveryParty: 'Destinatarju',
            orderParty: 'Xerrej (li jordna)',
            sellerParty: 'Bejjiegħ (fornitur)',
            delivery: 'Kunsinna',
            shipment: 'Spedizzjoni',
            payment: 'Ħlas',
            allowances: 'Skontijiet / ħlasijiet addizzjonali',
            totals: 'Totali',
            vat: 'VAT',
            lines: 'Linji',
        },
        party: {
            seller: 'Bejjiegħ',
            buyer: 'Xerrej',
            payee: 'Benefiċjarju',
            taxRep: 'Rappreżentant fiskali',
            despatch: 'Mittent',
            delivery: 'Destinatarju',
            order: 'Xerrej',
            supplier: 'Fornitur',
        },
        field: {
            name: 'Isem',
            legalName: 'Isem legali',
            vatId: 'Numru tal-VAT',
            companyId: 'Numru ta’ reġistrazzjoni',
            endpoint: 'Indirizz elettroniku',
            partyId: 'Identifikatur',
            street: 'Triq',
            street2: 'Indirizz addizzjonali',
            city: 'Lokalità',
            postal: 'Kodiċi postali',
            region: 'Reġjun',
            country: 'Pajjiż',
            contact: 'Persuna ta’ kuntatt',
            phone: 'Telefon',
            email: 'E-mail',

            invoiceNo: 'Numru tal-fattura',
            creditNoteNo: 'Numru tan-nota ta’ kreditu',
            despatchNo: 'Numru tan-nota tal-kunsinna',
            issueDate: 'Data tal-ħruġ',
            issueTime: 'Ħin tal-ħruġ',
            dueDate: 'Data tal-iskadenza',
            typeCode: 'Kodiċi tat-tip ta’ dokument',
            note: 'Nota',
            taxPointDate: 'Data tal-punt tat-taxxa',
            currency: 'Munita',
            taxCurrency: 'Munita tal-kontabilità tal-VAT',
            buyerRef: 'Referenza tax-xerrej',
            accountingCost: 'Referenza tal-kontabilità tax-xerrej',
            periodStart: 'Bidu tal-perjodu tal-fatturazzjoni',
            periodEnd: 'Tmiem tal-perjodu tal-fatturazzjoni',
            customization: 'Identifikatur tal-ispeċifikazzjoni',
            profile: 'Proċess kummerċjali',

            orderRef: 'Referenza tal-ordni tax-xiri',
            salesOrderRef: 'Referenza tal-ordni tal-bejgħ',
            contractRef: 'Referenza tal-kuntratt',
            projectRef: 'Referenza tal-proġett',
            despatchRef: 'Referenza tan-nota tal-kunsinna',
            receiptRef: 'Referenza tal-avviż ta’ riċevuta',
            precedingInvoice: 'Fattura preċedenti',
            precedingInvoiceDate: 'Data tal-fattura preċedenti',
            attachmentId: 'Dokument ta’ sostenn',
            attachmentDesc: 'Deskrizzjoni tad-dokument ta’ sostenn',

            deliveryDate: 'Data tal-kunsinna',
            deliveryLocation: 'ID tal-post tal-kunsinna',
            deliverToName: 'Destinatarju tal-kunsinna',
            deliveryStreet: 'Triq tal-kunsinna',
            deliveryCity: 'Lokalità tal-kunsinna',
            deliveryPostal: 'Kodiċi postali tal-kunsinna',
            deliveryCountry: 'Pajjiż tal-kunsinna',

            paymentMeans: 'Kodiċi tal-mezz ta’ ħlas',
            paymentId: 'Referenza tal-ħlas',
            iban: 'IBAN / numru tal-kont',
            accountName: 'Isem tal-kont',
            bic: 'BIC',
            cardNumber: 'Numru tal-karta',
            mandate: 'Mandat ta’ debitu dirett',
            paymentTerms: 'Termini tal-ħlas',

            allowanceAmount: 'Ammont tal-iskont',
            allowanceReason: 'Raġuni għall-iskont',
            chargeAmount: 'Ammont tal-ħlas addizzjonali',
            chargeReason: 'Raġuni għall-ħlas addizzjonali',

            lineTotal: 'Total tal-ammonti netti tal-linji',
            taxExclusive: 'Total mingħajr VAT',
            taxInclusive: 'Total inkluż il-VAT',
            allowanceTotal: 'Total tal-iskontijiet',
            chargeTotal: 'Total tal-ħlasijiet addizzjonali',
            prepaid: 'Ammont imħallas',
            rounding: 'Ammont tal-arrotondament',
            payable: 'Ammont dovut',

            vatTotal: 'Ammont totali tal-VAT',
            vatBase: 'Ammont taxxabbli skont il-kategorija tal-VAT',
            vatAmount: 'Ammont tat-taxxa skont il-kategorija tal-VAT',
            vatCategory: 'Kodiċi tal-kategorija tal-VAT',
            vatRate: 'Rata tal-VAT (%)',
            vatExemption: 'Raġuni għall-eżenzjoni mill-VAT',
            vatExemptionCode: 'Kodiċi tar-raġuni għall-eżenzjoni mill-VAT',

            lineId: 'Numru tal-linja',
            lineNote: 'Nota tal-linja',
            quantity: 'Kwantità',
            unit: 'Unità',
            lineNet: 'Ammont nett tal-linja',
            itemName: 'Isem tal-oġġett',
            itemDesc: 'Deskrizzjoni tal-oġġett',
            sellerItemId: 'ID tal-oġġett tal-bejjiegħ',
            buyerItemId: 'ID tal-oġġett tax-xerrej',
            standardItemId: 'ID standard tal-oġġett (GTIN)',
            originCountry: 'Pajjiż tal-oriġini',
            classification: 'Klassifikazzjoni tal-oġġett',
            lineVatCategory: 'Kategorija tal-VAT tal-linja',
            lineVatRate: 'Rata tal-VAT tal-linja (%)',
            price: 'Prezz unitarju',
            baseQuantity: 'Kwantità bażi tal-prezz',
            priceDiscount: 'Skont fuq il-prezz',
            lineAllowance: 'Skont tal-linja',
            lineAllowanceReason: 'Raġuni għall-iskont tal-linja',
            orderLineRef: 'Referenza tal-linja tal-ordni',
            linePeriodStart: 'Bidu tal-perjodu tal-linja',
            linePeriodEnd: 'Tmiem tal-perjodu tal-linja',

            shipmentId: 'ID tal-ispedizzjoni',
            grossWeight: 'Piż gross',
            grossVolume: 'Volum gross',
            trackingId: 'Numru tal-intraċċar',
            estStartDate: 'Kunsinna stmata minn (data)',
            estStartTime: 'Kunsinna stmata minn (ħin)',
            estEndDate: 'Kunsinna stmata sa (data)',
            estEndTime: 'Kunsinna stmata sa (ħin)',
            carrier: 'Trasportatur',
            despatchDate: 'Data tal-ispedizzjoni',
            despatchTime: 'Ħin tal-ispedizzjoni',
            handlingUnit: 'Unità tal-immaniġġar tat-trasport (SSCC)',
            handlingUnitType: 'Tip ta’ unità tal-immaniġġar',
            deliveredQty: 'Kwantità kkunsinnata',
            outstandingQty: 'Kwantità pendenti',
            outstandingReason: 'Raġuni għall-kwantità pendenti',
            lot: 'Numru tal-lott',
            expiry: 'L-aħjar qabel / data tal-iskadenza',
            serial: 'Numru tas-serje',
        },
    },
};

export default mt;
