import type { ExtraDocTextPack } from './types';

const nb: ExtraDocTextPack = {
    titles: {
        invoice: 'Faktura',
        credit: 'Kreditnota',
        corrected: 'Korrigert faktura',
        prepayment: 'Forskuddsfaktura',
        partial: 'Delfaktura',
        selfbilled: 'Selvfaktura',
        despatch: 'Følgeseddel',
    },
    sample: {
        note: 'Takk for handelen.',
        paymentTerms: 'Betales netto innen 30 dager.',
        creditNote: 'Kreditering av én returnert vare (skadet under transport).',
        correctedNote: 'Denne fakturaen korrigerer enhetsprisen på den opprinnelige fakturaen.',
        prepaymentNote: 'Forskuddsbetaling for ordre {{order}}; beløpet trekkes fra på sluttfakturaen.',
        partialNote: 'Delfaktura for prosjektets første fase.',
        prepaymentItem: 'Forskudd ({{pct}} %)',
        discount: 'Kunderabatt',
        product: 'Ergonomisk kontorstol',
        productDesc: 'Svart nettingrygg, justerbare armlener',
        service: 'Montering og oppsett',
        accessory: 'Gulvbeskyttelsesmatte',
        despatchNote: 'Vennligst lever til varemottaket.',
        backorderReason: 'Midlertidig utsolgt; ettersendes neste uke.',
    },
    objects: {
        newText: 'Ny tekst',
        header: 'Overskrift {{n}}',
        cell: 'Celle {{n}}',
        fieldName: 'Feltnavn',
        image: 'Bilde',
        chooseImage: 'Velg et bilde',
        newColumn: 'Ny kolonne',
        computed: 'Beregnet',
        formulaLabel: 'Forskudd (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Dokument',
            refs: 'Referanser',
            seller: 'Selger',
            buyer: 'Kjøper',
            payee: 'Betalingsmottaker',
            taxRep: 'Selgers mva-representant',
            despatchParty: 'Avsender',
            deliveryParty: 'Mottaker',
            orderParty: 'Kjøper (bestiller)',
            sellerParty: 'Selger (leverandør)',
            delivery: 'Levering',
            shipment: 'Forsendelse',
            payment: 'Betaling',
            allowances: 'Rabatter / gebyrer',
            totals: 'Summer',
            vat: 'Mva',
            lines: 'Linjer',
        },
        party: {
            seller: 'Selger',
            buyer: 'Kjøper',
            payee: 'Betalingsmottaker',
            taxRep: 'Mva-representant',
            despatch: 'Avsender',
            delivery: 'Mottaker',
            order: 'Kjøper',
            supplier: 'Leverandør',
        },
        field: {
            name: 'Navn',
            legalName: 'Juridisk navn',
            vatId: 'Mva-nummer',
            companyId: 'Organisasjonsnummer',
            endpoint: 'Elektronisk adresse',
            partyId: 'Identifikator',
            street: 'Gateadresse',
            street2: 'Tilleggsadresse',
            city: 'Poststed',
            postal: 'Postnummer',
            region: 'Region',
            country: 'Land',
            contact: 'Kontaktperson',
            phone: 'Telefon',
            email: 'E-post',

            invoiceNo: 'Fakturanummer',
            creditNoteNo: 'Kreditnotanummer',
            despatchNo: 'Følgeseddelnummer',
            issueDate: 'Utstedelsesdato',
            issueTime: 'Utstedelsestidspunkt',
            dueDate: 'Forfallsdato',
            typeCode: 'Dokumenttypekode',
            note: 'Merknad',
            taxPointDate: 'Dato for avgiftsplikt',
            currency: 'Valuta',
            taxCurrency: 'Regnskapsvaluta for mva',
            buyerRef: 'Kjøpers referanse',
            accountingCost: 'Kjøpers konteringsreferanse',
            periodStart: 'Faktureringsperiode start',
            periodEnd: 'Faktureringsperiode slutt',
            customization: 'Spesifikasjons-ID',
            profile: 'Forretningsprosess',

            orderRef: 'Innkjøpsordrereferanse',
            salesOrderRef: 'Salgsordrereferanse',
            contractRef: 'Kontraktsreferanse',
            projectRef: 'Prosjektreferanse',
            despatchRef: 'Følgeseddelreferanse',
            receiptRef: 'Mottaksreferanse',
            precedingInvoice: 'Tidligere faktura',
            precedingInvoiceDate: 'Dato for tidligere faktura',
            attachmentId: 'Vedlegg',
            attachmentDesc: 'Beskrivelse av vedlegg',

            deliveryDate: 'Leveringsdato',
            deliveryLocation: 'Leveringssted-ID',
            deliverToName: 'Leveres til',
            deliveryStreet: 'Leveringsadresse, gate',
            deliveryCity: 'Leveringsadresse, poststed',
            deliveryPostal: 'Leveringsadresse, postnr.',
            deliveryCountry: 'Leveringsland',

            paymentMeans: 'Betalingsmåtekode',
            paymentId: 'Betalingsreferanse (KID)',
            iban: 'IBAN / kontonummer',
            accountName: 'Kontonavn',
            bic: 'BIC',
            cardNumber: 'Kortnummer',
            mandate: 'Fullmakt for direkte debitering',
            paymentTerms: 'Betalingsbetingelser',

            allowanceAmount: 'Rabattbeløp',
            allowanceReason: 'Rabattårsak',
            chargeAmount: 'Gebyrbeløp',
            chargeReason: 'Gebyrårsak',

            lineTotal: 'Sum linjebeløp netto',
            taxExclusive: 'Sum ekskl. mva',
            taxInclusive: 'Sum inkl. mva',
            allowanceTotal: 'Sum rabatter',
            chargeTotal: 'Sum gebyrer',
            prepaid: 'Betalt beløp',
            rounding: 'Øreavrunding',
            payable: 'Å betale',

            vatTotal: 'Sum mva',
            vatBase: 'Grunnlag per mva-kategori',
            vatAmount: 'Mva-beløp per kategori',
            vatCategory: 'Mva-kategorikode',
            vatRate: 'Mva-sats (%)',
            vatExemption: 'Årsak til mva-fritak',
            vatExemptionCode: 'Kode for mva-fritak',

            lineId: 'Linjenummer',
            lineNote: 'Linjemerknad',
            quantity: 'Antall',
            unit: 'Enhet',
            lineNet: 'Linjebeløp netto',
            itemName: 'Varenavn',
            itemDesc: 'Varebeskrivelse',
            sellerItemId: 'Selgers varenummer',
            buyerItemId: 'Kjøpers varenummer',
            standardItemId: 'Standard vare-ID (GTIN)',
            originCountry: 'Opprinnelsesland',
            classification: 'Vareklassifisering',
            lineVatCategory: 'Linjens mva-kategori',
            lineVatRate: 'Linjens mva-sats (%)',
            price: 'Enhetspris',
            baseQuantity: 'Basismengde for pris',
            priceDiscount: 'Prisrabatt',
            lineAllowance: 'Linjerabatt',
            lineAllowanceReason: 'Årsak til linjerabatt',
            orderLineRef: 'Ordrelinjereferanse',
            linePeriodStart: 'Linjeperiode start',
            linePeriodEnd: 'Linjeperiode slutt',

            shipmentId: 'Forsendelses-ID',
            grossWeight: 'Bruttovekt',
            grossVolume: 'Bruttovolum',
            trackingId: 'Sporingsnummer',
            estStartDate: 'Forventet levering fra (dato)',
            estStartTime: 'Forventet levering fra (tid)',
            estEndDate: 'Forventet levering til (dato)',
            estEndTime: 'Forventet levering til (tid)',
            carrier: 'Transportør',
            despatchDate: 'Forsendelsesdato',
            despatchTime: 'Forsendelsestidspunkt',
            handlingUnit: 'Transportenhet (SSCC)',
            handlingUnitType: 'Type transportenhet',
            deliveredQty: 'Levert antall',
            outstandingQty: 'Restantall',
            outstandingReason: 'Årsak til restordre',
            lot: 'Batchnummer',
            expiry: 'Best før / utløpsdato',
            serial: 'Serienummer',
        },
    },
};

export default nb;
