import type { ExtraDocTextPack } from './types';

const nl: ExtraDocTextPack = {
    titles: {
        invoice: 'Factuur',
        credit: 'Creditnota',
        corrected: 'Gecorrigeerde factuur',
        prepayment: 'Voorschotfactuur',
        partial: 'Deelfactuur',
        selfbilled: 'Factuur uitgereikt door afnemer',
        despatch: 'Pakbon',
    },
    sample: {
        note: 'Hartelijk dank voor uw opdracht.',
        paymentTerms: 'Te betalen binnen 30 dagen zonder aftrek.',
        creditNote: 'Creditering van één geretourneerd artikel (beschadigd tijdens transport).',
        correctedNote: 'Deze factuur corrigeert de eenheidsprijs van de oorspronkelijke factuur.',
        prepaymentNote: 'Voorschot voor bestelling {{order}}; dit wordt verrekend met de eindfactuur.',
        partialNote: 'Deelfactuur voor de eerste projectfase.',
        prepaymentItem: 'Voorschot ({{pct}}%)',
        discount: 'Klantenkorting',
        product: 'Ergonomische bureaustoel',
        productDesc: 'Zwarte netrug, verstelbare armleuningen',
        service: 'Montage en installatie',
        accessory: 'Vloerbeschermingsmat',
        despatchNote: 'Graag afleveren bij de goederenontvangst.',
        backorderReason: 'Tijdelijk niet op voorraad; volgt volgende week.',
    },
    objects: {
        newText: 'Nieuwe tekst',
        header: 'Kop {{n}}',
        cell: 'Cel {{n}}',
        fieldName: 'Veldnaam',
        image: 'Afbeelding',
        chooseImage: 'Kies een afbeelding',
        newColumn: 'Nieuwe kolom',
        computed: 'Berekend',
        formulaLabel: 'Voorschot (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Document',
            refs: 'Referenties',
            seller: 'Verkoper',
            buyer: 'Koper',
            payee: 'Begunstigde',
            taxRep: 'Fiscaal vertegenwoordiger verkoper',
            despatchParty: 'Verzender',
            deliveryParty: 'Ontvanger',
            orderParty: 'Koper (besteller)',
            sellerParty: 'Verkoper (leverancier)',
            delivery: 'Levering',
            shipment: 'Zending',
            payment: 'Betaling',
            allowances: 'Kortingen / toeslagen',
            totals: 'Totalen',
            vat: 'Btw',
            lines: 'Regels',
        },
        party: {
            seller: 'Verkoper',
            buyer: 'Koper',
            payee: 'Begunstigde',
            taxRep: 'Fiscaal vertegenwoordiger',
            despatch: 'Verzender',
            delivery: 'Ontvanger',
            order: 'Koper',
            supplier: 'Leverancier',
        },
        field: {
            name: 'Naam',
            legalName: 'Statutaire naam',
            vatId: 'Btw-nummer',
            companyId: 'Registratienummer',
            endpoint: 'Elektronisch adres',
            partyId: 'Identificatie',
            street: 'Straat',
            street2: 'Extra adresregel',
            city: 'Plaats',
            postal: 'Postcode',
            region: 'Regio',
            country: 'Land',
            contact: 'Contactpersoon',
            phone: 'Telefoon',
            email: 'E-mail',

            invoiceNo: 'Factuurnummer',
            creditNoteNo: 'Creditnotanummer',
            despatchNo: 'Pakbonnummer',
            issueDate: 'Documentdatum',
            issueTime: 'Documenttijd',
            dueDate: 'Vervaldatum',
            typeCode: 'Documenttypecode',
            note: 'Opmerking',
            taxPointDate: 'Datum belastbaar feit',
            currency: 'Valuta',
            taxCurrency: 'Btw-boekingsvaluta',
            buyerRef: 'Referentie koper',
            accountingCost: 'Boekhoudreferentie koper',
            periodStart: 'Begin factuurperiode',
            periodEnd: 'Einde factuurperiode',
            customization: 'Specificatie-ID',
            profile: 'Bedrijfsproces',

            orderRef: 'Referentie inkooporder',
            salesOrderRef: 'Referentie verkooporder',
            contractRef: 'Contractreferentie',
            projectRef: 'Projectreferentie',
            despatchRef: 'Referentie pakbon',
            receiptRef: 'Referentie ontvangstbericht',
            precedingInvoice: 'Voorgaande factuur',
            precedingInvoiceDate: 'Datum voorgaande factuur',
            attachmentId: 'Ondersteunend document',
            attachmentDesc: 'Omschrijving ondersteunend document',

            deliveryDate: 'Leverdatum',
            deliveryLocation: 'Afleverlocatie-ID',
            deliverToName: 'Afleveren aan',
            deliveryStreet: 'Straat (levering)',
            deliveryCity: 'Plaats (levering)',
            deliveryPostal: 'Postcode (levering)',
            deliveryCountry: 'Land (levering)',

            paymentMeans: 'Code betaalwijze',
            paymentId: 'Betalingskenmerk',
            iban: 'IBAN / rekeningnummer',
            accountName: 'Naam rekeninghouder',
            bic: 'BIC',
            cardNumber: 'Kaartnummer',
            mandate: 'Incassomachtiging',
            paymentTerms: 'Betalingsvoorwaarden',

            allowanceAmount: 'Kortingsbedrag',
            allowanceReason: 'Reden korting',
            chargeAmount: 'Toeslagbedrag',
            chargeReason: 'Reden toeslag',

            lineTotal: 'Som nettoregelbedragen',
            taxExclusive: 'Totaal excl. btw',
            taxInclusive: 'Totaal incl. btw',
            allowanceTotal: 'Som kortingen',
            chargeTotal: 'Som toeslagen',
            prepaid: 'Betaald bedrag',
            rounding: 'Afrondingsbedrag',
            payable: 'Te betalen bedrag',

            vatTotal: 'Totaal btw-bedrag',
            vatBase: 'Grondslag per btw-categorie',
            vatAmount: 'Btw-bedrag per categorie',
            vatCategory: 'Btw-categoriecode',
            vatRate: 'Btw-tarief (%)',
            vatExemption: 'Reden btw-vrijstelling',
            vatExemptionCode: 'Code reden btw-vrijstelling',

            lineId: 'Regelnummer',
            lineNote: 'Regelopmerking',
            quantity: 'Aantal',
            unit: 'Eenheid',
            lineNet: 'Nettoregelbedrag',
            itemName: 'Artikelnaam',
            itemDesc: 'Artikelomschrijving',
            sellerItemId: 'Artikelnummer verkoper',
            buyerItemId: 'Artikelnummer koper',
            standardItemId: 'Standaard artikel-ID (GTIN)',
            originCountry: 'Land van herkomst',
            classification: 'Artikelclassificatie',
            lineVatCategory: 'Btw-categorie regel',
            lineVatRate: 'Btw-tarief regel (%)',
            price: 'Stukprijs',
            baseQuantity: 'Basishoeveelheid prijs',
            priceDiscount: 'Prijskorting',
            lineAllowance: 'Regelkorting',
            lineAllowanceReason: 'Reden regelkorting',
            orderLineRef: 'Referentie orderregel',
            linePeriodStart: 'Begin regelperiode',
            linePeriodEnd: 'Einde regelperiode',

            shipmentId: 'Zendingsnummer',
            grossWeight: 'Brutogewicht',
            grossVolume: 'Brutovolume',
            trackingId: 'Trackingnummer',
            estStartDate: 'Verwachte levering vanaf (datum)',
            estStartTime: 'Verwachte levering vanaf (tijd)',
            estEndDate: 'Verwachte levering tot (datum)',
            estEndTime: 'Verwachte levering tot (tijd)',
            carrier: 'Vervoerder',
            despatchDate: 'Verzenddatum',
            despatchTime: 'Verzendtijd',
            handlingUnit: 'Transporteenheid (SSCC)',
            handlingUnitType: 'Type transporteenheid',
            deliveredQty: 'Geleverd aantal',
            outstandingQty: 'Openstaand aantal',
            outstandingReason: 'Reden nalevering',
            lot: 'Lotnummer',
            expiry: 'Houdbaarheids- / vervaldatum',
            serial: 'Serienummer',
        },
    },
};

export default nl;
