import type { ExtraDocTextPack } from './types';

const pl: ExtraDocTextPack = {
    titles: {
        invoice: 'Faktura',
        credit: 'Faktura korygująca',
        corrected: 'Korekta faktury',
        prepayment: 'Faktura zaliczkowa',
        partial: 'Faktura częściowa',
        selfbilled: 'Faktura (samofakturowanie)',
        despatch: 'Wydanie zewnętrzne (WZ)',
    },
    sample: {
        note: 'Dziękujemy za współpracę.',
        paymentTerms: 'Płatne w terminie 30 dni bez potrąceń.',
        creditNote: 'Korekta za jeden zwrócony produkt (uszkodzony w transporcie).',
        correctedNote: 'Niniejsza faktura koryguje cenę jednostkową z faktury pierwotnej.',
        prepaymentNote: 'Zaliczka na zamówienie {{order}}; zostanie rozliczona w fakturze końcowej.',
        partialNote: 'Faktura częściowa za pierwszy etap projektu.',
        prepaymentItem: 'Zaliczka ({{pct}}%)',
        discount: 'Rabat dla stałych klientów',
        product: 'Ergonomiczne krzesło biurowe',
        productDesc: 'Czarne oparcie z siatki, regulowane podłokietniki',
        service: 'Montaż i konfiguracja',
        accessory: 'Mata ochronna na podłogę',
        despatchNote: 'Prosimy o dostarczenie do wejścia towarowego.',
        backorderReason: 'Chwilowo niedostępny; dostawa w przyszłym tygodniu.',
    },
    objects: {
        newText: 'Nowy tekst',
        header: 'Nagłówek {{n}}',
        cell: 'Komórka {{n}}',
        fieldName: 'Nazwa pola',
        image: 'Obraz',
        chooseImage: 'Wybierz obraz',
        newColumn: 'Nowa kolumna',
        computed: 'Obliczone',
        formulaLabel: 'Zaliczka (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Dokument',
            refs: 'Odniesienia',
            seller: 'Sprzedawca',
            buyer: 'Nabywca',
            payee: 'Odbiorca płatności',
            taxRep: 'Przedstawiciel podatkowy sprzedawcy',
            despatchParty: 'Nadawca',
            deliveryParty: 'Odbiorca dostawy',
            orderParty: 'Nabywca (zamawiający)',
            sellerParty: 'Sprzedawca (dostawca)',
            delivery: 'Dostawa',
            shipment: 'Przesyłka',
            payment: 'Płatność',
            allowances: 'Rabaty / obciążenia',
            totals: 'Podsumowanie',
            vat: 'VAT',
            lines: 'Pozycje',
        },
        party: {
            seller: 'Sprzedawca',
            buyer: 'Nabywca',
            payee: 'Odbiorca płatności',
            taxRep: 'Przedstawiciel podatkowy',
            despatch: 'Nadawca',
            delivery: 'Odbiorca',
            order: 'Nabywca',
            supplier: 'Dostawca',
        },
        field: {
            name: 'Nazwa',
            legalName: 'Pełna nazwa',
            vatId: 'NIP (numer VAT)',
            companyId: 'Numer rejestrowy',
            endpoint: 'Adres elektroniczny',
            partyId: 'Identyfikator',
            street: 'Ulica',
            street2: 'Ulica (cd.)',
            city: 'Miejscowość',
            postal: 'Kod pocztowy',
            region: 'Region',
            country: 'Kraj',
            contact: 'Osoba kontaktowa',
            phone: 'Telefon',
            email: 'E-mail',

            invoiceNo: 'Numer faktury',
            creditNoteNo: 'Numer faktury korygującej',
            despatchNo: 'Numer awiza wysyłki',
            issueDate: 'Data wystawienia',
            issueTime: 'Godzina wystawienia',
            dueDate: 'Termin płatności',
            typeCode: 'Kod rodzaju dokumentu',
            note: 'Uwagi',
            taxPointDate: 'Data powstania obowiązku podatkowego',
            currency: 'Waluta',
            taxCurrency: 'Waluta rozliczenia VAT',
            buyerRef: 'Referencja nabywcy',
            accountingCost: 'Referencja księgowa nabywcy',
            periodStart: 'Początek okresu rozliczeniowego',
            periodEnd: 'Koniec okresu rozliczeniowego',
            customization: 'Identyfikator specyfikacji',
            profile: 'Proces biznesowy',

            orderRef: 'Numer zamówienia',
            salesOrderRef: 'Numer zamówienia sprzedaży',
            contractRef: 'Numer umowy',
            projectRef: 'Numer projektu',
            despatchRef: 'Numer awiza wysyłki',
            receiptRef: 'Numer potwierdzenia odbioru',
            precedingInvoice: 'Faktura pierwotna',
            precedingInvoiceDate: 'Data faktury pierwotnej',
            attachmentId: 'Dokument uzupełniający',
            attachmentDesc: 'Opis dokumentu uzupełniającego',

            deliveryDate: 'Data dostawy',
            deliveryLocation: 'Identyfikator miejsca dostawy',
            deliverToName: 'Odbiorca dostawy',
            deliveryStreet: 'Ulica dostawy',
            deliveryCity: 'Miejscowość dostawy',
            deliveryPostal: 'Kod pocztowy dostawy',
            deliveryCountry: 'Kraj dostawy',

            paymentMeans: 'Kod formy płatności',
            paymentId: 'Tytuł płatności',
            iban: 'IBAN / numer rachunku',
            accountName: 'Nazwa rachunku',
            bic: 'BIC',
            cardNumber: 'Numer karty',
            mandate: 'Mandat polecenia zapłaty',
            paymentTerms: 'Warunki płatności',

            allowanceAmount: 'Kwota rabatu',
            allowanceReason: 'Przyczyna rabatu',
            chargeAmount: 'Kwota opłaty dodatkowej',
            chargeReason: 'Przyczyna opłaty dodatkowej',

            lineTotal: 'Suma wartości netto pozycji',
            taxExclusive: 'Razem netto',
            taxInclusive: 'Razem brutto',
            allowanceTotal: 'Suma rabatów',
            chargeTotal: 'Suma opłat dodatkowych',
            prepaid: 'Kwota zapłacona',
            rounding: 'Zaokrąglenie',
            payable: 'Do zapłaty',

            vatTotal: 'Kwota VAT razem',
            vatBase: 'Podstawa opodatkowania wg kategorii VAT',
            vatAmount: 'Kwota VAT wg kategorii',
            vatCategory: 'Kod kategorii VAT',
            vatRate: 'Stawka VAT (%)',
            vatExemption: 'Podstawa zwolnienia z VAT',
            vatExemptionCode: 'Kod podstawy zwolnienia z VAT',

            lineId: 'Numer pozycji',
            lineNote: 'Uwaga do pozycji',
            quantity: 'Ilość',
            unit: 'Jednostka miary',
            lineNet: 'Wartość netto pozycji',
            itemName: 'Nazwa towaru lub usługi',
            itemDesc: 'Opis towaru lub usługi',
            sellerItemId: 'Kod towaru sprzedawcy',
            buyerItemId: 'Kod towaru nabywcy',
            standardItemId: 'Kod standardowy (GTIN)',
            originCountry: 'Kraj pochodzenia',
            classification: 'Klasyfikacja towaru',
            lineVatCategory: 'Kategoria VAT pozycji',
            lineVatRate: 'Stawka VAT pozycji (%)',
            price: 'Cena jednostkowa netto',
            baseQuantity: 'Ilość bazowa ceny',
            priceDiscount: 'Rabat od ceny',
            lineAllowance: 'Rabat na pozycji',
            lineAllowanceReason: 'Przyczyna rabatu na pozycji',
            orderLineRef: 'Pozycja zamówienia',
            linePeriodStart: 'Początek okresu pozycji',
            linePeriodEnd: 'Koniec okresu pozycji',

            shipmentId: 'Identyfikator przesyłki',
            grossWeight: 'Waga brutto',
            grossVolume: 'Objętość brutto',
            trackingId: 'Numer śledzenia',
            estStartDate: 'Przewidywana dostawa od (data)',
            estStartTime: 'Przewidywana dostawa od (godzina)',
            estEndDate: 'Przewidywana dostawa do (data)',
            estEndTime: 'Przewidywana dostawa do (godzina)',
            carrier: 'Przewoźnik',
            despatchDate: 'Data wysyłki',
            despatchTime: 'Godzina wysyłki',
            handlingUnit: 'Jednostka transportowa (SSCC)',
            handlingUnitType: 'Rodzaj jednostki transportowej',
            deliveredQty: 'Ilość dostarczona',
            outstandingQty: 'Ilość zaległa',
            outstandingReason: 'Przyczyna zaległości',
            lot: 'Numer partii',
            expiry: 'Data minimalnej trwałości / ważności',
            serial: 'Numer seryjny',
        },
    },
};

export default pl;
