import type { ExtraDocTextPack } from './types';

const pt: ExtraDocTextPack = {
    titles: {
        invoice: 'Fatura',
        credit: 'Nota de crédito',
        corrected: 'Fatura retificativa',
        prepayment: 'Fatura de adiantamento',
        partial: 'Fatura parcial',
        selfbilled: 'Fatura (autofaturação)',
        despatch: 'Guia de remessa',
    },
    sample: {
        note: 'Obrigado pela sua preferência.',
        paymentTerms: 'Pagamento a 30 dias, sem desconto.',
        creditNote: 'Crédito por um artigo devolvido (danificado no transporte).',
        correctedNote: 'Esta fatura retifica o preço unitário da fatura original.',
        prepaymentNote: 'Adiantamento referente à encomenda {{order}}; será deduzido na fatura final.',
        partialNote: 'Fatura parcial relativa à primeira fase do projeto.',
        prepaymentItem: 'Adiantamento ({{pct}}%)',
        discount: 'Desconto de fidelização',
        product: 'Cadeira de escritório ergonómica',
        productDesc: 'Costas em rede preta, braços reguláveis',
        service: 'Montagem e instalação',
        accessory: 'Tapete de proteção do pavimento',
        despatchNote: 'Entregar na receção de mercadorias.',
        backorderReason: 'Temporariamente esgotado; segue na próxima semana.',
    },
    objects: {
        newText: 'Novo texto',
        header: 'Cabeçalho {{n}}',
        cell: 'Célula {{n}}',
        fieldName: 'Nome do campo',
        image: 'Imagem',
        chooseImage: 'Escolher uma imagem',
        newColumn: 'Nova coluna',
        computed: 'Calculado',
        formulaLabel: 'Adiantamento (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Documento',
            refs: 'Referências',
            seller: 'Vendedor',
            buyer: 'Adquirente',
            payee: 'Beneficiário',
            taxRep: 'Representante fiscal do vendedor',
            despatchParty: 'Expedidor',
            deliveryParty: 'Destinatário',
            orderParty: 'Adquirente (encomenda)',
            sellerParty: 'Vendedor (fornecedor)',
            delivery: 'Entrega',
            shipment: 'Expedição',
            payment: 'Pagamento',
            allowances: 'Descontos / encargos',
            totals: 'Totais',
            vat: 'IVA',
            lines: 'Linhas',
        },
        party: {
            seller: 'Vendedor',
            buyer: 'Adquirente',
            payee: 'Beneficiário',
            taxRep: 'Representante fiscal',
            despatch: 'Expedidor',
            delivery: 'Destinatário',
            order: 'Adquirente',
            supplier: 'Fornecedor',
        },
        field: {
            name: 'Nome',
            legalName: 'Denominação social',
            vatId: 'N.º de IVA (NIF)',
            companyId: 'Número de registo',
            endpoint: 'Endereço eletrónico',
            partyId: 'Identificador',
            street: 'Rua',
            street2: 'Morada adicional',
            city: 'Localidade',
            postal: 'Código postal',
            region: 'Região',
            country: 'País',
            contact: 'Pessoa de contacto',
            phone: 'Telefone',
            email: 'E-mail',

            invoiceNo: 'Número da fatura',
            creditNoteNo: 'Número da nota de crédito',
            despatchNo: 'Número da guia de remessa',
            issueDate: 'Data de emissão',
            issueTime: 'Hora de emissão',
            dueDate: 'Data de vencimento',
            typeCode: 'Código do tipo de documento',
            note: 'Nota',
            taxPointDate: 'Data de exigibilidade do IVA',
            currency: 'Moeda',
            taxCurrency: 'Moeda de contabilização do IVA',
            buyerRef: 'Referência do adquirente',
            accountingCost: 'Referência contabilística do adquirente',
            periodStart: 'Início do período de faturação',
            periodEnd: 'Fim do período de faturação',
            customization: 'Identificador da especificação',
            profile: 'Processo de negócio',

            orderRef: 'Referência da nota de encomenda',
            salesOrderRef: 'Referência da encomenda de venda',
            contractRef: 'Referência do contrato',
            projectRef: 'Referência do projeto',
            despatchRef: 'Referência da guia de remessa',
            receiptRef: 'Referência do aviso de receção',
            precedingInvoice: 'Fatura anterior',
            precedingInvoiceDate: 'Data da fatura anterior',
            attachmentId: 'Documento de suporte',
            attachmentDesc: 'Descrição do documento de suporte',

            deliveryDate: 'Data de entrega',
            deliveryLocation: 'ID do local de entrega',
            deliverToName: 'Entregar a',
            deliveryStreet: 'Rua de entrega',
            deliveryCity: 'Localidade de entrega',
            deliveryPostal: 'Código postal de entrega',
            deliveryCountry: 'País de entrega',

            paymentMeans: 'Código do meio de pagamento',
            paymentId: 'Referência de pagamento',
            iban: 'IBAN / número de conta',
            accountName: 'Titular da conta',
            bic: 'BIC',
            cardNumber: 'Número do cartão',
            mandate: 'Autorização de débito direto',
            paymentTerms: 'Condições de pagamento',

            allowanceAmount: 'Valor do desconto',
            allowanceReason: 'Motivo do desconto',
            chargeAmount: 'Valor do encargo',
            chargeReason: 'Motivo do encargo',

            lineTotal: 'Soma dos valores líquidos das linhas',
            taxExclusive: 'Total sem IVA',
            taxInclusive: 'Total com IVA',
            allowanceTotal: 'Total de descontos',
            chargeTotal: 'Total de encargos',
            prepaid: 'Valor pago',
            rounding: 'Arredondamento',
            payable: 'Valor a pagar',

            vatTotal: 'Total do IVA',
            vatBase: 'Base tributável por categoria de IVA',
            vatAmount: 'Valor do IVA por categoria',
            vatCategory: 'Código da categoria de IVA',
            vatRate: 'Taxa de IVA (%)',
            vatExemption: 'Motivo de isenção de IVA',
            vatExemptionCode: 'Código do motivo de isenção de IVA',

            lineId: 'Número da linha',
            lineNote: 'Nota da linha',
            quantity: 'Quantidade',
            unit: 'Unidade',
            lineNet: 'Valor líquido da linha',
            itemName: 'Designação do artigo',
            itemDesc: 'Descrição do artigo',
            sellerItemId: 'Código do artigo (vendedor)',
            buyerItemId: 'Código do artigo (adquirente)',
            standardItemId: 'Código normalizado do artigo (GTIN)',
            originCountry: 'País de origem',
            classification: 'Classificação do artigo',
            lineVatCategory: 'Categoria de IVA da linha',
            lineVatRate: 'Taxa de IVA da linha (%)',
            price: 'Preço unitário',
            baseQuantity: 'Quantidade base do preço',
            priceDiscount: 'Desconto no preço',
            lineAllowance: 'Desconto da linha',
            lineAllowanceReason: 'Motivo do desconto da linha',
            orderLineRef: 'Referência da linha da encomenda',
            linePeriodStart: 'Início do período da linha',
            linePeriodEnd: 'Fim do período da linha',

            shipmentId: 'ID da expedição',
            grossWeight: 'Peso bruto',
            grossVolume: 'Volume bruto',
            trackingId: 'Número de seguimento',
            estStartDate: 'Entrega prevista a partir de (data)',
            estStartTime: 'Entrega prevista a partir de (hora)',
            estEndDate: 'Entrega prevista até (data)',
            estEndTime: 'Entrega prevista até (hora)',
            carrier: 'Transportador',
            despatchDate: 'Data de expedição',
            despatchTime: 'Hora de expedição',
            handlingUnit: 'Unidade de transporte (SSCC)',
            handlingUnitType: 'Tipo de unidade de transporte',
            deliveredQty: 'Quantidade entregue',
            outstandingQty: 'Quantidade pendente',
            outstandingReason: 'Motivo da quantidade pendente',
            lot: 'Número de lote',
            expiry: 'Consumir de preferência antes de / validade',
            serial: 'Número de série',
        },
    },
};

export default pt;
