import type { ExtraDocTextPack } from './types';

const ro: ExtraDocTextPack = {
    titles: {
        invoice: 'Factură',
        credit: 'Factură de stornare',
        corrected: 'Factură de corecție',
        prepayment: 'Factură de avans',
        partial: 'Factură parțială',
        selfbilled: 'Autofactură',
        despatch: 'Aviz de însoțire a mărfii',
    },
    sample: {
        note: 'Vă mulțumim pentru colaborare.',
        paymentTerms: 'Plata în termen de 30 de zile, fără deduceri.',
        creditNote: 'Stornare pentru un articol returnat (deteriorat în timpul transportului).',
        correctedNote: 'Această factură corectează prețul unitar din factura inițială.',
        prepaymentNote: 'Avans pentru comanda {{order}}; se va deduce din factura finală.',
        partialNote: 'Factură parțială pentru prima etapă a proiectului.',
        prepaymentItem: 'Avans ({{pct}}%)',
        discount: 'Discount de fidelitate',
        product: 'Scaun de birou ergonomic',
        productDesc: 'Spătar din plasă neagră, cotiere reglabile',
        service: 'Montaj și punere în funcțiune',
        accessory: 'Covoraș de protecție pentru pardoseală',
        despatchNote: 'Vă rugăm să livrați la recepția de mărfuri.',
        backorderReason: 'Temporar indisponibil în stoc; se livrează săptămâna viitoare.',
    },
    objects: {
        newText: 'Text nou',
        header: 'Antet {{n}}',
        cell: 'Celula {{n}}',
        fieldName: 'Nume câmp',
        image: 'Imagine',
        chooseImage: 'Alegeți o imagine',
        newColumn: 'Coloană nouă',
        computed: 'Calculat',
        formulaLabel: 'Avans (20%): ',
    },
    catalog: {
        cat: {
            doc: 'Document',
            refs: 'Referințe',
            seller: 'Vânzător',
            buyer: 'Cumpărător',
            payee: 'Beneficiarul plății',
            taxRep: 'Reprezentant fiscal al vânzătorului',
            despatchParty: 'Expeditor',
            deliveryParty: 'Destinatar',
            orderParty: 'Cumpărător (comandă)',
            sellerParty: 'Vânzător (furnizor)',
            delivery: 'Livrare',
            shipment: 'Expediere',
            payment: 'Plată',
            allowances: 'Reduceri / taxe suplimentare',
            totals: 'Totaluri',
            vat: 'TVA',
            lines: 'Linii',
        },
        party: {
            seller: 'Vânzător',
            buyer: 'Cumpărător',
            payee: 'Beneficiar plată',
            taxRep: 'Reprezentant fiscal',
            despatch: 'Expeditor',
            delivery: 'Destinatar',
            order: 'Cumpărător',
            supplier: 'Furnizor',
        },
        field: {
            name: 'Nume',
            legalName: 'Denumire legală',
            vatId: 'Cod de înregistrare în scopuri de TVA',
            companyId: 'Număr de înregistrare',
            endpoint: 'Adresă electronică',
            partyId: 'Identificator',
            street: 'Stradă',
            street2: 'Adresă suplimentară',
            city: 'Localitate',
            postal: 'Cod poștal',
            region: 'Județ',
            country: 'Țară',
            contact: 'Persoană de contact',
            phone: 'Telefon',
            email: 'E-mail',

            invoiceNo: 'Număr factură',
            creditNoteNo: 'Număr factură de stornare',
            despatchNo: 'Număr aviz de însoțire',
            issueDate: 'Data emiterii',
            issueTime: 'Ora emiterii',
            dueDate: 'Data scadenței',
            typeCode: 'Cod tip document',
            note: 'Notă',
            taxPointDate: 'Data exigibilității TVA',
            currency: 'Monedă',
            taxCurrency: 'Moneda de contabilizare a TVA',
            buyerRef: 'Referința cumpărătorului',
            accountingCost: 'Referința contabilă a cumpărătorului',
            periodStart: 'Început perioadă de facturare',
            periodEnd: 'Sfârșit perioadă de facturare',
            customization: 'Identificatorul specificației',
            profile: 'Proces de afaceri',

            orderRef: 'Referință comandă de achiziție',
            salesOrderRef: 'Referință comandă de vânzare',
            contractRef: 'Referință contract',
            projectRef: 'Referință proiect',
            despatchRef: 'Referință aviz de expediție',
            receiptRef: 'Referință aviz de recepție',
            precedingInvoice: 'Factura anterioară',
            precedingInvoiceDate: 'Data facturii anterioare',
            attachmentId: 'Document justificativ',
            attachmentDesc: 'Descrierea documentului justificativ',

            deliveryDate: 'Data livrării',
            deliveryLocation: 'ID loc de livrare',
            deliverToName: 'Livrare către',
            deliveryStreet: 'Stradă livrare',
            deliveryCity: 'Localitate livrare',
            deliveryPostal: 'Cod poștal livrare',
            deliveryCountry: 'Țară livrare',

            paymentMeans: 'Cod modalitate de plată',
            paymentId: 'Referință plată',
            iban: 'IBAN / număr de cont',
            accountName: 'Titularul contului',
            bic: 'BIC',
            cardNumber: 'Număr card',
            mandate: 'Mandat de debitare directă',
            paymentTerms: 'Condiții de plată',

            allowanceAmount: 'Valoare reducere',
            allowanceReason: 'Motivul reducerii',
            chargeAmount: 'Valoare taxă suplimentară',
            chargeReason: 'Motivul taxei suplimentare',

            lineTotal: 'Suma valorilor nete ale liniilor',
            taxExclusive: 'Total fără TVA',
            taxInclusive: 'Total cu TVA',
            allowanceTotal: 'Total reduceri',
            chargeTotal: 'Total taxe suplimentare',
            prepaid: 'Sumă plătită',
            rounding: 'Rotunjire',
            payable: 'Total de plată',

            vatTotal: 'Valoare totală TVA',
            vatBase: 'Bază impozabilă pe categorie de TVA',
            vatAmount: 'Valoare TVA pe categorie',
            vatCategory: 'Cod categorie TVA',
            vatRate: 'Cota TVA (%)',
            vatExemption: 'Motivul scutirii de TVA',
            vatExemptionCode: 'Cod motiv scutire de TVA',

            lineId: 'Număr linie',
            lineNote: 'Notă linie',
            quantity: 'Cantitate',
            unit: 'Unitate de măsură',
            lineNet: 'Valoare netă linie',
            itemName: 'Denumire articol',
            itemDesc: 'Descriere articol',
            sellerItemId: 'Cod articol vânzător',
            buyerItemId: 'Cod articol cumpărător',
            standardItemId: 'Cod standard articol (GTIN)',
            originCountry: 'Țara de origine',
            classification: 'Clasificare articol',
            lineVatCategory: 'Categorie TVA linie',
            lineVatRate: 'Cota TVA linie (%)',
            price: 'Preț unitar',
            baseQuantity: 'Cantitate de bază a prețului',
            priceDiscount: 'Reducere de preț',
            lineAllowance: 'Reducere pe linie',
            lineAllowanceReason: 'Motivul reducerii pe linie',
            orderLineRef: 'Referință linie comandă',
            linePeriodStart: 'Început perioadă linie',
            linePeriodEnd: 'Sfârșit perioadă linie',

            shipmentId: 'ID expediere',
            grossWeight: 'Greutate brută',
            grossVolume: 'Volum brut',
            trackingId: 'Număr de urmărire',
            estStartDate: 'Livrare estimată de la (data)',
            estStartTime: 'Livrare estimată de la (ora)',
            estEndDate: 'Livrare estimată până la (data)',
            estEndTime: 'Livrare estimată până la (ora)',
            carrier: 'Transportator',
            despatchDate: 'Data expedierii',
            despatchTime: 'Ora expedierii',
            handlingUnit: 'Unitate de transport (SSCC)',
            handlingUnitType: 'Tip unitate de transport',
            deliveredQty: 'Cantitate livrată',
            outstandingQty: 'Cantitate restantă',
            outstandingReason: 'Motivul cantității restante',
            lot: 'Număr lot',
            expiry: 'A se consuma înainte de / data expirării',
            serial: 'Număr de serie',
        },
    },
};

export default ro;
