import type { ExtraDocTextPack } from './types';

const sk: ExtraDocTextPack = {
    titles: {
        invoice: 'Faktúra',
        credit: 'Dobropis',
        corrected: 'Opravná faktúra',
        prepayment: 'Zálohová faktúra',
        partial: 'Čiastková faktúra',
        selfbilled: 'Faktúra vyhotovená odberateľom',
        despatch: 'Dodací list',
    },
    sample: {
        note: 'Ďakujeme za spoluprácu.',
        paymentTerms: 'Splatné do 30 dní bez zrážok.',
        creditNote: 'Dobropis za jeden vrátený kus (poškodený pri preprave).',
        correctedNote: 'Táto faktúra opravuje jednotkovú cenu pôvodnej faktúry.',
        prepaymentNote: 'Záloha na objednávku {{order}}; bude odpočítaná v konečnej faktúre.',
        partialNote: 'Čiastková faktúra za prvú etapu projektu.',
        prepaymentItem: 'Záloha ({{pct}} %)',
        discount: 'Vernostná zľava',
        product: 'Ergonomická kancelárska stolička',
        productDesc: 'Čierne sieťované operadlo, nastaviteľné opierky rúk',
        service: 'Montáž a nastavenie',
        accessory: 'Ochranná podložka na podlahu',
        despatchNote: 'Prosíme o doručenie k vchodu pre zásobovanie.',
        backorderReason: 'Dočasne nie je na sklade; dodáme budúci týždeň.',
    },
    objects: {
        newText: 'Nový text',
        header: 'Hlavička {{n}}',
        cell: 'Bunka {{n}}',
        fieldName: 'Názov poľa',
        image: 'Obrázok',
        chooseImage: 'Vyberte obrázok',
        newColumn: 'Nový stĺpec',
        computed: 'Vypočítané',
        formulaLabel: 'Záloha (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Doklad',
            refs: 'Odkazy',
            seller: 'Dodávateľ',
            buyer: 'Odberateľ',
            payee: 'Príjemca platby',
            taxRep: 'Daňový zástupca dodávateľa',
            despatchParty: 'Odosielateľ',
            deliveryParty: 'Príjemca zásielky',
            orderParty: 'Odberateľ (objednávateľ)',
            sellerParty: 'Dodávateľ (predávajúci)',
            delivery: 'Dodanie',
            shipment: 'Zásielka',
            payment: 'Platba',
            allowances: 'Zľavy / prirážky',
            totals: 'Súčty',
            vat: 'DPH',
            lines: 'Položky',
        },
        party: {
            seller: 'Dodávateľ',
            buyer: 'Odberateľ',
            payee: 'Príjemca platby',
            taxRep: 'Daňový zástupca',
            despatch: 'Odosielateľ',
            delivery: 'Príjemca',
            order: 'Odberateľ',
            supplier: 'Dodávateľ',
        },
        field: {
            name: 'Názov',
            legalName: 'Obchodné meno',
            vatId: 'IČ DPH',
            companyId: 'IČO',
            endpoint: 'Elektronická adresa',
            partyId: 'Identifikátor',
            street: 'Ulica',
            street2: 'Doplnková adresa',
            city: 'Mesto',
            postal: 'PSČ',
            region: 'Kraj',
            country: 'Štát',
            contact: 'Kontaktná osoba',
            phone: 'Telefón',
            email: 'E-mail',

            invoiceNo: 'Číslo faktúry',
            creditNoteNo: 'Číslo dobropisu',
            despatchNo: 'Číslo avíza o odoslaní',
            issueDate: 'Dátum vyhotovenia',
            issueTime: 'Čas vyhotovenia',
            dueDate: 'Dátum splatnosti',
            typeCode: 'Kód typu dokladu',
            note: 'Poznámka',
            taxPointDate: 'Dátum vzniku daňovej povinnosti',
            currency: 'Mena',
            taxCurrency: 'Mena na vyúčtovanie DPH',
            buyerRef: 'Referencia odberateľa',
            accountingCost: 'Účtovná referencia odberateľa',
            periodStart: 'Začiatok fakturačného obdobia',
            periodEnd: 'Koniec fakturačného obdobia',
            customization: 'Identifikátor špecifikácie',
            profile: 'Obchodný proces',

            orderRef: 'Číslo objednávky',
            salesOrderRef: 'Číslo predajnej objednávky',
            contractRef: 'Číslo zmluvy',
            projectRef: 'Číslo projektu',
            despatchRef: 'Číslo avíza o odoslaní',
            receiptRef: 'Číslo príjemky',
            precedingInvoice: 'Pôvodná faktúra',
            precedingInvoiceDate: 'Dátum pôvodnej faktúry',
            attachmentId: 'Podporný doklad',
            attachmentDesc: 'Popis podporného dokladu',

            deliveryDate: 'Dátum dodania',
            deliveryLocation: 'ID miesta dodania',
            deliverToName: 'Príjemca dodávky',
            deliveryStreet: 'Ulica dodania',
            deliveryCity: 'Mesto dodania',
            deliveryPostal: 'PSČ dodania',
            deliveryCountry: 'Štát dodania',

            paymentMeans: 'Kód spôsobu úhrady',
            paymentId: 'Variabilný symbol',
            iban: 'IBAN / číslo účtu',
            accountName: 'Názov účtu',
            bic: 'BIC',
            cardNumber: 'Číslo karty',
            mandate: 'Mandát na inkaso',
            paymentTerms: 'Platobné podmienky',

            allowanceAmount: 'Suma zľavy',
            allowanceReason: 'Dôvod zľavy',
            chargeAmount: 'Suma prirážky',
            chargeReason: 'Dôvod prirážky',

            lineTotal: 'Súčet položiek bez DPH',
            taxExclusive: 'Spolu bez DPH',
            taxInclusive: 'Spolu s DPH',
            allowanceTotal: 'Súčet zliav',
            chargeTotal: 'Súčet prirážok',
            prepaid: 'Uhradené',
            rounding: 'Zaokrúhlenie',
            payable: 'Na úhradu',

            vatTotal: 'DPH spolu',
            vatBase: 'Základ dane v kategórii DPH',
            vatAmount: 'Výška DPH v kategórii',
            vatCategory: 'Kód kategórie DPH',
            vatRate: 'Sadzba DPH (%)',
            vatExemption: 'Dôvod oslobodenia od DPH',
            vatExemptionCode: 'Kód dôvodu oslobodenia od DPH',

            lineId: 'Číslo riadku',
            lineNote: 'Poznámka k položke',
            quantity: 'Množstvo',
            unit: 'Merná jednotka',
            lineNet: 'Suma položky bez DPH',
            itemName: 'Názov položky',
            itemDesc: 'Popis položky',
            sellerItemId: 'Kód tovaru dodávateľa',
            buyerItemId: 'Kód tovaru odberateľa',
            standardItemId: 'Štandardný kód tovaru (GTIN)',
            originCountry: 'Krajina pôvodu',
            classification: 'Klasifikácia tovaru',
            lineVatCategory: 'Kategória DPH položky',
            lineVatRate: 'Sadzba DPH položky (%)',
            price: 'Jednotková cena',
            baseQuantity: 'Základné množstvo pre cenu',
            priceDiscount: 'Zľava z ceny',
            lineAllowance: 'Zľava na položke',
            lineAllowanceReason: 'Dôvod zľavy na položke',
            orderLineRef: 'Riadok objednávky',
            linePeriodStart: 'Začiatok obdobia položky',
            linePeriodEnd: 'Koniec obdobia položky',

            shipmentId: 'ID zásielky',
            grossWeight: 'Hmotnosť brutto',
            grossVolume: 'Objem brutto',
            trackingId: 'Sledovacie číslo',
            estStartDate: 'Predpokladané dodanie od (dátum)',
            estStartTime: 'Predpokladané dodanie od (čas)',
            estEndDate: 'Predpokladané dodanie do (dátum)',
            estEndTime: 'Predpokladané dodanie do (čas)',
            carrier: 'Dopravca',
            despatchDate: 'Dátum odoslania',
            despatchTime: 'Čas odoslania',
            handlingUnit: 'Prepravná jednotka (SSCC)',
            handlingUnitType: 'Typ prepravnej jednotky',
            deliveredQty: 'Dodané množstvo',
            outstandingQty: 'Nedodané množstvo',
            outstandingReason: 'Dôvod nedodania',
            lot: 'Číslo šarže',
            expiry: 'Minimálna trvanlivosť / spotrebujte do',
            serial: 'Sériové číslo',
        },
    },
};

export default sk;
