import type { ExtraDocTextPack } from './types';

const sl: ExtraDocTextPack = {
    titles: {
        invoice: 'Račun',
        credit: 'Dobropis',
        corrected: 'Popravek računa',
        prepayment: 'Avansni račun',
        partial: 'Delni račun',
        selfbilled: 'Račun (samofakturiranje)',
        despatch: 'Dobavnica',
    },
    sample: {
        note: 'Hvala za vaše zaupanje.',
        paymentTerms: 'Plačljivo v 30 dneh brez odbitka.',
        creditNote: 'Dobropis za en vrnjen izdelek (poškodovan med prevozom).',
        correctedNote: 'Ta račun popravlja ceno na enoto prvotnega računa.',
        prepaymentNote: 'Avans za naročilo {{order}}; poračunan bo v končnem računu.',
        partialNote: 'Delni račun za prvo fazo projekta.',
        prepaymentItem: 'Avans ({{pct}} %)',
        discount: 'Popust za zveste stranke',
        product: 'Ergonomski pisarniški stol',
        productDesc: 'Črn mrežast naslon, nastavljivi naslonjali za roke',
        service: 'Montaža in nastavitev',
        accessory: 'Zaščitna podloga za tla',
        despatchNote: 'Prosimo, dostavite na vhod za blago.',
        backorderReason: 'Začasno ni na zalogi; sledi prihodnji teden.',
    },
    objects: {
        newText: 'Novo besedilo',
        header: 'Naslov {{n}}',
        cell: 'Celica {{n}}',
        fieldName: 'Ime polja',
        image: 'Slika',
        chooseImage: 'Izberite sliko',
        newColumn: 'Nov stolpec',
        computed: 'Izračunano',
        formulaLabel: 'Avans (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Dokument',
            refs: 'Sklici',
            seller: 'Prodajalec',
            buyer: 'Kupec',
            payee: 'Prejemnik plačila',
            taxRep: 'Davčni zastopnik prodajalca',
            despatchParty: 'Pošiljatelj',
            deliveryParty: 'Prejemnik blaga',
            orderParty: 'Kupec (naročnik)',
            sellerParty: 'Prodajalec (dobavitelj)',
            delivery: 'Dobava',
            shipment: 'Pošiljka',
            payment: 'Plačilo',
            allowances: 'Popusti / doplačila',
            totals: 'Skupni zneski',
            vat: 'DDV',
            lines: 'Postavke',
        },
        party: {
            seller: 'Prodajalec',
            buyer: 'Kupec',
            payee: 'Prejemnik plačila',
            taxRep: 'Davčni zastopnik',
            despatch: 'Pošiljatelj',
            delivery: 'Prejemnik',
            order: 'Kupec',
            supplier: 'Dobavitelj',
        },
        field: {
            name: 'Naziv',
            legalName: 'Uradni naziv',
            vatId: 'ID za DDV',
            companyId: 'Matična številka',
            endpoint: 'Elektronski naslov',
            partyId: 'Identifikator',
            street: 'Ulica',
            street2: 'Dodatni naslov',
            city: 'Kraj',
            postal: 'Poštna številka',
            region: 'Regija',
            country: 'Država',
            contact: 'Kontaktna oseba',
            phone: 'Telefon',
            email: 'E-pošta',

            invoiceNo: 'Številka računa',
            creditNoteNo: 'Številka dobropisa',
            despatchNo: 'Številka dobavnice',
            issueDate: 'Datum izdaje',
            issueTime: 'Čas izdaje',
            dueDate: 'Datum zapadlosti',
            typeCode: 'Koda vrste dokumenta',
            note: 'Opomba',
            taxPointDate: 'Datum nastanka obveznosti DDV',
            currency: 'Valuta',
            taxCurrency: 'Valuta obračuna DDV',
            buyerRef: 'Sklic kupca',
            accountingCost: 'Računovodski sklic kupca',
            periodStart: 'Začetek obračunskega obdobja',
            periodEnd: 'Konec obračunskega obdobja',
            customization: 'Identifikator specifikacije',
            profile: 'Poslovni proces',

            orderRef: 'Sklic na naročilnico',
            salesOrderRef: 'Sklic na prodajno naročilo',
            contractRef: 'Sklic na pogodbo',
            projectRef: 'Sklic na projekt',
            despatchRef: 'Sklic na dobavnico',
            receiptRef: 'Sklic na prevzemnico',
            precedingInvoice: 'Predhodni račun',
            precedingInvoiceDate: 'Datum predhodnega računa',
            attachmentId: 'Spremni dokument',
            attachmentDesc: 'Opis spremnega dokumenta',

            deliveryDate: 'Datum dobave',
            deliveryLocation: 'ID lokacije dobave',
            deliverToName: 'Prejemnik dobave',
            deliveryStreet: 'Ulica dobave',
            deliveryCity: 'Kraj dobave',
            deliveryPostal: 'Poštna številka dobave',
            deliveryCountry: 'Država dobave',

            paymentMeans: 'Koda načina plačila',
            paymentId: 'Sklic plačila',
            iban: 'IBAN / številka bančnega računa',
            accountName: 'Imetnik računa',
            bic: 'BIC',
            cardNumber: 'Številka kartice',
            mandate: 'Soglasje za direktno obremenitev',
            paymentTerms: 'Plačilni pogoji',

            allowanceAmount: 'Znesek popusta',
            allowanceReason: 'Razlog popusta',
            chargeAmount: 'Znesek doplačila',
            chargeReason: 'Razlog doplačila',

            lineTotal: 'Vsota neto zneskov postavk',
            taxExclusive: 'Skupaj brez DDV',
            taxInclusive: 'Skupaj z DDV',
            allowanceTotal: 'Vsota popustov',
            chargeTotal: 'Vsota doplačil',
            prepaid: 'Plačani znesek',
            rounding: 'Znesek zaokrožitve',
            payable: 'Znesek za plačilo',

            vatTotal: 'Skupni znesek DDV',
            vatBase: 'Davčna osnova kategorije DDV',
            vatAmount: 'Znesek DDV kategorije',
            vatCategory: 'Koda kategorije DDV',
            vatRate: 'Stopnja DDV (%)',
            vatExemption: 'Razlog za oprostitev DDV',
            vatExemptionCode: 'Koda razloga za oprostitev DDV',

            lineId: 'Številka postavke',
            lineNote: 'Opomba postavke',
            quantity: 'Količina',
            unit: 'Enota mere',
            lineNet: 'Neto znesek postavke',
            itemName: 'Naziv artikla',
            itemDesc: 'Opis artikla',
            sellerItemId: 'Šifra artikla prodajalca',
            buyerItemId: 'Šifra artikla kupca',
            standardItemId: 'Standardna šifra artikla (GTIN)',
            originCountry: 'Država porekla',
            classification: 'Klasifikacija artikla',
            lineVatCategory: 'Kategorija DDV postavke',
            lineVatRate: 'Stopnja DDV postavke (%)',
            price: 'Cena na enoto',
            baseQuantity: 'Osnovna količina cene',
            priceDiscount: 'Popust na ceno',
            lineAllowance: 'Popust postavke',
            lineAllowanceReason: 'Razlog popusta postavke',
            orderLineRef: 'Sklic na postavko naročila',
            linePeriodStart: 'Začetek obdobja postavke',
            linePeriodEnd: 'Konec obdobja postavke',

            shipmentId: 'ID pošiljke',
            grossWeight: 'Bruto teža',
            grossVolume: 'Bruto prostornina',
            trackingId: 'Številka za sledenje',
            estStartDate: 'Predvidena dobava od (datum)',
            estStartTime: 'Predvidena dobava od (ura)',
            estEndDate: 'Predvidena dobava do (datum)',
            estEndTime: 'Predvidena dobava do (ura)',
            carrier: 'Prevoznik',
            despatchDate: 'Datum odpreme',
            despatchTime: 'Čas odpreme',
            handlingUnit: 'Transportna enota (SSCC)',
            handlingUnitType: 'Vrsta transportne enote',
            deliveredQty: 'Dobavljena količina',
            outstandingQty: 'Nedobavljena količina',
            outstandingReason: 'Razlog za nedobavljeno količino',
            lot: 'Številka lota',
            expiry: 'Uporabno najmanj do / rok uporabe',
            serial: 'Serijska številka',
        },
    },
};

export default sl;
