import type { ExtraDocTextPack } from './types';

const sv: ExtraDocTextPack = {
    titles: {
        invoice: 'Faktura',
        credit: 'Kreditfaktura',
        corrected: 'Korrigerad faktura',
        prepayment: 'Förskottsfaktura',
        partial: 'Delfaktura',
        selfbilled: 'Självfaktura',
        despatch: 'Följesedel',
    },
    sample: {
        note: 'Tack för förtroendet.',
        paymentTerms: 'Betalas inom 30 dagar netto.',
        creditNote: 'Kreditering av en returnerad vara (skadad under transport).',
        correctedNote: 'Denna faktura korrigerar à-priset på den ursprungliga fakturan.',
        prepaymentNote: 'Förskottsbetalning för order {{order}}; dras av på slutfakturan.',
        partialNote: 'Delfaktura för projektets första etapp.',
        prepaymentItem: 'Förskott ({{pct}} %)',
        discount: 'Kundrabatt',
        product: 'Ergonomisk kontorsstol',
        productDesc: 'Svart nätrygg, justerbara armstöd',
        service: 'Installation och montering',
        accessory: 'Golvskyddsmatta',
        despatchNote: 'Vänligen leverera till godsmottagningen.',
        backorderReason: 'Tillfälligt slut i lager; levereras nästa vecka.',
    },
    objects: {
        newText: 'Ny text',
        header: 'Rubrik {{n}}',
        cell: 'Cell {{n}}',
        fieldName: 'Fältnamn',
        image: 'Bild',
        chooseImage: 'Välj en bild',
        newColumn: 'Ny kolumn',
        computed: 'Beräknad',
        formulaLabel: 'Förskott (20 %): ',
    },
    catalog: {
        cat: {
            doc: 'Dokument',
            refs: 'Referenser',
            seller: 'Säljare',
            buyer: 'Köpare',
            payee: 'Betalningsmottagare',
            taxRep: 'Säljarens skatteombud',
            despatchParty: 'Avsändare',
            deliveryParty: 'Mottagare',
            orderParty: 'Köpare (beställare)',
            sellerParty: 'Säljare (leverantör)',
            delivery: 'Leverans',
            shipment: 'Försändelse',
            payment: 'Betalning',
            allowances: 'Rabatter / avgifter',
            totals: 'Summor',
            vat: 'Moms',
            lines: 'Rader',
        },
        party: {
            seller: 'Säljare',
            buyer: 'Köpare',
            payee: 'Betalningsmottagare',
            taxRep: 'Skatteombud',
            despatch: 'Avsändare',
            delivery: 'Mottagare',
            order: 'Köpare',
            supplier: 'Leverantör',
        },
        field: {
            name: 'Namn',
            legalName: 'Juridiskt namn',
            vatId: 'Momsregistreringsnummer',
            companyId: 'Organisationsnummer',
            endpoint: 'Elektronisk adress',
            partyId: 'Identifierare',
            street: 'Gatuadress',
            street2: 'Ytterligare adressrad',
            city: 'Ort',
            postal: 'Postnummer',
            region: 'Region',
            country: 'Land',
            contact: 'Kontaktperson',
            phone: 'Telefon',
            email: 'E-post',

            invoiceNo: 'Fakturanummer',
            creditNoteNo: 'Kreditfakturanummer',
            despatchNo: 'Följesedelsnummer',
            issueDate: 'Utfärdandedatum',
            issueTime: 'Utfärdandetid',
            dueDate: 'Förfallodatum',
            typeCode: 'Dokumenttypkod',
            note: 'Notering',
            taxPointDate: 'Datum för skattskyldighet',
            currency: 'Valuta',
            taxCurrency: 'Redovisningsvaluta för moms',
            buyerRef: 'Köparens referens',
            accountingCost: 'Köparens konteringsreferens',
            periodStart: 'Faktureringsperiodens början',
            periodEnd: 'Faktureringsperiodens slut',
            customization: 'Specifikations-ID',
            profile: 'Affärsprocess',

            orderRef: 'Inköpsorderreferens',
            salesOrderRef: 'Säljorderreferens',
            contractRef: 'Avtalsreferens',
            projectRef: 'Projektreferens',
            despatchRef: 'Följesedelsreferens',
            receiptRef: 'Mottagningsreferens',
            precedingInvoice: 'Tidigare faktura',
            precedingInvoiceDate: 'Datum för tidigare faktura',
            attachmentId: 'Bilaga',
            attachmentDesc: 'Beskrivning av bilaga',

            deliveryDate: 'Leveransdatum',
            deliveryLocation: 'Leveransplats-ID',
            deliverToName: 'Leveransmottagare',
            deliveryStreet: 'Leveransadress, gata',
            deliveryCity: 'Leveransadress, ort',
            deliveryPostal: 'Leveransadress, postnummer',
            deliveryCountry: 'Leveransland',

            paymentMeans: 'Betalningssättskod',
            paymentId: 'Betalningsreferens',
            iban: 'IBAN / kontonummer',
            accountName: 'Kontonamn',
            bic: 'BIC',
            cardNumber: 'Kortnummer',
            mandate: 'Autogiromedgivande',
            paymentTerms: 'Betalningsvillkor',

            allowanceAmount: 'Rabattbelopp',
            allowanceReason: 'Rabattorsak',
            chargeAmount: 'Avgiftsbelopp',
            chargeReason: 'Avgiftsorsak',

            lineTotal: 'Summa radbelopp netto',
            taxExclusive: 'Summa exkl. moms',
            taxInclusive: 'Summa inkl. moms',
            allowanceTotal: 'Summa rabatter',
            chargeTotal: 'Summa avgifter',
            prepaid: 'Betalt belopp',
            rounding: 'Öresavrundning',
            payable: 'Att betala',

            vatTotal: 'Total moms',
            vatBase: 'Beskattningsunderlag per momskategori',
            vatAmount: 'Momsbelopp per kategori',
            vatCategory: 'Momskategorikod',
            vatRate: 'Momssats (%)',
            vatExemption: 'Skäl för momsundantag',
            vatExemptionCode: 'Kod för momsundantag',

            lineId: 'Radnummer',
            lineNote: 'Radnotering',
            quantity: 'Antal',
            unit: 'Enhet',
            lineNet: 'Radbelopp netto',
            itemName: 'Artikelnamn',
            itemDesc: 'Artikelbeskrivning',
            sellerItemId: 'Säljarens artikelnummer',
            buyerItemId: 'Köparens artikelnummer',
            standardItemId: 'Standardartikel-ID (GTIN)',
            originCountry: 'Ursprungsland',
            classification: 'Artikelklassificering',
            lineVatCategory: 'Radens momskategori',
            lineVatRate: 'Radens momssats (%)',
            price: 'À-pris',
            baseQuantity: 'Basmängd för pris',
            priceDiscount: 'Prisrabatt',
            lineAllowance: 'Radrabatt',
            lineAllowanceReason: 'Orsak till radrabatt',
            orderLineRef: 'Orderradsreferens',
            linePeriodStart: 'Radperiodens början',
            linePeriodEnd: 'Radperiodens slut',

            shipmentId: 'Försändelse-ID',
            grossWeight: 'Bruttovikt',
            grossVolume: 'Bruttovolym',
            trackingId: 'Spårningsnummer',
            estStartDate: 'Beräknad leverans från (datum)',
            estStartTime: 'Beräknad leverans från (tid)',
            estEndDate: 'Beräknad leverans till (datum)',
            estEndTime: 'Beräknad leverans till (tid)',
            carrier: 'Transportör',
            despatchDate: 'Avsändningsdatum',
            despatchTime: 'Avsändningstid',
            handlingUnit: 'Transportenhet (SSCC)',
            handlingUnitType: 'Typ av transportenhet',
            deliveredQty: 'Levererat antal',
            outstandingQty: 'Restnoterat antal',
            outstandingReason: 'Orsak till restnotering',
            lot: 'Batchnummer',
            expiry: 'Bäst före / utgångsdatum',
            serial: 'Serienummer',
        },
    },
};

export default sv;
